/**
 * Editorial design system — warm ivory, charcoal, restrained terracotta.
 * Reading-first: low-contrast surfaces, comfortable long-session contrast.
 */

export const palette = {
  ivory: '#F7F5F0',
  white: '#FFFFFF',
  charcoal: '#252525',
  grayMuted: '#737373',
  terracotta: '#B65F45',
  beige: '#E9E3D8',
  beigeDeep: '#D5CEC4',
  inkSoft: '#5C5C5C',
  danger: '#A84848',

  darkBg: '#171717',
  darkElevated: '#202020',
  darkHigher: '#292929',
  darkText: '#F2F0EB',
  darkTextSecondary: '#B8B5AE',
  darkTextMuted: '#85827C',
  darkBorder: '#343434',
  darkTerracotta: '#C9785B',
  darkAccentSoft: '#3A2923',

  assessmentGotItBorder: '#D5D0C8',
  assessmentGotItIndicator: '#8A8A8A',
  assessmentAlmostBg: '#F5F0E8',
  assessmentAlmostBorder: '#D4C4A8',
  assessmentAlmostIndicator: '#C4A574',
  assessmentNotYetBg: '#FAF6F4',
  assessmentNotYetBorder: '#D4A99A',
  assessmentNotYetIndicator: '#B65F45',

  darkAssessmentGotItBorder: '#404040',
  darkAssessmentGotItIndicator: '#9A9690',
  darkAssessmentAlmostBg: '#2A261F',
  darkAssessmentAlmostBorder: '#4A4030',
  darkAssessmentAlmostIndicator: '#C4A574',
  darkAssessmentNotYetBg: '#2E221E',
  darkAssessmentNotYetBorder: '#5A3D32',
  darkAssessmentNotYetIndicator: '#C9785B',
} as const;

const lightAssessment = {
  assessmentGotItBg: palette.white,
  assessmentGotItBorder: palette.assessmentGotItBorder,
  assessmentGotItText: palette.charcoal,
  assessmentGotItIndicator: palette.assessmentGotItIndicator,
  assessmentAlmostBg: palette.assessmentAlmostBg,
  assessmentAlmostBorder: palette.assessmentAlmostBorder,
  assessmentAlmostText: palette.charcoal,
  assessmentAlmostIndicator: palette.assessmentAlmostIndicator,
  assessmentNotYetBg: palette.assessmentNotYetBg,
  assessmentNotYetBorder: palette.assessmentNotYetBorder,
  assessmentNotYetText: palette.charcoal,
  assessmentNotYetIndicator: palette.assessmentNotYetIndicator,
} as const;

const darkAssessment = {
  assessmentGotItBg: palette.darkHigher,
  assessmentGotItBorder: palette.darkAssessmentGotItBorder,
  assessmentGotItText: palette.darkText,
  assessmentGotItIndicator: palette.darkAssessmentGotItIndicator,
  assessmentAlmostBg: palette.darkAssessmentAlmostBg,
  assessmentAlmostBorder: palette.darkAssessmentAlmostBorder,
  assessmentAlmostText: palette.darkText,
  assessmentAlmostIndicator: palette.darkAssessmentAlmostIndicator,
  assessmentNotYetBg: palette.darkAssessmentNotYetBg,
  assessmentNotYetBorder: palette.darkAssessmentNotYetBorder,
  assessmentNotYetText: palette.darkText,
  assessmentNotYetIndicator: palette.darkAssessmentNotYetIndicator,
} as const;

export const Colors = {
  light: {
    text: palette.charcoal,
    textSecondary: palette.grayMuted,
    textMuted: '#9A9590',
    background: palette.ivory,
    backgroundElevated: palette.white,
    backgroundHigher: palette.beige,
    backgroundAtmosphereTop: '#F3F0EA',
    backgroundAtmosphereBottom: palette.ivory,
    tint: palette.terracotta,
    tintSoft: '#C47E67',
    accent: palette.terracotta,
    accentSoft: '#F0E8E2',
    buttonPrimary: palette.charcoal,
    onButtonPrimary: palette.ivory,
    onTint: palette.ivory,
    tabIconDefault: palette.grayMuted,
    tabIconSelected: palette.charcoal,
    border: 'rgba(37, 37, 37, 0.08)',
    progressTrack: palette.beige,
    progressFill: palette.terracotta,
    readerSurface: palette.white,
    sentenceHighlight: 'rgba(182, 95, 69, 0.14)',
    danger: palette.danger,
    statusNew: '#9A9590',
    statusLearning: '#C4A574',
    statusFamiliar: '#7A8FA8',
    statusMastered: '#6B9080',
    ...lightAssessment,
  },
  dark: {
    text: palette.darkText,
    textSecondary: palette.darkTextSecondary,
    textMuted: palette.darkTextMuted,
    background: palette.darkBg,
    backgroundElevated: palette.darkElevated,
    backgroundHigher: palette.darkHigher,
    backgroundAtmosphereTop: '#1C1C1C',
    backgroundAtmosphereBottom: palette.darkBg,
    tint: palette.darkTerracotta,
    tintSoft: '#D89072',
    accent: palette.darkTerracotta,
    accentSoft: palette.darkAccentSoft,
    buttonPrimary: palette.darkText,
    onButtonPrimary: palette.darkBg,
    onTint: palette.darkBg,
    tabIconDefault: palette.darkTextMuted,
    tabIconSelected: palette.darkText,
    border: palette.darkBorder,
    progressTrack: '#2A2A2A',
    progressFill: palette.darkTerracotta,
    readerSurface: palette.darkElevated,
    sentenceHighlight: 'rgba(201, 120, 91, 0.22)',
    danger: '#E07A7A',
    statusNew: palette.darkTextMuted,
    statusLearning: '#C4A574',
    statusFamiliar: '#8FA4BE',
    statusMastered: '#7FA892',
    ...darkAssessment,
  },
} as const;

/** WCAG-oriented palettes; terracotta accent replaces legacy green. */
export const HighContrastColors = {
  light: {
    text: '#000000',
    textSecondary: '#1A1A1A',
    textMuted: '#333333',
    background: '#FFFFFF',
    backgroundElevated: '#FFFFFF',
    backgroundHigher: '#F0F0F0',
    backgroundAtmosphereTop: '#FFFFFF',
    backgroundAtmosphereBottom: '#FFFFFF',
    tint: '#8B3A28',
    tintSoft: '#8B3A28',
    accent: '#8B3A28',
    accentSoft: '#F5E8E4',
    buttonPrimary: '#000000',
    onButtonPrimary: '#FFFFFF',
    onTint: '#FFFFFF',
    tabIconDefault: '#333333',
    tabIconSelected: '#000000',
    border: '#000000',
    progressTrack: '#D0D0D0',
    progressFill: '#8B3A28',
    readerSurface: '#FFFFFF',
    sentenceHighlight: '#F5DED6',
    danger: '#9B1C1C',
    statusNew: '#333333',
    statusLearning: '#7A4E00',
    statusFamiliar: '#1A4A7A',
    statusMastered: '#1A5C3A',
    ...lightAssessment,
  },
  dark: {
    text: '#FFFFFF',
    textSecondary: '#F2F2F2',
    textMuted: '#E0E0E0',
    background: '#000000',
    backgroundElevated: '#141414',
    backgroundHigher: '#1E1E1E',
    backgroundAtmosphereTop: '#000000',
    backgroundAtmosphereBottom: '#000000',
    tint: '#E8956F',
    tintSoft: '#E8956F',
    accent: '#E8956F',
    accentSoft: '#3A2923',
    buttonPrimary: '#FFFFFF',
    onButtonPrimary: '#000000',
    onTint: '#000000',
    tabIconDefault: '#CCCCCC',
    tabIconSelected: '#FFFFFF',
    border: '#FFFFFF',
    progressTrack: '#333333',
    progressFill: '#E8956F',
    readerSurface: '#000000',
    sentenceHighlight: '#4A2820',
    danger: '#FF8A8A',
    statusNew: '#E0E0E0',
    statusLearning: '#F5C16C',
    statusFamiliar: '#8FA4BE',
    statusMastered: '#7FA892',
    ...darkAssessment,
  },
} as const;

export type ThemeColors = (typeof Colors)[keyof typeof Colors];
export type ColorSchemeName = keyof typeof Colors;

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  readerHorizontal: 22,
  readerVertical: 20,
} as const;

export const Radii = {
  sm: 8,
  md: 12,
  lg: 16,
  pill: 999,
} as const;

export const Typography = {
  brand: {
    fontFamily: 'CormorantGaramond_600SemiBold',
    fontSize: 42,
    lineHeight: 48,
    letterSpacing: 0.5,
  },
  heroTitle: {
    fontFamily: 'CormorantGaramond_600SemiBold',
    fontSize: 32,
    lineHeight: 40,
    letterSpacing: 0.2,
  },
  chapterEyebrow: {
    fontFamily: 'Literata_500Medium',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 1.6,
    textTransform: 'uppercase' as const,
  },
  chapterTitle: {
    fontFamily: 'CormorantGaramond_600SemiBold',
    fontSize: 28,
    lineHeight: 34,
  },
  body: {
    fontFamily: 'Literata_400Regular',
    fontSize: 16,
    lineHeight: 26,
  },
  reader: {
    fontFamily: 'Literata_400Regular',
    fontSize: 22,
    lineHeight: 40,
  },
  readerDialogue: {
    fontFamily: 'Literata_400Regular_Italic',
    fontSize: 22,
    lineHeight: 40,
  },
  label: {
    fontFamily: 'Literata_500Medium',
    fontSize: 14,
    lineHeight: 20,
  },
  caption: {
    fontFamily: 'Literata_400Regular',
    fontSize: 13,
    lineHeight: 18,
  },
  button: {
    fontFamily: 'Literata_600SemiBold',
    fontSize: 16,
    lineHeight: 22,
  },
  stat: {
    fontFamily: 'CormorantGaramond_600SemiBold',
    fontSize: 28,
    lineHeight: 32,
  },
} as const;

export const MinTouchTarget = 44;
