/** Inflections to merge into existing A1 lemmas + new A2 lemmas. */

const inflections = {
  essere: ['ero', 'eri', 'era', 'eravamo', 'eravate', 'erano', 'stato', 'stata', 'stati', 'state'],
  avere: ['avevo', 'avevi', 'aveva', 'avevamo', 'avevate', 'avevano', 'avuto', 'avuta', 'avuti', 'aver', 'avrebbero'],
  andare: ['andato', 'andata', 'andati', 'andate', 'andavo', 'andava', 'andremo', 'andrà', 'andando'],
  fare: ['fatto', 'fatta', 'facevo', 'faceva', 'facendo', 'farò', 'faremo', 'far', 'facevano'],
  dire: ['detto', 'dicevo', 'diceva', 'diciamo', 'dicendo', 'dirò', 'dir', 'dicono'],
  potere: ['potevo', 'potevi', 'poteva', 'potuto', 'possiamo', 'possono', 'potremo', 'potrà', 'potevano'],
  volere: ['volevo', 'voleva', 'volevano', 'voluto', 'vogliamo', 'vorrei', 'vorrebbe'],
  dovere: ['dovevo', 'doveva', 'dovuto', 'dobbiamo', 'dovremo', 'dovrà', 'dovevano', 'dovremmo'],
  sapere: ['sapevo', 'sapeva', 'saputo', 'sappiamo', 'saprò'],
  vedere: ['visto', 'visti', 'vedevo', 'vedeva', 'vediamo', 'vedendo', 'vedrò'],
  dare: ['dato', 'data', 'davo', 'dava', 'diamo', 'darò'],
  stare: ['stavo', 'stava', 'stavamo', 'stando', 'starò', 'stanno'],
  venire: ['venuto', 'venuta', 'venivo', 'veniva', 'veniamo', 'verrà', 'venite', 'vengono'],
  prendere: ['preso', 'prendevo', 'prendeva', 'prendiamo'],
  parlare: ['parlato', 'parlavo', 'parlava', 'parlavano', 'parliamo', 'parlando'],
  mangiare: ['mangiato', 'mangiavo', 'mangiava', 'mangiamo'],
  bere: ['bevuto', 'bevevo', 'beveva'],
  lavorare: ['lavorato', 'lavoravo', 'lavorava', 'lavoriamo', 'lavorando'],
  cercare: ['cercato', 'cercavo', 'cercava', 'cerchiamo', 'cercando', 'cerca', 'cerco'],
  trovare: ['trovato', 'trovavo', 'trovava', 'troviamo'],
  guardare: ['guardato', 'guardava', 'guardiamo'],
  camminare: ['camminato', 'camminava', 'camminiamo', 'camminavano'],
  entrare: ['entrato', 'entrata', 'entrava', 'entriamo', 'entrate'],
  uscire: ['uscito', 'uscita', 'uscivo', 'usciva', 'usciamo'],
  arrivare: ['arrivato', 'arrivata', 'arrivati', 'arrivava', 'arriviamo', 'arrivando', 'arriveranno'],
  partire: ['partito', 'partita', 'partiva', 'partiamo'],
  aiutare: ['aiutato', 'aiutati', 'aiutava', 'aiutiamo', 'aiutando'],
  conoscere: ['conosciuto', 'conoscevo', 'conosceva', 'conosciamo'],
  sentire: ['sentito', 'sentivo', 'sentiva', 'sentiamo'],
  tornare: ['tornato', 'tornata', 'tornava', 'torniamo'],
  lasciare: ['lasciato', 'lasciava', 'lasciamo'],
  aspettare: ['aspettato', 'aspettavo', 'aspettava', 'aspettiamo', 'aspettando', 'aspettavamo', 'aspettavano'],
  capire: ['capito', 'capivo', 'capiva', 'capiamo'],
  chiedere: ['chiesto', 'chiedevo', 'chiedeva', 'chiediamo'],
  rispondere: ['risposto', 'rispondeva', 'rispondiamo'],
  comprare: ['comprato', 'comprava', 'compriamo'],
  pagare: ['pagato', 'pagava', 'paghiamo', 'paga'],
  aprire: ['aperto', 'aperta', 'aperti', 'apriva', 'apriamo', 'apre'],
  chiudere: ['chiuso', 'chiusa', 'chiude', 'chiudeva', 'chiudiamo'],
  vivere: ['vissuto', 'vivevo', 'viveva', 'viviamo', 'vive', 'vivo', 'viva', 'viveva'],
  piacere: ['piace', 'piacciono', 'piaceva', 'piaciuto'],
  portare: ['portato', 'portava', 'portiamo'],
  chiamare: ['chiamato', 'chiamava', 'chiamiamo', 'chiama', 'chiamo'],
  incontrare: ['incontrato', 'incontrava', 'incontriamo'],
  ascoltare: ['ascoltato', 'ascoltata', 'ascoltava', 'ascoltiamo', 'ascolta', 'ascolti', 'ascolto'],
  costare: ['costato', 'costa', 'costava'],
  cambiare: ['cambiato', 'cambiata', 'cambiava', 'cambiamo', 'cambia', 'cambio', 'cambiando', 'cambierà', 'cambiar'],
  iniziare: ['iniziato', 'iniziata', 'iniziava', 'iniziando'],
  passare: ['passato', 'passata', 'passava', 'passando'],
  risolvere: ['risolto', 'risolveva'],
  perche: ['perché', 'Perché'],
  ce: ["c'è", "C'è", "c'era", "c'erano"],
  dove_e: ["dov'è", "Dov'è"],
  tutto: ['tutti', 'tutte', 'tutta'],
  bello: ['bella', 'belli', 'belle'],
  felice: ['felici'],
  stanco: ['stanca', 'stanchi', 'stanche'],
  piccolo: ['piccola', 'piccoli', 'piccole'],
  grande: ['grandi'],
  nuovo: ['nuova', 'nuovi', 'nuove'],
  buono: ['buona', 'buoni', 'buone'],
  mio: ['mia', 'miei', 'mie'],
  tuo: ['tua', 'tuoi', 'tue'],
  suo: ['sua', 'suoi', 'sue'],
  nostro: ['nostra', 'nostri', 'nostre'],
  questo: ['questa', 'questi', 'queste'],
  quello: ['quella', 'quelli', 'quelle', 'quel'],
  altro: ['altra', 'altri', 'altre'],
  primo: ['prima'],
  tranquillo: ['tranquilla', 'tranquilli'],
  importante: ['importanti'],
  difficile: ['difficili'],
  facile: ['facili'],
  gentile: ['gentili'],
  simpatico: ['simpatica'],
  sicuro: ['sicura'],
  amico: ['amica', 'amici', 'amiche'],
  collega: ['colleghi', 'colleghe'],
  persona: ['persone'],
  giorno: ['giorni'],
  soldi: ['soldo'],
  ora: ['ore'],
  poco: ["po'", 'po’', 'pochi', 'poca', 'poche'],
  troppo: ['troppi', 'troppa', 'troppe'],
  vecchio: ['vecchia', 'vecchi', 'vecchie'],
  cosa: ['cose'],
  problema: ['problemi'],
  lavoro: ['lavori'],
  casa: ['case'],
  a: ['ad'],
  ai: ['agli'],
  anche: ["anch'io", 'Anch’io', "Anch'io"],
  come: ["com'è", 'Com’è', "Com'è"],
  negozio: ['negozi'],
  chiave: ['chiavi'],
  domanda: ['domande'],
  giusto: ['giusta', 'giuste', 'giusti'],
  pronto: ['pronta', 'pronti'],
  solo: ['sola'],
  vicino: ['vicina', 'vicini'],
  libero: ['libera', 'liberi'],
  imparare: ['imparato', 'impari', 'imparando', 'imparava'],
  incontrare: ['incontrato', 'incontrati', 'incontrava', 'incontriamo'],
  entrare: ['entrato', 'entrata', 'entrava', 'entriamo', 'entrate', 'entravano'],
  risolvere: ['risolto', 'risolveva', 'risolvendo'],
  caldo: ['calda'],
  messaggio: ['messaggi'],
  strada: ['strade'],
  sera: ['sere'],
  piano: ['piani'],
  primo: ['prima', 'primi'],
  rumoroso: ['rumorosa'],
  io: ['me'],
  tu: ['te'],
  voi: ['vi'],
  dei: ['degli'],
};

function L(lemmaId, italian, english, partOfSpeech, introducedChapter, extra = {}) {
  return {
    lemmaId,
    italian,
    english,
    partOfSpeech,
    difficulty: extra.difficulty ?? 2,
    frequency: extra.frequency ?? 'medium',
    introducedChapter,
    cefrLevel: extra.cefrLevel ?? 'A2',
    cefrConfidence: extra.cefrConfidence ?? 0.7,
    frequencyBand: extra.frequencyBand ?? 'common',
    register: extra.register ?? 'neutral',
    topic: extra.topic ?? 'everyday',
    abstractness: extra.abstractness ?? (partOfSpeech === 'noun' ? 'concrete' : 'mixed'),
    inflections: extra.inflections ?? [],
  };
}

const lemmas = [
  L('ieri', 'ieri', 'yesterday', 'adverb', 21, { frequency: 'high' }),
  L('settimana', 'settimana', 'week', 'noun', 21, { inflections: ['settimane'] }),
  L('mese', 'mese', 'month', 'noun', 24, { inflections: ['mesi'] }),
  L('sabato', 'sabato', 'Saturday', 'noun', 24),
  L('domenica', 'domenica', 'Sunday', 'noun', 24),
  L('pomeriggio', 'pomeriggio', 'afternoon', 'noun', 21),
  L('notte', 'notte', 'night', 'noun', 22),
  L('forse', 'forse', 'maybe', 'adverb', 21, { frequency: 'high' }),
  L('quindi', 'quindi', 'so / therefore', 'conjunction', 22),
  L('pero', 'però', 'but / however', 'conjunction', 22, { inflections: ['però', 'Però'] }),
  L('mentre', 'mentre', 'while', 'conjunction', 23),
  L('senza', 'senza', 'without', 'preposition', 23),
  L('cosi', 'così', 'so / like this', 'adverb', 22, { inflections: ['così', 'Così'] }),
  L('quasi', 'quasi', 'almost', 'adverb', 25),
  L('abbastanza', 'abbastanza', 'enough / quite', 'adverb', 25),
  L('davvero', 'davvero', 'really', 'adverb', 26),
  L('magari', 'magari', 'maybe / I wish', 'adverb', 28),
  L('stesso', 'stesso', 'same', 'adjective', 22, { inflections: ['stessa', 'stessi', 'stesse'] }),
  L('volta', 'volta', 'time (occasion)', 'noun', 22, { inflections: ['volte'] }),
  L('cliente', 'cliente', 'customer', 'noun', 22, { inflections: ['clienti'] }),
  L('tavolo', 'tavolo', 'table', 'noun', 22, { inflections: ['tavoli'] }),
  L('conto', 'conto', 'bill / account', 'noun', 27, { inflections: ['conti'] }),
  L('festa', 'festa', 'party / celebration', 'noun', 30),
  L('notizia', 'notizia', 'news', 'noun', 26, { inflections: ['notizie'] }),
  L('chiamata', 'chiamata', 'phone call', 'noun', 24, { inflections: ['chiamate'] }),
  L('mamma', 'mamma', 'mom', 'noun', 24),
  L('papa', 'papà', 'dad', 'noun', 24, { inflections: ['papà'] }),
  L('stipendio', 'stipendio', 'salary', 'noun', 37),
  L('bisogno', 'bisogno', 'need', 'noun', 21),
  L('solito', 'solito', 'usual', 'adjective', 21, { inflections: ['solita'] }),
  L('preoccupato', 'preoccupato', 'worried', 'adjective', 25, { inflections: ['preoccupata', 'preoccupati'] }),
  L('contento', 'contento', 'glad / content', 'adjective', 23, { inflections: ['contenta', 'contenti'] }),
  L('vecchio', 'vecchio', 'old', 'adjective', 25, { inflections: ['vecchia', 'vecchi'] }),
  L('speciale', 'speciale', 'special', 'adjective', 30, { inflections: ['speciali'] }),
  L('prossimo', 'prossimo', 'next', 'adjective', 24, { inflections: ['prossima'] }),
  L('ultimo', 'ultimo', 'last', 'adjective', 29, { inflections: ['ultima', 'ultimi'] }),
  L('meglio', 'meglio', 'better', 'adverb', 27),
  L('peggio', 'peggio', 'worse', 'adverb', 28),
  L('nessuno', 'nessuno', 'nobody / no', 'pronoun', 28, { inflections: ['nessuna'] }),
  L('gente', 'gente', 'people', 'noun', 30),
  L('ne', 'ne', 'of it / of them (clitic)', 'pronoun', 23, { frequency: 'high' }),
  L('ragione', 'ragione', 'reason / right', 'noun', 23),
  L('pensare', 'pensare', 'to think', 'verb', 23, {
    inflections: ['penso', 'pensi', 'pensa', 'pensiamo', 'pensate', 'pensano', 'pensato', 'pensavo', 'pensava', 'pensando'],
  }),
  L('sembrare', 'sembrare', 'to seem', 'verb', 23, {
    inflections: ['sembro', 'sembra', 'sembrano', 'sembrava', 'sembrato'],
  }),
  L('dipendere', 'dipendere', 'to depend', 'verb', 28, {
    inflections: ['dipende', 'dipendono', 'dipendeva'],
  }),
  L('importare', 'importare', 'to matter', 'verb', 27, {
    inflections: ['importa', 'importano', 'importava'],
  }),
  L('decidere', 'decidere', 'to decide', 'verb', 26, {
    inflections: ['decido', 'decidi', 'decide', 'decidiamo', 'deciso', 'decisa', 'decideva', 'deciderà'],
  }),
  L('ricordare', 'ricordare', 'to remember', 'verb', 26, {
    inflections: ['ricordo', 'ricordi', 'ricorda', 'ricordiamo', 'ricordato', 'ricordava'],
  }),
  L('dimenticare', 'dimenticare', 'to forget', 'verb', 27, {
    inflections: ['dimentico', 'dimentichi', 'dimentica', 'dimentichiamo', 'dimenticato', 'dimenticava'],
  }),
  L('scegliere', 'scegliere', 'to choose', 'verb', 29, {
    inflections: ['scelgo', 'scegli', 'sceglie', 'scegliamo', 'scelto', 'scelta', 'sceglieva'],
  }),
  L('rimanere', 'rimanere', 'to remain', 'verb', 25, {
    inflections: ['rimango', 'rimani', 'rimane', 'rimaniamo', 'rimasto', 'rimasta', 'rimaneva'],
  }),
  L('restare', 'restare', 'to stay', 'verb', 25, {
    inflections: ['resto', 'resti', 'resta', 'restiamo', 'restato', 'restata', 'restava', 'restavano'],
  }),
  L('vendere', 'vendere', 'to sell', 'verb', 26, {
    inflections: ['vendo', 'vendi', 'vende', 'vendiamo', 'venduto', 'vendeva'],
  }),
  L('offrire', 'offrire', 'to offer', 'verb', 36, {
    inflections: ['offro', 'offri', 'offre', 'offriamo', 'offerto', 'offriva'],
  }),
  L('accettare', 'accettare', 'to accept', 'verb', 36, {
    inflections: ['accetto', 'accetti', 'accetta', 'accettiamo', 'accettato', 'accettava'],
  }),
  L('spiegare', 'spiegare', 'to explain', 'verb', 29, {
    inflections: ['spiego', 'spieghi', 'spiega', 'spieghiamo', 'spiegato', 'spiegava'],
  }),
  L('servire', 'servire', 'to serve / to be needed', 'verb', 21, {
    inflections: ['servo', 'servi', 'serve', 'serviamo', 'servito', 'serviva'],
  }),
  L('preparare', 'preparare', 'to prepare', 'verb', 21, {
    inflections: ['preparo', 'prepari', 'prepara', 'prepariamo', 'preparato', 'preparava', 'preparando'],
  }),
  L('organizzare', 'organizzare', 'to organize', 'verb', 31, {
    inflections: ['organizzo', 'organizzi', 'organizza', 'organizziamo', 'organizzato'],
  }),
  L('aumentare', 'aumentare', 'to increase', 'verb', 24, {
    inflections: ['aumenta', 'aumentano', 'aumentato', 'aumentava'],
  }),
  L('telefonare', 'telefonare', 'to call (by phone)', 'verb', 24, {
    inflections: ['telefoni', 'telefona', 'telefoniamo', 'telefonato'],
  }),
  L('funzionare', 'funzionare', 'to work / to function', 'verb', 32, {
    inflections: ['funziona', 'funzionano', 'funzionava', 'funzionato'],
  }),
  L('lettera', 'lettera', 'letter', 'noun', 40),
  L('futuro', 'futuro', 'future', 'noun', 40, { abstractness: 'abstract' }),
  L('proposta', 'proposta', 'proposal', 'noun', 36),
  L('fino', 'fino', 'until / up to', 'preposition', 29),
  L('durante', 'durante', 'during', 'preposition', 32),
  L('piu', 'più', 'more', 'adverb', 21, { frequency: 'high', inflections: ['più', 'Più'] }),
  L('meno', 'meno', 'less', 'adverb', 25),
  L('qualche', 'qualche', 'some', 'adjective', 22),
  L('proprio', 'proprio', 'really / own', 'adverb', 26),
  L('paura', 'paura', 'fear', 'noun', 28),
  L('dormire', 'dormire', 'to sleep', 'verb', 21, { inflections: ['dormo', 'dorme', 'dormiamo', 'dormito', 'dormiva'] }),
  L('scrivere', 'scrivere', 'to write', 'verb', 24, { inflections: ['scrivo', 'scrive', 'scriviamo', 'scritto', 'scriveva'] }),
  L('continuare', 'continuare', 'to continue', 'verb', 22, {
    inflections: ['continuo', 'continua', 'continuiamo', 'continuato', 'continuata', 'continuava'],
  }),
  L('fermare', 'fermare', 'to stop', 'verb', 23, {
    inflections: ['fermo', 'ferma', 'fermiamo', 'fermato', 'fermata', 'fermati', 'fermava'],
  }),
  L('finire', 'finire', 'to finish', 'verb', 27, {
    inflections: ['finisco', 'finisce', 'finiamo', 'finito', 'finita', 'finiva'],
  }),
  L('cominciare', 'cominciare', 'to begin', 'verb', 21, {
    inflections: ['comincio', 'comincia', 'cominciamo', 'cominciato', 'cominciava'],
  }),
  L('mettere', 'mettere', 'to put', 'verb', 24, {
    inflections: ['metto', 'mette', 'mettiamo', 'messo', 'messa', 'metteva'],
  }),
  L('sedere', 'sedere', 'to sit', 'verb', 23, {
    inflections: ['siedo', 'siede', 'sediamo', 'seduto', 'seduta', 'seduti'],
  }),
  L('davanti', 'davanti', 'in front of', 'adverb', 23),
  L('almeno', 'almeno', 'at least', 'adverb', 31),
  L('finalmente', 'finalmente', 'finally', 'adverb', 32),
  L('verso', 'verso', 'toward', 'preposition', 29),
  L('sotto', 'sotto', 'under', 'preposition', 23),
  L('cena', 'cena', 'dinner', 'noun', 24),
  L('cuore', 'cuore', 'heart', 'noun', 28),
  L('forte', 'forte', 'strong / loud', 'adjective', 28, { inflections: ['forti'] }),
  L('giovane', 'giovane', 'young', 'adjective', 30, { inflections: ['giovani'] }),
  L('pane', 'pane', 'bread', 'noun', 31),
  L('vino', 'vino', 'wine', 'noun', 39),
  L('musica', 'musica', 'music', 'noun', 30),
  L('voce', 'voce', 'voice', 'noun', 26, { inflections: ['voci'] }),
  L('luce', 'luce', 'light', 'noun', 28, { inflections: ['luci'] }),
  L('venerdi', 'venerdì', 'Friday', 'noun', 25, { inflections: ['venerdì'] }),
  L('giovedi', 'giovedì', 'Thursday', 'noun', 25, { inflections: ['giovedì'] }),
  L('parte', 'parte', 'part', 'noun', 32, { inflections: ['parti'] }),
  L('pieno', 'pieno', 'full', 'adjective', 32, { inflections: ['piena', 'pieni'] }),
  L('vuoto', 'vuoto', 'empty', 'adjective', 32, { inflections: ['vuota', 'vuoti'] }),
  L('signore', 'signore', 'sir / gentleman', 'noun', 22, { inflections: ['signora'] }),
  L('ordine', 'ordine', 'order', 'noun', 34),
  L('piatto', 'piatto', 'plate / dish', 'noun', 34, { inflections: ['piatti'] }),
  L('cinque', 'cinque', 'five', 'number', 34),
  L('dieci', 'dieci', 'ten', 'number', 34),
  L('quattro', 'quattro', 'four', 'number', 31),
  L('sala', 'sala', 'room / hall', 'noun', 34),
  L('cucina', 'cucina', 'kitchen', 'noun', 31),
  L('lavare', 'lavare', 'to wash', 'verb', 34, { inflections: ['lavo', 'lava', 'laviamo', 'lavato'] }),
  L('cucinare', 'cucinare', 'to cook', 'verb', 24, { inflections: ['cucino', 'cuciniamo', 'cucinato'] }),
  L('svegliare', 'svegliare', 'to wake', 'verb', 21, {
    inflections: ['sveglio', 'sveglia', 'svegliato', 'svegliata'],
  }),
  L('finestra', 'finestra', 'window', 'noun', 21, { inflections: ['finestre'] }),
  L('diverso', 'diverso', 'different', 'adjective', 21, { inflections: ['diversa', 'diversi', 'diverse'] }),
  L('sorridere', 'sorridere', 'to smile', 'verb', 21, { inflections: ['sorride', 'sorriso', 'sorridiva', 'sorridiva'] }),
  L('orario', 'orario', 'schedule / on time', 'noun', 21),
  L('lunedi', 'lunedì', 'Monday', 'noun', 21, { inflections: ['lunedì'] }),
  L('martedi', 'martedì', 'Tuesday', 'noun', 26, { inflections: ['martedì'] }),
  L('mercoledi', 'mercoledì', 'Wednesday', 'noun', 27, { inflections: ['mercoledì'] }),
  L('fretta', 'fretta', 'hurry', 'noun', 22),
  L('lontano', 'lontano', 'far', 'adjective', 22, { inflections: ['lontana'] }),
  L('strano', 'strano', 'strange', 'adjective', 25, { inflections: ['strana'] }),
  L('calma', 'calma', 'calm', 'noun', 23),
  L('anno', 'anno', 'year', 'noun', 29, { inflections: ['anni'] }),
  L('occupato', 'occupato', 'busy', 'adjective', 23, { inflections: ['occupata'] }),
  L('leggere', 'leggere', 'to read', 'verb', 25, { inflections: ['leggo', 'legge', 'leggiamo', 'letto'] }),
  L('contare', 'contare', 'to count', 'verb', 25, { inflections: ['conta', 'contiamo', 'contato'] }),
  L('tanto', 'tanto', 'so much / many', 'adverb', 22, { inflections: ['tanti', 'tante', 'tanta'] }),
  L('parola', 'parola', 'word', 'noun', 26, { inflections: ['parole'] }),
  L('chiaro', 'chiaro', 'clear', 'adjective', 32, { inflections: ['chiara', 'chiari'] }),
  L('vero', 'vero', 'true / real', 'adjective', 36, { inflections: ['vera', 'vere', 'veri'] }),
  L('segno', 'segno', 'sign', 'noun', 33),
  L('carta', 'carta', 'paper / letter paper', 'noun', 40),
  L('vita', 'vita', 'life', 'noun', 21),
  L('modo', 'modo', 'way', 'noun', 31),
  L('subito', 'subito', 'immediately', 'adverb', 37),
  L('alcuno', 'alcuno', 'some / a few', 'adjective', 38, { inflections: ['alcuna', 'alcuni', 'alcune'] }),
  L('lungo', 'lungo', 'long', 'adjective', 25),
  L('quanto', 'quanto', 'how much / how long', 'adverb', 26),
  L('provare', 'provare', 'to try', 'verb', 30, { inflections: ['provo', 'provi', 'prova', 'proviamo', 'provato'] }),
  L('giornata', 'giornata', 'day (the whole day)', 'noun', 25),
  L('rumore', 'rumore', 'noise', 'noun', 38),
  L('sorpreso', 'sorpreso', 'surprised', 'adjective', 35),
];

module.exports = { inflections, lemmas };
