const { N, D, PH, Q } = require('./story-helpers');

function ch(n, title, titleIt, locationIds, characterIds, event, paragraphs, questions) {
  return {
    id: `luca-a-roma-${String(n).padStart(2, '0')}`,
    number: n,
    title,
    titleIt,
    locationIds,
    characterIds,
    events: [event],
    paragraphs,
    questions,
  };
}

const ev = (id, summary, characterIds, locationIds, rememberedFacts) => ({
  id,
  summary,
  characterIds,
  locationIds,
  rememberedFacts,
});

const chapters = [
  ch(
    31,
    'Messages',
    'Messaggi',
    ['quartiere', 'lavoro-caffe', 'appartamento-luca'],
    ['luca', 'sofia', 'marco', 'giulia'],
    ev('ev-31-organize', 'The friends organize: messages, food, and people in the neighborhood.', ['luca', 'sofia', 'marco', 'giulia'], ['quartiere', 'lavoro-caffe'], ['Sofia writes messages', 'Marco helps in the neighborhood']),
    [
      [
        N('Il giorno dopo il gruppo ha cominciato a organizzare la festa.', 'The next day the group began to organize the celebration.'),
        N('Sofia ha scritto messaggi alle persone del quartiere, una dopo l’altra.', 'Sofia wrote messages to people in the neighborhood, one after another.'),
        D('sofia', 'Dico che sabato c’è caffè, pane e amici. Non costa tanto.', 'I say that on Saturday there is coffee, bread, and friends. It does not cost much.'),
        D('marco', 'Io cammino e parlo con la gente. Qualche persona ascolta, qualche persona no.', 'I walk and talk with people. Some people listen, some do not.'),
        N('Luca era al lavoro, e però pensava già a sabato.', 'Luca was at work, and yet he was already thinking about Saturday.'),
        N('Ogni messaggio era piccolo, e insieme potevano essere tanti.', 'Every message was small, and together they could be many.'),
      ],
      [
        N('Giulia ha preparato un piano per la sala: tavoli, luce, un posto per la musica.', 'Giulia prepared a plan for the room: tables, light, a place for the music.'),
        D('giulia', 'Se la gente viene, dobbiamo essere pronti. Io resto vicino alla cucina.', 'If people come, we must be ready. I stay near the kitchen.'),
        D('luca', 'Io posso stare alla porta e dire buongiorno. Ci penso io.', 'I can stay at the door and say good morning. I’ll take care of it.', [PH('Ci penso io', 'I think about it I', 'I’ll take care of it')]),
        D('sofia', 'E io parlo con le persone. Conosco questo quartiere.', 'And I talk with people. I know this neighborhood.'),
        N('Marco ha sorriso, stanco ma contento di avere una cosa da fare.', 'Marco smiled, tired but glad to have something to do.'),
        N('Per la prima volta dopo tanti giorni, il problema aveva un ordine.', 'For the first time after many days, the problem had an order.'),
      ],
      [
        N('Nel pomeriggio Luca ha dimenticato di dire una cosa a Giulia.', 'In the afternoon Luca forgot to tell Giulia something.'),
        N('Sofia aveva chiesto pane a un negozio, e Luca doveva dirlo al lavoro.', 'Sofia had asked a shop for bread, and Luca had to say it at work.'),
        D('giulia', 'Il pane? Non lo so. Tu non hai detto niente questa mattina.', 'The bread? I don’t know. You didn’t say anything this morning.', [PH('Non lo so', 'I it not know', 'I don’t know')]),
        D('luca', 'Scusa. Ho dimenticato. Adesso lo dico. Non c’è problema, vero?', 'Sorry. I forgot. I’ll say it now. No problem, right?', [PH('Non c’è problema', 'there is not problem', 'no problem')]),
        D('giulia', 'Va bene. Ma sabato non possiamo dimenticare le cose importanti.', 'All right. But on Saturday we cannot forget the important things.', [PH('Va bene', 'it goes well', 'okay')]),
        N('Luca ha capito. Organizzare non era solo un’idea. Era lavoro, come il caffè.', 'Luca understood. Organizing was not only an idea. It was work, like the café.'),
      ],
      [
        N('La sera i quattro amici si sono incontrati un momento in piazza.', 'In the evening the four friends met for a moment in the square.'),
        D('sofia', 'Qualche persona viene. Non tutte, ma qualche persona sì.', 'Some people are coming. Not all, but some people yes.'),
        D('marco', 'Io ho parlato con un signore vicino ai negozi. Ha detto “vediamo”.', 'I spoke with a man near the shops. He said “we’ll see”.', [PH('vediamo', 'we see', 'we’ll see')]),
        D('luca', 'Meglio di niente. Domani continuiamo.', 'Better than nothing. Tomorrow we continue.'),
        N('Roma era piena di luci, e il gruppo era stanco in un modo buono.', 'Rome was full of lights, and the group was tired in a good way.'),
        N('La festa non era ancora arrivata, e però era già iniziata così.', 'The celebration had not arrived yet, and yet it had already begun like this.'),
      ],
    ],
    [
      Q('event', 'How do they organize the Saturday gathering?', ['Messages, talking in the neighborhood, and a plan for the room', 'They buy a train', 'They close the café'], 0, 'Sofia writes, Marco walks, Giulia plans the room.'),
      Q('character', 'What does Luca forget?', ['To tell Giulia about the bread', 'His key', 'Sofia’s name'], 0, 'Sofia asked a shop for bread; he did not say it at work.'),
      Q('direct', 'Where does Luca want to stay during the gathering?', ['At the door', 'At home', 'At the station'], 0, 'He will say buongiorno at the door.'),
    ],
  ),
  ch(
    32,
    'It gets harder',
    'Diventa più difficile',
    ['lavoro-caffe'],
    ['luca', 'giulia', 'padrone'],
    ev('ev-32-harder', 'The plan gets more complicated: few replies, a tired owner, Giulia wants more hours.', ['luca', 'giulia', 'padrone'], ['lavoro-caffe'], ['Few people have confirmed', 'Giulia asks for more hours if the café stays']),
    [
      [
        N('Due giorni dopo, la festa era più vicina, e i problemi erano più chiari.', 'Two days later, the celebration was closer, and the problems were clearer.'),
        N('Poche persone avevano detto sì. Tante avevano detto “forse” o niente.', 'Few people had said yes. Many had said “maybe” or nothing.'),
        D('giulia', 'Se viene poca gente, il padrone vede una sala vuota. È peggio.', 'If few people come, the owner sees an empty room. It is worse.'),
        D('luca', 'Hai ragione. Dobbiamo fare di più, non solo aspettare messaggi.', 'You’re right. We must do more, not only wait for messages.', [PH('Hai ragione', 'you have reason', 'you’re right')]),
        N('Il padrone ascoltava da vicino e non sorridiva.', 'The owner was listening nearby and was not smiling.'),
        N('La sala, durante il giorno, era ancora quasi vuota.', 'The room, during the day, was still almost empty.'),
      ],
      [
        D('padrone', 'Io sono stanco. Una festa è una cosa bella, ma il caffè deve funzionare ogni giorno.', 'I am tired. A celebration is a nice thing, but the café must work every day.'),
        D('luca', 'Lo sappiamo. Per questo vogliamo le persone qui, non solo sabato.', 'We know. That is why we want people here, not only on Saturday.'),
        D('giulia', 'Se il caffè resta, io voglio lavorare di più. Non solo poche ore.', 'If the café stays, I want to work more. Not only a few hours.'),
        N('Il padrone ha guardato Giulia. Non ha detto di no, e non ha detto di sì.', 'The owner looked at Giulia. He did not say no, and he did not say yes.'),
        D('padrone', 'Prima vediamo sabato. Poi parliamo di ore e di soldi.', 'First we see Saturday. Then we talk about hours and money.', [PH('vediamo', 'we see', 'we’ll see')]),
        N('Giulia ha accettato, ma Luca ha visto che per lei era importante.', 'Giulia accepted, but Luca saw that it mattered to her.'),
      ],
      [
        N('Nel pomeriggio un cliente ha chiesto se il caffè chiudeva.', 'In the afternoon a customer asked if the café was closing.'),
        D('luca', 'Non ancora. Sabato c’è una festa piccola. Può venire, se vuole.', 'Not yet. Saturday there is a small celebration. You can come, if you want.'),
        N('Il cliente ha sorriso e ha detto che forse veniva con la famiglia.', 'The customer smiled and said he might come with the family.'),
        N('Una famiglia non è tanta gente, e però era una notizia buona.', 'One family is not many people, and yet it was good news.'),
        D('giulia', 'Vedi? Se parliamo, qualcuno ascolta. Dipende da noi, in parte.', 'See? If we talk, someone listens. It depends on us, in part.', [PH('Dipende', 'it depends', 'it depends')]),
        N('Luca ha messo questa cosa nel cuore: parlare era già un lavoro.', 'Luca put this in his heart: talking was already a job.'),
      ],
      [
        N('La sera Luca ha chiamato Sofia e ha spiegato i nuovi problemi.', 'In the evening Luca called Sofia and explained the new problems.'),
        D('sofia', 'Allora domani io e Marco andiamo di nuovo nel quartiere. Non importa se siamo stanchi.', 'Then tomorrow Marco and I go into the neighborhood again. It doesn’t matter if we are tired.', [PH('Non importa', 'it does not matter', 'it doesn’t matter')]),
        D('luca', 'Grazie. Io resto al caffè. Il padrone ha bisogno di vedere il nostro lavoro.', 'Thanks. I stay at the café. The owner needs to see our work.'),
        N('Dopo la chiamata Luca ha guardato la sua piccola casa e ha pensato all’affitto.', 'After the call Luca looked at his small home and thought about the rent.'),
        N('Se sabato non funzionava, il futuro del lavoro era difficile.', 'If Saturday did not work, the future of the job was hard.'),
        N('E però adesso non era solo. Questo cambiava la paura.', 'And yet now he was not alone. This changed the fear.'),
      ],
    ],
    [
      Q('event', 'What new problem appears?', ['Few people have said yes, and the owner is tired', 'Marco lost a suitcase', 'Sofia left Rome'], 0, 'Many replies are “maybe” or nothing.'),
      Q('character', 'What does Giulia want if the café stays?', ['More hours of work', 'To sell the café', 'A train ticket'], 0, 'She does not want only a few hours.'),
      Q('inference', 'Why does Luca stay at the café the next day?', ['So the owner sees them working', 'Because he forgot Sofia', 'Because he is angry'], 0, 'He says the owner needs to see them work.'),
    ],
  ),
  ch(
    33,
    'Where is Marco?',
    'Dov’è Marco?',
    ['lavoro-caffe', 'quartiere', 'strada'],
    ['luca', 'sofia', 'marco', 'giulia'],
    ev('ev-33-marco-late', 'Marco is late; friends look for him; he was at a small work talk.', ['luca', 'sofia', 'marco', 'giulia'], ['quartiere'], ['Marco was late because he was looking for work', 'They still need him for Saturday']),
    [
      [
        N('Il giorno dopo Sofia e Marco avevano un appuntamento in piazza, ma Marco non c’era.', 'The next day Sofia and Marco had an appointment in the square, but Marco was not there.'),
        N('Sofia ha aspettato, ha guardato la strada, e poi ha chiamato Luca.', 'Sofia waited, looked at the street, and then called Luca.'),
        D('sofia', 'Marco non arriva. Hai sue notizie?', 'Marco is not arriving. Do you have news of him?'),
        D('luca', 'No. Ieri ha detto di venire. Adesso cerco. Aspetta lì.', 'No. Yesterday he said he would come. I’ll look now. Wait there.'),
        N('Luca ha chiesto a Giulia di restare al caffè e è uscito.', 'Luca asked Giulia to stay at the café and went out.'),
        N('Mentre camminava, aveva un po’ di paura. Marco aveva già avuto problemi.', 'While he walked, he was a little afraid. Marco had already had problems.'),
      ],
      [
        N('Luca ha cercato vicino ai negozi e vicino alla stazione del quartiere.', 'Luca looked near the shops and near the neighborhood station.'),
        N('Non l’ha trovato. Poi ha visto Sofia, ancora in piazza, stanca di aspettare.', 'He did not find him. Then he saw Sofia, still in the square, tired of waiting.'),
        D('sofia', 'Forse ha dimenticato. O forse ha un problema di soldi e non vuole dirlo.', 'Maybe he forgot. Or maybe he has a money problem and does not want to say it.'),
        D('luca', 'Lo cerchiamo ancora un po’. Poi dobbiamo tornare al lavoro.', 'We’ll look a little more. Then we must go back to work.'),
        N('Hanno camminato insieme, e dopo un’ora hanno visto Marco vicino a un ufficio piccolo.', 'They walked together, and after an hour they saw Marco near a small office.'),
        N('Marco li ha visti e si è fermato, senza parole.', 'Marco saw them and stopped, without words.'),
      ],
      [
        D('marco', 'Scusa. C’era una persona per un lavoro. Dovevo parlare. Non ho visto l’orario.', 'Sorry. There was a person about a job. I had to talk. I did not see the time.'),
        D('sofia', 'Potevi chiamare. Noi ti aspettavamo.', 'You could have called. We were waiting for you.'),
        D('marco', 'Hai ragione. Ho pensato solo a me. Non è giusto.', 'You’re right. I thought only of myself. It is not right.', [PH('Hai ragione', 'you have reason', 'you’re right')]),
        N('Luca ha ascoltato. Il lavoro di Marco era importante, e però gli amici anche.', 'Luca listened. Marco’s work was important, and yet friends were too.'),
        D('luca', 'Va bene. Adesso sei qui. Che notizia c’è, del lavoro?', 'All right. Now you are here. What news is there, about the job?', [PH('Va bene', 'it goes well', 'okay')]),
        D('marco', 'Niente di sicuro. Hanno detto “vediamo”. Come il signore del quartiere.', 'Nothing sure. They said “we’ll see”. Like the man in the neighborhood.', [PH('vediamo', 'we see', 'we’ll see')]),
      ],
      [
        N('I tre sono tornati verso il caffè. Giulia li ha guardati dalla porta.', 'The three went back toward the café. Giulia looked at them from the door.'),
        D('giulia', 'Allora? Sabato abbiamo bisogno di te, Marco. Non di “vediamo”.', 'So? Saturday we need you, Marco. Not “we’ll see”.'),
        D('marco', 'Ci sono. Lo ricordo. Non dimentico più.', 'I am here. I remember. I will not forget again.'),
        N('Sofia ha sorriso un poco. Il problema era risolto per oggi, non per sempre.', 'Sofia smiled a little. The problem was solved for today, not forever.'),
        N('Luca ha pensato che gli amici erano così: a volte tardi, a volte forti.', 'Luca thought that friends were like that: sometimes late, sometimes strong.'),
        N('Prima di sera hanno ancora parlato con due persone del quartiere.', 'Before evening they still talked with two people from the neighborhood.'),
      ],
    ],
    [
      Q('event', 'Why is Marco late?', ['He was talking about a possible job', 'He left Rome', 'He was at Nonna Rosa’s house'], 0, 'He lost track of time at a small office.'),
      Q('sequence', 'What do Luca and Sofia do first?', ['They look for Marco, then go back to the café', 'They close the café', 'They take a train'], 0, 'Sofia waits; Luca searches; they find him.'),
      Q('character', 'What does Giulia tell Marco?', ['Saturday they need him, not “we’ll see”', 'He should sell the café', 'He should stay home'], 0, 'She is direct about Saturday.'),
    ],
  ),
  ch(
    34,
    'Saturday morning',
    'Sabato mattina',
    ['lavoro-caffe'],
    ['luca', 'giulia', 'marco', 'sofia', 'padrone'],
    ev('ev-34-prep', 'Saturday morning they prepare the café: tables, food, music.', ['luca', 'giulia', 'marco', 'sofia', 'padrone'], ['lavoro-caffe'], ['The group prepares the festa', 'The owner watches but helps a little']),
    [
      [
        N('Sabato mattina Luca si è svegliato presto e ha aperto la finestra.', 'Saturday morning Luca woke up early and opened the window.'),
        N('Roma era già piena di luce. Oggi non era un giorno come gli altri.', 'Rome was already full of light. Today was not a day like the others.'),
        N('Ha camminato al caffè e ha trovato Giulia già dentro, con i tavoli aperti.', 'He walked to the café and found Giulia already inside, with the tables open.'),
        D('giulia', 'Buongiorno. Oggi lavoriamo di più, e però è una cosa nostra.', 'Good morning. Today we work more, and yet it is our thing.'),
        D('luca', 'Sì. Ho paura e sono contento. È strano, vero?', 'Yes. I am afraid and I am glad. It is strange, right?'),
        D('giulia', 'Un po’. Dai. Portiamo i tavoli più vicini. La sala deve sembrare piena.', 'A little. Come on. Let’s bring the tables closer. The room must seem full.'),
      ],
      [
        N('Marco è arrivato in orario, con pane di un negozio e più tranquillo.', 'Marco arrived on time, with bread from a shop and calmer.'),
        D('marco', 'Il pane c’è. Non ho dimenticato. E ho dormito poco, ma sono qui.', 'The bread is here. I did not forget. And I slept little, but I am here.'),
        N('Sofia è arrivata dopo, con messaggi nuovi: qualche persona veniva nel pomeriggio.', 'Sofia arrived after, with new messages: some people were coming in the afternoon.'),
        D('sofia', 'Nonna Rosa viene. Ha detto che porta anche una vecchia amica.', 'Nonna Rosa is coming. She said she is also bringing an old friend.'),
        N('Il padrone ha guardato il pane, i tavoli e i giovani, senza dire troppo.', 'The owner looked at the bread, the tables, and the young people, without saying too much.'),
        D('padrone', 'Va bene. Io resto in cucina. Se serve, chiamo.', 'All right. I stay in the kitchen. If needed, I call.', [PH('Va bene', 'it goes well', 'okay')]),
      ],
      [
        N('Hanno messo i piatti, l’acqua, il caffè. Luca ha lavato i tavoli due volte.', 'They put out the plates, the water, the coffee. Luca washed the tables twice.'),
        N('Giulia ha scelto un posto per la musica, non troppo forte, vicino alla finestra.', 'Giulia chose a place for the music, not too loud, near the window.'),
        D('luca', 'Che ne dici? Così le persone possono parlare.', 'What do you say? This way people can talk.', [PH('Che ne dici?', 'what of it do you say', 'what do you say?')]),
        D('giulia', 'Mi sembra giusto.', 'It seems right to me.', [PH('Mi sembra', 'it seems to me', 'it seems to me')]),
        N('Marco ha preparato il pane, e Sofia ha scritto un piccolo segno sulla porta.', 'Marco prepared the bread, and Sofia wrote a small sign on the door.'),
        N('Sulla porta c’era una cosa piccola: “Oggi, festa. Venite.”', 'On the door there was a small thing: “Today, celebration. Come.”'),
      ],
      [
        N('Prima, la gente non c’era. C’era un momento tranquillo.', 'At first, people were not there. There was a quiet moment.'),
        N('Luca ha guardato i suoi amici e ha pensato al primo giorno a Roma, alla stazione.', 'Luca looked at his friends and thought of the first day in Rome, at the station.'),
        N('Adesso aveva una casa, un lavoro, e una sala da preparare insieme.', 'Now he had a home, a job, and a room to prepare together.'),
        D('sofia', 'Se viene poca gente, non importa. Abbiamo fatto una cosa.', 'If few people come, it doesn’t matter. We did something.', [PH('non importa', 'it does not matter', 'it doesn’t matter')]),
        D('luca', 'Sì. Però io voglio gente qui. Per Giulia, per il padrone, per noi.', 'Yes. But I want people here. For Giulia, for the owner, for us.'),
        N('Fuori, la strada del quartiere cominciava a essere più viva.', 'Outside, the neighborhood street was beginning to be more alive.'),
      ],
    ],
    [
      Q('event', 'What do they do on Saturday morning?', ['They prepare tables, bread, music, and a sign', 'They take a train', 'They sell the café'], 0, 'Everyone has a job in the room.'),
      Q('character', 'Who arrives on time with bread?', ['Marco', 'The owner', 'Luca’s dad'], 0, 'Marco did not forget.'),
      Q('direct', 'What does the sign on the door say?', ['Today, small celebration. Come in.', 'Closed', 'For sale'], 0, 'Sofia writes a simple sign.'),
    ],
  ),
  ch(
    35,
    'The room fills',
    'La sala si riempie',
    ['lavoro-caffe'],
    ['luca', 'giulia', 'sofia', 'marco', 'padrone', 'nonna-rosa'],
    ev('ev-35-festa', 'The gathering starts slowly, then the room fills with neighborhood people.', ['luca', 'giulia', 'sofia', 'marco', 'padrone', 'nonna-rosa'], ['lavoro-caffe'], ['People come in the afternoon', 'Nonna Rosa arrives']),
    [
      [
        N('Nel primo pomeriggio la sala era ancora quasi vuota.', 'In the early afternoon the room was still almost empty.'),
        N('Luca stava alla porta e diceva buongiorno a chi passava, ma pochi entravano.', 'Luca stood at the door and said good morning to people who passed, but few came in.'),
        D('luca', 'Forse non viene nessuno.', 'Maybe nobody is coming.'),
        D('sofia', 'Aspetta. È presto. Le persone del quartiere mangiano e poi escono.', 'Wait. It is early. Neighborhood people eat and then go out.'),
        N('Giulia ha portato caffè a un tavolo vuoto, solo per fare qualcosa.', 'Giulia brought coffee to an empty table, only to do something.'),
        N('Il padrone guardava dalla cucina, senza sorridere.', 'The owner watched from the kitchen, without smiling.'),
      ],
      [
        N('Poi è arrivata Nonna Rosa, con un’amica vecchia e con una voce forte.', 'Then Nonna Rosa arrived, with an old friend and with a strong voice.'),
        D('nonna-rosa', 'Allora, siamo qui. Dov’è il caffè? E il pane?', 'So, we are here. Where is the coffee? And the bread?'),
        N('Marco ha sorriso e ha portato pane e acqua. La sala non era più del tutto vuota.', 'Marco smiled and brought bread and water. The room was no longer completely empty.'),
        N('Dopo Nonna Rosa sono arrivate tre persone del quartiere, poi una famiglia.', 'After Nonna Rosa three neighborhood people arrived, then a family.'),
        D('giulia', 'Vedi? Adesso comincia.', 'See? Now it begins.'),
        N('Luca ha sentito il cuore più tranquillo, e ha continuato a stare alla porta.', 'Luca felt his heart calmer, and he continued to stay at the door.'),
      ],
      [
        N('In un’ora la sala era quasi piena. C’era musica, voci, e c’era caffè.', 'In an hour the room was almost full. There was music, voices, and there was coffee.'),
        N('Sofia parlava con la gente. Giulia serviva. Marco aiutava con i piatti.', 'Sofia talked with people. Giulia served. Marco helped with the plates.'),
        N('Il padrone è uscito dalla cucina e ha guardato i tavoli pieni, un po’ sorpreso.', 'The owner came out of the kitchen and looked at the full tables, a little surprised.'),
        D('padrone', 'Tanta gente. Non lo vedevo da tanto tempo.', 'So many people. I had not seen this for a long time.'),
        D('luca', 'Sono persone del quartiere. Volevano una ragione per venire.', 'They are neighborhood people. They wanted a reason to come.'),
        N('Una signora ha detto che il caffè le piaceva, e che tornava la settimana dopo.', 'A woman said she liked the café, and that she would come back the next week.'),
      ],
      [
        N('Luca ha portato acqua a un tavolo e ha ascoltato le persone parlare di Roma, di casa, di lavoro.', 'Luca brought water to a table and listened to people talk about Rome, home, work.'),
        N('Non capiva tutte le parole, e però capiva la cosa importante: la sala viveva.', 'He did not understand all the words, and yet he understood the important thing: the room was alive.'),
        D('sofia', 'Tu stai bene alla porta. Le persone ti vedono e entrano.', 'You are good at the door. People see you and come in.'),
        D('luca', 'Grazie. Oggi non sono il ragazzo nuovo. Oggi sono qui con voi.', 'Thanks. Today I am not the new guy. Today I am here with you.'),
        N('Fuori era ancora giorno. Dentro, il caffè non era più un posto vuoto.', 'Outside it was still day. Inside, the café was no longer an empty place.'),
        N('La festa piccola funzionava, almeno per queste ore.', 'The small celebration was working, at least for these hours.'),
      ],
    ],
    [
      Q('sequence', 'What happens first in the afternoon?', ['The room is almost empty, then Nonna Rosa arrives', 'The owner sells the café', 'Everyone leaves'], 0, 'It starts slow; then people come.'),
      Q('event', 'How does the owner react when the room fills?', ['He is a little surprised; he had not seen this in a long time', 'He closes the door', 'He leaves Rome'], 0, 'He comes out of the kitchen.'),
      Q('inference', 'What does Luca understand even if he misses some words?', ['That the room is alive and people wanted a reason to come', 'That he must leave the job', 'That Marco is gone'], 0, 'The important thing is the living room of people.'),
    ],
  ),
  ch(
    36,
    'Luca speaks',
    'Luca parla',
    ['lavoro-caffe'],
    ['luca', 'giulia', 'sofia', 'marco', 'padrone', 'nonna-rosa'],
    ev('ev-36-speak', 'Luca speaks to the room; the owner listens; the gathering becomes a reason to stay.', ['luca', 'giulia', 'padrone', 'nonna-rosa'], ['lavoro-caffe'], ['Luca speaks in front of people', 'The padrone hears that the neighborhood cares']),
    [
      [
        N('Più tardi, quando la sala era piena, Giulia ha fatto un segno a Luca.', 'Later, when the room was full, Giulia made a sign to Luca.'),
        D('giulia', 'Parla. Due parole. Le persone sono qui anche per questo posto.', 'Speak. Two words. People are here also for this place.'),
        D('luca', 'Io? Non so. Ho paura.', 'Me? I don’t know. I am afraid.'),
        D('sofia', 'Ci pensiamo noi, se vuoi. Ma mi sembra che tu puoi.', 'We’ll take care of it, if you want. But it seems to me that you can.', [
          PH('mi sembra', 'it seems to me', 'it seems to me'),
        ]),
        N('Luca ha guardato Nonna Rosa. Lei ha sorriso e ha detto, senza fretta: “Va bene così.”', 'Luca looked at Nonna Rosa. She smiled and said, without hurry: “It’s all right like this.”'),
        N('Allora Luca si è fermato nella sala, con il cuore forte.', 'Then Luca stopped in the room, with a strong heart.'),
      ],
      [
        D('luca', 'Buona sera. Io lavoro qui. Qualche mese fa sono arrivato a Roma, solo.', 'Good evening. I work here. A few months ago I arrived in Rome, alone.'),
        D('luca', 'Adesso ho una casa, un lavoro e amici. Questo caffè è una parte di tutto questo.', 'Now I have a home, a job, and friends. This café is a part of all this.'),
        D('luca', 'Se vi piace, tornate. Non solo oggi. Anche lunedì, anche giovedì.', 'If you like it, come back. Not only today. Also Monday, also Thursday.'),
        N('Qualche persona ha sorriso. Qualche persona ha detto “bene” piano.', 'Some people smiled. Some people said “good” quietly.'),
        N('Il padrone ascoltava vicino alla cucina, senza parlare.', 'The owner was listening near the kitchen, without speaking.'),
        N('Marco ha portato un caffè a Nonna Rosa, e lei ha ascoltato Luca come ascolta le cose vere.', 'Marco brought a coffee to Nonna Rosa, and she listened to Luca as she listens to true things.'),
      ],
      [
        N('Dopo le parole, la festa è continuata. La musica non era troppo forte. Le persone restavano.', 'After the words, the celebration continued. The music was not too loud. People stayed.'),
        D('nonna-rosa', 'Hai detto poco, e hai detto tanto. Va bene.', 'You said little, and you said a lot. All right.', [PH('Va bene', 'it goes well', 'okay')]),
        D('giulia', 'Il padrone ti ha ascoltato. L’ho visto.', 'The owner listened to you. I saw it.'),
        D('luca', 'Va bene. Io volevo solo dire una cosa vera.', 'All right. I only wanted to say a true thing.'),
        N('Una famiglia ha chiesto l’orario della settimana. Giulia ha spiegato, contenta di fare di più.', 'A family asked about the week’s hours. Giulia explained, glad to do more.'),
        N('Sofia era vicino a Luca, non come una persona che aiuta un ragazzo nuovo, ma come un’amica.', 'Sofia was near Luca, not as a person who helps a new guy, but as a friend.'),
      ],
      [
        N('Quando la luce fuori è cambiata, qualche persona è partita, e qualche persona è restata ancora.', 'When the light outside changed, some people left, and some people stayed still.'),
        D('padrone', 'Oggi il caffè ha funzionato. Non so ancora il futuro. Ma oggi sì.', 'Today the café worked. I still don’t know the future. But today, yes.'),
        D('luca', 'Grazie per aver detto sì a questa festa.', 'Thanks for having said yes to this celebration.'),
        D('padrone', 'Voi avete fatto il lavoro. Io ho solo aperto la cucina.', 'You did the work. I only opened the kitchen.'),
        N('Luca ha capito che il padrone non era un problema da risolvere come un biglietto.', 'Luca understood that the owner was not a problem to solve like a ticket.'),
        N('Era una persona stanca, e oggi aveva visto di nuovo la sua sala piena.', 'He was a tired person, and today he had seen his room full again.'),
      ],
    ],
    [
      Q('event', 'What does Luca do in front of the people?', ['He speaks about his life in Rome and asks them to come back', 'He sells the café', 'He leaves with Marco'], 0, 'He says the café is part of his home, job, and friends.'),
      Q('character', 'How is Sofia standing with Luca now?', ['As a friend, not only as a helper', 'As his boss', 'As a stranger'], 0, 'She is near him as an equal friend.'),
      Q('direct', 'What does the owner say about the future?', ['He still does not know, but today the café worked', 'He will sell tomorrow', 'He will leave Rome'], 0, 'Today yes; the future is still open.'),
    ],
  ),
  ch(
    37,
    'More hours',
    'Più ore',
    ['lavoro-caffe'],
    ['luca', 'giulia', 'padrone'],
    ev('ev-37-hours', 'After the festa, more customers come; the owner will not sell and offers more hours.', ['luca', 'giulia', 'padrone'], ['lavoro-caffe'], ['The padrone will not sell', 'Luca and Giulia get more hours']),
    [
      [
        N('Lunedì mattina Luca è andato al lavoro con un po’ di paura. Una festa è un giorno. Il lunedì è la vita.', 'Monday morning Luca went to work a little afraid. A celebration is one day. Monday is life.'),
        N('Quando ha aperto la porta, c’erano già due clienti a un tavolo.', 'When he opened the door, there were already two customers at a table.'),
        N('Non era una sala piena, e però non era vuota come la settimana prima.', 'It was not a full room, and yet it was not empty like the week before.'),
        D('giulia', 'Buongiorno. Vedi? Qualcuno è tornato.', 'Good morning. See? Someone came back.'),
        D('luca', 'Sì. Mi sembra un primo giorno vero, anche se piccolo.', 'Yes. It seems like a real first day to me, even if small.', [PH('Mi sembra', 'it seems to me', 'it seems to me')]),
        N('Hanno lavorato. Il caffè, l’acqua, i conti. Cose di ogni giorno, ma diverse.', 'They worked. Coffee, water, bills. Everyday things, but different.'),
      ],
      [
        N('Nel pomeriggio il padrone ha chiesto a Luca e Giulia di restare un momento.', 'In the afternoon the owner asked Luca and Giulia to stay a moment.'),
        D('padrone', 'Non vendo. Non adesso. Il caffè resta. Almeno questo mese, e il prossimo.', 'I am not selling. Not now. The café stays. At least this month, and the next.'),
        D('giulia', 'Grazie. Per me è importante restare.', 'Thanks. For me it is important to stay.'),
        D('padrone', 'Voi due lavorate di più, se volete. Ho bisogno di ore, non di una persona nuova.', 'You two work more, if you want. I need hours, not a new person.'),
        N('Luca ha sentito le parole “se volete” e ha capito che poteva scegliere.', 'Luca heard the words “if you want” and understood that he could choose.'),
        D('luca', 'Sì. Accetto. Ho bisogno dello stipendio, e mi piace questo posto.', 'Yes. I accept. I need the salary, and I like this place.'),
      ],
      [
        D('giulia', 'Anch’io accetto. Ma voglio anche organizzare, non solo servire.', 'I accept too. But I also want to organize, not only serve.'),
        D('padrone', 'Va bene. Vediamo. Tu fai un piano della settimana. Io ascolto.', 'All right. We’ll see. You make a plan for the week. I listen.', [
          PH('Va bene', 'it goes well', 'okay'),
          PH('Vediamo', 'we see', 'we’ll see'),
        ]),
        N('Giulia ha sorriso, finalmente, come una persona ascoltata.', 'Giulia smiled, finally, like a person who was heard.'),
        N('Per Luca era una notizia buona due volte: il lavoro restava, e Giulia aveva il suo posto.', 'For Luca it was good news twice: the job stayed, and Giulia had her place.'),
        N('Il problema grande non era del tutto finito. Un mese non è un futuro.', 'The big problem was not completely finished. A month is not a future.'),
        N('E però oggi potevano lavorare senza quella paura di ieri.', 'And yet today they could work without that fear from yesterday.'),
      ],
      [
        N('La sera Luca ha contato i soldi con più calma. L’affitto di questo mese era sicuro.', 'In the evening Luca counted his money more calmly. This month’s rent was sure.'),
        N('Ha scritto un messaggio a Sofia e a Marco: il caffè resta, per adesso.', 'He wrote a message to Sofia and Marco: the café stays, for now.'),
        N('Sofia ha risposto subito. Marco ha risposto dopo, contento, e cerca ancora un lavoro.', 'Sofia replied at once. Marco replied later, glad, and he still looks for work.'),
        N('Luca ha chiuso la finestra e ha pensato alle ore nuove.', 'Luca closed the window and thought about the new hours.'),
        N('Più ore voleva dire più soldi, e anche meno tempo libero.', 'More hours meant more money, and also less free time.'),
        N('Doveva parlare di questo con Sofia. Non era una cosa da decidere da solo, nel cuore.', 'He had to talk about this with Sofia. It was not a thing to decide alone, in his heart.'),
      ],
    ],
    [
      Q('event', 'What does the owner decide?', ['He will not sell, at least for now, and offers more hours', 'He closes forever', 'He fires Giulia'], 0, 'The café stays this month and the next.'),
      Q('character', 'What extra thing does Giulia want?', ['To organize, not only serve', 'To leave Rome', 'To buy the café alone'], 0, 'The owner says she can make a weekly plan.'),
      Q('inference', 'Why is Luca’s news mixed?', ['More hours mean more money but less free time', 'He lost his apartment', 'Sofia is angry'], 0, 'He wants to talk with Sofia before deciding everything in his heart.'),
    ],
  ),
  ch(
    38,
    'Dinner with Sofia',
    'Cena con Sofia',
    ['centro', 'quartiere'],
    ['luca', 'sofia'],
    ev('ev-38-dinner', 'Luca and Sofia have dinner as equal friends and talk about hours and life.', ['luca', 'sofia'], ['centro'], ['Sofia has her own busy life', 'They talk as equals about the future of hours']),
    [
      [
        N('Due sere dopo, Luca e Sofia si sono incontrati per una cena piccola nel centro.', 'Two evenings later, Luca and Sofia met for a small dinner in the center.'),
        N('Non era un ristorante grande. Era un posto tranquillo, con luce calda e poco rumore.', 'It was not a big restaurant. It was a quiet place, with warm light and little noise.'),
        D('sofia', 'Allora. Il caffè resta. Tu sei contento?', 'So. The café stays. Are you glad?'),
        D('luca', 'Sì. E ho più ore. Più soldi, meno tempo. Non so se è tutto buono.', 'Yes. And I have more hours. More money, less time. I don’t know if it is all good.'),
        D('sofia', 'Dipende da cosa vuoi. La casa, gli amici, il lavoro. Non è una cosa sola.', 'It depends on what you want. Home, friends, work. It is not one thing only.', [PH('Dipende', 'it depends', 'it depends')]),
        N('Luca ha ascoltato. Sofia non stava risolvendo il suo problema. Stava parlando con lui.', 'Luca listened. Sofia was not solving his problem. She was talking with him.'),
      ],
      [
        N('Hanno mangiato pasta e hanno bevuto un po’ di vino, senza fretta.', 'They ate pasta and drank a little wine, without hurry.'),
        D('luca', 'Tu come stai, di vero? Non solo “bene”.', 'How are you, really? Not only “fine”.', [PH('come stai', 'how are you staying', 'how are you')]),
        D('sofia', 'Il mio lavoro è tanto. Qualche giorno sono stanca. Qualche giorno sono felice.', 'My job is a lot. Some days I am tired. Some days I am happy.'),
        D('sofia', 'E ho la nonna, e Marco, e te. Non sono sola. Questo aiuta.', 'And I have grandma, and Marco, and you. I am not alone. This helps.'),
        N('Luca ha sorriso. “E te” era una cosa piccola e grande.', 'Luca smiled. “And you” was a small and big thing.'),
        D('luca', 'Per me sei un’amica, non solo la persona che mi ha aiutato i primi giorni.', 'For me you are a friend, not only the person who helped me in the first days.'),
      ],
      [
        D('sofia', 'Lo so. Anch’io. I primi giorni ti ho aiutato perché eri nuovo. Adesso è diverso.', 'I know. Me too. The first days I helped you because you were new. Now it is different.'),
        D('sofia', 'Adesso mi piace parlare con te delle cose vere. Del lavoro, della paura, dei piani.', 'Now I like talking with you about real things. Work, fear, plans.'),
        D('luca', 'Che ne dici, allora, delle ore nuove? Accetto tutte, o ne scelgo tre o quattro?', 'What do you say, then, about the new hours? Do I accept all of them, or choose three or four?', [
          PH('Che ne dici', 'what of it do you say', 'what do you say'),
        ]),
        D('sofia', 'Scegli. Non dire di sì a tutto perché hai paura di restare senza soldi.', 'Choose. Don’t say yes to everything because you are afraid of being without money.'),
        N('Luca ha pensato all’affitto, e poi agli amici, e poi a Giulia.', 'Luca thought about the rent, and then about friends, and then about Giulia.'),
        D('luca', 'Hai ragione. Domani parlo con il padrone. Voglio più ore, ma non tutte le ore.', 'You’re right. Tomorrow I talk with the owner. I want more hours, but not all the hours.', [PH('Hai ragione', 'you have reason', 'you’re right')]),
      ],
      [
        N('Dopo la cena hanno camminato un poco. Roma di sera era bella, e loro parlavano piano.', 'After dinner they walked a little. Rome in the evening was beautiful, and they spoke quietly.'),
        N('Non hanno deciso il futuro di un anno. Hanno deciso solo il giorno dopo.', 'They did not decide the future of a year. They only decided the next day.'),
        D('sofia', 'Ci vediamo presto. Non andare lontano tra le ore del caffè.', 'See you soon. Don’t go far among the café hours.', [PH('Ci vediamo', 'we see each other', 'see you')]),
        D('luca', 'Non vado lontano. Ci penso io a restare nei tuoi giorni, e tu nei miei.', 'I won’t go far. I’ll take care of staying in your days, and you in mine.', [PH('Ci penso io', 'I think about it I', 'I’ll take care of it')]),
        N('Sofia ha sorriso, e per un momento il lavoro sembrava lontano.', 'Sofia smiled, and for a moment work seemed far away.'),
        N('Poi Luca è andato a casa, e Sofia anche, con più parole vere di prima.', 'Then Luca went home, and Sofia too, with more true words than before.'),
      ],
    ],
    [
      Q('event', 'What do Luca and Sofia do?', ['They have a small dinner and talk as equal friends', 'They sell the café', 'They take Marco to the station'], 0, 'They eat, talk about hours and real life.'),
      Q('character', 'What does Sofia advise about the new hours?', ['Choose; don’t say yes to everything out of fear', 'Take every hour', 'Leave the job'], 0, 'She tells him to choose.'),
      Q('inference', 'How has their relationship changed since A1?', ['They talk as friends, not only helper and newcomer', 'They no longer speak', 'Sofia is his boss'], 0, 'Sofia says it is different now.'),
    ],
  ),
  ch(
    39,
    'A place for Marco',
    'Un posto per Marco',
    ['lavoro-caffe', 'quartiere'],
    ['luca', 'marco', 'giulia', 'sofia', 'padrone'],
    ev('ev-39-marco-work', 'Marco gets a little work helping at the café on busy days; friends have a small dinner.', ['luca', 'marco', 'giulia', 'padrone'], ['lavoro-caffe'], ['Marco helps on busy days', 'It is not a full job but it is a start']),
    [
      [
        N('Il giorno dopo Luca ha parlato con il padrone delle ore, come deciso con Sofia.', 'The next day Luca spoke with the owner about the hours, as decided with Sofia.'),
        D('luca', 'Voglio più ore, ma non tutte. Devo avere tempo per la casa e per gli amici.', 'I want more hours, but not all. I must have time for home and for friends.'),
        D('padrone', 'Va bene. Sei chiaro. Mi piace. Facciamo un orario giusto.', 'All right. You are clear. I like that. We’ll make a fair schedule.', [PH('Va bene', 'it goes well', 'okay')]),
        N('Mentre parlavano, Marco è arrivato alla porta, come un cliente senza soldi e con una domanda.', 'While they talked, Marco arrived at the door, like a customer without money and with a question.'),
        D('marco', 'Scusa. Posso parlare un momento? Ho bisogno di dirvi una cosa.', 'Sorry. Can I talk a moment? I need to tell you something.'),
        N('Giulia ha fatto segno di sì. Il padrone ha aspettato, stanco ma aperto.', 'Giulia signaled yes. The owner waited, tired but open.'),
      ],
      [
        D('marco', 'Cerco lavoro. Non ho trovato un posto grande. Ma posso aiutare qui, nei giorni pieni.', 'I am looking for work. I did not find a big place. But I can help here, on full days.'),
        D('marco', 'Non chiedo tanto. Chiedo di fare qualcosa, e di non restare solo a cercare.', 'I don’t ask for much. I ask to do something, and not to stay only looking.'),
        N('Luca ha guardato Giulia. Lei ha guardato il padrone.', 'Luca looked at Giulia. She looked at the owner.'),
        D('giulia', 'I giorni pieni abbiamo bisogno di una persona in più. Sabato l’abbiamo visto.', 'On full days we need one more person. We saw it on Saturday.'),
        D('padrone', 'Poche ore. Pochi soldi. Non è un lavoro grande. Se vuoi, proviamo.', 'Few hours. Little money. It is not a big job. If you want, we try.'),
        D('marco', 'Voglio. Grazie. Per me è già tanto.', 'I want to. Thanks. For me it is already a lot.'),
      ],
      [
        N('Luca era contento in un modo tranquillo. Il problema di Marco non era finito, e però c’era un primo giorno.', 'Luca was glad in a quiet way. Marco’s problem was not finished, and yet there was a first day.'),
        D('luca', 'Se lavori qui, ci vediamo di più. Va bene per me.', 'If you work here, we’ll see each other more. That’s fine for me.', [PH('Va bene', 'it goes well', 'okay')]),
        D('marco', 'Per me anche. Gli amici e un po’ di lavoro. Non è il treno di prima. È meglio.', 'For me too. Friends and a little work. It is not the train from before. It is better.'),
        N('Nel pomeriggio Sofia è passata e ha sentito la notizia. Ha sorriso a Marco senza fare troppe parole.', 'In the afternoon Sofia came by and heard the news. She smiled at Marco without too many words.'),
        D('sofia', 'Finalmente. Non sei più solo a cercare. Hai un posto, anche se piccolo.', 'Finally. You are no longer only looking. You have a place, even if small.'),
        N('Marco ha detto poco, ma sembrava diverso.', 'Marco said little, but he seemed different.'),
      ],
      [
        N('La sera i quattro hanno mangiato insieme vicino al caffè, con pane, qualcosa da bere, e vino per chi voleva.', 'In the evening the four ate together near the café, with bread, something to drink, and wine for whoever wanted it.'),
        N('Non era una festa grande. Era una cena di persone che avevano fatto una cosa difficile.', 'It was not a big celebration. It was a dinner of people who had done a hard thing.'),
        D('giulia', 'Il caffè resta. Marco aiuta. Luca ha più ore. Io organizzo. Che settimana.', 'The café stays. Marco helps. Luca has more hours. I organize. What a week.'),
        D('sofia', 'E io non sono solo la ragazza del quartiere che aiuta. Sono qui perché voglio.', 'And I am not only the neighborhood girl who helps. I am here because I want to be.'),
        N('Luca ha preso l’acqua, perché non voleva troppo vino, e ha sorriso.', 'Luca took the water, because he did not want too much wine, and he smiled.'),
        D('luca', 'A Roma, allora. E a noi.', 'To Rome, then. And to us.'),
      ],
    ],
    [
      Q('event', 'What work does Marco get?', ['A little help at the café on busy days, not a big job', 'He becomes the owner', 'He leaves for a train job'], 0, 'Few hours, little money, a start.'),
      Q('character', 'What does Luca tell the owner about hours?', ['He wants more hours but not all of them', 'He wants to stop working', 'He wants to sell'], 0, 'He needs time for home and friends.'),
      Q('direct', 'What does Sofia say about her place in the group?', ['She is there because she wants to be, not only as a helper', 'She is leaving', 'She is the new owner'], 0, 'She states it at dinner.'),
    ],
  ),
  ch(
    40,
    'A letter',
    'Una lettera',
    ['appartamento-luca', 'lavoro-caffe', 'quartiere'],
    ['luca', 'sofia', 'giulia', 'marco'],
    ev('ev-40-letter', 'A letter about the future arrives; the café is safe for now; friends will talk tomorrow.', ['luca', 'sofia', 'giulia', 'marco'], ['appartamento-luca'], ['A letter raises a question about the future', 'Hook: tomorrow they talk about the future']),
    [
      [
        N('Una settimana dopo, la vita di Luca aveva un orario nuovo e una casa che conosceva meglio.', 'A week later, Luca’s life had a new schedule and a home he knew better.'),
        N('Il caffè aveva più clienti di prima, non tanti come sabato, ma abbastanza.', 'The café had more customers than before, not as many as Saturday, but enough.'),
        N('Marco veniva nei giorni pieni. Giulia faceva il piano della settimana. Luca serviva e imparava.', 'Marco came on full days. Giulia made the week’s plan. Luca served and learned.'),
        N('Sofia passava quando poteva, non per aiutare Luca come prima, ma per stare con lui.', 'Sofia came by when she could, not to help Luca as before, but to be with him.'),
        N('Un pomeriggio, a casa, Luca ha trovato una lettera sotto la porta.', 'One afternoon, at home, Luca found a letter under the door.'),
        N('Non era un messaggio sul telefono. Era carta, con il suo nome.', 'It was not a message on the phone. It was paper, with his name.'),
      ],
      [
        N('Ha aperto la lettera e ha letto piano. Non capiva tutte le parole, e però capiva la cosa importante.', 'He opened the letter and read slowly. He did not understand all the words, and yet he understood the important thing.'),
        N('Qualcuno scriveva del futuro: una proposta, un posto, un’altra città, o forse solo una domanda.', 'Someone was writing about the future: a proposal, a place, another city, or maybe only a question.'),
        N('Luca si è seduto. Roma era fuori dalla finestra, la stessa e diversa.', 'Luca sat down. Rome was outside the window, the same and different.'),
        N('Aveva una casa, un lavoro, amici. Perché una lettera doveva cambiare i suoi giorni?', 'He had a home, a job, friends. Why should a letter change his days?'),
        N('E però il cuore era un po’ forte, come il primo giorno alla stazione.', 'And yet his heart was a little strong, like the first day at the station.'),
        N('Ha messo la lettera sul tavolo e non ha deciso niente, da solo.', 'He put the letter on the table and did not decide anything, alone.'),
      ],
      [
        N('La sera ha portato la lettera al caffè, dopo il lavoro, quando Giulia chiudeva i tavoli.', 'In the evening he brought the letter to the café, after work, when Giulia was closing the tables.'),
        D('luca', 'C’è una lettera. Parla del futuro. Non so cosa fare.', 'There is a letter. It talks about the future. I don’t know what to do.'),
        D('giulia', 'Non decidere adesso. Domani. Con le persone giuste.', 'Don’t decide now. Tomorrow. With the right people.'),
        N('Sofia e Marco sono arrivati, perché Luca aveva scritto un messaggio: “Domani parliamo.”', 'Sofia and Marco arrived, because Luca had written a message: “Tomorrow we talk.”'),
        D('sofia', 'Che c’è? Stai bene?', 'What is it? Are you well?'),
        D('luca', 'Sì. È una lettera. Non è un problema come il biglietto. È un’altra cosa.', 'Yes. It is a letter. It is not a problem like the ticket. It is another thing.'),
      ],
      [
        D('marco', 'Allora domani. Oggi hai lavorato. Oggi il caffè è aperto. Questo resta.', 'Then tomorrow. Today you worked. Today the café is open. This stays.'),
        D('sofia', 'Hai ragione. Non dobbiamo scegliere il futuro in un momento.', 'You’re right. We must not choose the future in a moment.', [PH('Hai ragione', 'you have reason', 'you’re right')]),
        N('Luca ha guardato gli amici, la sala, la porta che lui apriva ogni mattina.', 'Luca looked at his friends, the room, the door he opened every morning.'),
        N('La nuova vita non era più nuova come il primo giorno. Era sua, con i suoi problemi e le sue persone.', 'The new life was no longer new like the first day. It was his, with its problems and its people.'),
        D('luca', 'Va bene. Domani parliamo del futuro.', 'All right. Tomorrow we talk about the future.', [PH('Va bene', 'it goes well', 'okay')]),
        N('Fuori, Roma continuava. Dentro, la lettera stava sul tavolo, chiusa di nuovo, e aspettava.', 'Outside, Rome continued. Inside, the letter lay on the table, closed again, and waited.'),
      ],
    ],
    [
      Q('event', 'What does Luca find at home?', ['A letter about the future', 'A lost suitcase', 'A train ticket'], 0, 'Paper under the door, with his name.'),
      Q('character', 'What does Giulia tell him to do?', ['Not decide now; wait until tomorrow with the right people', 'Leave Rome at once', 'Sell the café'], 0, 'Tomorrow, with the right people.'),
      Q('inference', 'Why is the last line a beginning, not only an ending?', ['They will talk about the future tomorrow, so the story continues', 'Luca has left Rome', 'The café is sold'], 0, '“Domani parliamo del futuro.”'),
    ],
  ),
];

module.exports = { chapters };
