const { N, D, PH, Q } = require('./story-helpers');

function ch(n, title, titleIt, locationIds, characterIds, event, paragraphs, questions) {
  return {
    id: `luca-a-roma-${String(n).padStart(2, '0')}`,
    number: n,
    title,
    titleIt,
    locationIds,
    characterIds,
    events: [event],
    paragraphs,
    questions,
  };
}

const ev = (id, summary, characterIds, locationIds, rememberedFacts) => ({
  id,
  summary,
  characterIds,
  locationIds,
  rememberedFacts,
});

const chapters = [
  ch(
    22,
    'An evening with Sofia',
    'Una sera con Sofia',
    ['lavoro-caffe', 'quartiere', 'strada', 'centro'],
    ['luca', 'sofia'],
    ev('ev-22-sofia', 'After work Luca walks with Sofia; their friendship feels more equal.', ['luca', 'sofia'], ['lavoro-caffe', 'quartiere'], ['Sofia has her own busy week', 'They plan to meet again']),
    [
      [
        N('Quando Luca ha finito il lavoro, Sofia lo stava già aspettando vicino alla porta.', 'When Luca finished work, Sofia was already waiting for him near the door.'),
        D('sofia', 'Ciao, Luca. Come stai oggi?', 'Hi, Luca. How are you today?', [PH('Come stai', 'how are you staying', 'how are you')]),
        D('luca', 'Bene. Oggi ho lavorato di più, ma non sono troppo stanco.', 'Good. Today I worked more, but I am not too tired.'),
        N('Sofia ha sorriso e hanno camminato insieme nel quartiere.', 'Sofia smiled and they walked together in the neighborhood.'),
        N('Era sera, e le persone erano ancora fuori, vicino ai negozi e alla piazza.', 'It was evening, and people were still outside, near the shops and the square.'),
        N('Luca conosceva già queste strade, e però ogni volta vedeva qualcosa di nuovo.', 'Luca already knew these streets, and yet every time he saw something new.'),
      ],
      [
        D('sofia', 'Io oggi ho lavorato tanto. Il mio lavoro non è facile questa settimana.', 'I worked a lot today. My job is not easy this week.'),
        D('luca', 'Hai bisogno di aiuto?', 'Do you need help?'),
        D('sofia', 'No. Grazie. Questa volta ci penso io.', 'No. Thanks. This time I’ll take care of it.', [PH('ci penso io', 'I think about it I', 'I’ll take care of it')]),
        N('Luca ha ascoltato. Sofia non era solo la ragazza che lo aiutava.', 'Luca listened. Sofia was not only the girl who helped him.'),
        N('Aveva i suoi giorni, i suoi problemi e le sue cose da fare.', 'She had her days, her problems, and her things to do.'),
        D('luca', 'Va bene. Se hai bisogno, puoi dirmi.', 'All right. If you need something, you can tell me.', [PH('Va bene', 'it goes well', 'okay')]),
      ],
      [
        N('Si sono fermati vicino a un piccolo negozio e hanno guardato le luci della sera.', 'They stopped near a small shop and looked at the evening lights.'),
        D('sofia', 'Come va il caffè? I clienti sono gentili?', 'How is the café going? Are the customers kind?'),
        D('luca', 'Qualche cliente è difficile. Giulia mi aiuta, e io ascolto.', 'Some customers are difficult. Giulia helps me, and I listen.'),
        D('sofia', 'Mi sembra una cosa giusta. Tu impari, e lei non è sola.', 'That seems right to me. You learn, and she is not alone.', [PH('Mi sembra', 'it seems to me', 'it seems to me')]),
        N('Luca era contento di parlare così, senza paura grande e senza fretta.', 'Luca was glad to talk like this, without great fear and without hurry.'),
        N('Per un momento il lavoro sembrava lontano, e Roma era solo una bella sera.', 'For a moment work seemed far away, and Rome was only a beautiful evening.'),
      ],
      [
        D('sofia', 'Domenica sono libera. Che ne dici? Ci vediamo?', 'Sunday I am free. What do you say? Shall we meet?', [
          PH('Che ne dici?', 'what of it do you say', 'what do you say?'),
          PH('Ci vediamo', 'we see each other', 'see you'),
        ]),
        D('luca', 'Sì. Mi piace. Possiamo camminare un po’ nel centro.', 'Yes. I like that. We can walk a little in the center.'),
        D('sofia', 'Va bene. Allora ci vediamo domenica.', 'All right. Then we’ll see each other on Sunday.', [PH('Va bene', 'it goes well', 'okay')]),
        N('Sofia è partita verso casa, e Luca è rimasto un momento nella strada.', 'Sofia left toward home, and Luca stayed a moment in the street.'),
        N('La sua nuova vita aveva amici, non solo lavoro e una piccola casa.', 'His new life had friends, not only work and a small home.'),
        N('Mentre tornava a casa, pensava già a domenica.', 'While he went home, he was already thinking about Sunday.'),
      ],
    ],
    [
      Q('character', 'Who waits for Luca after work?', ['Sofia', 'Marco', 'The owner'], 0, 'Sofia is already waiting near the door.'),
      Q('event', 'What do they plan?', ['To meet on Sunday', 'To leave Rome', 'To close the café'], 0, 'Sofia is free on Sunday and they agree to meet.'),
      Q('inference', 'Why does Luca listen carefully to Sofia?', ['Because she has her own work and problems', 'Because he does not like her', 'Because he wants to leave'], 0, 'He sees she is not only the person who helps him.'),
    ],
  ),
  ch(
    23,
    'Giulia’s day',
    'La giornata di Giulia',
    ['lavoro-caffe'],
    ['luca', 'giulia', 'padrone'],
    ev('ev-23-giulia', 'Giulia takes more responsibility and talks with Luca as a colleague.', ['luca', 'giulia'], ['lavoro-caffe'], ['Giulia has worked at the café a long time', 'A difficult customer arrives']),
    [
      [
        N('Il giorno dopo Luca è arrivato al lavoro più tardi del solito, ma non troppo.', 'The next day Luca arrived at work later than usual, but not too late.'),
        N('Giulia stava già preparando i tavoli e ha guardato l’orario.', 'Giulia was already preparing the tables and looked at the time.'),
        D('giulia', 'Buongiorno. Oggi abbiamo bisogno di essere pronti. Arrivano clienti presto.', 'Good morning. Today we need to be ready. Customers arrive early.'),
        D('luca', 'Va bene. Puoi dire cosa fare e lo faccio.', 'All right. You can say what to do and I’ll do it.'),
        N('Giulia ha spiegato l’ordine dei tavoli e Luca ha ascoltato senza dire troppo.', 'Giulia explained the order of the tables and Luca listened without saying too much.'),
        N('Lei non era solo una collega gentile. Voleva fare bene il suo lavoro.', 'She was not only a kind colleague. She wanted to do her job well.'),
      ],
      [
        N('Un signore è entrato e ha chiesto qualcosa di difficile.', 'A gentleman came in and asked for something difficult.'),
        D('padrone', 'Luca, vai tu. Io non ho tempo.', 'Luca, you go. I do not have time.'),
        N('Luca ha avuto un po’ di paura, ma Giulia era vicino a lui.', 'Luca was a little afraid, but Giulia was near him.'),
        D('giulia', 'Tu ascolti. Io aiuto se serve. Non c’è problema.', 'You listen. I’ll help if needed. No problem.', [PH('Non c’è problema', 'there is not problem', 'no problem')]),
        N('Luca ha portato acqua e caffè e ha chiesto di nuovo, con calma.', 'Luca brought water and coffee and asked again, calmly.'),
        N('Il signore ha sorriso. Il problema era piccolo, e insieme l’hanno risolto.', 'The gentleman smiled. The problem was small, and together they solved it.'),
      ],
      [
        N('Nel pomeriggio c’erano meno persone, e Giulia si è seduta un momento.', 'In the afternoon there were fewer people, and Giulia sat down for a moment.'),
        D('giulia', 'Io lavoro qui da tanto tempo. Qualche volta il padrone non ascolta.', 'I have worked here for a long time. Sometimes the owner does not listen.'),
        D('luca', 'Tu fai tanto. Mi sembra importante.', 'You do a lot. It seems important to me.', [PH('Mi sembra', 'it seems to me', 'it seems to me')]),
        D('giulia', 'Hai ragione. Voglio fare di più, non solo portare caffè.', 'You’re right. I want to do more, not only bring coffee.', [PH('Hai ragione', 'you have reason', 'you’re right')]),
        N('Luca ha capito. Giulia aveva un piano, anche se non lo diceva tutto.', 'Luca understood. Giulia had a plan, even if she did not say all of it.'),
        N('I due colleghi hanno lavorato fino a sera, e la sala era tranquilla.', 'The two colleagues worked until evening, and the room was quiet.'),
      ],
      [
        D('giulia', 'Domani arrivi in orario, va bene?', 'Tomorrow you arrive on time, all right?'),
        D('luca', 'Sì. Ci penso io. Grazie per oggi.', 'Yes. I’ll take care of it. Thanks for today.', [PH('Ci penso io', 'I think about it I', 'I’ll take care of it')]),
        N('Giulia ha sorriso, stanca ma contenta.', 'Giulia smiled, tired but glad.'),
        N('Luca è uscito e ha camminato verso casa con una nuova idea.', 'Luca went out and walked toward home with a new idea.'),
        N('Al lavoro non era più solo il ragazzo nuovo.', 'At work he was no longer only the new guy.'),
        N('Era un collega, e questo cambiava i suoi giorni.', 'He was a colleague, and this changed his days.'),
      ],
    ],
    [
      Q('event', 'What happens with the difficult customer?', ['Luca and Giulia solve the small problem', 'The owner closes the café', 'Luca leaves work'], 0, 'They listen and solve it together.'),
      Q('character', 'What does Giulia want?', ['To do more than only serve coffee', 'To leave Rome', 'To sell the café'], 0, 'She wants more responsibility.'),
      Q('direct', 'What does Giulia ask Luca to do tomorrow?', ['Arrive on time', 'Call his family', 'Find Marco'], 0, 'She asks him to arrive on time.'),
    ],
  ),
  ch(
    24,
    'A call home',
    'Una chiamata a casa',
    ['appartamento-luca'],
    ['luca'],
    ev('ev-24-call', 'Luca calls his parents and talks about his new life in Rome.', ['luca'], ['appartamento-luca'], ['Luca speaks with mamma and papà', 'They worry about rent and work']),
    [
      [
        N('Domenica mattina Luca è rimasto a casa. Sofia arrivava più tardi.', 'Sunday morning Luca stayed home. Sofia was coming later.'),
        N('Ha preso il telefono e ha chiamato la mamma e il papà.', 'He took the phone and called his mom and dad.'),
        N('La chiamata non era facile, perché lui voleva dire tante cose.', 'The call was not easy, because he wanted to say many things.'),
        D('luca', 'Ciao. Sto bene. Ho una casa piccola e un lavoro al caffè.', 'Hi. I am well. I have a small home and a job at the café.'),
        N('Dall’altra parte c’era la voce della mamma, contenta e un po’ preoccupata.', 'On the other side there was his mom’s voice, glad and a little worried.'),
        N('Luca ha sorriso e ha guardato la finestra della sua stanza.', 'Luca smiled and looked at the window of his room.'),
      ],
      [
        N('Ha spiegato i suoi giorni: la mattina al lavoro, la sera a casa, gli amici.', 'He explained his days: morning at work, evening at home, friends.'),
        N('Ha parlato di Sofia, di Giulia e anche di Marco.', 'He talked about Sofia, Giulia, and also Marco.'),
        N('Ha detto che l’affitto non è economico, e però lui paga.', 'He said the rent is not cheap, and yet he pays.'),
        N('Aveva bisogno di soldi, ma aveva anche un piano.', 'He needed money, but he also had a plan.'),
        N('Mentre parlava, Roma fuori era tranquilla e piena di luce.', 'While he spoke, Rome outside was quiet and full of light.'),
        N('Per la prima volta la famiglia sembrava lontana, e però vicina.', 'For the first time family seemed far away, and yet close.'),
      ],
      [
        N('Il papà ha chiesto se Luca voleva tornare.', 'Dad asked if Luca wanted to come back.'),
        D('luca', 'Adesso no. Qui ho lavoro e amici. Magari un giorno, non lo so.', 'Not now. Here I have work and friends. Maybe one day, I don’t know.', [
          PH('non lo so', 'I it not know', 'I don’t know'),
        ]),
        N('La mamma ha detto che va bene, se lui è contento.', 'Mom said it is all right, if he is happy.'),
        D('luca', 'Non c’è problema. Sto imparando. I giorni sono diversi, ma buoni.', 'No problem. I am learning. The days are different, but good.', [
          PH('Non c’è problema', 'there is not problem', 'no problem'),
        ]),
        N('Dopo la chiamata Luca si è seduto e ha pensato al futuro, ma solo un momento.', 'After the call Luca sat down and thought about the future, but only for a moment.'),
        N('Poi ha preparato qualcosa da mangiare, perché aveva fame.', 'Then he prepared something to eat, because he was hungry.'),
      ],
      [
        N('Nel pomeriggio Sofia è arrivata, come deciso.', 'In the afternoon Sofia arrived, as decided.'),
        D('sofia', 'Hai chiamato casa?', 'Did you call home?'),
        D('luca', 'Sì. La mamma è contenta. Il papà vuole sapere tutto.', 'Yes. Mom is glad. Dad wants to know everything.'),
        D('sofia', 'Capisco. Anch’io chiamo la nonna quando ho bisogno di una voce.', 'I understand. I also call grandma when I need a voice.'),
        N('Hanno camminato nel centro, senza fretta, e hanno parlato di cose piccole.', 'They walked in the center, without hurry, and talked about small things.'),
        N('Luca era più sicuro di ieri, e questo gli piaceva.', 'Luca was more sure than yesterday, and he liked that.'),
      ],
    ],
    [
      Q('event', 'Who does Luca call?', ['His mom and dad', 'The owner', 'Marco'], 0, 'He calls mamma and papà.'),
      Q('direct', 'Does Luca want to go back now?', ['No, not now', 'Yes, immediately', 'He already left Rome'], 0, 'He says not now; he has work and friends.'),
      Q('sequence', 'What happens after the call?', ['Sofia arrives and they walk in the center', 'Luca goes to work', 'They take a train'], 0, 'Sofia comes in the afternoon.'),
    ],
  ),
  ch(
    25,
    'Fewer people',
    'Meno persone',
    ['lavoro-caffe', 'appartamento-luca'],
    ['luca', 'giulia', 'padrone'],
    ev('ev-25-empty', 'The café has fewer customers and the owner looks worried.', ['luca', 'giulia', 'padrone'], ['lavoro-caffe'], ['Fewer customers come', 'Luca worries about rent']),
    [
      [
        N('Lunedì al caffè c’erano meno clienti del solito.', 'Monday at the café there were fewer customers than usual.'),
        N('Luca ha preparato i tavoli, e però tanti tavoli sono restati vuoti.', 'Luca prepared the tables, and yet many tables stayed empty.'),
        N('Giulia ha guardato la sala e non ha sorriso.', 'Giulia looked at the room and did not smile.'),
        D('giulia', 'Questa settimana è strana. Quasi nessuno entra.', 'This week is strange. Almost nobody comes in.'),
        D('luca', 'Dipende dal tempo, forse.', 'It depends on the weather, maybe.', [PH('Dipende', 'it depends', 'it depends')]),
        N('Fuori non faceva freddo. Il problema sembrava un altro.', 'Outside it was not cold. The problem seemed to be something else.'),
      ],
      [
        N('Il padrone è arrivato e ha guardato i tavoli vuoti per un tempo lungo.', 'The owner arrived and looked at the empty tables for a long time.'),
        N('Non ha detto niente, e questo era peggio di una domanda.', 'He said nothing, and this was worse than a question.'),
        D('padrone', 'Lavoriamo. Vediamo come va la giornata.', 'Let’s work. We’ll see how the day goes.', [PH('Vediamo', 'we see', 'we’ll see')]),
        N('Luca ha servito i pochi clienti con calma e ha ascoltato le loro voci.', 'Luca served the few customers calmly and listened to their voices.'),
        N('Ogni caffè era importante. Ogni conto era importante.', 'Every coffee was important. Every bill was important.'),
        N('Nel pomeriggio la sala era ancora quasi vuota.', 'In the afternoon the room was still almost empty.'),
      ],
      [
        D('giulia', 'Il padrone è preoccupato. Io lo vedo.', 'The owner is worried. I can see it.'),
        D('luca', 'Anch’io. Se il caffè va male, il mio lavoro va male.', 'Me too. If the café goes badly, my job goes badly.'),
        N('La sera Luca è tornato a casa e ha contato i soldi per l’affitto.', 'In the evening Luca went home and counted the money for the rent.'),
        N('Aveva abbastanza per questo mese, ma non per tanti mesi.', 'He had enough for this month, but not for many months.'),
        N('Si è seduto vicino alla finestra e ha pensato al lavoro, non solo alla casa.', 'He sat near the window and thought about work, not only about home.'),
        N('La nuova vita aveva bisogno del caffè. Senza il caffè, tutto cambiava.', 'The new life needed the café. Without the café, everything changed.'),
      ],
      [
        N('Prima di dormire ha scritto un messaggio a Sofia.', 'Before sleeping he wrote a message to Sofia.'),
        N('Non ha detto tutto. Ha detto solo che il lavoro era strano.', 'He did not say everything. He only said that work was strange.'),
        N('Sofia ha risposto tardi: “Domani parliamo. Non sei solo.”', 'Sofia replied late: “Tomorrow we talk. You are not alone.”'),
        N('Luca ha letto il messaggio due volte.', 'Luca read the message twice.'),
        N('Poi ha chiuso la finestra e ha dormito, ma non ha dormito bene.', 'Then he closed the window and slept, but he did not sleep well.'),
        N('Qualcosa stava cambiando al caffè, e lui voleva capire.', 'Something was changing at the café, and he wanted to understand.'),
      ],
    ],
    [
      Q('event', 'What is different at the café?', ['There are fewer customers', 'The café is full', 'Luca loses his key'], 0, 'Many tables stay empty.'),
      Q('character', 'Who looks worried without saying much?', ['The owner', 'Sofia', 'Marco'], 0, 'The padrone looks at empty tables and says little.'),
      Q('inference', 'Why does Luca count his money?', ['Because rent still matters if work goes badly', 'Because he wants a new train ticket', 'Because Sofia asked for money'], 0, 'He has enough for this month, not for many months.'),
    ],
  ),
  ch(
    26,
    'Bad news',
    'Una notizia difficile',
    ['lavoro-caffe'],
    ['luca', 'giulia', 'padrone'],
    ev('ev-26-sell', 'The owner says he may sell or change the café.', ['luca', 'giulia', 'padrone'], ['lavoro-caffe'], ['The padrone may sell the café', 'Giulia and Luca are worried']),
    [
      [
        N('Martedì mattina il padrone ha chiuso la porta un momento e ha parlato con loro.', 'Tuesday morning the owner closed the door for a moment and spoke with them.'),
        N('Giulia e Luca si sono fermati vicino ai tavoli e hanno ascoltato.', 'Giulia and Luca stopped near the tables and listened.'),
        D('padrone', 'Devo dirvi una cosa. Il caffè non va bene. Ci sono pochi clienti.', 'I must tell you something. The café is not going well. There are few customers.'),
        D('padrone', 'Forse lo vendo. O forse cambio tutto. Non ho deciso.', 'Maybe I will sell it. Or maybe I will change everything. I have not decided.'),
        N('La sala era tranquilla. Fuori, la strada continuava come ogni giorno.', 'The room was quiet. Outside, the street continued like every day.'),
        N('Luca ha sentito il cuore un po’ forte, e Giulia ha guardato il padrone.', 'Luca felt his heart a little strong, and Giulia looked at the owner.'),
      ],
      [
        D('giulia', 'Da quanto tempo pensi questo?', 'How long have you been thinking this?'),
        D('padrone', 'Da qualche settimana. Non è una cosa di ieri.', 'For a few weeks. It is not a thing from yesterday.'),
        D('luca', 'E il nostro lavoro?', 'And our jobs?'),
        D('padrone', 'Dipende. Se vendo, non lo so. Vediamo.', 'It depends. If I sell, I don’t know. We’ll see.', [
          PH('Dipende', 'it depends', 'it depends'),
          PH('Vediamo', 'we see', 'we’ll see'),
        ]),
        N('Giulia voleva dire di più, ma in quel momento è arrivato un cliente.', 'Giulia wanted to say more, but at that moment a customer arrived.'),
        N('Hanno aperto di nuovo e hanno lavorato, con la notizia dentro.', 'They opened again and worked, with the news inside them.'),
      ],
      [
        N('Nel pomeriggio Giulia ha parlato con Luca nella cucina piccola.', 'In the afternoon Giulia spoke with Luca in the small kitchen.'),
        D('giulia', 'Io resto qui se posso. Questo posto è importante per me.', 'I stay here if I can. This place is important to me.'),
        D('luca', 'Anch’io. Qui ho iniziato. Non voglio partire così.', 'Me too. I started here. I don’t want to leave like this.'),
        D('giulia', 'Allora dobbiamo fare qualcosa. Non solo aspettare.', 'Then we must do something. Not only wait.'),
        N('Luca ha detto di sì, anche se non aveva ancora un piano.', 'Luca said yes, even though he did not yet have a plan.'),
        N('La notizia era grande, e i due colleghi non erano più tranquilli.', 'The news was big, and the two colleagues were no longer calm.'),
      ],
      [
        N('La sera il padrone è uscito prima, stanco e senza tante parole.', 'In the evening the owner left earlier, tired and without many words.'),
        N('Luca ha chiuso i tavoli con Giulia e ha pensato a Sofia e a Marco.', 'Luca closed the tables with Giulia and thought about Sofia and Marco.'),
        N('I suoi amici potevano aiutare a pensare, non solo a lavorare.', 'His friends could help him think, not only work.'),
        D('luca', 'Domani parlo con Sofia. Lei conosce il quartiere.', 'Tomorrow I talk with Sofia. She knows the neighborhood.'),
        D('giulia', 'Bene. Io ci penso anche io, tutta la notte.', 'Good. I’ll think about it too, all night.'),
        N('Fuori, Roma era la stessa. Dentro, il lavoro di Luca non era più sicuro.', 'Outside, Rome was the same. Inside, Luca’s job was no longer sure.'),
      ],
    ],
    [
      Q('event', 'What news does the owner give?', ['He may sell or change the café', 'He gives Luca more money', 'He closes for a holiday'], 0, 'He has not decided yet.'),
      Q('character', 'What does Giulia want to do?', ['Stay and do something, not only wait', 'Leave Rome with Luca', 'Buy a train ticket'], 0, 'The place matters to her.'),
      Q('direct', 'Who will Luca talk to tomorrow?', ['Sofia', 'His dad', 'Nonna Rosa'], 0, 'He says he will talk with Sofia.'),
    ],
  ),
  ch(
    27,
    'Sofia’s opinion',
    'L’opinione di Sofia',
    ['quartiere', 'strada', 'centro'],
    ['luca', 'sofia'],
    ev('ev-27-sofia', 'Luca tells Sofia the café news; she offers her own view as a friend.', ['luca', 'sofia'], ['quartiere'], ['Sofia knows the neighborhood and wants to help think']),
    [
      [
        N('Mercoledì Luca ha incontrato Sofia vicino alla piazza, dopo il lavoro.', 'Wednesday Luca met Sofia near the square, after work.'),
        N('Lei lo ha visto e ha capito subito che c’era un problema.', 'She saw him and understood at once that there was a problem.'),
        D('sofia', 'Allora. Parla. Ieri il messaggio era strano.', 'So. Talk. Yesterday the message was strange.'),
        D('luca', 'Il padrone forse vende il caffè. O cambia tutto. Non ha deciso.', 'The owner might sell the café. Or change everything. He has not decided.'),
        D('sofia', 'Questa è una notizia grande.', 'That is big news.'),
        N('Hanno camminato senza parlare per un momento, tra le persone della sera.', 'They walked without speaking for a moment, among the evening people.'),
      ],
      [
        D('sofia', 'Il quartiere ha bisogno di un caffè. Le persone vanno lì da tanto tempo.', 'The neighborhood needs a café. People have gone there for a long time.'),
        D('luca', 'Sì. Ma i clienti sono pochi adesso. Io l’ho visto.', 'Yes. But there are few customers now. I have seen it.'),
        D('sofia', 'Pochi clienti non è la stessa cosa di vendere. È capire perché.', 'Few customers is not the same as selling. It is understanding why.'),
        N('Luca ha ascoltato. Sofia non stava solo aiutando il ragazzo nuovo.', 'Luca listened. Sofia was not only helping the new guy.'),
        N('Stava pensando con lui, da amica, con la sua idea.', 'She was thinking with him, as a friend, with her own idea.'),
        D('luca', 'Hai ragione. Giulia dice la stessa cosa. Dobbiamo fare qualcosa.', 'You’re right. Giulia says the same thing. We must do something.', [PH('Hai ragione', 'you have reason', 'you’re right')]),
      ],
      [
        D('sofia', 'Che ne dici di parlare con la gente del quartiere?', 'What do you say about talking with people in the neighborhood?', [
          PH('Che ne dici', 'what of it do you say', 'what do you say'),
        ]),
        D('luca', 'Possiamo. Ma come? Io lavoro e non ho tanto tempo.', 'We can. But how? I work and I don’t have much time.'),
        D('sofia', 'Non importa. Un piano piccolo è meglio di niente.', 'It doesn’t matter. A small plan is better than nothing.', [PH('Non importa', 'it does not matter', 'it doesn’t matter')]),
        N('Si sono fermati vicino a un negozio e hanno guardato la strada.', 'They stopped near a shop and looked at the street.'),
        N('Sofia ha detto che la nonna conosce tante persone vecchie e giovani.', 'Sofia said grandma knows many old and young people.'),
        D('luca', 'Allora andiamo da Nonna Rosa. Magari lei ha un’idea.', 'Then let’s go to Nonna Rosa. Maybe she has an idea.'),
      ],
      [
        N('Prima di partire, Sofia si è fermata vicino a Luca, senza fretta.', 'Before leaving, Sofia stopped near Luca, without hurry.'),
        D('sofia', 'Non sei solo in questa cosa. Ci sono io, e ci sono gli altri.', 'You are not alone in this. I am here, and the others are here.'),
        D('luca', 'Lo so. Grazie. Mi sembra importante sentire questo.', 'I know. Thanks. It seems important to hear this.', [PH('Mi sembra', 'it seems to me', 'it seems to me')]),
        N('Luca era preoccupato, e però era anche contento di avere un’amica così.', 'Luca was worried, and yet he was also glad to have a friend like this.'),
        N('Hanno deciso di vedere Nonna Rosa il giorno dopo.', 'They decided to see Nonna Rosa the next day.'),
        N('La notizia era ancora difficile, ma adesso c’era un primo giorno di piano.', 'The news was still hard, but now there was a first day of a plan.'),
      ],
    ],
    [
      Q('event', 'What does Luca tell Sofia?', ['The owner may sell the café', 'He lost his key', 'Marco left Rome'], 0, 'He repeats the padrone’s news.'),
      Q('character', 'How does Sofia respond?', ['She thinks with him and suggests talking to people', 'She tells him to leave the job', 'She laughs and goes home'], 0, 'She treats it as a shared problem.'),
      Q('inference', 'Why do they want to visit Nonna Rosa?', ['Because she knows many people in the neighborhood', 'Because they need a train ticket', 'Because the owner lives there'], 0, 'Sofia says grandma knows old and young people.'),
    ],
  ),
  ch(
    28,
    'Marco’s week',
    'La settimana di Marco',
    ['lavoro-caffe', 'quartiere'],
    ['luca', 'marco', 'giulia'],
    ev('ev-28-marco', 'Marco still has money trouble and looks for work; Luca listens.', ['luca', 'marco'], ['lavoro-caffe'], ['Marco needs work and money', 'The ticket crisis is over but stress continues']),
    [
      [
        N('Giovedì Marco è arrivato al caffè nel pomeriggio, quando c’erano pochi clienti.', 'Thursday Marco arrived at the café in the afternoon, when there were few customers.'),
        N('Luca lo ha visto e ha sorriso, ma Marco non sembrava tranquillo.', 'Luca saw him and smiled, but Marco did not seem calm.'),
        D('marco', 'Ciao. Posso stare un momento? Non ho bisogno di caffè. Non ho tanti soldi.', 'Hi. Can I stay a moment? I don’t need coffee. I don’t have much money.'),
        D('luca', 'Stai. Non c’è problema. L’acqua è per te.', 'Stay. No problem. The water is for you.', [PH('Non c’è problema', 'there is not problem', 'no problem')]),
        N('Giulia ha portato l’acqua senza dire il prezzo. Ha capito.', 'Giulia brought the water without saying the price. She understood.'),
        N('Marco si è seduto e ha guardato i tavoli vuoti.', 'Marco sat down and looked at the empty tables.'),
      ],
      [
        D('marco', 'Il viaggio è passato. Il biglietto e la valigia li abbiamo trovati. Ricordi?', 'The trip is over. We found the ticket and the suitcase. Do you remember?'),
        D('luca', 'Sì. Adesso sei a Roma, come noi.', 'Yes. Now you are in Rome, like us.'),
        D('marco', 'Sì. Ma il lavoro no. Cerco e non trovo. Ogni giorno è lo stesso.', 'Yes. But not work. I look and I do not find. Every day is the same.'),
        N('Luca ha ascoltato. Il problema di Marco non era più il treno.', 'Luca listened. Marco’s problem was no longer the train.'),
        N('Era i soldi di ogni giorno, e la paura di non trovare un posto.', 'It was everyday money, and the fear of not finding a place.'),
        D('luca', 'Anch’io ho paura. Qui il caffè forse chiude. O cambia.', 'I am afraid too. Here the café might close. Or change.'),
      ],
      [
        D('marco', 'Allora siamo in due. Che bella notizia.', 'Then there are two of us. What good news.'),
        N('Ha detto così, e poi ha sorriso un poco. Luca ha sorriso anche lui.', 'He said it like that, and then he smiled a little. Luca smiled too.'),
        D('giulia', 'Se resta il caffè, magari un giorno c’è bisogno di più persone.', 'If the café stays, maybe one day there is a need for more people.'),
        D('marco', 'Magari. Adesso cerco ancora. Non voglio solo aspettare.', 'Maybe. Now I still look. I don’t want to only wait.'),
        D('luca', 'Se sento qualcosa, ti chiamo. Ci penso io.', 'If I hear something, I’ll call you. I’ll take care of it.', [PH('Ci penso io', 'I think about it I', 'I’ll take care of it')]),
        N('Marco ha detto grazie, e per un momento sembrava meno solo.', 'Marco said thanks, and for a moment he seemed less alone.'),
      ],
      [
        N('Prima di partire, Marco ha chiesto di Sofia.', 'Before leaving, Marco asked about Sofia.'),
        D('luca', 'Domani andiamo da Nonna Rosa. C’è un’idea, forse.', 'Tomorrow we go to Nonna Rosa. There is an idea, maybe.'),
        D('marco', 'Se posso, vengo. Non ho lavoro, ma ho tempo. E ho bisogno degli amici.', 'If I can, I’ll come. I don’t have work, but I have time. And I need friends.'),
        D('luca', 'Vieni. Insieme è meglio.', 'Come. Together is better.'),
        N('Marco è uscito nella strada, e Luca è rimasto a lavorare.', 'Marco went out into the street, and Luca stayed to work.'),
        N('I problemi erano due, e però gli amici erano gli stessi.', 'The problems were two, and yet the friends were the same.'),
      ],
    ],
    [
      Q('character', 'What is Marco’s problem now?', ['He cannot find work and has little money', 'He lost his ticket again', 'He wants to sell the café'], 0, 'The trip is over; everyday money is the issue.'),
      Q('direct', 'What does Luca offer Marco?', ['Water and a promise to call if he hears of work', 'A train ticket', 'His apartment'], 0, 'Giulia brings water; Luca will call.'),
      Q('event', 'What does Marco decide?', ['To come with them to Nonna Rosa if he can', 'To leave Rome tonight', 'To buy the café'], 0, 'He has time and needs friends.'),
    ],
  ),
  ch(
    29,
    'Nonna’s idea',
    'L’idea della nonna',
    ['casa-nonna'],
    ['luca', 'sofia', 'marco', 'nonna-rosa'],
    ev('ev-29-nonna', 'Nonna Rosa hears the news and suggests a Saturday gathering at the café.', ['luca', 'sofia', 'marco', 'nonna-rosa'], ['casa-nonna'], ['Nonna suggests a Saturday festa so people come']),
    [
      [
        N('Venerdì Luca, Sofia e Marco sono andati a casa di Nonna Rosa.', 'Friday Luca, Sofia and Marco went to Nonna Rosa’s house.'),
        N('La casa era piccola, calda e piena di cose vecchie e belle.', 'The house was small, warm, and full of old and beautiful things.'),
        D('nonna-rosa', 'Entrate. Avete fame? C’è pane e qualcosa da mangiare.', 'Come in. Are you hungry? There is bread and something to eat.'),
        D('sofia', 'Grazie, nonna. Prima dobbiamo parlare con te.', 'Thanks, grandma. First we need to talk to you.'),
        N('Si sono seduti, e Luca ha spiegato la notizia del caffè.', 'They sat down, and Luca explained the café news.'),
        N('Nonna Rosa ha ascoltato senza fretta, come fa con le cose importanti.', 'Nonna Rosa listened without hurry, as she does with important things.'),
      ],
      [
        D('nonna-rosa', 'Quel caffè lo conosco da tanti anni. Le persone del quartiere anche.', 'I have known that café for many years. The neighborhood people have too.'),
        D('marco', 'Ma adesso pochi clienti entrano.', 'But now few customers go in.'),
        D('nonna-rosa', 'Perché nessuno chiama le persone? Un caffè non vive solo. Vive con la gente.', 'Why does nobody call the people? A café does not live alone. It lives with people.'),
        N('Sofia ha sorriso. Conosceva quella voce. Era la voce di un piano.', 'Sofia smiled. She knew that voice. It was the voice of a plan.'),
        D('sofia', 'Che idea hai, nonna?', 'What idea do you have, grandma?'),
        D('nonna-rosa', 'Sabato. Una festa piccola. Pane, caffè, musica, amici. Le persone vengono se c’è una ragione.', 'Saturday. A small celebration. Bread, coffee, music, friends. People come if there is a reason.'),
      ],
      [
        D('luca', 'Il padrone non ha deciso. Magari non vuole una festa.', 'The owner has not decided. Maybe he does not want a celebration.'),
        D('nonna-rosa', 'Allora gli diciamo. Non aspettiamo. Gli diamo una ragione per restare, non per vendere.', 'Then we tell him. We don’t wait. We give him a reason to stay, not to sell.'),
        D('marco', 'Io posso aiutare. Non ho soldi, ma ho tempo e posso lavorare.', 'I can help. I don’t have money, but I have time and I can work.'),
        D('sofia', 'Io conosco gente. Posso dire alle persone del quartiere.', 'I know people. I can tell people in the neighborhood.'),
        N('Luca ha sentito qualcosa di nuovo: non era solo il suo problema al lavoro.', 'Luca felt something new: it was not only his problem at work.'),
        N('Era una cosa del gruppo, come il viaggio, ma qui a Roma.', 'It was a group thing, like the trip, but here in Rome.'),
      ],
      [
        D('nonna-rosa', 'Prima parlate con Giulia e con il padrone. Poi, se dicono sì, io vengo sabato.', 'First talk with Giulia and the owner. Then, if they say yes, I come on Saturday.'),
        D('luca', 'Va bene. Ci pensiamo noi. Grazie.', 'All right. We’ll take care of it. Thanks.', [PH('Va bene', 'it goes well', 'okay')]),
        N('Hanno mangiato un poco, e la casa era tranquilla.', 'They ate a little, and the house was quiet.'),
        N('Prima di uscire, Nonna Rosa ha detto a Luca di non avere troppa paura.', 'Before they left, Nonna Rosa told Luca not to be too afraid.'),
        D('nonna-rosa', 'Tu sei giovane, ma non sei solo. Questo è già tanto.', 'You are young, but you are not alone. That is already a lot.'),
        N('Nella strada, i tre amici avevano un piano per il giorno dopo.', 'In the street, the three friends had a plan for the next day.'),
      ],
    ],
    [
      Q('event', 'What idea does Nonna Rosa suggest?', ['A small Saturday gathering at the café', 'Selling the café quickly', 'A trip outside Rome'], 0, 'Bread, coffee, music, friends.'),
      Q('character', 'How can Marco help?', ['With time and hands, not money', 'By paying the owner', 'By leaving the group'], 0, 'He says he has no money but has time.'),
      Q('sequence', 'What must they do first?', ['Talk with Giulia and the owner', 'Buy a train ticket', 'Close the café'], 0, 'Nonna says talk first, then she will come.'),
    ],
  ),
  ch(
    30,
    'We try',
    'Proviamo',
    ['lavoro-caffe'],
    ['luca', 'giulia', 'padrone', 'sofia'],
    ev('ev-30-decide', 'The group asks the owner; he is unsure but lets them try Saturday.', ['luca', 'giulia', 'padrone', 'sofia'], ['lavoro-caffe'], ['The padrone allows a Saturday festa', 'Giulia will help organize']),
    [
      [
        N('Sabato non era ancora arrivato. Prima dovevano scegliere, e decidere.', 'Saturday had not arrived yet. First they had to choose, and decide.'),
        N('Luca e Sofia sono andati al caffè la mattina, e Giulia li ha visti.', 'Luca and Sofia went to the café in the morning, and Giulia saw them.'),
        D('luca', 'Abbiamo un’idea. Una festa piccola, sabato. Per le persone del quartiere.', 'We have an idea. A small celebration, Saturday. For people in the neighborhood.'),
        D('giulia', 'Mi piace. Ma il padrone deve dire sì. Senza di lui non funziona.', 'I like it. But the owner must say yes. Without him it does not work.'),
        N('Il padrone era dentro, vicino alla porta della cucina, e ha ascoltato.', 'The owner was inside, near the kitchen door, and he listened.'),
        N('Non sembrava contento. Sembrava solo stanco.', 'He did not seem glad. He only seemed tired.'),
      ],
      [
        D('sofia', 'Le persone vengono se c’è una ragione. Il caffè può vivere ancora.', 'People come if there is a reason. The café can still live.'),
        D('padrone', 'Una festa costa. Io non ho tanti soldi adesso.', 'A celebration costs. I don’t have much money now.'),
        D('luca', 'Facciamo una cosa piccola. Pane, caffè, amici. Non è un ristorante grande.', 'Let’s do a small thing. Bread, coffee, friends. It is not a big restaurant.'),
        D('giulia', 'Io organizzo con loro. Tu non sei solo in questa cosa.', 'I’ll organize with them. You are not alone in this.'),
        N('Il padrone ha guardato i tavoli vuoti e poi ha guardato i tre giovani.', 'The owner looked at the empty tables and then looked at the three young people.'),
        D('padrone', 'Va bene. Proviamo. Sabato. Se non funziona, io decido dopo.', 'All right. Let’s try. Saturday. If it does not work, I decide after.', [PH('Va bene', 'it goes well', 'okay')]),
      ],
      [
        N('Luca ha sentito il cuore più tranquillo, ma il lavoro non era finito.', 'Luca felt his heart calmer, but the work was not finished.'),
        D('sofia', 'Allora dobbiamo dire alle persone. Io scrivo messaggi. Marco aiuta.', 'Then we must tell people. I’ll write messages. Marco helps.'),
        D('giulia', 'Io preparo la sala e parlo con i clienti che ancora vengono.', 'I’ll prepare the room and talk with the customers who still come.'),
        D('luca', 'Io parlo con il padrone e aiuto dove serve. Ci penso io alla porta.', 'I’ll talk with the owner and help where needed. I’ll take care of the door.', [PH('Ci penso io', 'I think about it I', 'I’ll take care of it')]),
        N('Avevano scelto un giorno, e avevano deciso di restare insieme in questa cosa.', 'They had chosen a day, and they had decided to stay together in this.'),
        N('La notizia difficile aveva adesso un piano, anche se piccolo.', 'The difficult news now had a plan, even if it was small.'),
      ],
      [
        N('Nel pomeriggio qualche cliente è entrato, e Giulia ha parlato della festa.', 'In the afternoon some customers came in, and Giulia talked about the celebration.'),
        N('Una signora ha detto che forse veniva, se aveva tempo.', 'A woman said she might come, if she had time.'),
        N('Non era tanta gente, e però era un primo giorno.', 'It was not many people, and yet it was a first day.'),
        D('sofia', 'Domani lavoriamo su questo. Oggi è già tanto.', 'Tomorrow we work on this. Today is already a lot.'),
        D('luca', 'Sì. Mi sembra giusto.', 'Yes. It seems right to me.', [PH('Mi sembra', 'it seems to me', 'it seems to me')]),
        N('Quando Luca è tornato a casa, ha dormito meglio della notte prima.', 'When Luca went home, he slept better than the night before.'),
      ],
    ],
    [
      Q('event', 'What does the owner decide?', ['They may try a small Saturday gathering', 'He sells the café that day', 'He fires Luca'], 0, 'He says they can try, then he will decide.'),
      Q('character', 'Who will write messages to people?', ['Sofia', 'The owner', 'Luca’s dad'], 0, 'Sofia will write messages; Marco helps.'),
      Q('direct', 'What kind of gathering do they want?', ['Small: bread, coffee, friends', 'A big restaurant night', 'A trip outside Rome'], 0, 'Luca says it is not a big restaurant.'),
    ],
  ),
];

module.exports = { chapters };
