/**
 * Comprehension questions for "Luca a Roma" — chapters 1–20.
 * Exactly 3 questions per chapter (60 total). English `question` always present;
 * selective `questionIt` Italian prompts from ch6 onward (scaffolding ramp).
 */

const questionsByChapterNumber = {
  1: [
    {
      id: 'ch01_q01',
      chapterId: 'luca-a-roma-01',
      type: 'direct',
      question: 'Where does Luca arrive?',
      choices: ['In Rome', 'In Milan', 'In Naples'],
      correctChoice: 0,
      explanation: 'Luca arrives in Rome and goes to the station.',
      difficulty: 1,
    },
    {
      id: 'ch01_q02',
      chapterId: 'luca-a-roma-01',
      type: 'character',
      question: 'How does Luca feel when he arrives?',
      choices: ['Tired and hungry', 'Angry and busy', 'Calm and full'],
      correctChoice: 0,
      explanation: 'Luca is stanco (tired) and has fame (is hungry).',
      difficulty: 1,
    },
    {
      id: 'ch01_q03',
      chapterId: 'luca-a-roma-01',
      type: 'event',
      question: 'What does Luca do near the station?',
      choices: ['He enters a bar', 'He buys a ticket home', 'He finds an apartment'],
      correctChoice: 0,
      explanation: 'Looking for something to eat, Luca finds a bar nearby, goes in, and eats.',
      difficulty: 1,
    },
  ],

  2: [
    {
      id: 'ch02_q01',
      chapterId: 'luca-a-roma-02',
      type: 'event',
      question: 'What does Luca do in the city?',
      choices: ['He walks the streets', 'He starts a new job', 'He leaves Rome'],
      correctChoice: 0,
      explanation: 'Luca walks through Rome and sees that the city is big and beautiful.',
      difficulty: 1,
    },
    {
      id: 'ch02_q02',
      chapterId: 'luca-a-roma-02',
      type: 'direct',
      question: 'What does Luca think about Rome?',
      choices: ['It is big and beautiful', 'It is small and quiet', 'It is empty and cold'],
      correctChoice: 0,
      explanation: 'The chapter stresses that Rome is grande and bella.',
      difficulty: 1,
    },
    {
      id: 'ch02_q03',
      chapterId: 'luca-a-roma-02',
      type: 'sequence',
      question: 'After walking, where does Luca go again?',
      choices: ['Back to the bar', 'To the train station', 'To Sofia’s house'],
      correctChoice: 0,
      explanation: 'He returns to the bar; he is still hungry but feels well (sta bene).',
      difficulty: 1,
    },
  ],

  3: [
    {
      id: 'ch03_q01',
      chapterId: 'luca-a-roma-03',
      type: 'direct',
      question: 'What is Luca looking for?',
      choices: ['A place to live near the center', 'A train ticket', 'A restaurant job'],
      correctChoice: 0,
      explanation: 'Luca searches for an apartment or house near the city center.',
      difficulty: 1,
    },
    {
      id: 'ch03_q02',
      chapterId: 'luca-a-roma-03',
      type: 'event',
      question: 'What problem does Luca face while looking?',
      choices: ['Housing costs a lot', 'There are no streets', 'The bar is closed'],
      correctChoice: 0,
      explanation: 'Places near the center cost a lot, and Luca has few soldi.',
      difficulty: 1,
    },
    {
      id: 'ch03_q03',
      chapterId: 'luca-a-roma-03',
      type: 'character',
      question: 'How much money does Luca have?',
      choices: ['Not much', 'A lot', 'Enough for any apartment'],
      correctChoice: 0,
      explanation: 'He has few soldi, so expensive apartments are a problem.',
      difficulty: 1,
    },
  ],

  4: [
    {
      id: 'ch04_q01',
      chapterId: 'luca-a-roma-04',
      type: 'event',
      question: 'What does Luca find in this chapter?',
      choices: ['A small apartment near the center', 'A big house outside Rome', 'A hotel room for one night'],
      correctChoice: 0,
      explanation: 'He finds a small apartment near the center that he can take.',
      difficulty: 1,
    },
    {
      id: 'ch04_q02',
      chapterId: 'luca-a-roma-04',
      type: 'direct',
      question: 'What does Luca get for the apartment?',
      choices: ['A key', 'A train ticket', 'A job contract'],
      correctChoice: 0,
      explanation: 'He gets the key, opens the door, and sees the room.',
      difficulty: 1,
    },
    {
      id: 'ch04_q03',
      chapterId: 'luca-a-roma-04',
      type: 'character',
      question: 'How is the rent for Luca?',
      choices: ['Not too much', 'Impossible to pay', 'Free'],
      correctChoice: 0,
      explanation: 'The affitto is not too high for him compared with other places.',
      difficulty: 1,
    },
  ],

  5: [
    {
      id: 'ch05_q01',
      chapterId: 'luca-a-roma-05',
      type: 'character',
      question: 'Who does Luca meet at the bar?',
      choices: ['Sofia', 'Marco', 'Giulia'],
      correctChoice: 0,
      explanation: 'At the familiar bar, Luca meets Sofia for the first time.',
      difficulty: 1,
    },
    {
      id: 'ch05_q02',
      chapterId: 'luca-a-roma-05',
      type: 'direct',
      question: 'What do they talk about?',
      choices: ['How they are and that Luca is new in Rome', 'Buying a house together', 'Leaving Italy'],
      correctChoice: 0,
      explanation: 'They greet each other (Come stai) and Luca says he is new in Rome.',
      difficulty: 1,
    },
    {
      id: 'ch05_q03',
      chapterId: 'luca-a-roma-05',
      type: 'event',
      question: 'How do Luca and Sofia end the meeting?',
      choices: ['They say they will see each other again', 'They argue and leave', 'Sofia hires Luca'],
      correctChoice: 0,
      explanation: 'They say “Ci vediamo,” planning to meet again.',
      difficulty: 1,
    },
  ],

  6: [
    {
      id: 'ch06_q01',
      chapterId: 'luca-a-roma-06',
      type: 'event',
      question: 'What does Sofia show Luca?',
      questionIt: 'Cosa mostra Sofia a Luca?',
      choices: ['Her neighborhood', 'The train station', 'A new apartment'],
      correctChoice: 0,
      explanation: 'Sofia takes Luca around her quartiere.',
      difficulty: 1,
    },
    {
      id: 'ch06_q02',
      chapterId: 'luca-a-roma-06',
      type: 'direct',
      question: 'Which places do they see in the neighborhood?',
      choices: ['A shop and a piazza', 'A museum and an airport', 'Only the station'],
      correctChoice: 0,
      explanation: 'They visit a negozio and the piazza.',
      difficulty: 1,
    },
    {
      id: 'ch06_q03',
      chapterId: 'luca-a-roma-06',
      type: 'character',
      question: 'Who helps Luca learn the area?',
      choices: ['Sofia', 'The café owner', 'Nonna Rosa'],
      correctChoice: 0,
      explanation: 'Sofia is the one who shows him around.',
      difficulty: 1,
    },
  ],

  7: [
    {
      id: 'ch07_q01',
      chapterId: 'luca-a-roma-07',
      type: 'direct',
      question: 'Why does Luca need a job?',
      questionIt: 'Perché Luca vuole un lavoro?',
      choices: ['To pay the rent', 'To buy a car', 'To leave Rome forever'],
      correctChoice: 0,
      explanation: 'He needs work so he can pay for his apartment.',
      difficulty: 1,
    },
    {
      id: 'ch07_q02',
      chapterId: 'luca-a-roma-07',
      type: 'character',
      question: 'Who offers to help Luca find work?',
      choices: ['Sofia', 'Marco', 'Giulia'],
      correctChoice: 0,
      explanation: 'Sofia says she will help him with the job search.',
      difficulty: 1,
    },
    {
      id: 'ch07_q03',
      chapterId: 'luca-a-roma-07',
      type: 'event',
      question: 'What is Luca’s main goal in this chapter?',
      choices: ['Finding work for the rent', 'Moving to another city', 'Opening his own bar'],
      correctChoice: 0,
      explanation: 'The chapter centers on needing a job to cover rent.',
      difficulty: 1,
    },
  ],

  8: [
    {
      id: 'ch08_q01',
      chapterId: 'luca-a-roma-08',
      type: 'event',
      question: 'Where does Luca ask about work?',
      questionIt: 'Dove chiede lavoro Luca?',
      choices: ['At a café', 'At the train station', 'At Sofia’s house'],
      correctChoice: 0,
      explanation: 'He goes to a café and asks about a job.',
      difficulty: 1,
    },
    {
      id: 'ch08_q02',
      chapterId: 'luca-a-roma-08',
      type: 'direct',
      question: 'How does Luca start when he asks?',
      choices: ['He says “excuse me” (scusa)', 'He demands a contract', 'He leaves without speaking'],
      correctChoice: 0,
      explanation: 'He politely says scusa when he asks about work.',
      difficulty: 1,
    },
    {
      id: 'ch08_q03',
      chapterId: 'luca-a-roma-08',
      type: 'sequence',
      question: 'What does Luca do after asking?',
      choices: ['He waits for an answer', 'He starts work immediately', 'He buys the café'],
      correctChoice: 0,
      explanation: 'After asking, he waits to hear back.',
      difficulty: 1,
    },
  ],

  9: [
    {
      id: 'ch09_q01',
      chapterId: 'luca-a-roma-09',
      type: 'character',
      question: 'Who offers Luca a job?',
      questionIt: 'Chi offre un lavoro a Luca?',
      choices: ['The café owner (padrone)', 'Sofia', 'Marco'],
      correctChoice: 0,
      explanation: 'The padrone tells Luca he can work there.',
      difficulty: 1,
    },
    {
      id: 'ch09_q02',
      chapterId: 'luca-a-roma-09',
      type: 'direct',
      question: 'What does the owner tell Luca?',
      choices: ['He can work there', 'There is no work', 'He must leave Rome'],
      correctChoice: 0,
      explanation: 'The owner says Luca può lavorare at the café.',
      difficulty: 1,
    },
    {
      id: 'ch09_q03',
      chapterId: 'luca-a-roma-09',
      type: 'event',
      question: 'When does Luca start the job?',
      choices: ['Tomorrow', 'Next month', 'Never'],
      correctChoice: 0,
      explanation: 'He is told he starts tomorrow.',
      difficulty: 1,
    },
  ],

  10: [
    {
      id: 'ch10_q01',
      chapterId: 'luca-a-roma-10',
      type: 'event',
      question: 'What happens on Luca’s first day?',
      choices: ['He works at the café', 'He moves to a new city', 'He quits immediately'],
      correctChoice: 0,
      explanation: 'It is his primo giorno at the café.',
      difficulty: 1,
    },
    {
      id: 'ch10_q02',
      chapterId: 'luca-a-roma-10',
      type: 'character',
      question: 'Who does Luca meet at work?',
      questionIt: 'Chi incontra Luca al lavoro?',
      choices: ['Giulia, a colleague', 'Nonna Rosa', 'Marco'],
      correctChoice: 0,
      explanation: 'He meets Giulia, who works with him.',
      difficulty: 1,
    },
    {
      id: 'ch10_q03',
      chapterId: 'luca-a-roma-10',
      type: 'direct',
      question: 'What is Giulia’s role for Luca?',
      choices: ['She is his colleague', 'She is his landlord', 'She is Sofia’s grandmother'],
      correctChoice: 0,
      explanation: 'Giulia works at the same café as Luca.',
      difficulty: 1,
    },
  ],

  11: [
    {
      id: 'ch11_q01',
      chapterId: 'luca-a-roma-11',
      type: 'character',
      question: 'Who does Luca meet at the café in this chapter?',
      questionIt: 'Chi incontra Luca al caffè?',
      choices: ['Marco, Sofia’s friend', 'A new padrone', 'Only tourists'],
      correctChoice: 0,
      explanation: 'Sofia brings her friend Marco; Luca meets him.',
      difficulty: 1,
    },
    {
      id: 'ch11_q02',
      chapterId: 'luca-a-roma-11',
      type: 'direct',
      question: 'How is Marco connected to Sofia?',
      choices: ['He is her friend', 'He is her boss', 'He is a stranger to her'],
      correctChoice: 0,
      explanation: 'Marco is introduced as Sofia’s friend.',
      difficulty: 1,
    },
    {
      id: 'ch11_q03',
      chapterId: 'luca-a-roma-11',
      type: 'event',
      question: 'Where does the meeting with Marco happen?',
      questionIt: 'Dove incontrano Marco?',
      choices: ['At the café', 'At the station', 'At Nonna Rosa’s house'],
      correctChoice: 0,
      explanation: 'They meet at the café where Luca works.',
      difficulty: 1,
    },
  ],

  12: [
    {
      id: 'ch12_q01',
      chapterId: 'luca-a-roma-12',
      type: 'event',
      question: 'What problem does Marco have?',
      questionIt: 'Qual è il problema di Marco?',
      choices: ['He needs money for a ticket', 'He lost his apartment key', 'He hates the café'],
      correctChoice: 0,
      explanation: 'Marco needs money for a ticket and feels stressed.',
      difficulty: 1,
    },
    {
      id: 'ch12_q02',
      chapterId: 'luca-a-roma-12',
      type: 'character',
      question: 'How does Marco seem?',
      questionIt: 'Come sta Marco?',
      choices: ['Tired and unsure', 'Happy and relaxed', 'Angry at Luca'],
      correctChoice: 0,
      explanation: 'He is tired and says “Non lo so,” showing he is unsure.',
      difficulty: 1,
    },
    {
      id: 'ch12_q03',
      chapterId: 'luca-a-roma-12',
      type: 'direct',
      question: 'What phrase shows Marco does not know what to do?',
      choices: ['“Non lo so”', '“Ci vediamo”', '“Buongiorno”'],
      correctChoice: 0,
      explanation: 'Marco says “Non lo so” when he cannot see a clear solution.',
      difficulty: 1,
    },
  ],

  13: [
    {
      id: 'ch13_q01',
      chapterId: 'luca-a-roma-13',
      type: 'event',
      question: 'How do the friends respond to Marco’s problem?',
      questionIt: 'Come aiutano gli amici Marco?',
      choices: ['They help him', 'They ignore him', 'They fire him'],
      correctChoice: 0,
      explanation: 'The group comes together to help Marco.',
      difficulty: 1,
    },
    {
      id: 'ch13_q02',
      chapterId: 'luca-a-roma-13',
      type: 'character',
      question: 'Who gives Marco money?',
      questionIt: 'Chi dà soldi a Marco?',
      choices: ['Sofia', 'Giulia', 'The train conductor'],
      correctChoice: 0,
      explanation: 'Sofia gives him money so he can get a ticket.',
      difficulty: 1,
    },
    {
      id: 'ch13_q03',
      chapterId: 'luca-a-roma-13',
      type: 'direct',
      question: 'What does the help allow Marco to get?',
      choices: ['A ticket', 'A new apartment', 'A café of his own'],
      correctChoice: 0,
      explanation: 'With the money, Marco can get the ticket he needs.',
      difficulty: 1,
    },
  ],

  14: [
    {
      id: 'ch14_q01',
      chapterId: 'luca-a-roma-14',
      type: 'event',
      question: 'What new urgency appears for Marco?',
      questionIt: 'Cosa deve fare Marco presto?',
      choices: ['He must leave soon', 'He must buy a house', 'He must become padrone'],
      correctChoice: 0,
      explanation: 'A message makes clear that Marco has little time and must leave soon.',
      difficulty: 1,
    },
    {
      id: 'ch14_q02',
      chapterId: 'luca-a-roma-14',
      type: 'direct',
      question: 'How do the friends learn about the urgency?',
      choices: ['From a message', 'From a newspaper', 'From a tourist'],
      correctChoice: 0,
      explanation: 'A phone message tells them Marco must leave soon.',
      difficulty: 2,
    },
    {
      id: 'ch14_q03',
      chapterId: 'luca-a-roma-14',
      type: 'sequence',
      question: 'What do they realize they need next?',
      questionIt: 'Di cosa hanno bisogno?',
      choices: ['A plan', 'A bigger apartment', 'A new café'],
      correctChoice: 0,
      explanation: 'With little time left, they need a piano (plan).',
      difficulty: 1,
    },
  ],

  15: [
    {
      id: 'ch15_q01',
      chapterId: 'luca-a-roma-15',
      type: 'character',
      question: 'Whose house is part of making the plan?',
      questionIt: 'Di chi è la casa?',
      choices: ['Nonna Rosa’s', 'Giulia’s', 'The padrone’s'],
      correctChoice: 0,
      explanation: 'The group is at Nonna Rosa’s as they form their plan.',
      difficulty: 1,
    },
    {
      id: 'ch15_q02',
      chapterId: 'luca-a-roma-15',
      type: 'event',
      question: 'What do they decide?',
      questionIt: 'Cosa decidono?',
      choices: ['To leave together tomorrow', 'To stay in Rome forever', 'To fire Marco'],
      correctChoice: 0,
      explanation: 'Their plan is to leave together the next day.',
      difficulty: 1,
    },
    {
      id: 'ch15_q03',
      chapterId: 'luca-a-roma-15',
      type: 'inference',
      question: 'Why is Nonna Rosa important in this chapter?',
      choices: [
        'Her place is where the group makes the plan',
        'She sells them train tickets',
        'She takes Marco’s job',
      ],
      correctChoice: 0,
      explanation: 'The plan comes together at Nonna Rosa’s house.',
      difficulty: 2,
    },
  ],

  16: [
    {
      id: 'ch16_q01',
      chapterId: 'luca-a-roma-16',
      type: 'event',
      question: 'Where do they go to leave?',
      questionIt: 'Dove vanno per partire?',
      choices: ['To the station', 'To the café', 'To the piazza'],
      correctChoice: 0,
      explanation: 'They go to the station with their luggage.',
      difficulty: 1,
    },
    {
      id: 'ch16_q02',
      chapterId: 'luca-a-roma-16',
      type: 'direct',
      question: 'What do they bring with them?',
      questionIt: 'Cosa portano con loro?',
      choices: ['A suitcase (valigia)', 'A new apartment key', 'Only empty hands'],
      correctChoice: 0,
      explanation: 'They have a valigia as they head for the train.',
      difficulty: 1,
    },
    {
      id: 'ch16_q03',
      chapterId: 'luca-a-roma-16',
      type: 'sequence',
      question: 'What happens after they reach the station?',
      questionIt: 'Cosa fanno alla stazione?',
      choices: ['They take the train and leave Rome', 'They go back to work', 'They cancel the trip'],
      correctChoice: 0,
      explanation: 'They board the train and leave Rome.',
      difficulty: 1,
    },
  ],

  17: [
    {
      id: 'ch17_q01',
      chapterId: 'luca-a-roma-17',
      type: 'direct',
      question: 'Where are they during this chapter?',
      questionIt: 'Dove sono in questo capitolo?',
      choices: ['Outside Rome, on the trip', 'Back at the café', 'Still at the station only'],
      correctChoice: 0,
      explanation: 'They are fuori da Roma, continuing the journey.',
      difficulty: 1,
    },
    {
      id: 'ch17_q02',
      chapterId: 'luca-a-roma-17',
      type: 'event',
      question: 'What do they do on the trip?',
      questionIt: 'Cosa fanno durante il viaggio?',
      choices: ['They eat and the trip goes well', 'They lose the train on purpose', 'They return immediately'],
      correctChoice: 0,
      explanation: 'They eat, talk, and the viaggio goes well.',
      difficulty: 1,
    },
    {
      id: 'ch17_q03',
      chapterId: 'luca-a-roma-17',
      type: 'character',
      question: 'How is the group feeling about the journey so far?',
      questionIt: 'Come va il viaggio?',
      choices: ['Things are going fine', 'Everything has already failed', 'They are lost in Milan'],
      correctChoice: 0,
      explanation: 'At this point the trip is still going well.',
      difficulty: 2,
    },
  ],

  18: [
    {
      id: 'ch18_q01',
      chapterId: 'luca-a-roma-18',
      type: 'event',
      question: 'What surprise happens on the train?',
      questionIt: 'Cosa succede sul treno?',
      choices: ['There is a problem with the ticket or suitcase', 'They win a prize', 'Sofia buys a house'],
      correctChoice: 0,
      explanation: 'A problem appears: the ticket and/or valigia cannot be found.',
      difficulty: 1,
    },
    {
      id: 'ch18_q02',
      chapterId: 'luca-a-roma-18',
      type: 'direct',
      question: 'What cannot be found?',
      questionIt: 'Cosa non trovano?',
      choices: ['The ticket and the suitcase', 'Sofia’s phone only', 'The café menu'],
      correctChoice: 0,
      explanation: 'Marco cannot find the ticket, and the suitcase is missing.',
      difficulty: 1,
    },
    {
      id: 'ch18_q03',
      chapterId: 'luca-a-roma-18',
      type: 'inference',
      question: 'Why is this a serious problem for the group?',
      questionIt: 'Perché è un problema serio?',
      choices: [
        'Without the ticket and suitcase they cannot continue smoothly',
        'They already arrived home',
        'The café owner called them back',
      ],
      correctChoice: 0,
      explanation: 'Missing travel essentials stops a smooth continuation of the trip.',
      difficulty: 2,
    },
  ],

  19: [
    {
      id: 'ch19_q01',
      chapterId: 'luca-a-roma-19',
      type: 'event',
      question: 'How is the problem solved?',
      questionIt: 'Come risolvono il problema?',
      choices: ['They find the suitcase and ticket together', 'They abandon Marco', 'They buy a new train'],
      correctChoice: 0,
      explanation: 'Working together, they find the valigia and the ticket.',
      difficulty: 1,
    },
    {
      id: 'ch19_q02',
      chapterId: 'luca-a-roma-19',
      type: 'character',
      question: 'Who solves the problem?',
      questionIt: 'Chi risolve il problema?',
      choices: ['The friends, together', 'Only the train conductor alone', 'Only Nonna Rosa from Rome'],
      correctChoice: 0,
      explanation: 'They resolve it as a group.',
      difficulty: 1,
    },
    {
      id: 'ch19_q03',
      chapterId: 'luca-a-roma-19',
      type: 'sequence',
      question: 'What comes after they find what was missing?',
      questionIt: 'Cosa succede dopo?',
      choices: ['The problem is resolved', 'They get stuck forever', 'They start a new job on the train'],
      correctChoice: 0,
      explanation: 'Finding the suitcase and ticket means the crisis is over.',
      difficulty: 2,
    },
  ],

  20: [
    {
      id: 'ch20_q01',
      chapterId: 'luca-a-roma-20',
      type: 'event',
      question: 'Where do they go at the end?',
      questionIt: 'Dove vanno alla fine?',
      choices: ['Back to Rome', 'To a new country', 'Nowhere—they stay on the train'],
      correctChoice: 0,
      explanation: 'They return to Rome (tornare a casa).',
      difficulty: 1,
    },
    {
      id: 'ch20_q02',
      chapterId: 'luca-a-roma-20',
      type: 'direct',
      question: 'What does Luca have when he returns?',
      questionIt: 'Cosa ha Luca quando torna?',
      choices: ['A home, a job, and friends', 'Only a suitcase', 'Nothing at all'],
      correctChoice: 0,
      explanation: 'He has casa, lavoro, and amici—home, work, and friends.',
      difficulty: 1,
    },
    {
      id: 'ch20_q03',
      chapterId: 'luca-a-roma-20',
      type: 'inference',
      question: 'What does the ending show about Luca’s life in Rome?',
      questionIt: 'Cosa mostra la fine della storia?',
      choices: [
        'He has built a real life there with work and friends',
        'He never found a place to stay',
        'He is alone and without work',
      ],
      correctChoice: 0,
      explanation: 'Returning with friends and having home and a job shows he belongs in Rome.',
      difficulty: 2,
    },
  ],
};

module.exports = { questionsByChapterNumber };
