module.exports = [
  {
    number: 3,
    title: "Tuesday",
    titleIt: "Martedì",
    summary: "Pietro delivers coffee on Tuesday. They talk about the weather. He looks at the book shelf, not at Elena.",
    facts: [
          "Pietro delivers coffee on Tuesdays",
          "Pietro is quiet and awkward at the counter",
          "Elena and Pietro talk only about the weather",
          "Pietro looks at the shelf with the book, not at Elena"
    ],
    locationIds: ["caffe-brenta","bancone-brenta","scaffale-libro","van-pietro"],
    characterIds: ["elena-marini","pietro-baldo","bruna","katia"],
    sentences: [
      { text: "Martedì mattina il Caffè Brenta apre presto.", en: "Tuesday morning Caffè Brenta opens early.", speakerId: null },
      { text: "Elena mette lo zucchero nelle ciotole sul bancone.", en: "Elena puts sugar in the bowls on the counter.", speakerId: null },
      { text: "Katia prepara le tazzine e controlla la macchina del caffè.", en: "Katia prepares the cups and checks the coffee machine.", speakerId: null },
      { text: "Fuori c'è nebbia su Marina di Brenta.", en: "Outside there is fog over Marina di Brenta.", speakerId: null },
      { text: "Un furgone si ferma davanti al caffè.", en: "A van stops in front of the café.", speakerId: null },
      { text: "Bruna guarda dalla finestra e annuisce.", en: "Bruna looks from the window and nods.", speakerId: null },
      { text: "È Pietro. Martedì.", en: "It's Pietro. Tuesday.", speakerId: "bruna" },
      { text: "Pietro entra con due scatole di caffè.", en: "Pietro comes in with two boxes of coffee.", speakerId: null },
      { text: "Ha le mani grandi e lo sguardo basso.", en: "He has big hands and his gaze down.", speakerId: null },
      { text: "Porta l'odore del furgone e dei chicchi.", en: "He brings the smell of the van and the beans.", speakerId: null },
      { text: "Buongiorno.", en: "Good morning.", speakerId: "pietro-baldo" },
      { text: "Buongiorno.", en: "Good morning.", speakerId: "elena-marini" },
      { text: "Bruna fa le presentazioni vicino al bancone.", en: "Bruna makes introductions near the counter.", speakerId: null },
      { text: "Elena, questo è Pietro. Porta il caffè ogni martedì.", en: "Elena, this is Pietro. He brings the coffee every Tuesday.", speakerId: "bruna" },
      { text: "Pietro, Elena lavora qui da pochi giorni.", en: "Pietro, Elena has worked here for a few days.", speakerId: "bruna" },
      { text: "Piacere.", en: "Nice to meet you.", speakerId: "pietro-baldo" },
      { text: "Piacere.", en: "Nice to meet you.", speakerId: "elena-marini" },
      { text: "Poi c'è un silenzio corto e strano.", en: "Then there is a short, strange silence.", speakerId: null },
      { text: "Elena cerca una frase facile.", en: "Elena looks for an easy sentence.", speakerId: null },
      { text: "C'è tanta nebbia oggi.", en: "There's a lot of fog today.", speakerId: "elena-marini" },
      { text: "Sì. Tanto.", en: "Yes. A lot.", speakerId: "pietro-baldo" },
      { text: "Katia alza un sopracciglio dietro al bancone.", en: "Katia raises an eyebrow behind the counter.", speakerId: null },
      { text: "Pietro lascia le scatole vicino alla porta del magazzino.", en: "Pietro leaves the boxes near the storeroom door.", speakerId: null },
      { text: "Bruna firma un foglio sul bancone.", en: "Bruna signs a sheet on the counter.", speakerId: null },
      { text: "Vuoi un caffè prima di ripartire?", en: "Do you want a coffee before you leave?", speakerId: "elena-marini" },
      { text: "No, grazie. Devo andare.", en: "No, thanks. I have to go.", speakerId: "pietro-baldo" },
      { text: "Parlano ancora del tempo, perché non sanno altro.", en: "They talk about the weather again, because they don't know what else.", speakerId: null },
      { text: "Domani forse piove.", en: "Maybe it will rain tomorrow.", speakerId: "elena-marini" },
      { text: "Forse. In laguna cambia sempre.", en: "Maybe. On the lagoon it always changes.", speakerId: "pietro-baldo" },
      { text: "L'aria tra loro è morta.", en: "The air between them is dead.", speakerId: null },
      { text: "Elena è brava al bancone con i clienti.", en: "Elena is good at the counter with customers.", speakerId: null },
      { text: "Con Pietro le parole sono piccole e fredde.", en: "With Pietro the words are small and cold.", speakerId: null },
      { text: "Lei sistema lo zucchero senza motivo.", en: "She rearranges the sugar for no reason.", speakerId: null },
      { text: "Lui tiene le chiavi del furgone in mano.", en: "He holds the van keys in his hand.", speakerId: null },
      { text: "Prima di uscire, Pietro guarda verso lo scaffale.", en: "Before leaving, Pietro looks toward the shelf.", speakerId: null },
      { text: "Non guarda Elena.", en: "He does not look at Elena.", speakerId: null },
      { text: "Guarda il libro grosso vicino allo zucchero.", en: "He looks at the thick book near the sugar.", speakerId: null },
      { text: "Solo un secondo, ma Elena lo vede.", en: "Only a second, but Elena sees it.", speakerId: null },
      { text: "Poi lui apre la porta e saluta Bruna.", en: "Then he opens the door and greets Bruna.", speakerId: null },
      { text: "A martedì prossimo.", en: "See you next Tuesday.", speakerId: "bruna" },
      { text: "Sì. Martedì.", en: "Yes. Tuesday.", speakerId: "pietro-baldo" },
      { text: "Esce senza fare altro rumore.", en: "He leaves without making more noise.", speakerId: null },
      { text: "Il furgone parte nella nebbia.", en: "The van leaves into the fog.", speakerId: null },
      { text: "Elena resta al bancone con una tazza vuota in mano.", en: "Elena stays at the counter with an empty cup in her hand.", speakerId: null },
      { text: "Ha parlato di nebbia e di pioggia.", en: "She talked about fog and rain.", speakerId: null },
      { text: "Niente di vero. Niente di vivo.", en: "Nothing true. Nothing alive.", speakerId: null },
      { text: "Katia lava una tazza e parla piano.", en: "Katia washes a cup and speaks quietly.", speakerId: null },
      { text: "Bel discorso.", en: "Nice conversation.", speakerId: "katia" },
      { text: "Elena alza le spalle.", en: "Elena shrugs.", speakerId: null },
      { text: "È timido.", en: "He's shy.", speakerId: "elena-marini" },
      { text: "O forse ha solo fretta.", en: "Or maybe he's just in a hurry.", speakerId: "elena-marini" },
      { text: "Nel pomeriggio i clienti diminuiscono.", en: "In the afternoon the customers thin out.", speakerId: null },
      { text: "Elena apre il libro sullo scaffale.", en: "Elena opens the book on the shelf.", speakerId: null },
      { text: "Non c'è una riga nuova.", en: "There is no new line.", speakerId: null },
      { text: "C'è ancora vero sotto questo tavolo balla.", en: "There is still vero under questo tavolo balla.", speakerId: null },
      { text: "Elena chiude il libro e lo rimette vicino allo zucchero.", en: "Elena closes the book and puts it back near the sugar.", speakerId: null },
      { text: "Pensa allo sguardo di Pietro sullo scaffale.", en: "She thinks of Pietro's glance at the shelf.", speakerId: null },
      { text: "Perché ha guardato il libro e non lei?", en: "Why did he look at the book and not at her?", speakerId: null },
      { text: "Bruna mette i chicchi nuovi nel magazzino e torna al bancone.", en: "Bruna puts the new beans in the storeroom and returns to the counter.", speakerId: null },
      { text: "Il martedì è sempre così: caffè, fogli e poco altro.", en: "Tuesday is always like this: coffee, papers, and little else.", speakerId: "bruna" },
      { text: "Elena annuisce e serve un cliente con lo zucchero.", en: "Elena nods and serves a customer with sugar.", speakerId: null },
      { text: "Vorrebbe parlare meglio, ma non sa come.", en: "She would like to talk better, but she does not know how.", speakerId: null },
      { text: "Katia cambia argomento e parla di un tavolo sporco.", en: "Katia changes the subject and talks about a dirty table.", speakerId: null },
      { text: "Quel tavolo vicino alla finestra balla ancora.", en: "That table near the window still wobbles.", speakerId: "katia" },
      { text: "Elena va a sistemarlo con un pezzo di carta.", en: "Elena goes to fix it with a piece of paper.", speakerId: null },
      { text: "Mentre lavora, ripensa allo sguardo di Pietro sul libro.", en: "While she works, she thinks again of Pietro looking at the book.", speakerId: null },
      { text: "Forse ha solo cercato lo zucchero.", en: "Maybe he was only looking for the sugar.", speakerId: null },
      { text: "O forse no.", en: "Or maybe not.", speakerId: null },
      { text: "Alla fine del turno Elena lava le ultime tazzine.", en: "At the end of the shift Elena washes the last cups.", speakerId: null },
      { text: "Il furgone non c'è più. Resta solo il martedì nella testa.", en: "The van is gone. Only Tuesday remains in her head.", speakerId: null },
      { text: "Non trova una risposta.", en: "She finds no answer.", speakerId: null },
      { text: "Torna al bancone e prepara un altro caffè.", en: "She goes back to the counter and makes another coffee.", speakerId: null },
      { text: "Il martedì finisce così: con nebbia fuori e silenzio dentro.", en: "Tuesday ends like that: with fog outside and silence inside.", speakerId: null },
    ],
    questions: [
      {
        type: "direct",
        question: "When does Pietro deliver coffee?",
        choices: ["On Tuesdays","On Sundays","Every night"],
        correctChoice: 0,
        explanation: "Bruna says he brings coffee every Tuesday."
      },
      {
        type: "direct",
        question: "What do Elena and Pietro talk about?",
        choices: ["The weather","The book rules","Elena's mother"],
        correctChoice: 0,
        explanation: "They only manage fog and rain talk."
      },
      {
        type: "direct",
        question: "Where does Pietro look before leaving?",
        choices: ["At the shelf with the book","At Katia's phone","At Elena's face"],
        correctChoice: 0,
        explanation: "He looks at the shelf near the sugar, not at Elena."
      },
    ]
  },
  {
    number: 4,
    title: "The second line",
    titleIt: "La seconda riga",
    summary: "A new note appears: oggi ho paura del silenzio. Elena answers with too many words and feels exposed.",
    facts: [
          "A new line appears: oggi ho paura del silenzio",
          "Elena writes a long personal answer",
          "Elena feels she answered too much",
          "The book conversation becomes more emotional"
    ],
    locationIds: ["caffe-brenta","bancone-brenta","scaffale-libro"],
    characterIds: ["elena-marini","bruna","katia"],
    sentences: [
      { text: "Mercoledì il caffè è pieno fin dal mattino.", en: "On Wednesday the café is full from the morning.", speakerId: null },
      { text: "Elena lavora al bancone senza pensare troppo.", en: "Elena works at the counter without thinking too much.", speakerId: null },
      { text: "Prepara cappuccini, mette lo zucchero, sorride.", en: "She makes cappuccinos, puts out sugar, smiles.", speakerId: null },
      { text: "Poi, tra due ordini, si ferma vicino allo scaffale.", en: "Then, between two orders, she stops near the shelf.", speakerId: null },
      { text: "Apre il libro con le mani ancora umide.", en: "She opens the book with hands still damp.", speakerId: null },
      { text: "C'è una riga nuova, scritta con penna nera.", en: "There is a new line, written in black pen.", speakerId: null },
      { text: "Oggi ho paura del silenzio.", en: "Today I am afraid of silence.", speakerId: null },
      { text: "Elena legge due volte.", en: "Elena reads it twice.", speakerId: null },
      { text: "La frase è semplice e vera.", en: "The sentence is simple and true.", speakerId: null },
      { text: "Le sembra di conoscerla già, dentro.", en: "It feels like she already knows it, inside.", speakerId: null },
      { text: "Prende la penna dal bancone.", en: "She takes the pen from the counter.", speakerId: null },
      { text: "Vuole scrivere poco, come l'altra volta.", en: "She wants to write little, like last time.", speakerId: null },
      { text: "Invece la mano corre.", en: "Instead her hand runs.", speakerId: null },
      { text: "Anche io.", en: "Me too.", speakerId: null },
      { text: "Al bancone parlo facile con tutti.", en: "At the counter I talk easily with everyone.", speakerId: null },
      { text: "A casa il silenzio è pesante.", en: "At home silence is heavy.", speakerId: null },
      { text: "A volte preferisco lo zucchero, le tazze e il rumore del caffè.", en: "Sometimes I prefer sugar, cups, and the noise of the café.", speakerId: null },
      { text: "Se scrivo qui, non tremo.", en: "If I write here, I do not tremble.", speakerId: null },
      { text: "Se parlo, sì.", en: "If I speak, I do.", speakerId: null },
      { text: "Elena guarda la pagina piena.", en: "Elena looks at the full page.", speakerId: null },
      { text: "Ha scritto troppo.", en: "She has written too much.", speakerId: null },
      { text: "Vuole cancellare, ma l'inchiostro è già secco.", en: "She wants to erase it, but the ink is already dry.", speakerId: null },
      { text: "Chiude il libro e torna al bancone in fretta.", en: "She closes the book and hurries back to the counter.", speakerId: null },
      { text: "Un cliente chiede un cappuccino senza zucchero.", en: "A customer asks for a cappuccino without sugar.", speakerId: null },
      { text: "Elena sorride e lavora, ma dentro è ancora sul libro.", en: "Elena smiles and works, but inside she is still on the book.", speakerId: null },
      { text: "Katia nota il suo silenzio.", en: "Katia notices her silence.", speakerId: null },
      { text: "Tutto bene?", en: "Everything okay?", speakerId: "katia" },
      { text: "Sì. Solo pensieri.", en: "Yes. Just thoughts.", speakerId: "elena-marini" },
      { text: "Bruna passa vicino allo scaffale e non apre il libro.", en: "Bruna passes near the shelf and does not open the book.", speakerId: null },
      { text: "Nel pomeriggio i clienti diminuiscono.", en: "In the afternoon the customers thin out.", speakerId: null },
      { text: "Elena asciuga il bancone due volte.", en: "Elena wipes the counter twice.", speakerId: null },
      { text: "Poi rilegge la sua risposta di nascosto.", en: "Then she secretly rereads her answer.", speakerId: null },
      { text: "Le sembra troppo personale.", en: "It feels too personal.", speakerId: null },
      { text: "La riga dell'altro era corta.", en: "The other person's line was short.", speakerId: null },
      { text: "La sua è lunga e scoperta.", en: "Hers is long and exposed.", speakerId: null },
      { text: "Ha paura di aver detto troppo a uno sconosciuto.", en: "She is afraid she said too much to a stranger.", speakerId: null },
      { text: "Ma non toglie la pagina.", en: "But she does not take the page away.", speakerId: null },
      { text: "Lascia le parole dove sono.", en: "She leaves the words where they are.", speakerId: null },
      { text: "Alla sera Bruna conta i soldi vicino alla cassa.", en: "In the evening Bruna counts the money near the register.", speakerId: null },
      { text: "Elena mette lo zucchero a posto e spegne una luce.", en: "Elena puts the sugar back and turns off a light.", speakerId: null },
      { text: "Il libro resta sullo scaffale, chiuso e pesante.", en: "The book stays on the shelf, closed and heavy.", speakerId: null },
      { text: "Elena esce e cammina nella nebbia di Marina di Brenta.", en: "Elena goes out and walks in the fog of Marina di Brenta.", speakerId: null },
      { text: "Ripete la frase nella testa come una canzone corta.", en: "She repeats the sentence in her head like a short song.", speakerId: null },
      { text: "Oggi ho paura del silenzio.", en: "Today I am afraid of silence.", speakerId: null },
      { text: "Anche lei ha paura.", en: "She is afraid too.", speakerId: null },
      { text: "Ma al bancone nessuno lo sa.", en: "But at the counter nobody knows.", speakerId: null },
      { text: "Prima di scrivere, Elena ascolta il rumore del bancone.", en: "Before writing, Elena listens to the noise of the counter.", speakerId: null },
      { text: "Un caffè, due zuccheri, un tavolo vicino alla porta.", en: "One coffee, two sugars, a table near the door.", speakerId: null },
      { text: "Poi la riga nuova la ferma.", en: "Then the new line stops her.", speakerId: null },
      { text: "Ha paura anche lei, ma di solito lo nasconde con una frase facile.", en: "She is afraid too, but usually she hides it with an easy sentence.", speakerId: null },
      { text: "Nel libro non nasconde niente.", en: "In the book she hides nothing.", speakerId: null },
      { text: "Scrive ancora: a Padova parlavo di lavoro.", en: "She also writes: in Padova I talked about work.", speakerId: null },
      { text: "Qui parlo di tutto e di niente.", en: "Here I talk about everything and nothing.", speakerId: null },
      { text: "Il silenzio vero arriva dopo, quando chiudo il caffè.", en: "The real silence comes later, when I close the café.", speakerId: null },
      { text: "Bruna le chiede se vuole un cornetto.", en: "Bruna asks if she wants a croissant.", speakerId: null },
      { text: "No, grazie. Solo caffè.", en: "No, thanks. Just coffee.", speakerId: "elena-marini" },
      { text: "Elena beve e pensa alla seconda riga.", en: "Elena drinks and thinks of the second line.", speakerId: null },
      { text: "Vorrebbe sapere chi ha paura del silenzio.", en: "She would like to know who is afraid of silence.", speakerId: null },
      { text: "Ma la regola è chiara: non si chiede chi.", en: "But the rule is clear: you do not ask who.", speakerId: null },
      { text: "Così lascia la domanda chiusa nel petto.", en: "So she leaves the question shut in her chest.", speakerId: null },
      { text: "E lascia troppe risposte sulla carta.", en: "And she leaves too many answers on paper.", speakerId: null },
      { text: "Solo il libro. Solo quella seconda riga.", en: "Only the book. Only that second line.", speakerId: null },
      { text: "Elena pensa: la prossima volta scrivo meno.", en: "Elena thinks: next time I will write less.", speakerId: null },
      { text: "Non è sicura di riuscirci.", en: "She is not sure she can.", speakerId: null },
    ],
    questions: [
      {
        type: "direct",
        question: "What is the new line in the book?",
        choices: ["Oggi ho paura del silenzio","Questo tavolo balla","Martedì porto il caffè"],
        correctChoice: 0,
        explanation: "The stranger writes about fear of silence."
      },
      {
        type: "direct",
        question: "How does Elena answer?",
        choices: ["With a long personal reply","With one word only","She does not answer"],
        correctChoice: 0,
        explanation: "She writes too much about home and the counter."
      },
      {
        type: "direct",
        question: "How does Elena feel after writing?",
        choices: ["She thinks she wrote too much","She wants to sell the book","She tells Katia everything"],
        correctChoice: 0,
        explanation: "She is ashamed of the long answer."
      },
    ]
  },
  {
    number: 5,
    title: "Katia",
    titleIt: "Katia",
    summary: "Katia says everyone writes in the book and nobody admits it. She herself has never written.",
    facts: [
          "Many people write in the book",
          "Nobody admits writing",
          "Katia has never written in the book",
          "Elena keeps her own writing secret"
    ],
    locationIds: ["caffe-brenta","bancone-brenta","scaffale-libro"],
    characterIds: ["elena-marini","katia","bruna"],
    sentences: [
      { text: "Giovedì piove piano su Marina di Brenta.", en: "On Thursday it rains lightly on Marina di Brenta.", speakerId: null },
      { text: "Il Caffè Brenta ha pochi clienti.", en: "Caffè Brenta has few customers.", speakerId: null },
      { text: "Elena e Katia lavorano al bancone senza fretta.", en: "Elena and Katia work at the counter without hurry.", speakerId: null },
      { text: "Katia asciuga una tazza e parla senza guardare Elena.", en: "Katia dries a cup and talks without looking at Elena.", speakerId: null },
      { text: "Tu hai scritto nel libro.", en: "You wrote in the book.", speakerId: "katia" },
      { text: "Elena si ferma con lo zucchero in mano.", en: "Elena stops with the sugar in her hand.", speakerId: null },
      { text: "Non è una domanda forte. È una frase quieta.", en: "It is not a strong question. It is a quiet sentence.", speakerId: null },
      { text: "Forse.", en: "Maybe.", speakerId: "elena-marini" },
      { text: "Katia sorride un poco.", en: "Katia smiles a little.", speakerId: null },
      { text: "Tutti scrivono.", en: "Everyone writes.", speakerId: "katia" },
      { text: "Nessuno ammette.", en: "Nobody admits it.", speakerId: "katia" },
      { text: "Elena mette lo zucchero in una ciotola e respira.", en: "Elena puts sugar in a bowl and breathes.", speakerId: null },
      { text: "Anche Bruna?", en: "Bruna too?", speakerId: "elena-marini" },
      { text: "Bruna guarda. Non scrive sempre.", en: "Bruna watches. She doesn't always write.", speakerId: "katia" },
      { text: "A volte legge e basta.", en: "Sometimes she only reads.", speakerId: "katia" },
      { text: "E tu?", en: "And you?", speakerId: "elena-marini" },
      { text: "Katia scuote la testa e mette la tazza sullo scaffale.", en: "Katia shakes her head and puts the cup on the shelf.", speakerId: null },
      { text: "Io non ho mai scritto.", en: "I have never written.", speakerId: "katia" },
      { text: "Perché?", en: "Why?", speakerId: "elena-marini" },
      { text: "Perché se lo scrivo, poi è vero.", en: "Because if I write it, then it is true.", speakerId: "katia" },
      { text: "Elena capisce subito.", en: "Elena understands at once.", speakerId: null },
      { text: "Per lei il libro è più facile della voce.", en: "For her the book is easier than the voice.", speakerId: null },
      { text: "Per Katia è il contrario: la carta fa paura.", en: "For Katia it is the opposite: paper is scary.", speakerId: null },
      { text: "Bruna esce dal magazzino con un sacco di caffè.", en: "Bruna comes out of the storeroom with a bag of coffee.", speakerId: null },
      { text: "Di che parlate?", en: "What are you talking about?", speakerId: "bruna" },
      { text: "Del bancone. Dello zucchero.", en: "About the counter. About the sugar.", speakerId: "katia" },
      { text: "Elena non corregge la bugia piccola.", en: "Elena does not correct the small lie.", speakerId: null },
      { text: "Nel pomeriggio Elena rilegge alcune pagine del libro.", en: "In the afternoon Elena rereads some pages of the book.", speakerId: null },
      { text: "Ci sono mani diverse e inchiostri diversi.", en: "There are different hands and different inks.", speakerId: null },
      { text: "Alcune frasi sono pratiche: il tavolo, il caffè, il martedì.", en: "Some sentences are practical: the table, the coffee, Tuesday.", speakerId: null },
      { text: "Altre sono paura e solitudine.", en: "Others are fear and loneliness.", speakerId: null },
      { text: "Nessuno firma. Nessuno dice il proprio nome.", en: "Nobody signs. Nobody says their name.", speakerId: null },
      { text: "Elena pensa a Katia, che vede tutto e dice poco.", en: "Elena thinks of Katia, who sees everything and says little.", speakerId: null },
      { text: "Pensa anche a se stessa, che scrive troppo.", en: "She also thinks of herself, who writes too much.", speakerId: null },
      { text: "Alla sera chiudono il caffè insieme.", en: "In the evening they close the café together.", speakerId: null },
      { text: "Katia spegne le luci vicino allo scaffale.", en: "Katia turns off the lights near the shelf.", speakerId: null },
      { text: "Il libro resta al suo posto, vicino allo zucchero.", en: "The book stays in its place, near the sugar.", speakerId: null },
      { text: "Elena?", en: "Elena?", speakerId: "katia" },
      { text: "Sì.", en: "Yes.", speakerId: "elena-marini" },
      { text: "Non chiedere chi scrive.", en: "Don't ask who writes.", speakerId: "katia" },
      { text: "Lo so. È una regola di Bruna.", en: "I know. It's one of Bruna's rules.", speakerId: "elena-marini" },
      { text: "Katia mette la giacca e apre la porta.", en: "Katia puts on her jacket and opens the door.", speakerId: null },
      { text: "Non è solo una regola.", en: "It's not only a rule.", speakerId: "katia" },
      { text: "È anche protezione.", en: "It's also protection.", speakerId: "katia" },
      { text: "Escono insieme sotto la pioggia leggera.", en: "They go out together under the light rain.", speakerId: null },
      { text: "Elena non dice che ha paura del silenzio anche lei.", en: "Elena does not say that she is afraid of silence too.", speakerId: null },
      { text: "Lo ha già scritto nel libro, dove nessuno ammette.", en: "She has already written it in the book, where nobody admits.", speakerId: null },
      { text: "Katia cammina accanto a lei senza fare altre domande.", en: "Katia walks beside her without asking more questions.", speakerId: null },
      { text: "Elena sistema le bustine di zucchero in fila sul bancone.", en: "Elena lines up the sugar packets on the counter.", speakerId: null },
      { text: "Katia parla ancora del libro come di una cosa normale e pericolosa.", en: "Katia still talks about the book as something normal and dangerous.", speakerId: null },
      { text: "Una volta un cliente ha chiesto se si vendeva.", en: "Once a customer asked if it was for sale.", speakerId: "katia" },
      { text: "Bruna ha detto no. Punto.", en: "Bruna said no. Period.", speakerId: "katia" },
      { text: "Elena ride piano.", en: "Elena laughs softly.", speakerId: null },
      { text: "Io non lo venderei.", en: "I would not sell it.", speakerId: "elena-marini" },
      { text: "Certo. Perché ci hai scritto dentro.", en: "Of course. Because you wrote in it.", speakerId: "katia" },
      { text: "Elena non conferma e non nega.", en: "Elena neither confirms nor denies.", speakerId: null },
      { text: "Guarda lo scaffale e cambia discorso.", en: "She looks at the shelf and changes the subject.", speakerId: null },
      { text: "Il tavolo balla ancora?", en: "Does the table still wobble?", speakerId: "elena-marini" },
      { text: "Sì. Come le persone.", en: "Yes. Like people.", speakerId: "katia" },
      { text: "Nel pomeriggio arriva un po' di sole tra la pioggia.", en: "In the afternoon a little sun comes through the rain.", speakerId: null },
      { text: "Elena pensa che Katia conosce il caffè meglio di lei.", en: "Elena thinks that Katia knows the café better than she does.", speakerId: null },
      { text: "Conosce anche i silenzi.", en: "She also knows the silences.", speakerId: null },
      { text: "Per questo non scrive: non vuole lasciare prove.", en: "That is why she does not write: she does not want to leave proof.", speakerId: null },
      { text: "Al bancone sono colleghe.", en: "At the counter they are colleagues.", speakerId: null },
      { text: "Nel libro Elena è sola con una voce senza faccia.", en: "In the book Elena is alone with a voice without a face.", speakerId: null },
      { text: "E Katia, che non scrive mai, sa già troppo.", en: "And Katia, who never writes, already knows too much.", speakerId: null },
    ],
    questions: [
      {
        type: "direct",
        question: "What does Katia say about people and the book?",
        choices: ["Everyone writes; nobody admits it","Only Bruna writes","Nobody ever writes"],
        correctChoice: 0,
        explanation: "Katia states that everyone writes and nobody admits it."
      },
      {
        type: "direct",
        question: "Has Katia written in the book?",
        choices: ["No, never","Yes, every day","Only once on Tuesday"],
        correctChoice: 0,
        explanation: "Katia says she has never written."
      },
      {
        type: "direct",
        question: "Why does Katia avoid writing?",
        choices: ["Writing would make it true","She cannot read","Bruna forbids her"],
        correctChoice: 0,
        explanation: "She says if she writes it, then it becomes true."
      },
    ]
  },
  {
    number: 6,
    title: "Mirella",
    titleIt: "Mirella",
    summary: "Elena's mother wants her to stay in town. Mirella says Elena's father used to speak on paper.",
    facts: [
          "Mirella wants Elena to stay in Marina di Brenta",
          "Elena uses the café as an escape from home talk",
          "Elena's father used to speak on paper",
          "Elena recognizes the habit of writing instead of speaking"
    ],
    locationIds: ["cucina-mirella","marina-di-brenta","caffe-brenta"],
    characterIds: ["elena-marini","mirella-marini"],
    sentences: [
      { text: "Domenica Elena è a casa di sua madre.", en: "On Sunday Elena is at her mother's house.", speakerId: null },
      { text: "La cucina di Mirella è piccola e calda.", en: "Mirella's kitchen is small and warm.", speakerId: null },
      { text: "C'è odore di caffè e di pane.", en: "There is a smell of coffee and bread.", speakerId: null },
      { text: "Mirella mette due tazzine sul tavolo e lo zucchero vicino.", en: "Mirella puts two cups on the table and the sugar nearby.", speakerId: null },
      { text: "Resti qui, vero?", en: "You're staying here, right?", speakerId: "mirella-marini" },
      { text: "Elena guarda lo zucchero e non la madre.", en: "Elena looks at the sugar and not at her mother.", speakerId: null },
      { text: "Lavoro al Caffè Brenta. Per ora sì.", en: "I work at Caffè Brenta. For now, yes.", speakerId: "elena-marini" },
      { text: "Padova è finita.", en: "Padova is over.", speakerId: "mirella-marini" },
      { text: "Sì. Il lavoro là è finito.", en: "Yes. The job there is finished.", speakerId: "elena-marini" },
      { text: "Mirella annuisce e riempie le tazzine.", en: "Mirella nods and fills the cups.", speakerId: null },
      { text: "Qui hai casa. Hai me. Hai il caffè.", en: "Here you have a home. You have me. You have the café.", speakerId: "mirella-marini" },
      { text: "Elena sorride, ma è stanca di questa pressione dolce.", en: "Elena smiles, but she is tired of this sweet pressure.", speakerId: null },
      { text: "Il caffè mi piace. Il bancone mi piace.", en: "I like the café. I like the counter.", speakerId: "elena-marini" },
      { text: "Al bancone parli tanto.", en: "At the counter you talk a lot.", speakerId: "mirella-marini" },
      { text: "A casa parli poco.", en: "At home you talk little.", speakerId: "mirella-marini" },
      { text: "Elena beve il caffè e sente il silenzio della cucina.", en: "Elena drinks the coffee and feels the kitchen silence.", speakerId: null },
      { text: "Al bancone è più facile.", en: "At the counter it is easier.", speakerId: "elena-marini" },
      { text: "Mirella guarda fuori dalla finestra, verso la nebbia.", en: "Mirella looks out the window, toward the fog.", speakerId: null },
      { text: "Tuo padre parlava così, sulla carta.", en: "Your father spoke like that, on paper.", speakerId: "mirella-marini" },
      { text: "Elena alza gli occhi.", en: "Elena raises her eyes.", speakerId: null },
      { text: "Sulla carta?", en: "On paper?", speakerId: "elena-marini" },
      { text: "Sì. Scriveva biglietti. Scriveva frasi corte.", en: "Yes. He wrote notes. He wrote short sentences.", speakerId: "mirella-marini" },
      { text: "In voce era più chiuso.", en: "In speech he was more closed.", speakerId: "mirella-marini" },
      { text: "Elena resta zitta un momento lungo.", en: "Elena stays quiet for a long moment.", speakerId: null },
      { text: "Pensa al libro vicino allo zucchero al caffè.", en: "She thinks of the book near the sugar at the café.", speakerId: null },
      { text: "Pensa alle sue risposte lunghe e alla paura del silenzio.", en: "She thinks of her long answers and the fear of silence.", speakerId: null },
      { text: "Mamma, io non sono papà.", en: "Mum, I'm not dad.", speakerId: "elena-marini" },
      { text: "Lo so.", en: "I know.", speakerId: "mirella-marini" },
      { text: "Ma a volte ti assomigli.", en: "But sometimes you resemble him.", speakerId: "mirella-marini" },
      { text: "Dopo pranzo Elena dice che deve andare.", en: "After lunch Elena says she has to go.", speakerId: null },
      { text: "Dove?", en: "Where?", speakerId: "mirella-marini" },
      { text: "Al caffè. Devo aiutare Bruna con il bancone.", en: "To the café. I have to help Bruna with the counter.", speakerId: "elena-marini" },
      { text: "È domenica.", en: "It's Sunday.", speakerId: "mirella-marini" },
      { text: "Lo so. Solo un'ora.", en: "I know. Just an hour.", speakerId: "elena-marini" },
      { text: "Mirella non crede del tutto, ma non ferma la figlia.", en: "Mirella does not fully believe her, but she does not stop her daughter.", speakerId: null },
      { text: "Elena pedala verso il Caffè Brenta con il vento in faccia.", en: "Elena bikes toward Caffè Brenta with the wind in her face.", speakerId: null },
      { text: "Il caffè è chiuso. La porta è scura.", en: "The café is closed. The door is dark.", speakerId: null },
      { text: "Lei guarda la serratura e ride di se stessa.", en: "She looks at the lock and laughs at herself.", speakerId: null },
      { text: "Ha usato il caffè come scusa.", en: "She used the café as an excuse.", speakerId: null },
      { text: "Ha paura di restare troppo nella cucina di Mirella.", en: "She is afraid of staying too long in Mirella's kitchen.", speakerId: null },
      { text: "Nella cucina le parole sono vere e pesanti.", en: "In the kitchen the words are true and heavy.", speakerId: null },
      { text: "Nel libro le parole sono vere in un altro modo, più sicuro.", en: "In the book the words are true in another way, safer.", speakerId: null },
      { text: "Elena torna a casa piano, senza dire dove è stata davvero.", en: "Elena goes home slowly, without saying where she really was.", speakerId: null },
      { text: "Di sera scrive un messaggio a Bruna.", en: "In the evening she writes a message to Bruna.", speakerId: null },
      { text: "Domani arrivo presto al bancone.", en: "Tomorrow I'll arrive early at the counter.", speakerId: "elena-marini" },
      { text: "Poi pensa al padre e alla carta.", en: "Then she thinks of her father and of paper.", speakerId: null },
      { text: "Mirella taglia il pane e parla ancora di restare.", en: "Mirella cuts the bread and talks again about staying.", speakerId: null },
      { text: "Marina di Brenta non è Padova, ma è casa.", en: "Marina di Brenta is not Padova, but it is home.", speakerId: "mirella-marini" },
      { text: "Elena sa che è vero e che non basta.", en: "Elena knows it is true and that it is not enough.", speakerId: null },
      { text: "Nel caffè ho un bancone. Qui ho domande.", en: "At the café I have a counter. Here I have questions.", speakerId: "elena-marini" },
      { text: "Le domande vanno bene.", en: "Questions are fine.", speakerId: "mirella-marini" },
      { text: "Se restano in cucina, però, pesano.", en: "If they stay in the kitchen, though, they are heavy.", speakerId: null },
      { text: "Mirella le tocca la mano.", en: "Mirella touches her hand.", speakerId: null },
      { text: "Tuo padre metteva le cose vere nei biglietti.", en: "Your father put true things in notes.", speakerId: "mirella-marini" },
      { text: "A tavola diceva poco.", en: "At the table he said little.", speakerId: "mirella-marini" },
      { text: "Elena beve l'ultimo sorso di caffè.", en: "Elena drinks the last sip of coffee.", speakerId: null },
      { text: "Forse anche io faccio così.", en: "Maybe I do that too.", speakerId: "elena-marini" },
      { text: "Lo so.", en: "I know.", speakerId: "mirella-marini" },
      { text: "Quando Elena torna dalla porta chiusa del caffè, ha freddo alle mani.", en: "When Elena returns from the café's closed door, her hands are cold.", speakerId: null },
      { text: "Ha scappato da una verità per andare verso un'altra.", en: "She ran from one truth toward another.", speakerId: null },
      { text: "E nessuna delle due è detta in voce.", en: "And neither is said out loud.", speakerId: null },
      { text: "E al silenzio che ha ancora paura di dire ad alta voce.", en: "And of the silence she is still afraid to say out loud.", speakerId: null },
      { text: "Mirella vuole che resti.", en: "Mirella wants her to stay.", speakerId: null },
      { text: "Elena resta, ma nasconde la parte vera in un libro di altri.", en: "Elena stays, but she hides the true part in someone else's book.", speakerId: null },
    ],
    questions: [
      {
        type: "direct",
        question: "What does Mirella want?",
        choices: ["Elena to stay in town","Elena to return to Padova","Elena to sell the café"],
        correctChoice: 0,
        explanation: "Mirella asks if Elena is staying and lists reasons to stay."
      },
      {
        type: "direct",
        question: "How did Elena's father speak, according to Mirella?",
        choices: ["On paper","Only at the café","Never at all"],
        correctChoice: 0,
        explanation: "Mirella says he spoke on paper."
      },
      {
        type: "direct",
        question: "Why does Elena leave for the café on Sunday?",
        choices: ["To escape the heavy talk at home","Because Bruna called her in","To meet Pietro"],
        correctChoice: 0,
        explanation: "The café is closed; she used it as an excuse to leave."
      },
    ]
  },
  {
    number: 7,
    title: "Pietro again",
    titleIt: "Pietro di nuovo",
    summary: "Elena tries to talk like her notes and fails. Pietro spills coffee beans; the moment turns into comedy.",
    facts: [
          "Elena tries to be honest like in the book and fails",
          "Pietro spills a bag of coffee beans",
          "They laugh awkwardly together",
          "Spoken conversation stays worse than the notes"
    ],
    locationIds: ["caffe-brenta","bancone-brenta","scaffale-libro","van-pietro","magazzino-caffe"],
    characterIds: ["elena-marini","pietro-baldo","bruna","katia"],
    sentences: [
      { text: "Martedì di nuovo. Elena aspetta il furgone.", en: "Tuesday again. Elena waits for the van.", speakerId: null },
      { text: "Prova frasi vere nella testa, come nel libro.", en: "She tries true sentences in her head, like in the book.", speakerId: null },
      { text: "Vuole essere la nota: vera, semplice, coraggiosa.", en: "She wants to be the note: true, simple, brave.", speakerId: null },
      { text: "Pietro entra con un sacco di chicchi di caffè.", en: "Pietro comes in with a sack of coffee beans.", speakerId: null },
      { text: "Buongiorno.", en: "Good morning.", speakerId: "pietro-baldo" },
      { text: "Buongiorno.", en: "Good morning.", speakerId: "elena-marini" },
      { text: "Elena respira e prova.", en: "Elena breathes and tries.", speakerId: null },
      { text: "Oggi... oggi al bancone c'è molto rumore.", en: "Today... today at the counter there is a lot of noise.", speakerId: "elena-marini" },
      { text: "Sì.", en: "Yes.", speakerId: "pietro-baldo" },
      { text: "Non è quello che voleva dire.", en: "That is not what she wanted to say.", speakerId: null },
      { text: "Voleva dire: oggi ho paura del silenzio.", en: "She wanted to say: today I am afraid of silence.", speakerId: null },
      { text: "Ma la frase resta nel petto e non esce.", en: "But the sentence stays in her chest and does not come out.", speakerId: null },
      { text: "Il tempo?", en: "The weather?", speakerId: "pietro-baldo" },
      { text: "Nebbia. Come sempre al martedì.", en: "Fog. As always on Tuesday.", speakerId: "elena-marini" },
      { text: "Katia sussurra dietro al bancone.", en: "Katia whispers behind the counter.", speakerId: null },
      { text: "Geniale.", en: "Brilliant.", speakerId: "katia" },
      { text: "Elena arrossisce e odia il bancone per un secondo.", en: "Elena blushes and hates the counter for a second.", speakerId: null },
      { text: "Pietro solleva il sacco verso il magazzino.", en: "Pietro lifts the sack toward the storeroom.", speakerId: null },
      { text: "Il sacco si apre vicino allo zucchero.", en: "The sack opens near the sugar.", speakerId: null },
      { text: "I chicchi di caffè cadono sul pavimento con un rumore piccolo e ridicolo.", en: "The coffee beans fall on the floor with a small, ridiculous sound.", speakerId: null },
      { text: "Oh no.", en: "Oh no.", speakerId: "pietro-baldo" },
      { text: "Aspetta. Prendo la scopa.", en: "Wait. I'll get the broom.", speakerId: "elena-marini" },
      { text: "Elena prende la scopa dietro al bancone.", en: "Elena takes the broom from behind the counter.", speakerId: null },
      { text: "Pietro è in ginocchio e raccoglie i chicchi con le mani.", en: "Pietro is on his knees and gathers the beans with his hands.", speakerId: null },
      { text: "Scusa. Sono goffo.", en: "Sorry. I'm clumsy.", speakerId: "pietro-baldo" },
      { text: "Va bene. Succede. Anche il tavolo balla, qui.", en: "It's fine. It happens. Even the table wobbles, here.", speakerId: "elena-marini" },
      { text: "Pietro alza gli occhi un momento e quasi sorride.", en: "Pietro raises his eyes for a moment and almost smiles.", speakerId: null },
      { text: "Bruna arriva dal magazzino e guarda il pavimento.", en: "Bruna arrives from the storeroom and looks at the floor.", speakerId: null },
      { text: "Il caffè sul pavimento è un peccato.", en: "Coffee on the floor is a shame.", speakerId: "bruna" },
      { text: "Ma poi ride e scuote la testa.", en: "But then she laughs and shakes her head.", speakerId: null },
      { text: "Almeno oggi non parlate solo di nebbia.", en: "At least today you're not only talking about fog.", speakerId: "bruna" },
      { text: "Elena e Pietro ridono insieme.", en: "Elena and Pietro laugh together.", speakerId: null },
      { text: "È una risata corta, goffa, vera.", en: "It is a short, clumsy, true laugh.", speakerId: null },
      { text: "È meglio del silenzio morto di martedì scorso.", en: "It is better than last Tuesday's dead silence.", speakerId: null },
      { text: "Quando il pavimento è pulito, Pietro firma il foglio sul bancone.", en: "When the floor is clean, Pietro signs the sheet on the counter.", speakerId: null },
      { text: "Elena vuole dire qualcosa di vero prima che lui esca.", en: "Elena wants to say something true before he leaves.", speakerId: null },
      { text: "Mi piace il martedì.", en: "I like Tuesdays.", speakerId: "elena-marini" },
      { text: "La frase esce storta e troppo piccola.", en: "The sentence comes out wrong and too small.", speakerId: null },
      { text: "Anche a me. Il lavoro.", en: "Me too. The work.", speakerId: "pietro-baldo" },
      { text: "Lui pensa al lavoro. Lei pensava a lui.", en: "He thinks of work. She was thinking of him.", speakerId: null },
      { text: "Pietro guarda lo scaffale del libro un secondo.", en: "Pietro looks at the book shelf for a second.", speakerId: null },
      { text: "Poi prende le chiavi del furgone e saluta.", en: "Then he takes the van keys and says goodbye.", speakerId: null },
      { text: "A martedì.", en: "See you Tuesday.", speakerId: "pietro-baldo" },
      { text: "Elena resta con la scopa in mano.", en: "Elena stays with the broom in her hand.", speakerId: null },
      { text: "Ha fallito di nuovo nella voce.", en: "She has failed again in speech.", speakerId: null },
      { text: "Nel libro avrebbe scritto meglio.", en: "In the book she would have written better.", speakerId: null },
      { text: "Katia le passa vicino e parla piano.", en: "Katia passes near her and speaks quietly.", speakerId: null },
      { text: "I chicchi erano carini.", en: "The beans were cute.", speakerId: "katia" },
      { text: "Zitta.", en: "Shut up.", speakerId: "elena-marini" },
      { text: "Ma anche Elena sorride, nonostante tutto.", en: "But Elena smiles too, despite everything.", speakerId: null },
      { text: "Nel pomeriggio apre il libro vicino allo zucchero.", en: "In the afternoon she opens the book near the sugar.", speakerId: null },
      { text: "Non scrive la scena dei chicchi.", en: "She does not write the bean scene.", speakerId: null },
      { text: "Scrive solo una riga onesta e brutta.", en: "She only writes one honest, ugly line.", speakerId: null },
      { text: "Prima che Pietro arrivi, Elena ripete una frase al bancone vuoto.", en: "Before Pietro arrives, Elena repeats a sentence at the empty counter.", speakerId: null },
      { text: "Oggi ho paura del silenzio.", en: "Today I am afraid of silence.", speakerId: "elena-marini" },
      { text: "La voce le sembra strana fuori dal libro.", en: "Her voice sounds strange outside the book.", speakerId: null },
      { text: "Quando lui è lì, la frase sparisce.", en: "When he is there, the sentence disappears.", speakerId: null },
      { text: "Restano solo nebbia, chicchi e una scopa.", en: "Only fog, beans, and a broom remain.", speakerId: null },
      { text: "Bruna porta un altro sacco di zucchero sul bancone.", en: "Bruna brings another sack of sugar onto the counter.", speakerId: null },
      { text: "Fate attenzione, voi due.", en: "Be careful, you two.", speakerId: "bruna" },
      { text: "Sì.", en: "Yes.", speakerId: "elena-marini" },
      { text: "Pietro raccoglie ancora un chicco sotto lo scaffale del libro.", en: "Pietro picks up one more bean under the book shelf.", speakerId: null },
      { text: "Il libro non si è sporcato. Elena lo controlla.", en: "The book did not get dirty. Elena checks it.", speakerId: null },
      { text: "Per un secondo pensa di dirgli: guardi sempre lì.", en: "For a second she thinks of telling him: you always look there.", speakerId: null },
      { text: "Non lo dice.", en: "She does not say it.", speakerId: null },
      { text: "Dice solo grazie quando lui le passa la scopa.", en: "She only says thank you when he passes her the broom.", speakerId: null },
      { text: "Grazie.", en: "Thank you.", speakerId: "elena-marini" },
      { text: "Prego.", en: "You're welcome.", speakerId: "pietro-baldo" },
      { text: "Così finisce il tentativo: con due parole piccole e tanti chicchi.", en: "That is how the attempt ends: with two small words and many beans.", speakerId: null },
      { text: "Oggi ho parlato male.", en: "Today I spoke badly.", speakerId: null },
      { text: "Poi chiude il libro e torna al bancone.", en: "Then she closes the book and goes back to the counter.", speakerId: null },
      { text: "Il martedì resta goffo. Ma almeno ha riso.", en: "Tuesday stays clumsy. But at least she laughed.", speakerId: null },
    ],
    questions: [
      {
        type: "direct",
        question: "What does Elena try to do with Pietro?",
        choices: ["Speak as honestly as in the notes","Sell him the book","Invite him to Padova"],
        correctChoice: 0,
        explanation: "She wants to be like the note but fails."
      },
      {
        type: "direct",
        question: "What comic accident happens?",
        choices: ["Pietro spills coffee beans","Elena burns the sugar","Bruna locks the van"],
        correctChoice: 0,
        explanation: "The sack opens and beans fall on the floor."
      },
      {
        type: "direct",
        question: "What does Elena write later?",
        choices: ["Oggi ho parlato male","Sei Pietro","Martedì è finito"],
        correctChoice: 0,
        explanation: "She admits in the book that she spoke badly."
      },
    ]
  },
  {
    number: 8,
    title: "Sergio",
    titleIt: "Sergio",
    summary: "The stranger writes about a brother who cannot sleep. Elena wrongly assumes a breakup story.",
    facts: [
          "A note mentions a brother who does not sleep",
          "Elena assumes the writer is talking about a breakup",
          "Bruna mentions Pietro has family problems",
          "Elena's soft advice misses the real situation"
    ],
    locationIds: ["caffe-brenta","bancone-brenta","scaffale-libro"],
    characterIds: ["elena-marini","bruna","katia"],
    sentences: [
      { text: "Venerdì Elena apre il libro prima del turno.", en: "On Friday Elena opens the book before the shift.", speakerId: null },
      { text: "Il caffè è ancora quieto. Lo zucchero è già sul bancone.", en: "The café is still quiet. The sugar is already on the counter.", speakerId: null },
      { text: "C'è una riga nuova, scritta di fretta.", en: "There is a new line, written in a hurry.", speakerId: null },
      { text: "Mio fratello non dorme.", en: "My brother does not sleep.", speakerId: null },
      { text: "La casa è piena di paura quieta.", en: "The house is full of quiet fear.", speakerId: null },
      { text: "Io resto sveglio con lui e non so cosa dire.", en: "I stay awake with him and do not know what to say.", speakerId: null },
      { text: "Elena legge e immagina una storia sbagliata.", en: "Elena reads and imagines the wrong story.", speakerId: null },
      { text: "Pensa a una relazione finita.", en: "She thinks of a finished relationship.", speakerId: null },
      { text: "Pensa a un letto vuoto, a litigi, a un addio.", en: "She thinks of an empty bed, arguments, a goodbye.", speakerId: null },
      { text: "Nella sua testa il fratello è quasi un ex, non un fratello.", en: "In her head the brother is almost an ex, not a brother.", speakerId: null },
      { text: "Scrive una risposta dolce e fuori posto.", en: "She writes a soft, out-of-place answer.", speakerId: null },
      { text: "A volte le persone se ne vanno.", en: "Sometimes people leave.", speakerId: null },
      { text: "Non è colpa tua se il silenzio resta.", en: "It is not your fault if the silence remains.", speakerId: null },
      { text: "Il tempo aiuta, anche se adesso non sembra.", en: "Time helps, even if it does not seem so now.", speakerId: null },
      { text: "Chiude il libro contenta.", en: "She closes the book satisfied.", speakerId: null },
      { text: "Crede di aver capito e di aver aiutato.", en: "She believes she has understood and helped.", speakerId: null },
      { text: "Durante il turno Bruna parla di una consegna in ritardo.", en: "During the shift Bruna talks about a late delivery.", speakerId: null },
      { text: "Pietro questa settimana è stato in ritardo due volte.", en: "Pietro was late twice this week.", speakerId: "bruna" },
      { text: "Ha problemi in famiglia, credo.", en: "He has family problems, I think.", speakerId: "bruna" },
      { text: "Elena alza la testa dal bancone.", en: "Elena raises her head from the counter.", speakerId: null },
      { text: "Che problemi?", en: "What problems?", speakerId: "elena-marini" },
      { text: "Non so. Non chiedo tutto. Non è il mio stile.", en: "I don't know. I don't ask everything. It's not my style.", speakerId: "bruna" },
      { text: "Katia lava i bicchieri e parla senza guardare.", en: "Katia washes the glasses and talks without looking.", speakerId: null },
      { text: "Al bancone si sente tutto e niente.", en: "At the counter you hear everything and nothing.", speakerId: "katia" },
      { text: "Elena pensa al fratello che non dorme.", en: "Elena thinks of the brother who does not sleep.", speakerId: null },
      { text: "Nella sua testa resta ancora una rottura d'amore.", en: "In her head it is still a breakup.", speakerId: null },
      { text: "Non collega Pietro al libro.", en: "She does not connect Pietro to the book.", speakerId: null },
      { text: "Non sente ancora il nome Sergio.", en: "She does not yet hear the name Sergio.", speakerId: null },
      { text: "Nel pomeriggio rilegge la sua risposta.", en: "In the afternoon she rereads her answer.", speakerId: null },
      { text: "Le sembra buona. Le sembra anche un po' fuori posto.", en: "It seems good. It also seems a bit out of place.", speakerId: null },
      { text: "Ma lei non lo sa ancora.", en: "But she does not know that yet.", speakerId: null },
      { text: "Un cliente chiede lo zucchero per il tavolo vicino alla finestra.", en: "A customer asks for sugar for the table near the window.", speakerId: null },
      { text: "Elena lo porta al tavolo.", en: "Elena brings it to the table.", speakerId: null },
      { text: "Il tavolo balla ancora un poco.", en: "The table still wobbles a little.", speakerId: null },
      { text: "Elena sorride alla memoria della prima riga del libro.", en: "Elena smiles at the memory of the book's first line.", speakerId: null },
      { text: "Alla sera Katia spegne le luci del bancone.", en: "In the evening Katia turns off the counter lights.", speakerId: null },
      { text: "Elena tocca la copertina del libro vicino allo zucchero.", en: "Elena touches the book's cover near the sugar.", speakerId: null },
      { text: "Spera che la persona legga e stia meglio.", en: "She hopes the person reads and feels better.", speakerId: null },
      { text: "Non sa che Sergio esiste davvero.", en: "She does not know that Sergio really exists.", speakerId: null },
      { text: "Non sa che il fratello è in recupero dopo un incidente.", en: "She does not know the brother is in recovery after an accident.", speakerId: null },
      { text: "Sa solo una frase sulla carta e una ipotesi sbagliata.", en: "She only knows one sentence on paper and a wrong guess.", speakerId: null },
      { text: "Chiude il caffè con Bruna e Katia.", en: "She closes the café with Bruna and Katia.", speakerId: null },
      { text: "Fuori c'è nebbia. Dentro resta il libro.", en: "Outside there is fog. Inside the book remains.", speakerId: null },
      { text: "Elena cammina verso casa e ripete: mio fratello non dorme.", en: "Elena walks home and repeats: my brother does not sleep.", speakerId: null },
      { text: "Elena rilegge la riga del fratello mentre prepara il primo caffè.", en: "Elena rereads the brother line while making the first coffee.", speakerId: null },
      { text: "Immagina ancora una donna che se n'è andata.", en: "She still imagines a woman who left.", speakerId: null },
      { text: "Immagina porte chiuse e messaggi non letti.", en: "She imagines closed doors and unread messages.", speakerId: null },
      { text: "Per questo parla di persone che se ne vanno.", en: "That is why she writes about people who leave.", speakerId: null },
      { text: "Katia le chiede se vuole cambiare il turno di martedì.", en: "Katia asks if she wants to swap the Tuesday shift.", speakerId: null },
      { text: "No. Il martedì mi va bene.", en: "No. Tuesday is fine for me.", speakerId: "elena-marini" },
      { text: "Katia alza le spalle e porta lo zucchero a un tavolo.", en: "Katia shrugs and takes sugar to a table.", speakerId: null },
      { text: "Bruna torna sull'argomento di Pietro solo una volta.", en: "Bruna returns to the subject of Pietro only once.", speakerId: null },
      { text: "Se arriva in ritardo, non fare storie. Ha già abbastanza.", en: "If he arrives late, do not make a fuss. He already has enough.", speakerId: "bruna" },
      { text: "Va bene.", en: "Okay.", speakerId: "elena-marini" },
      { text: "Elena pensa al libro e alla sua risposta dolce.", en: "Elena thinks of the book and her soft answer.", speakerId: null },
      { text: "Spera di non aver fatto danno.", en: "She hopes she has not done harm.", speakerId: null },
      { text: "Non sa che ha scritto a una storia diversa.", en: "She does not know she wrote to a different story.", speakerId: null },
      { text: "Una storia di recupero, non di addio.", en: "A story of recovery, not of goodbye.", speakerId: null },
      { text: "Il bancone resta pieno. Il libro resta chiuso.", en: "The counter stays full. The book stays closed.", speakerId: null },
      { text: "E l'ipotesi sbagliata resta comoda fino al prossimo capitolo.", en: "And the wrong guess stays comfortable until the next chapter.", speakerId: null },
      { text: "Ancora pensa a un amore finito.", en: "She still thinks of a finished love.", speakerId: null },
      { text: "La verità è più semplice e più dura.", en: "The truth is simpler and harder.", speakerId: null },
      { text: "Ma quella arriva dopo.", en: "But that comes later.", speakerId: null },
    ],
    questions: [
      {
        type: "direct",
        question: "What does the new note say?",
        choices: ["A brother does not sleep","Pietro loves Elena","Bruna will sell the café"],
        correctChoice: 0,
        explanation: "The writer mentions a brother who cannot sleep."
      },
      {
        type: "direct",
        question: "What does Elena assume?",
        choices: ["A breakup story","A job promotion","A trip to Padova"],
        correctChoice: 0,
        explanation: "She imagines a finished relationship."
      },
      {
        type: "direct",
        question: "What does Bruna mention about Pietro?",
        choices: ["Family problems","He wrote in the book","He hates Tuesdays"],
        correctChoice: 0,
        explanation: "Bruna thinks Pietro has family problems."
      },
    ]
  }
];
