/** Il villaggio che non esiste — chapters 9–16 (A2+ fantasy). */
'use strict';

function s(text, en, speakerId = null) {
  return { text, en, speakerId };
}

function q(question, choices, correctChoice, explanation, type = 'direct') {
  return { type, question, choices, correctChoice, explanation };
}

module.exports = [
  {
    number: 9,
    title: 'Yesterday',
    titleIt: 'Ieri',
    summary:
      'Giada photographs the square in careful detail because she does not trust memory. She records signs, benches, the fountain, and shop names before anything can change.',
    facts: [
      'Giada photographs the square systematically',
      'She does not trust her own memory',
      'She records shop names, benches, and the fountain',
      'Elsa watches her take pictures without stopping her',
    ],
    locationIds: ['piazza-collevento', 'locanda-elsa'],
    characterIds: ['giada-rinaldi', 'elsa', 'neri'],
    sentences: [
    s('La mattina dopo il registro Giada esce con il telefono in mano.', 'The morning after the register Giada goes out with the phone in her hand.'),
    s('Non vuole parlare con nessuno.', 'She does not want to talk to anyone.'),
    s('Vuole solo ricordare bene ciò che vede.', 'She only wants to remember well what she sees.'),
    s('In piazza c\'è poco vento e odore di legno bagnato.', 'In the square there is little wind and a smell of wet wood.'),
    s('La fontana fa un rumore piccolo, sempre uguale.', 'The fountain makes a small sound, always the same.'),
    s('Giada alza il telefono e fotografa la fontana da sinistra.', 'Giada raises the phone and photographs the fountain from the left.'),
    s('Poi da destra.', 'Then from the right.'),
    s('Poi da davanti, con le tre panchine nello stesso fotogramma.', 'Then from the front, with the three benches in the same frame.'),
    s('Non ride.', 'She does not laugh.'),
    s('Lavora come se facesse un compito di scuola.', 'She works as if she were doing a school assignment.'),
    s('Fotografa il cartello del negozio di generi alimentari.', 'She photographs the grocery shop sign.'),
    s('Sul cartello c\'è scritto: ALIMENTARI ROSSI.', 'On the sign it says: ALIMENTARI ROSSI.'),
    s('Fotografa anche la porta, perché la maniglia è di ferro scuro.', 'She also photographs the door, because the handle is dark iron.'),
    s('Fotografa il banco del pane, chiuso, con una sedia fuori.', 'She photographs the bread counter, closed, with a chair outside.'),
    s('Fotografa il nome sulla sedia: TULLIO, scritto a matita.', 'She photographs the name on the chair: TULLIO, written in pencil.'),
    s('Elsa esce sulla soglia della locanda e la guarda.', 'Elsa comes out onto the inn threshold and watches her.'),
    s('Cosa fai, Anna?', 'What are you doing, Anna?', 'elsa'),
    s('Giada.', 'Giada.', 'giada-rinaldi'),
    s('Mi chiamo Giada.', 'My name is Giada.', 'giada-rinaldi'),
    s('Elsa fa un gesto piccolo con la mano, come per scusarsi senza scusarsi.', 'Elsa makes a small gesture with her hand, as if to apologize without apologizing.'),
    s('Cosa fai, Giada?', 'What are you doing, Giada?', 'elsa'),
    s('Fotografo.', 'I am taking photos.', 'giada-rinaldi'),
    s('Perché?', 'Why?', 'elsa'),
    s('Perché non mi fido della memoria.', 'Because I do not trust memory.', 'giada-rinaldi'),
    s('La mia, e anche quella degli altri.', 'Mine, and other people\'s too.', 'giada-rinaldi'),
    s('Elsa non risponde subito.', 'Elsa does not answer at once.'),
    s('Guarda la piazza come se la conoscesse da troppo tempo.', 'She looks at the square as if she had known it for too long.'),
    s('Ieri è già lontano.', 'Yesterday is already far away.', 'elsa'),
    s('Giada scatta ancora.', 'Giada shoots again.'),
    s('Fotografa il campanile corto della cappella.', 'She photographs the short bell tower of the chapel.'),
    s('Fotografa il muro dove qualcuno ha messo un vaso di gerani.', 'She photographs the wall where someone has put a pot of geraniums.'),
    s('Fotografa il numero sulla casa accanto: diciassette.', 'She photographs the number on the house next door: seventeen.'),
    s('Fotografa anche le ombre, perché le ombre dicono l\'ora.', 'She also photographs the shadows, because shadows tell the time.'),
    s('Neri arriva dalla strada della diga con le mani in tasca.', 'Neri arrives from the dam road with his hands in his pockets.'),
    s('Fai il turista?', 'Are you playing tourist?', 'neri'),
    s('No.', 'No.', 'giada-rinaldi'),
    s('Faccio l\'archivio.', 'I am making an archive.', 'giada-rinaldi'),
    s('Neri guarda lo schermo del telefono.', 'Neri looks at the phone screen.'),
    s('Qui le cose si spostano.', 'Here things move.', 'neri'),
    s('Lo so.', 'I know.', 'giada-rinaldi'),
    s('Per questo fotografo oggi.', 'That is why I photograph today.', 'giada-rinaldi'),
    s('Così domani posso confrontare.', 'So tomorrow I can compare.', 'giada-rinaldi'),
    s('Neri alza le spalle.', 'Neri shrugs.'),
    s('Confronta pure.', 'Go ahead and compare.', 'neri'),
    s('Poi dimmi se ti aiuta a dormire.', 'Then tell me if it helps you sleep.', 'neri'),
    s('Giada non sorride.', 'Giada does not smile.'),
    s('Continua a camminare lungo i bordi della piazza.', 'She keeps walking along the edges of the square.'),
    s('Fotografa la panchina sotto l\'albero.', 'She photographs the bench under the tree.'),
    s('Fotografa la panchina vicino alla fontana.', 'She photographs the bench near the fountain.'),
    s('Fotografa la terza panchina, quella stortata.', 'She photographs the third bench, the crooked one.'),
    s('Annota mentalmente: tre panchine, due verdi, una marrone.', 'She notes mentally: three benches, two green, one brown.'),
    s('Annota anche: cartello ROSSI, vaso a sinistra, sedia di Tullio fuori.', 'She also notes: ROSSI sign, pot on the left, Tullio\'s chair outside.'),
    s('Il sole sale e le ombre si accorciano.', 'The sun rises and the shadows shorten.'),
    s('Giada sente fame, ma non rientra subito.', 'Giada feels hungry, but she does not go back in at once.'),
    s('Vuole finire il giro prima che qualcuno le dica di lasciare stare.', 'She wants to finish the circuit before someone tells her to leave it alone.'),
    s('Elsa resta sulla soglia ancora un minuto.', 'Elsa stays on the threshold another minute.'),
    s('Poi rientra senza chiudere del tutto la porta.', 'Then she goes back in without closing the door completely.'),
    s('Giada fotografa anche quella porta socchiusa.', 'Giada also photographs that half-open door.'),
    s('È un dettaglio piccolo.', 'It is a small detail.'),
    s('Però i dettagli piccoli, ieri, erano già mentiti nel registro.', 'But small details, yesterday, were already lied about in the register.'),
    s('Alla fine ha quarantadue foto.', 'In the end she has forty-two photos.'),
    s('Le rivede una per una seduta sul bordo della fontana.', 'She reviews them one by one sitting on the edge of the fountain.'),
    s('Nessuna è bella.', 'None of them is beautiful.'),
    s('Sono utili.', 'They are useful.'),
    s('Questo le basta.', 'That is enough for her.'),
    s('Quando rientra in locanda, Elsa ha preparato pane e caffè.', 'When she goes back into the inn, Elsa has prepared bread and coffee.'),
    s('Mangia in silenzio.', 'She eats in silence.'),
    s('Il telefono resta sul tavolo, schermo spento, come una prova.', 'The phone stays on the table, screen off, like evidence.'),
    s('Conta i passi da un angolo all\'altro.', 'She counts the steps from one corner to the other.'),
    s('Conta anche le finestre chiuse al primo piano.', 'She also counts the closed windows on the first floor.'),
    s('Vuole una prova che ieri è esistito così, e non solo nella testa.', 'She wants proof that yesterday existed like this, and not only in her head.'),
    s('A Bologna, dopo litigi, fotografava le stanze per ricordare chi aveva spostato cosa.', 'In Bologna, after arguments, she photographed rooms to remember who had moved what.'),
    s('Qui fa lo stesso, ma il litigio è con un paese intero.', 'Here she does the same, but the argument is with a whole village.'),
    s('Il telefono scatta un suono corto a ogni foto.', 'The phone makes a short sound with every shot.'),
    s('Quel suono diventa un ritmo, quasi una preghiera laica.', 'That sound becomes a rhythm, almost a secular prayer.'),
    s('Una donna anziana passa e scuote la testa, senza fermarsi.', 'An old woman passes and shakes her head, without stopping.'),
    s('Giada non chiede perché.', 'Giada does not ask why.'),
    s('Sa già che le domande, a Collevento, costano risposte lente.', 'She already knows that questions, in Collevento, cost slow answers.'),
    s('Fotografa anche il cielo sopra il campanile, inutile e necessario.', 'She also photographs the sky above the bell tower, useless and necessary.'),
    s('Se domani il cielo è uguale, almeno sa che qualcosa resta.', 'If tomorrow the sky is the same, at least she knows something remains.'),
    s('Se cambia tutto il resto, avrà i numeri e i nomi di oggi.', 'If everything else changes, she will have today\'s numbers and names.'),
    s('Questa idea la tiene in piedi meglio del caffè.', 'This idea keeps her upright better than coffee.'),
    s('Neri, prima di andarsene, le dice solo: non mostrarle a tutti.', 'Neri, before leaving, only tells her: do not show them to everyone.', 'neri'),
    s('Alcune persone odiano le prove.', 'Some people hate evidence.', 'neri'),
    s('Giada mette il telefono in tasca come un segreto utile.', 'Giada puts the phone in her pocket like a useful secret.'),
    s('Torna a guardare la fontana un\'ultima volta.', 'She looks at the fountain one last time.'),
    s('L\'acqua di ieri e l\'acqua di oggi sembrano uguali.', 'Yesterday\'s water and today\'s water look the same.'),
    s('Le panchine, però, non le crede più.', 'The benches, though, she no longer trusts.'),
    s('Fuori, la piazza sembra ferma.', 'Outside, the square looks still.'),
    s('Giada pensa: ieri finisce solo quando smetto di guardarlo.', 'Giada thinks: yesterday ends only when I stop looking at it.'),
    s('E lei non ha ancora smesso.', 'And she has not stopped yet.'),
    ],
    questions: [
    q('Why does Giada photograph the square?', ['She does not trust memory', 'She wants to sell postcards', 'Elsa asks her to'], 0, 'She says she does not trust memory.'),
    q('What name is on the grocery sign?', ['ROSSI', 'NERI', 'ELSA'], 0, 'The sign says ALIMENTARI ROSSI.'),
    q('How many photos does she take?', ['Forty-two', 'Ten', 'Three'], 0, 'In the end she has forty-two photos.'),
    ],
  },

  {
    number: 10,
    title: 'Morning',
    titleIt: 'Il mattino',
    summary:
      'In the morning a shop sign has a different name and a bench has moved. Giada almost believes in magic, then catches Elsa with a ladder staging the square for an inspection.',
    facts: [
      'A shop sign has a different name in the morning',
      'A bench has been moved',
      'Giada catches Elsa with a ladder',
      'The morning changes are staging, not magic',
    ],
    locationIds: ['piazza-collevento', 'locanda-elsa'],
    characterIds: ['giada-rinaldi', 'elsa'],
    sentences: [
    s('Giada si sveglia presto, prima del caffè.', 'Giada wakes early, before coffee.'),
    s('Apre il telefono e controlla le foto di ieri.', 'She opens the phone and checks yesterday\'s photos.'),
    s('Poi esce in pigiama e scarpe, senza giacca.', 'Then she goes out in pajamas and shoes, without a jacket.'),
    s('La piazza sembra la stessa, e non lo è.', 'The square looks the same, and it is not.'),
    s('Il cartello del negozio non dice più ROSSI.', 'The shop sign no longer says ROSSI.'),
    s('Ora dice ALIMENTARI BIANCHI.', 'Now it says ALIMENTARI BIANCHI.'),
    s('Giada sente un colpo nello stomaco.', 'Giada feels a hit in her stomach.'),
    s('Controlla la foto: ieri era ROSSI, chiaro.', 'She checks the photo: yesterday it was ROSSI, clear.'),
    s('Oggi è Bianchi.', 'Today it is Bianchi.'),
    s('La panchina stortata non è più vicino alla fontana.', 'The crooked bench is no longer near the fountain.'),
    s('È sotto l\'albero, dove ieri c\'era una panchina verde.', 'It is under the tree, where yesterday there was a green bench.'),
    s('Il vaso di gerani è passato a destra.', 'The geranium pot has moved to the right.'),
    s('Per un secondo Giada pensa a una cosa impossibile.', 'For a second Giada thinks of something impossible.'),
    s('Pensa che il paese cambi da solo mentre dormono.', 'She thinks the village changes by itself while they sleep.'),
    s('Poi sente un rumore di legno contro muro.', 'Then she hears a sound of wood against wall.'),
    s('Dietro il negozio c\'è una scala.', 'Behind the shop there is a ladder.'),
    s('In cima alla scala c\'è Elsa, con un cartello nuovo sotto il braccio.', 'At the top of the ladder is Elsa, with a new sign under her arm.'),
    s('Elsa non ha visto Giada.', 'Elsa has not seen Giada.'),
    s('Sta togliendo viti con le dita ferme.', 'She is removing screws with steady fingers.'),
    s('Giada resta ferma un momento, poi parla.', 'Giada stays still a moment, then speaks.'),
    s('Quindi non è magia.', 'So it is not magic.', 'giada-rinaldi'),
    s('Elsa sobbalza e quasi cade.', 'Elsa jumps and almost falls.'),
    s('Scende di due pioli e guarda Giada come una ladra presa.', 'She comes down two rungs and looks at Giada like a caught thief.'),
    s('Non dovevi alzarti così presto.', 'You were not supposed to get up so early.', 'elsa'),
    s('Tu cambi i nomi.', 'You change the names.', 'giada-rinaldi'),
    s('Tu sposti le panchine.', 'You move the benches.', 'giada-rinaldi'),
    s('Elsa scende fino a terra e appoggia il cartello.', 'Elsa comes down to the ground and sets the sign down.'),
    s('Il cartello nuovo ha ancora odore di vernice.', 'The new sign still smells of paint.'),
    s('Non è un gioco.', 'It is not a game.', 'elsa'),
    s('È lavoro.', 'It is work.', 'elsa'),
    s('Lavoro per chi?', 'Work for whom?', 'giada-rinaldi'),
    s('Per l\'ispezione.', 'For the inspection.', 'elsa'),
    s('Giada ride senza gioia.', 'Giada laughs without joy.'),
    s('Quale ispezione?', 'Which inspection?', 'giada-rinaldi'),
    s('Quella di sempre.', 'The usual one.', 'elsa'),
    s('Quella che deve arrivare.', 'The one that is supposed to arrive.', 'elsa'),
    s('Elsa indica la piazza con un gesto stanco.', 'Elsa points at the square with a tired gesture.'),
    s('Se viene qualcuno dalla diga, deve trovare un paese in ordine.', 'If someone comes from the dam, they must find a tidy village.', 'elsa'),
    s('Nomi giusti.', 'Right names.', 'elsa'),
    s('Banchi puliti.', 'Clean counters.', 'elsa'),
    s('Niente che sembri abbandonato.', 'Nothing that looks abandoned.', 'elsa'),
    s('Giada guarda il cartello ROSSI a terra, vecchio e ancora buono.', 'Giada looks at the ROSSI sign on the ground, old and still good.'),
    s('E ieri era Rossi.', 'And yesterday it was Rossi.', 'giada-rinaldi'),
    s('Ieri pensavamo a un altro elenco.', 'Yesterday we were thinking of another list.', 'elsa'),
    s('A volte cambiamo secondo le carte che abbiamo.', 'Sometimes we change according to the papers we have.', 'elsa'),
    s('Non secondo la verità.', 'Not according to the truth.', 'giada-rinaldi'),
    s('Elsa non nega.', 'Elsa does not deny it.'),
    s('La verità, qui, è una cosa privata.', 'Truth, here, is a private thing.', 'elsa'),
    s('Fuori serve un paese che sembra possibile.', 'Outside you need a village that looks possible.', 'elsa'),
    s('Giada sente freddo alle braccia.', 'Giada feels cold on her arms.'),
    s('Non è un fantasma che sposta le cose.', 'It is not a ghost that moves things.'),
    s('Sono persone con scale e viti.', 'They are people with ladders and screws.'),
    s('Questo dovrebbe calmarla.', 'This should calm her.'),
    s('Invece la fa arrabbiare di più.', 'Instead it makes her angrier.'),
    s('Mi avete fatto pensare a un incubo.', 'You made me think of a nightmare.', 'giada-rinaldi'),
    s('Era solo scenografia.', 'It was only staging.', 'giada-rinaldi'),
    s('Elsa piega il cartello vecchio e lo mette sotto il braccio.', 'Elsa folds the old sign and puts it under her arm.'),
    s('Scenografia è una parola grossa.', 'Staging is a big word.', 'elsa'),
    s('Noi chiamiamo questo sopravvivenza.', 'We call this survival.', 'elsa'),
    s('Giada guarda la panchina spostata.', 'Giada looks at the moved bench.'),
    s('Posso aiutare a rimetterla?', 'Can I help put it back?', 'giada-rinaldi'),
    s('Elsa scuote la testa.', 'Elsa shakes her head.'),
    s('No.', 'No.', 'elsa'),
    s('Tu non sei del turno di mattina.', 'You are not on the morning shift.', 'elsa'),
    s('La frase è banale e dura.', 'The sentence is ordinary and hard.'),
    s('Giada capisce: anche lei è un oggetto fuori posto nella messa in scena.', 'Giada understands: she too is an object out of place in the staging.'),
    s('Rientra a vestirsi.', 'She goes back in to get dressed.'),
    s('Prima di chiudere la porta, fotografa il cartello Bianchi.', 'Before closing the door, she photographs the Bianchi sign.'),
    s('Poi fotografa Elsa che riprende la scala.', 'Then she photographs Elsa picking up the ladder again.'),
    s('Elsa non le chiede di cancellare le foto.', 'Elsa does not ask her to delete the photos.'),
    s('Forse perché sa che non basterebbe.', 'Perhaps because she knows it would not be enough.'),
    s('Giada confronta foto e realtà tre volte, come un compito di matematica.', 'Giada compares photo and reality three times, like a math assignment.'),
    s('Il numero diciassette sulla casa è ancora lì.', 'The number seventeen on the house is still there.'),
    s('Anche la fontana è nello stesso posto.', 'The fountain is also in the same place.'),
    s('Cambiano le cose che si possono svitare.', 'The things that can be unscrewed change.'),
    s('Questa osservazione le sembra più crudele di un incubo.', 'This observation seems crueler to her than a nightmare.'),
    s('Un incubo almeno non ha bisogno di scale.', 'A nightmare at least does not need ladders.'),
    s('Elsa, dopo la scoperta, parla meno e lavora di più.', 'Elsa, after being found out, speaks less and works more.'),
    s('Sistema la panchina con gesti precisi, da persona abituata.', 'She sets the bench with precise gestures, like someone used to it.'),
    s('Giada chiede se anche Tullio aiuta.', 'Giada asks if Tullio also helps.'),
    s('A volte sì.', 'Sometimes yes.', 'elsa'),
    s('A volte no.', 'Sometimes no.', 'elsa'),
    s('Dipende dalla schiena e dal giorno.', 'It depends on the back and the day.', 'elsa'),
    s('Giada pensa agli anni di mattine così.', 'Giada thinks of years of mornings like this.'),
    s('Anni di cartelli nuovi e nomi vecchi mescolati.', 'Years of new signs and old names mixed together.'),
    s('Capisce perché ieri Elsa ha detto che ieri è già lontano.', 'She understands why yesterday Elsa said yesterday is already far away.'),
    s('Qui ieri si cancella con un cacciavite.', 'Here yesterday is erased with a screwdriver.'),
    s('Prima di rientrare, Giada tocca il cartello Bianchi con un dito.', 'Before going back in, Giada touches the Bianchi sign with a finger.'),
    s('La vernice è quasi asciutta.', 'The paint is almost dry.'),
    s('Quasi: un dettaglio che denuncia il lavoro recente.', 'Almost: a detail that gives away recent work.'),
    s('Nella testa ripete: non magia, messa in scena.', 'In her head she repeats: not magic, staging.'),
    s('La ripetizione non toglie la rabbia, ma le dà una forma.', 'The repetition does not remove the anger, but gives it a shape.'),
    s('In cucina Giada beve acqua, non caffè.', 'In the kitchen Giada drinks water, not coffee.'),
    s('Il mattino ha tolto il mistero e ha lasciato la bugia.', 'Morning has removed the mystery and left the lie.'),
    s('Le bugie, almeno, si possono fotografare.', 'Lies, at least, can be photographed.'),
    ],
    questions: [
    q('What does the shop sign say in the morning?', ['ALIMENTARI BIANCHI', 'ALIMENTARI ROSSI', 'LOCANDA ELSA'], 0, 'The sign has changed to ALIMENTARI BIANCHI.'),
    q('Who is on the ladder?', ['Elsa', 'Neri', 'Tullio'], 0, 'Giada catches Elsa with a ladder.'),
    q('Why do they change the square?', ['For an inspection', 'For a festival', 'For tourists'], 0, 'Elsa says it is work for the inspection.'),
    ],
  },

  {
    number: 11,
    title: 'The inspection',
    titleIt: 'L\'ispezione',
    summary:
      'Tullio explains that the autumn inspection has been promised for thirty years and never comes. The village keeps preparing anyway.',
    facts: [
      'The inspection is supposed to come in autumn',
      'It has never come',
      'They have waited about thirty years',
      'People still stage the village for it',
    ],
    locationIds: ['piazza-collevento', 'strada-diga', 'locanda-elsa'],
    characterIds: ['giada-rinaldi', 'tullio', 'elsa'],
    sentences: [
    s('Verso metà mattina Tullio siede sulla sedia fuori dal banco del pane.', 'Toward mid-morning Tullio sits on the chair outside the bread counter.'),
    s('Ha un thermos e un giornale vecchio piegato in quattro.', 'He has a thermos and an old newspaper folded in four.'),
    s('Giada si ferma davanti a lui con le foto ancora in testa.', 'Giada stops in front of him with the photos still in her head.'),
    s('Elsa cambia i cartelli per un\'ispezione.', 'Elsa changes the signs for an inspection.', 'giada-rinaldi'),
    s('Tullio non sembra sorpreso.', 'Tullio does not look surprised.'),
    s('Sì.', 'Yes.', 'tullio'),
    s('Lo fa ogni settimana, in certi periodi.', 'She does it every week, in certain periods.', 'tullio'),
    s('Quando arriva questa ispezione?', 'When does this inspection arrive?', 'giada-rinaldi'),
    s('Tullio svita il thermos e versa un po\' di caffè nella coppa.', 'Tullio unscrews the thermos and pours a little coffee into the cup.'),
    s('In autunno.', 'In autumn.', 'tullio'),
    s('Dicevano in autunno.', 'They used to say in autumn.', 'tullio'),
    s('Giada aspetta il resto.', 'Giada waits for the rest.'),
    s('Tullio beve e guarda la strada della diga.', 'Tullio drinks and looks at the dam road.'),
    s('Non sono mai venuti.', 'They have never come.', 'tullio'),
    s('Mai?', 'Never?', 'giada-rinaldi'),
    s('Mai in tempo.', 'Never on time.', 'tullio'),
    s('Mai come persone che controllano case e nomi.', 'Never as people who check houses and names.', 'tullio'),
    s('A volte passa un tecnico.', 'Sometimes a technician passes.', 'tullio'),
    s('Guarda l\'acqua, non noi.', 'He looks at the water, not at us.', 'tullio'),
    s('Giada si siede sul bordo della fontana.', 'Giada sits on the edge of the fountain.'),
    s('Da quanto tempo aspettate?', 'How long have you been waiting?', 'giada-rinaldi'),
    s('Tullio conta sulle dita, poi smette.', 'Tullio counts on his fingers, then stops.'),
    s('Trent\'anni, più o meno.', 'Thirty years, more or less.', 'tullio'),
    s('Io ero già vecchio quando hanno promesso la prima volta.', 'I was already old when they promised the first time.', 'tullio'),
    s('Adesso sono solo più vecchio.', 'Now I am only older.', 'tullio'),
    s('Elsa esce con un secchio e lava la soglia della locanda.', 'Elsa comes out with a bucket and washes the inn threshold.'),
    s('Sente la conversazione e non la ferma.', 'She hears the conversation and does not stop it.'),
    s('Perché preparate ancora tutto?', 'Why do you still prepare everything?', 'giada-rinaldi'),
    s('Tullio alza le spalle lente.', 'Tullio shrugs slowly.'),
    s('Perché se smetti di prepararti, ammetti che non conti.', 'Because if you stop preparing, you admit you do not count.', 'tullio'),
    s('E noi vogliamo contare, almeno sulla carta.', 'And we want to count, at least on paper.', 'tullio'),
    s('Giada pensa al registro con la data di oggi e l\'inchiostro vecchio.', 'Giada thinks of the register with today\'s date and the old ink.'),
    s('Anche quello era una prova per qualcuno che non arriva.', 'That too was proof for someone who does not arrive.'),
    s('L\'ispezione doveva dire se il paese restava o andava sott\'acqua.', 'The inspection was supposed to say whether the village stayed or went under water.', 'tullio'),
    s('Poi il lago non è venuto.', 'Then the lake did not come.', 'tullio'),
    s('Le carte sì.', 'The papers did.', 'tullio'),
    s('Le carte hanno cancellato Collevento senza bagnarlo.', 'The papers erased Collevento without wetting it.', 'tullio'),
    s('Giada guarda Elsa che strofina la pietra come per un ospite importante.', 'Giada watches Elsa scrub the stone as if for an important guest.'),
    s('E se non vengono mai?', 'And if they never come?', 'giada-rinaldi'),
    s('Elsa risponde senza alzare gli occhi.', 'Elsa answers without raising her eyes.'),
    s('Allora abbiamo tenuto pulito per noi.', 'Then we kept it clean for ourselves.', 'elsa'),
    s('Non è la risposta peggiore.', 'It is not the worst answer.', 'elsa'),
    s('Tullio piega il giornale.', 'Tullio folds the newspaper.'),
    s('In autunno si sente di nuovo la voce in paese.', 'In autumn you hear the talk in the village again.', 'tullio'),
    s('Arrivano.', 'They are coming.', 'tullio'),
    s('Quest\'anno davvero.', 'This year for real.', 'tullio'),
    s('Poi passa l\'autunno.', 'Then autumn passes.', 'tullio'),
    s('E riparte l\'inverno con le scale e i cartelli.', 'And winter starts again with ladders and signs.', 'tullio'),
    s('Giada sente una stanchezza che non è sua.', 'Giada feels a tiredness that is not hers.'),
    s('Trent\'anni di prove generali senza spettacolo.', 'Thirty years of dress rehearsals without a show.'),
    s('Voi sapete che è una bugia.', 'You know it is a lie.', 'giada-rinaldi'),
    s('Sì.', 'Yes.', 'tullio'),
    s('Le bugie lunghe diventano abitudini.', 'Long lies become habits.', 'tullio'),
    s('Le abitudini tengono unite le persone.', 'Habits keep people together.', 'tullio'),
    s('Fino a quando?', 'Until when?', 'giada-rinaldi'),
    s('Tullio guarda di nuovo la diga, anche se da qui si vede poco.', 'Tullio looks toward the dam again, even though from here you see little.'),
    s('Fino a quando l\'acqua decide, o le carte, o noi.', 'Until the water decides, or the papers, or we do.', 'tullio'),
    s('Elsa vuota il secchio in un tombino.', 'Elsa empties the bucket into a drain.'),
    s('Tu non sei qui per giudicarci.', 'You are not here to judge us.', 'elsa'),
    s('Giada non risponde subito.', 'Giada does not answer at once.'),
    s('È vero: è arrivata per sbaglio, non per fare lezioni.', 'It is true: she arrived by mistake, not to give lessons.'),
    s('Però non riesce a chiamare questo solo sopravvivenza.', 'But she cannot call this only survival.'),
    s('È anche una trappola fatta di calendario.', 'It is also a trap made of calendar.'),
    s('Tullio le offre il thermos.', 'Tullio offers her the thermos.'),
    s('Bevi.', 'Drink.', 'tullio'),
    s('L\'ispezione non ha fretta.', 'The inspection is in no hurry.', 'tullio'),
    s('Giada beve un sorso amaro.', 'Giada drinks a bitter sip.'),
    s('Io sì.', 'I am.', 'giada-rinaldi'),
    s('Io ho fretta di capire.', 'I am in a hurry to understand.', 'giada-rinaldi'),
    s('Tullio annuisce una volta.', 'Tullio nods once.'),
    s('Giada chiede se esiste una lettera ufficiale dell\'ispezione.', 'Giada asks if there is an official inspection letter.'),
    s('Tullio sorride con un lato solo della bocca.', 'Tullio smiles with only one side of his mouth.'),
    s('Esistevano.', 'There used to be.', 'tullio'),
    s('Poi la carta si è bagnata, o persa, o messa in un cassetto troppo fondo.', 'Then the paper got wet, or lost, or put in a drawer too deep.', 'tullio'),
    s('Quello che resta è la voce delle persone.', 'What remains is people\'s voice.', 'tullio'),
    s('La voce dice: autunno.', 'The voice says: autumn.', 'tullio'),
    s('Ogni anno la stessa stagione, come una canzone rotta.', 'Every year the same season, like a broken song.'),
    s('Elsa aggiunge che in primavera si riparano i muri.', 'Elsa adds that in spring they repair the walls.'),
    s('In estate si dipingono i cartelli.', 'In summer they paint the signs.', 'elsa'),
    s('In autunno si aspetta.', 'In autumn they wait.', 'elsa'),
    s('In inverno si racconta che l\'anno dopo sarà diverso.', 'In winter they tell themselves next year will be different.', 'elsa'),
    s('Giada riconosce il ritmo di una famiglia che spera senza strumenti.', 'Giada recognizes the rhythm of a family that hopes without tools.'),
    s('Anche a casa sua, a volte, si ripetevano promesse senza data.', 'At her house, too, sometimes promises without dates were repeated.'),
    s('Qui la promessa ha trent\'anni e un secchio.', 'Here the promise is thirty years old and has a bucket.'),
    s('Tullio le mostra il giornale piegato: notizie di un\'altra valle.', 'Tullio shows her the folded newspaper: news from another valley.'),
    s('Di Collevento non c\'è una riga.', 'There is not a line about Collevento.', 'tullio'),
    s('Se non sei scritto, per molti non sei vero.', 'If you are not written, for many you are not real.', 'tullio'),
    s('Per questo laviamo la pietra.', 'That is why we wash the stone.', 'tullio'),
    s('Per sembrare veri nel giorno in cui qualcuno guarda.', 'To look real on the day someone looks.', 'tullio'),
    s('Giada beve ancora dal thermos e sente il ferro del bordo.', 'Giada drinks again from the thermos and feels the iron of the rim.'),
    s('L\'ispezione, capisce, è il nome che danno alla speranza istituzionale.', 'The inspection, she understands, is the name they give institutional hope.'),
    s('Senza quel nome, resterebbe solo l\'abitudine nuda.', 'Without that name, only bare habit would remain.'),
    s('Allora chiedi alle carte giuste, non solo ai cartelli.', 'Then ask the right papers, not only the signs.', 'tullio'),
    s('Giada guarda la piazza pulita per nessuno.', 'Giada looks at the square cleaned for no one.'),
    s('L\'autunno, qui, è una stagione che non finisce mai di arrivare.', 'Autumn, here, is a season that never finishes arriving.'),
    ],
    questions: [
    q('When is the inspection supposed to come?', ['In autumn', 'In summer', 'Every Monday'], 0, 'Tullio says they used to say in autumn.'),
    q('How long have they roughly waited?', ['Thirty years', 'Three years', 'Three days'], 0, 'Tullio says about thirty years.'),
    q('Have the inspectors ever really come?', ['No, not as promised', 'Yes, every year', 'Only at Christmas'], 0, 'Tullio says they have never come as promised.'),
    ],
  },

  {
    number: 12,
    title: 'Anna\'s photo',
    titleIt: 'La foto di Anna',
    summary:
      'Giada finds a photo of her mother at seventeen with the same jaw. She is angry that the village has stolen her face and treated her as Anna returned.',
    facts: [
      'Giada finds a photo of Anna at seventeen',
      'Anna has the same jaw as Giada',
      'The photo was kept in a drawer at the inn',
      'Giada is angry that her face was treated as stolen property',
    ],
    locationIds: ['locanda-elsa'],
    characterIds: ['giada-rinaldi', 'elsa', 'anna-rinaldi'],
    sentences: [
    s('Nel pomeriggio Elsa va al bosco per legna piccola e lascia la locanda aperta.', 'In the afternoon Elsa goes to the woods for small firewood and leaves the inn open.'),
    s('Giada resta dentro, non per rubare, ma per cercare.', 'Giada stays inside, not to steal, but to search.'),
    s('Apre il cassetto sotto il registro.', 'She opens the drawer under the register.'),
    s('Dentro ci sono fatture, elastici, una chiave senza etichetta.', 'Inside there are invoices, rubber bands, a key without a label.'),
    s('Sotto le fatture c\'è una busta senza francobollo.', 'Under the invoices there is an envelope without a stamp.'),
    s('Giada la apre con le mani ferme.', 'Giada opens it with steady hands.'),
    s('Dentro c\'è una fotografia stampata, non digitale.', 'Inside there is a printed photograph, not digital.'),
    s('Una ragazza di circa diciassette anni guarda la macchina da presa.', 'A girl of about seventeen looks at the camera.'),
    s('Ha i capelli tirati indietro e una maglietta chiara.', 'She has her hair pulled back and a light T-shirt.'),
    s('Ha la stessa mandibola di Giada.', 'She has the same jaw as Giada.'),
    s('Lo stesso modo di tenere la bocca chiusa quando è arrabbiata.', 'The same way of keeping her mouth closed when she is angry.'),
    s('Dietro la foto, a matita: Anna, estate 2007.', 'On the back of the photo, in pencil: Anna, summer 2007.'),
    s('Giada si siede per terra vicino al mobile.', 'Giada sits on the floor near the cabinet.'),
    s('Guarda la foto a lungo, senza piangere.', 'She looks at the photo a long time, without crying.'),
    s('Non è stupita del tutto.', 'She is not entirely surprised.'),
    s('Il registro aveva già detto il nome.', 'The register had already said the name.'),
    s('Però vedere il volto è diverso.', 'But seeing the face is different.'),
    s('Il volto è una prova che non si può spostare con una scala.', 'The face is proof you cannot move with a ladder.'),
    s('Elsa rientra con un fascio di rami e si ferma sulla soglia.', 'Elsa comes back with a bundle of branches and stops on the threshold.'),
    s('Ha trovato Anna.', 'She has found Anna.', 'elsa'),
    s('Non è una domanda.', 'It is not a question.'),
    s('Giada alza la foto.', 'Giada raises the photo.'),
    s('Questa è mia madre.', 'This is my mother.', 'giada-rinaldi'),
    s('Lo so.', 'I know.', 'elsa'),
    s('Allora perché mi chiami con il suo nome?', 'Then why do you call me by her name?', 'giada-rinaldi'),
    s('Elsa posa la legna e si asciuga le mani sul grembiule.', 'Elsa sets down the wood and dries her hands on her apron.'),
    s('Perché sei entrata con la stessa borsa.', 'Because you came in with the same bag.', 'elsa'),
    s('Con la stessa età in faccia.', 'With the same age on your face.', 'elsa'),
    s('Con lo stesso modo di guardare la porta come se volessi già andartene.', 'With the same way of looking at the door as if you already wanted to leave.', 'elsa'),
    s('Giada sente salire una rabbia netta.', 'Giada feels a clear anger rise.'),
    s('Non sono un ritorno.', 'I am not a return.', 'giada-rinaldi'),
    s('Non sono una copia.', 'I am not a copy.', 'giada-rinaldi'),
    s('Non sono la vostra seconda occasione.', 'I am not your second chance.', 'giada-rinaldi'),
    s('Elsa abbassa gli occhi sulla foto.', 'Elsa lowers her eyes to the photo.'),
    s('Avevo paura di dimenticare i dettagli.', 'I was afraid of forgetting the details.', 'elsa'),
    s('Allora ho tenuto quella carta.', 'So I kept that paper.', 'elsa'),
    s('Giada ride amara.', 'Giada laughs bitterly.'),
    s('Tu hai tenuto la sua faccia in un cassetto.', 'You kept her face in a drawer.', 'giada-rinaldi'),
    s('E quando sono arrivata, hai preso la mia.', 'And when I arrived, you took mine.', 'giada-rinaldi'),
    s('Come se un volto fosse proprietà del paese.', 'As if a face were village property.', 'giada-rinaldi'),
    s('Elsa non difende bene se stessa.', 'Elsa does not defend herself well.'),
    s('Anna è partita senza spiegare tutto.', 'Anna left without explaining everything.', 'elsa'),
    s('Per anni ho pensato che un giorno avrebbe ripreso quella stanza.', 'For years I thought one day she would take that room again.', 'elsa'),
    s('Poi sei scesa tu dal treno.', 'Then you got off the train.', 'elsa'),
    s('Giada stringe la foto fino a piegarne l\'angolo.', 'Giada grips the photo until she bends a corner.'),
    s('Mia madre vive a Bologna.', 'My mother lives in Bologna.', 'giada-rinaldi'),
    s('Ha un lavoro.', 'She has a job.', 'giada-rinaldi'),
    s('Ha una figlia che non voleva mandare qui.', 'She has a daughter she did not want to send here.', 'giada-rinaldi'),
    s('O forse sì, e non me l\'ha detto.', 'Or maybe she did, and she did not tell me.', 'giada-rinaldi'),
    s('Questa frase resta sospesa.', 'That sentence stays hanging.'),
    s('Elsa fa un passo avanti.', 'Elsa takes a step forward.'),
    s('Lascia la foto.', 'Leave the photo.', 'elsa'),
    s('No.', 'No.', 'giada-rinaldi'),
    s('Questa faccia è già stata rubata abbastanza.', 'This face has already been stolen enough.', 'giada-rinaldi'),
    s('La metto nella mia tasca, non nel tuo cassetto.', 'I am putting it in my pocket, not in your drawer.', 'giada-rinaldi'),
    s('Elsa non la ferma.', 'Elsa does not stop her.'),
    s('Forse perché sa di avere torto, o perché ha bisogno che qualcuno porti via Anna davvero.', 'Perhaps because she knows she is wrong, or because she needs someone to take Anna away for real.'),
    s('Giada sale in camera e chiude la porta.', 'Giada goes up to her room and closes the door.'),
    s('Appoggia la foto sul comodino, accanto al telefono.', 'She sets the photo on the nightstand, next to the phone.'),
    s('Guarda la mandibola nella carta e poi si tocca la propria.', 'She looks at the jaw on the paper and then touches her own.'),
    s('Stessa linea.', 'Same line.'),
    s('Storia diversa.', 'Different story.'),
    s('Questa differenza deve restare chiara.', 'That difference must stay clear.'),
    s('Fuori, Elsa riapre il registro e non scrive niente.', 'Outside, Elsa reopens the register and writes nothing.'),
    s('La ragazza nella foto non sorride.', 'The girl in the photo does not smile.'),
    s('Ha gli occhi stanchi di chi ha già deciso qualcosa di difficile.', 'She has the tired eyes of someone who has already decided something difficult.'),
    s('Giada cerca nella faccia la propria madre di oggi e la trova solo a tratti.', 'Giada looks in the face for her mother of today and finds her only in places.'),
    s('La mandibola sì.', 'The jaw, yes.'),
    s('Il resto è una straniera giovane.', 'The rest is a young stranger.'),
    s('Questa distanza fa male e aiuta.', 'This distance hurts and helps.'),
    s('Aiuta perché dimostra che Anna non è un mito fermo.', 'It helps because it shows Anna is not a frozen myth.'),
    s('È una persona che è cambiata dopo Collevento.', 'She is a person who changed after Collevento.'),
    s('Elsa, nella cucina, spezza i rami in pezzi uguali.', 'Elsa, in the kitchen, breaks the branches into equal pieces.'),
    s('Il rumore del legno riempie i silenzi sbagliati.', 'The sound of wood fills the wrong silences.'),
    s('Giada chiede dove è stata scattata la foto.', 'Giada asks where the photo was taken.'),
    s('In piazza, vicino alla fontana.', 'In the square, near the fountain.', 'elsa'),
    s('Anna odiava farsi fotografare, però quel giorno ha detto sì.', 'Anna hated being photographed, but that day she said yes.', 'elsa'),
    s('Giada guarda di nuovo la piazza dalla finestra.', 'Giada looks at the square again from the window.'),
    s('La fontana è la stessa.', 'The fountain is the same.'),
    s('La ragazza no.', 'The girl is not.'),
    s('E lei non vuole diventare la terza versione di quel sì.', 'And she does not want to become the third version of that yes.'),
    s('Mette la foto in una busta di carta trovata sul tavolo.', 'She puts the photo in a paper envelope found on the table.'),
    s('Scrive sopra, a matita: non Anna, madre.', 'She writes on it, in pencil: not Anna, mother.'),
    s('Poi scrive: Giada.', 'Then she writes: Giada.'),
    s('Il secondo nome è un confine.', 'The second name is a border.'),
    s('Elsa vede la busta e non commenta.', 'Elsa sees the envelope and does not comment.'),
    s('A volte il silenzio è l\'unica scusa che le resta.', 'Sometimes silence is the only excuse she has left.'),
    s('Giada pensa: non odio mia madre per la faccia.', 'Giada thinks: I do not hate my mother for the face.'),
    s('Odio chi usa una faccia come una chiave.', 'I hate whoever uses a face as a key.'),
    s('E Collevento ha usato la sua senza chiedere.', 'And Collevento used hers without asking.'),
    ],
    questions: [
    q('Who is in the photograph?', ['Anna at seventeen', 'Elsa as a child', 'Neri'], 0, 'The photo shows Anna, summer 2007.'),
    q('What physical detail matches Giada?', ['The jaw', 'A scar', 'Glasses'], 0, 'Anna has the same jaw as Giada.'),
    q('What does Giada do with the photo?', ['Keeps it in her pocket', 'Burns it', 'Gives it to Tullio'], 0, 'She puts it in her pocket, not Elsa\'s drawer.'),
    ],
  },

  {
    number: 13,
    title: 'The forest',
    titleIt: 'Il bosco',
    summary:
      'Giada goes into the forest despite the rule. She finds a fence with a sinkhole pictogram, not a monster sign, and the names of the 1978 survey team.',
    facts: [
      'Giada enters the forest against the village rule',
      'The fence warning is a sinkhole pictogram',
      'It is not a magical monster sign',
      'Names of the 1978 survey team are listed at the memorial',
    ],
    locationIds: ['bosco-recinto', 'memorial-1978', 'collevento-strada'],
    characterIds: ['giada-rinaldi', 'neri'],
    sentences: [
    s('Il giorno dopo Giada non chiede permesso.', 'The next day Giada does not ask permission.'),
    s('Prende una bottiglia d\'acqua e la foto di Anna in tasca.', 'She takes a bottle of water and Anna\'s photo in her pocket.'),
    s('Esce sulla strada del colle quando il sole è alto.', 'She goes out onto the hill road when the sun is high.'),
    s('Il bosco comincia subito dopo le ultime case.', 'The forest begins right after the last houses.'),
    s('L\'aria cambia: più fresca, più chiusa.', 'The air changes: cooler, more closed.'),
    s('Ricorda la regola: non si va nel bosco.', 'She remembers the rule: you do not go into the forest.'),
    s('Ricorda anche che le regole, qui, hanno ragioni fisiche.', 'She also remembers that the rules, here, have physical reasons.'),
    s('Cammina comunque.', 'She walks anyway.'),
    s('Dopo dieci minuti trova un recinto di rete metallica.', 'After ten minutes she finds a metal-mesh fence.'),
    s('Il cancello è chiuso con una catena vecchia.', 'The gate is closed with an old chain.'),
    s('Sul palo c\'è un cartello giallo piegato dal tempo.', 'On the post there is a yellow sign bent by time.'),
    s('All\'inizio Giada legge il disegno come un teschio.', 'At first Giada reads the drawing as a skull.'),
    s('Poi si avvicina.', 'Then she comes closer.'),
    s('Non è un teschio.', 'It is not a skull.'),
    s('È un pittogramma di terreno che cede: una figura stilizzata che sprofonda.', 'It is a pictogram of ground giving way: a stylized figure sinking.'),
    s('Sotto, in stampatello: PERICOLO VORAGINI.', 'Underneath, in block letters: DANGER SINHOLES.'),
    s('Giada sente sollievo e paura insieme.', 'Giada feels relief and fear together.'),
    s('Sollievo perché non c\'è un mostro da storia.', 'Relief because there is no storybook monster.'),
    s('Paura perché il suolo può aprirsi davvero.', 'Fear because the ground can really open.'),
    s('Cammina lungo il recinto senza salirlo.', 'She walks along the fence without climbing it.'),
    s('Cerca un punto dove la rete è più bassa.', 'She looks for a spot where the mesh is lower.'),
    s('Trova invece una targa di metallo fissata a due pali.', 'Instead she finds a metal plaque fixed to two posts.'),
    s('La targa è sporca, ma le lettere si leggono.', 'The plaque is dirty, but the letters can be read.'),
    s('SQUADRA RILIEVO 1978.', 'SURVEY TEAM 1978.'),
    s('Sotto ci sono nomi, uno sotto l\'altro.', 'Underneath there are names, one under the other.'),
    s('Marco Bellini.', 'Marco Bellini.'),
    s('Paola Greci.', 'Paola Greci.'),
    s('Stefano Mura.', 'Stefano Mura.'),
    s('Luciano Ferri.', 'Luciano Ferri.'),
    s('Due cognomi sono rovinati dalla ruggine.', 'Two surnames are ruined by rust.'),
    s('Giada legge ad alta voce, piano.', 'Giada reads aloud, quietly.'),
    s('Non per chiamare spiriti.', 'Not to call spirits.'),
    s('Per non dimenticare che erano persone con un lavoro.', 'So as not to forget they were people with a job.'),
    s('Dietro la targa il terreno è irregolare, più basso, con erba diversa.', 'Behind the plaque the ground is uneven, lower, with different grass.'),
    s('Capisce: qui qualcosa è crollato, anni fa.', 'She understands: something collapsed here, years ago.'),
    s('Il memorial non è magia.', 'The memorial is not magic.'),
    s('È memoria tecnica e lutto civile.', 'It is technical memory and civic mourning.'),
    s('Sente passi sulla foglia secca.', 'She hears steps on dry leaves.'),
    s('Neri arriva senza correre.', 'Neri arrives without running.'),
    s('Ti avevano detto di no.', 'They had told you no.', 'neri'),
    s('Lo so.', 'I know.', 'giada-rinaldi'),
    s('Neri indica il cartello giallo.', 'Neri points at the yellow sign.'),
    s('Non è una storia per spaventare i bambini.', 'It is not a story to scare children.', 'neri'),
    s('Il terreno mangia.', 'The ground eats.', 'neri'),
    s('Mangia macchine, strumenti, a volte gente.', 'It eats machines, tools, sometimes people.', 'neri'),
    s('Giada annuisce.', 'Giada nods.'),
    s('Perché nessuno spiega così in paese?', 'Why does nobody explain it like this in the village?', 'giada-rinaldi'),
    s('Neri alza un sopracciglio.', 'Neri raises an eyebrow.'),
    s('Perché «voragine» fa meno paura di «bosco maledetto» ai turisti.', 'Because "sinkhole" scares tourists less than "cursed forest."', 'neri'),
    s('E noi non siamo turisti.', 'And we are not tourists.', 'neri'),
    s('Però a volte le storie corte tengono i bambini lontani meglio delle spiegazioni.', 'But sometimes short stories keep children away better than explanations.', 'neri'),
    s('Giada guarda di nuovo i nomi del 1978.', 'Giada looks again at the 1978 names.'),
    s('Loro erano qui per la diga?', 'Were they here for the dam?', 'giada-rinaldi'),
    s('Per il lago che doveva arrivare.', 'For the lake that was supposed to come.', 'neri'),
    s('Hanno misurato, trapano, mappe.', 'They measured, drilled, mapped.', 'neri'),
    s('Poi il terreno ha risposto male.', 'Then the ground answered badly.', 'neri'),
    s('Neri non aggiunge dettagli cruenti.', 'Neri does not add bloody details.'),
    s('Non serve.', 'There is no need.'),
    s('Giada fotografa la targa.', 'Giada photographs the plaque.'),
    s('Fotografa il pittogramma della voragine.', 'She photographs the sinkhole pictogram.'),
    s('Fotografa il punto basso dietro il recinto, da lontano.', 'She photographs the low spot behind the fence, from a distance.'),
    s('Non supera la rete.', 'She does not cross the mesh.'),
    s('Rispetto e paura, insieme, bastano.', 'Respect and fear, together, are enough.'),
    s('Torniamo.', 'Let\'s go back.', 'neri'),
    s('Prima del pomeriggio le ombre mentono sulla profondità delle buche.', 'Before afternoon the shadows lie about how deep the holes are.', 'neri'),
    s('Giada lo segue sulla strada del colle.', 'Giada follows him onto the hill road.'),
    s('Nel taschino la foto di Anna batte contro il telefono a ogni passo.', 'In her pocket Anna\'s photo knocks against the phone with every step.'),
    s('Prima del recinto Giada cammina su terra dura e radici.', 'Before the fence Giada walks on hard earth and roots.'),
    s('Sente odore di funghi e di ferro umido.', 'She smells mushrooms and damp iron.'),
    s('Nessun uccello canta vicino alla targa.', 'No bird sings near the plaque.'),
    s('Forse è caso, forse è il terreno che non ama il peso.', 'Maybe it is chance, maybe it is ground that does not like weight.'),
    s('Giada non inventa storie sopra i fatti.', 'Giada does not invent stories on top of the facts.'),
    s('I fatti bastano: nomi, anno, pericolo stampato in giallo.', 'The facts are enough: names, year, danger printed in yellow.'),
    s('Legge di nuovo «PERICOLO VORAGINI» come si legge un orario.', 'She reads "DANGER SINKHOLES" again the way you read a timetable.'),
    s('Un orario non si discute: si usa.', 'A timetable is not argued with: it is used.'),
    s('Neri racconta che da ragazzo qualcuno gli aveva detto del mostro del bosco.', 'Neri says that as a boy someone had told him about the forest monster.'),
    s('Poi ha visto i documenti in comune, in una cartella dimenticata.', 'Then he saw the documents at the town hall, in a forgotten folder.'),
    s('Non c\'era un mostro.', 'There was no monster.', 'neri'),
    s('C\'erano perizie e croci sulle mappe.', 'There were surveys and crosses on the maps.', 'neri'),
    s('Giada apprezza che lui preferisca le perizie.', 'Giada appreciates that he prefers the surveys.'),
    s('Anche lei preferisce le prove alle favole, da sempre.', 'She too has always preferred evidence to fairy tales.'),
    s('Per questo odia quando gli adulti usano favole per comodità.', 'That is why she hates when adults use fairy tales for convenience.'),
    s('Davanti ai nomi del 1978 resta un minuto in silenzio.', 'In front of the 1978 names she stays a minute in silence.'),
    s('Non prega.', 'She does not pray.'),
    s('Ricorda soltanto che ogni progetto grande lascia conti umani.', 'She only remembers that every big project leaves human bills.'),
    s('Poi fotografa anche la catena del cancello, chiusa bene.', 'Then she also photographs the gate chain, locked well.'),
    s('Una prova che il divieto non è teatro vuoto.', 'Proof that the ban is not empty theater.'),
    s('È un confine fisico, tenuto da gente che sa perché.', 'It is a physical border, kept by people who know why.'),
    s('Sulla via del ritorno le gambe sono più pesanti.', 'On the way back her legs are heavier.'),
    s('Non per lo sforzo: per il peso dei fatti nuovi.', 'Not from effort: from the weight of new facts.'),
    s('Due prove diverse: una faccia, un elenco di morti tecnici.', 'Two different proofs: a face, a list of technical dead.'),
    s('Nessuna delle due è un destino scelto.', 'Neither is a chosen destiny.'),
    s('Sono fatti, e i fatti pesano.', 'They are facts, and facts weigh.'),
    ],
    questions: [
    q('What does the yellow sign really warn about?', ['Sinkholes', 'Wolves', 'Ghosts'], 0, 'It is a sinkhole pictogram: PERICOLO VORAGINI.'),
    q('What year is on the memorial plaque?', ['1978', '2007', '1999'], 0, 'It says survey team 1978.'),
    q('Does Giada climb past the fence?', ['No', 'Yes, to the dam', 'Only at night'], 0, 'She photographs from outside and does not cross.'),
    ],
  },

  {
    number: 14,
    title: 'Neri tells',
    titleIt: 'Neri racconta',
    summary:
      'Neri explains the unfinished dam, the lake that never filled, and the redrawn maps. He says the village stays off the map to help itself, not the company: non esistiamo per aiutarli.',
    facts: [
      'The dam project was meant to make a lake',
      'The lake was never finished',
      'Maps were redrawn with Collevento blank or deleted',
      'Neri says they do not exist on maps to help themselves, not the company',
    ],
    locationIds: ['strada-diga', 'edificio-idroelettrico', 'collevento-strada'],
    characterIds: ['giada-rinaldi', 'neri'],
    sentences: [
    s('Sulla strada della diga Neri cammina un passo avanti a Giada.', 'On the dam road Neri walks one step ahead of Giada.'),
    s('Non parla subito.', 'He does not speak at once.'),
    s('Aspetta il punto dove si vede l\'edificio idroelettrico in basso.', 'He waits for the point where you can see the hydro building below.'),
    s('Lì si ferma e indica con il mento.', 'There he stops and points with his chin.'),
    s('Quella doveva essere la centrale.', 'That was supposed to be the plant.', 'neri'),
    s('E laggiù, dove vedi il greto largo, doveva esserci il lago.', 'And down there, where you see the wide riverbed, there was supposed to be the lake.', 'neri'),
    s('Giada guarda.', 'Giada looks.'),
    s('Non c\'è un lago.', 'There is no lake.'),
    s('C\'è terra grigia, sassi, un filo d\'acqua stretto.', 'There is grey earth, stones, a thin thread of water.'),
    s('Hanno costruito pezzi.', 'They built pieces.', 'neri'),
    s('Hanno fatto prove.', 'They ran tests.', 'neri'),
    s('Hanno aperto e chiuso paratie secondo orari.', 'They opened and closed sluices on schedules.', 'neri'),
    s('Poi i soldi, o la geologia, o la politica, si sono fermati.', 'Then money, or geology, or politics, stopped.', 'neri'),
    s('Il progetto è restato a metà.', 'The project stayed half-done.', 'neri'),
    s('Giada pensa all\'acqua ogni sera sulla strada.', 'Giada thinks of the water every evening on the road.'),
    s('Quindi il tramonto non è un sortilegio.', 'So sunset is not a spell.', 'giada-rinaldi'),
    s('È un orologio della compagnia.', 'It is a company clock.', 'neri'),
    s('Aprono ancora secondo un piano vecchio.', 'They still open according to an old plan.', 'neri'),
    s('Perché è più facile tenere una procedura che cancellarla.', 'Because it is easier to keep a procedure than to cancel it.', 'neri'),
    s('Neri tira fuori dalla tasca la mappa piegata che Giada ha già visto.', 'Neri pulls from his pocket the folded map Giada has already seen.'),
    s('La apre sul guardrail caldo.', 'He opens it on the warm guardrail.'),
    s('Qui, guarda.', 'Here, look.', 'neri'),
    s('C\'è una macchia bianca dove dovrebbe esserci Collevento.', 'There is a white blotch where Collevento should be.'),
    s('Niente nome.', 'No name.'),
    s('Niente strade disegnate.', 'No drawn roads.'),
    s('Solo verde generico e una linea blu del fiume.', 'Only generic green and a blue line for the river.'),
    s('Sulle carte nuove il lago futuro era già disegnato.', 'On the new maps the future lake was already drawn.', 'neri'),
    s('Poi il lago non è arrivato.', 'Then the lake did not arrive.', 'neri'),
    s('Ma il paese restava scomodo.', 'But the village stayed inconvenient.', 'neri'),
    s('Allora hanno lasciato il bianco.', 'So they left the white.', 'neri'),
    s('Come se non esistessimo.', 'As if we did not exist.', 'neri'),
    s('Giada tocca la macchia con un dito.', 'Giada touches the blotch with a finger.'),
    s('Esistete.', 'You exist.', 'giada-rinaldi'),
    s('Io ci sono dentro.', 'I am inside it.', 'giada-rinaldi'),
    s('Neri piega un angolo della mappa.', 'Neri folds a corner of the map.'),
    s('Esistere per noi e esistere per loro non è uguale.', 'Existing for us and existing for them is not the same.', 'neri'),
    s('Se torniamo sulle mappe turistiche, arrivano domande.', 'If we go back onto tourist maps, questions arrive.', 'neri'),
    s('Arrivano progetti nuovi.', 'New projects arrive.', 'neri'),
    s('Arrivano offerte per andarcene «in modo civile».', 'Offers arrive for us to leave "in a civil way."', 'neri'),
    s('Giada ascolta senza interrompere.', 'Giada listens without interrupting.'),
    s('Neri parla come uno che ha ripetuto queste frasi nella testa molte sere.', 'Neri talks like someone who has repeated these sentences in his head many evenings.'),
    s('Gli anziani hanno deciso una cosa brutta e intelligente.', 'The elders decided something ugly and smart.', 'neri'),
    s('Restare fuori.', 'Stay off.', 'neri'),
    s('Non esistiamo per aiutarli.', 'We do not exist to help them.', 'neri'),
    s('Esistiamo, se serve, solo per noi.', 'We exist, if needed, only for ourselves.', 'neri'),
    s('La frase resta nell\'aria calda.', 'The sentence stays in the warm air.'),
    s('Giada la ripete piano, per tenerla.', 'Giada repeats it quietly, to keep it.'),
    s('Non esistiamo per aiutarli.', 'We do not exist to help them.', 'giada-rinaldi'),
    s('Neri annuisce.', 'Neri nods.'),
    s('Per questo Elsa lava soglie per ispezioni che non vengono.', 'That is why Elsa washes thresholds for inspections that do not come.', 'neri'),
    s('Per questo i cartelli cambiano secondo carte vecchie.', 'That is why signs change according to old papers.', 'neri'),
    s('È una difesa fatta di scenografia e silenzio.', 'It is a defense made of staging and silence.', 'neri'),
    s('Giada guarda l\'edificio in basso: finestre accese anche di giorno, forse luci di servizio.', 'Giada looks at the building below: windows lit even by day, maybe service lights.'),
    s('Loro esistono eccome.', 'They exist all right.', 'giada-rinaldi'),
    s('Sì.', 'Yes.', 'neri'),
    s('Hanno badge, auto alte, orari.', 'They have badges, high cars, schedules.', 'neri'),
    s('Noi abbiamo una piazza che si sposta e un nome cancellato.', 'We have a square that moves and a deleted name.', 'neri'),
    s('Vuoi andartene da qui.', 'You want to leave here.', 'giada-rinaldi'),
    s('Neri non nega.', 'Neri does not deny it.'),
    s('Voglio una strada che resti strada anche dopo le otto.', 'I want a road that stays a road even after eight.', 'neri'),
    s('Voglio un punto sulla mappa che non sia bianco.', 'I want a point on the map that is not white.', 'neri'),
    s('Però se sparisco solo io, il paese resta più debole.', 'But if only I disappear, the village stays weaker.', 'neri'),
    s('E loro diventano più forti.', 'And they become stronger.', 'neri'),
    s('Giada ripiega la mappa insieme a lui.', 'Giada folds the map together with him.'),
    s('Capisce meglio la rabbia quieta di Collevento.', 'She understands better Collevento\'s quiet anger.'),
    s('Non è folklore.', 'It is not folklore.'),
    s('È amministrazione e acqua e paura di essere utili al posto sbagliato.', 'It is administration and water and fear of being useful in the wrong place.'),
    s('Tornano verso il paese senza dire altro per un pezzo.', 'They walk back toward the village without saying more for a while.'),
    s('Neri spiega che la diga ha ancora tecnici in turno.', 'Neri explains that the dam still has technicians on shift.'),
    s('Loro non vivono a Collevento.', 'They do not live in Collevento.', 'neri'),
    s('Salgono e scendono con auto che non temono l\'acqua bassa.', 'They go up and down with cars that do not fear shallow water.', 'neri'),
    s('La sera aprono secondo un protocollo stampato anni fa.', 'In the evening they open according to a protocol printed years ago.', 'neri'),
    s('Nessuno in paese ha il potere di fermare quel protocollo.', 'Nobody in the village has the power to stop that protocol.', 'neri'),
    s('Giada chiede perché non protestano in città.', 'Giada asks why they do not protest in the city.'),
    s('Neri ride corto.', 'Neri laughs shortly.'),
    s('Protestare richiede esistere ufficialmente.', 'Protesting requires existing officially.', 'neri'),
    s('Noi siamo un errore amministrativo comodo.', 'We are a convenient administrative error.', 'neri'),
    s('Se gridiamo, diventiamo un problema da risolvere in fretta.', 'If we shout, we become a problem to solve quickly.', 'neri'),
    s('E i problemi comodi si risolvono con valigie e compensi.', 'And convenient problems are solved with suitcases and compensation.', 'neri'),
    s('Giada guarda di nuovo la macchia bianca sulla mappa.', 'Giada looks again at the white blotch on the map.'),
    s('Capisce la frase «non esistiamo per aiutarli» come una regola di difesa.', 'She understands the sentence "we do not exist to help them" as a defense rule.'),
    s('Non come orgoglio vuoto.', 'Not as empty pride.'),
    s('Come modo per non diventare utili al momento sbagliato.', 'As a way not to become useful at the wrong time.'),
    s('Neri ripiega la mappa con cura, sempre sugli stessi segni.', 'Neri refolds the map carefully, always on the same creases.'),
    s('Quella carta è più vera del cartello in piazza.', 'That paper is truer than the sign in the square.'),
    s('Perché non cerca di sembrare un paese perfetto.', 'Because it does not try to look like a perfect village.'),
    s('Mostra solo l\'assenza.', 'It only shows the absence.'),
    s('Giada chiede se lui ha mai messo Collevento a mano sulla mappa.', 'Giada asks if he has ever written Collevento onto the map by hand.'),
    s('Una volta.', 'Once.', 'neri'),
    s('Poi l\'ho cancellato.', 'Then I erased it.', 'neri'),
    s('Avevo paura di aiutare la compagnia senza volerlo.', 'I was afraid of helping the company without meaning to.', 'neri'),
    s('La confessione è piccola e pesante.', 'The confession is small and heavy.'),
    s('Camminano ancora un tratto in silenzio, con l\'edificio sotto di loro come un orologio acceso.', 'They walk another stretch in silence, with the building below them like a lit clock.'),
    s('Il vento porta odore di cemento caldo dall\'edificio.', 'The wind carries a smell of warm concrete from the building.'),
    s('Giada mette la frase di Neri accanto alla foto di Anna, nella testa.', 'Giada puts Neri\'s sentence next to Anna\'s photo, in her head.'),
    s('Due modi diversi di non farsi usare.', 'Two different ways of not being used.'),
    ],
    questions: [
    q('What was supposed to cover the valley?', ['A lake', 'A highway', 'A mall'], 0, 'The dam project was meant to make a lake.'),
    q('What is on the modern map where Collevento should be?', ['A blank / white area', 'A big red star', 'A tourist hotel'], 0, 'There is a white blotch with no name.'),
    q('What does Neri say about existing on maps?', ['We do not exist to help them', 'We want more tourists', 'We love the company'], 0, 'He says: non esistiamo per aiutarli.'),
    ],
  },

  {
    number: 15,
    title: 'The engineer',
    titleIt: 'L\'ingegnere',
    summary:
      'A company engineer visits in daylight, smiles, and offers compensation. At sunset he leaves in a high car; the water rules are for residents, not for him.',
    facts: [
      'An engineer visits Collevento in daylight',
      'He smiles and talks about compensation',
      'At sunset he leaves in a high car',
      'The evening water rule does not stop him',
    ],
    locationIds: ['piazza-collevento', 'strada-diga', 'edificio-idroelettrico', 'locanda-elsa'],
    characterIds: ['giada-rinaldi', 'ingegnere', 'elsa', 'tullio', 'neri'],
    sentences: [
    s('Il giorno dopo, verso le undici, arriva un\'auto alta e pulita.', 'The next day, around eleven, a high clean car arrives.'),
    s('Si ferma in piazza come se la piazza fosse un parcheggio normale.', 'It stops in the square as if the square were a normal parking lot.'),
    s('Scende un uomo in camicia chiara, senza cravatta.', 'A man in a light shirt gets out, without a tie.'),
    s('Sorride prima di parlare.', 'He smiles before speaking.'),
    s('Buongiorno.', 'Good morning.', 'ingegnere'),
    s('Sono dell\'ufficio lavori della diga.', 'I am from the dam works office.', 'ingegnere'),
    s('Elsa esce subito, con le mani ancora bagnate.', 'Elsa comes out at once, with her hands still wet.'),
    s('Tullio resta sulla sedia e non alza il giornale.', 'Tullio stays on his chair and does not raise the newspaper.'),
    s('Neri appare dall\'angolo e non saluta.', 'Neri appears from the corner and does not greet.'),
    s('Giada resta sulla soglia della locanda.', 'Giada stays on the inn threshold.'),
    s('L\'ingegnere guarda i volti come conta pezzi.', 'The engineer looks at the faces as if counting pieces.'),
    s('Che piacere rivedere Collevento così in ordine.', 'What a pleasure to see Collevento so tidy again.', 'ingegnere'),
    s('Elsa non ringrazia.', 'Elsa does not thank him.'),
    s('L\'ingegnere continua a sorridere.', 'The engineer keeps smiling.'),
    s('Siamo in una fase nuova di valutazione.', 'We are in a new evaluation phase.', 'ingegnere'),
    s('Ci sono fondi di accompagnamento.', 'There are support funds.', 'ingegnere'),
    s('Compensi per chi sceglie di trasferirsi in modo sereno.', 'Compensation for those who choose to move calmly.', 'ingegnere'),
    s('La parola «sereno» suona falsa nella piazza quieta.', 'The word "calmly" sounds false in the quiet square.'),
    s('Tullio parla senza alzarsi.', 'Tullio speaks without standing.'),
    s('L\'ispezione di autunno?', 'The autumn inspection?', 'tullio'),
    s('L\'ingegnere fa un gesto vago.', 'The engineer makes a vague gesture.'),
    s('Chiamiamola visita tecnica.', 'Let\'s call it a technical visit.', 'ingegnere'),
    s('Niente drammi.', 'No drama.', 'ingegnere'),
    s('Solo numeri e soluzioni.', 'Only numbers and solutions.', 'ingegnere'),
    s('Guarda Giada un secondo di troppo.', 'He looks at Giada a second too long.'),
    s('Lei non distoglie lo sguardo.', 'She does not look away.'),
    s('Lei è nuova?', 'Is she new?', 'ingegnere'),
    s('È di passaggio.', 'She is passing through.', 'elsa'),
    s('Ospite.', 'A guest.', 'elsa'),
    s('L\'ingegnere annuisce, soddisfatto della categoria.', 'The engineer nods, satisfied with the category.'),
    s('Meglio.', 'Better.', 'ingegnere'),
    s('I passaggi complicano meno dei residenti.', 'Passers-through complicate less than residents.', 'ingegnere'),
    s('Lascia una cartellina sottile sul tavolino fuori dalla locanda.', 'He leaves a thin folder on the little table outside the inn.'),
    s('Dentro ci sono fogli con tabelle e una lettera stampata.', 'Inside there are sheets with tables and a printed letter.'),
    s('Leggetela con calma.', 'Read it calmly.', 'ingegnere'),
    s('Non c\'è fretta oggi.', 'There is no hurry today.', 'ingegnere'),
    s('C\'è fretta nei progetti, però.', 'There is hurry in the projects, though.', 'neri'),
    s('L\'ingegnere sorride a Neri come a un ragazzo intelligente.', 'The engineer smiles at Neri as at a clever boy.'),
    s('I progetti hanno calendari.', 'Projects have calendars.', 'ingegnere'),
    s('I paesi hanno persone.', 'Villages have people.', 'ingegnere'),
    s('Noi cerchiamo di farli incontrare.', 'We try to make them meet.', 'ingegnere'),
    s('Giada pensa: incontrare significa spesso schiacciare.', 'Giada thinks: meeting often means crushing.'),
    s('L\'ingegnere gira un\'ora tra le case, parla poco, fotografa muri e tetti.', 'The engineer walks an hour among the houses, speaks little, photographs walls and roofs.'),
    s('Non fotografa i volti.', 'He does not photograph faces.'),
    s('Fotografa le prove che il paese è abitato.', 'He photographs proof that the village is inhabited.'),
    s('Verso sera torna in piazza e stringe la mano a Elsa.', 'Toward evening he returns to the square and shakes Elsa\'s hand.'),
    s('Grazie per l\'ordine.', 'Thank you for the tidiness.', 'ingegnere'),
    s('Aiuta tutti.', 'It helps everyone.', 'ingegnere'),
    s('Elsa ritira la mano subito.', 'Elsa pulls her hand back at once.'),
    s('Il sole scende dietro il colle.', 'The sun goes down behind the hill.'),
    s('Giada guarda l\'orologio del telefono.', 'Giada looks at the phone clock.'),
    s('Manca poco all\'ora dell\'acqua.', 'It is almost water time.'),
    s('L\'ingegnere apre lo sportello dell\'auto alta.', 'The engineer opens the door of the high car.'),
    s('Voi restate?', 'Are you staying?', 'giada-rinaldi'),
    s('Lui la guarda sorpreso che lei parli.', 'He looks at her, surprised that she speaks.'),
    s('Io no.', 'I am not.', 'ingegnere'),
    s('Ho una riunione a valle.', 'I have a meeting downhill.', 'ingegnere'),
    s('Sale, chiude, parte.', 'He gets in, closes, leaves.'),
    s('L\'auto alta prende la strada della diga senza esitare.', 'The high car takes the dam road without hesitating.'),
    s('Dieci minuti dopo, dalla stessa strada, arriva il rumore dell\'acqua che sale.', 'Ten minutes later, from the same road, comes the sound of rising water.'),
    s('La carreggiata si bagna, poi si copre.', 'The roadway gets wet, then covered.'),
    s('Tullio versa il caffè come ogni sera.', 'Tullio pours coffee as every evening.'),
    s('Vedi?', 'See?', 'tullio'),
    s('Le regole sono per chi abita.', 'The rules are for those who live here.', 'tullio'),
    s('Non per chi ha l\'auto giusta e il badge giusto.', 'Not for those with the right car and the right badge.', 'tullio'),
    s('Neri sputa a terra, lontano dai piedi di Elsa.', 'Neri spits on the ground, away from Elsa\'s feet.'),
    s('Sorride e paga.', 'He smiles and pays.', 'neri'),
    s('Poi se ne va sopra l\'acqua.', 'Then he leaves above the water.', 'neri'),
    s('Giada guarda la cartellina sul tavolino.', 'Giada looks at the folder on the little table.'),
    s('Nessuno la apre subito.', 'Nobody opens it at once.'),
    s('Aprirebbe una porta che loro tengono chiusa da anni.', 'It would open a door they have kept closed for years.'),
    s('Elsa la porta dentro comunque e la mette vicino al registro.', 'Elsa brings it inside anyway and puts it near the register.'),
    s('Non sopra.', 'Not on top.'),
    s('Vicino, come un oggetto pericoloso e utile.', 'Nearby, like a dangerous and useful object.'),
    s('Giada resta a guardare la strada diventata lago basso.', 'Giada stays watching the road become a shallow lake.'),
    s('L\'ingegnere ha portato un sorriso e una via d\'uscita a pagamento.', 'The engineer brought a smile and a paid exit.'),
    s('Mentre l\'ingegnere gira, Elsa sistema di nuovo un vaso.', 'While the engineer walks around, Elsa adjusts a pot again.'),
    s('Il gesto è automatico, da ispezione immaginaria.', 'The gesture is automatic, from an imaginary inspection.'),
    s('Giada lo nota e lo odia.', 'Giada notices it and hates it.'),
    s('Odia anche il sorriso dell\'uomo, troppo liscio.', 'She also hates the man\'s smile, too smooth.'),
    s('Un sorriso da riunione, non da strada bagnata.', 'A meeting smile, not a wet-road smile.'),
    s('Nella cartellina ci sono cifre alte e parole basse: opportunità, accompagnamento, chiusura ordinata.', 'In the folder there are high numbers and low words: opportunity, support, orderly closure.'),
    s('Giada legge solo le prime righe e chiude.', 'Giada reads only the first lines and closes it.'),
    s('Non vuole che i numeri le entrino in testa troppo presto.', 'She does not want the numbers in her head too soon.'),
    s('L\'ingegnere chiede a Tullio dell\'inverno passato.', 'The engineer asks Tullio about last winter.'),
    s('Tullio risponde con tre parole e uno sguardo lungo.', 'Tullio answers with three words and a long look.'),
    s('Freddo.', 'Cold.', 'tullio'),
    s('Come sempre.', 'As always.', 'tullio'),
    s('L\'uomo annuisce come se avesse ricevuto un rapporto completo.', 'The man nods as if he had received a full report.'),
    s('Prima di salire in auto controlla l\'orologio al polso.', 'Before getting into the car he checks the watch on his wrist.'),
    s('Conosce l\'ora dell\'acqua meglio di molti abitanti.', 'He knows water time better than many residents.'),
    s('Per questo parte in tempo.', 'That is why he leaves on time.'),
    s('Non perché rispetti la regola: perché la regola non lo riguarda.', 'Not because he respects the rule: because the rule does not apply to him.'),
    s('La riguarda solo se resta a piedi come gli altri.', 'It applies to him only if he stays on foot like the others.'),
    s('E lui non resta.', 'And he does not stay.'),
    s('Quando l\'acqua arriva, Giada prova a immaginare l\'auto alta già lontana, asciutta.', 'When the water arrives, Giada tries to imagine the high car already far away, dry.'),
    s('L\'immagine la irrita più del rumore della corrente.', 'The image irritates her more than the sound of the current.'),
    s('Neri dice che un giorno anche lui avrà un\'auto così.', 'Neri says that one day he too will have a car like that.'),
    s('Poi aggiunge: o una biglietteria vera.', 'Then he adds: or a real ticket office.', 'neri'),
    s('Elsa non commenta.', 'Elsa does not comment.'),
    s('Guarda solo la strada che non si può più attraversare.', 'She only looks at the road that can no longer be crossed.'),
    s('Ha anche portato la prova più chiara della giornata.', 'He also brought the clearest proof of the day.'),
    s('Collevento ha regole.', 'Collevento has rules.'),
    s('La compagnia ha eccezioni.', 'The company has exceptions.'),
    ],
    questions: [
    q('What does the engineer offer?', ['Compensation to move', 'Free train tickets', 'A festival'], 0, 'He talks about compensation for those who move.'),
    q('How does he leave at sunset?', ['In a high car', 'On foot through water', 'He stays the night'], 0, 'He leaves in the high car as water time arrives.'),
    q('Who are the evening water rules for?', ['Residents', 'Everyone including the engineer', 'Only tourists'], 0, 'Tullio says the rules are for those who live here.'),
    ],
  },

  {
    number: 16,
    title: 'Giada hates Elsa',
    titleIt: 'Giada odia Elsa',
    summary:
      'Giada confronts Elsa: the ready room, the wrong name, the staging. Elsa wanted Anna back, not a guest. The fight makes that clear.',
    facts: [
      'Giada confronts Elsa about being treated as Anna',
      'Elsa wanted Anna back, not a guest',
      'The ready room and register were for Anna\'s return',
      'The fight is about identity, not magic',
    ],
    locationIds: ['locanda-elsa'],
    characterIds: ['giada-rinaldi', 'elsa'],
    sentences: [
    s('Dopo cena la locanda è vuota di clienti.', 'After dinner the inn is empty of guests.'),
    s('C\'è solo Elsa che asciuga bicchieri e Giada che non aiuta.', 'There is only Elsa drying glasses and Giada who does not help.'),
    s('Il silenzio dura troppo.', 'The silence lasts too long.'),
    s('Giada lo rompe con una frase preparata male.', 'Giada breaks it with a badly prepared sentence.'),
    s('Tu non volevi un\'ospite.', 'You did not want a guest.', 'giada-rinaldi'),
    s('Elsa ferma il canovaccio.', 'Elsa stops the cloth.'),
    s('Volevi Anna.', 'You wanted Anna.', 'giada-rinaldi'),
    s('Elsa respira dal naso.', 'Elsa breathes through her nose.'),
    s('Non ricominciare.', 'Do not start again.', 'elsa'),
    s('Giada alza la voce, non troppo, abbastanza.', 'Giada raises her voice, not too much, enough.'),
    s('La stanza era già pronta.', 'The room was already ready.', 'giada-rinaldi'),
    s('Il registro aveva il suo nome con la data di oggi.', 'The register had her name with today\'s date.', 'giada-rinaldi'),
    s('Mi hai chiamata Anna sulla soglia.', 'You called me Anna on the threshold.', 'giada-rinaldi'),
    s('Hai tenuto la sua foto come un indizio da usare.', 'You kept her photo like a clue to use.', 'giada-rinaldi'),
    s('Elsa posa il bicchiere con troppa forza.', 'Elsa sets the glass down too hard.'),
    s('Tua madre è partita.', 'Your mother left.', 'elsa'),
    s('Ha lasciato buchi.', 'She left holes.', 'elsa'),
    s('Io ho riempito i buchi come potevo.', 'I filled the holes as I could.', 'elsa'),
    s('Non con me.', 'Not with me.', 'giada-rinaldi'),
    s('Non sono stucco.', 'I am not putty.', 'giada-rinaldi'),
    s('Non sono una seconda Anna da mettere nel letto fatto.', 'I am not a second Anna to put in the made bed.', 'giada-rinaldi'),
    s('Elsa arrossisce, non di vergogna sola: anche di rabbia.', 'Elsa blushes, not from shame alone: also from anger.'),
    s('Tu non sai cosa significa aspettare qualcuno che non scrive.', 'You do not know what it means to wait for someone who does not write.', 'elsa'),
    s('Aspettare un\'ispezione è una cosa.', 'Waiting for an inspection is one thing.', 'elsa'),
    s('Aspettare una ragazza che diceva «torno» è un\'altra.', 'Waiting for a girl who said "I\'ll come back" is another.', 'elsa'),
    s('Giada sente la foto di Anna nel taschino della felpa.', 'Giada feels Anna\'s photo in the hoodie pocket.'),
    s('Mia madre aveva diciassette anni.', 'My mother was seventeen.', 'giada-rinaldi'),
    s('Anche io.', 'Me too.', 'giada-rinaldi'),
    s('Questo non ti dà diritto sulla mia faccia.', 'That does not give you rights over my face.', 'giada-rinaldi'),
    s('Elsa fa un passo verso di lei.', 'Elsa takes a step toward her.'),
    s('Quando sei scesa dal treno ho visto una possibilità.', 'When you got off the train I saw a possibility.', 'elsa'),
    s('Non una persona.', 'Not a person.', 'giada-rinaldi'),
    s('Una possibilità.', 'A possibility.', 'giada-rinaldi'),
    s('Elsa chiude gli occhi un secondo.', 'Elsa closes her eyes a second.'),
    s('Sì.', 'Yes.', 'elsa'),
    s('Una possibilità.', 'A possibility.', 'elsa'),
    s('Volevo Anna, non un\'ospite.', 'I wanted Anna, not a guest.', 'elsa'),
    s('La confessione è netta.', 'The confession is clear.'),
    s('Non c\'è magia dentro.', 'There is no magic in it.'),
    s('C\'è soltanto bisogno, e bisogno fa danni.', 'There is only need, and need does damage.'),
    s('Giada trema alle mani.', 'Giada trembles in her hands.'),
    s('Allora smetti.', 'Then stop.', 'giada-rinaldi'),
    s('Smetti di preparare la mia stanza come un altare.', 'Stop preparing my room like an altar.', 'giada-rinaldi'),
    s('Smetti di usare il mio nome sbagliato.', 'Stop using my wrong name.', 'giada-rinaldi'),
    s('Smetti di lavare la piazza per farmi restare in una storia vecchia.', 'Stop washing the square to make me stay in an old story.', 'giada-rinaldi'),
    s('Elsa appoggia le mani sul bancone.', 'Elsa rests her hands on the counter.'),
    s('Se smetto, resta solo il vuoto.', 'If I stop, only the emptiness remains.', 'elsa'),
    s('Il vuoto c\'era già.', 'The emptiness was already there.', 'giada-rinaldi'),
    s('Tu ci hai messo me sopra, come un tappeto.', 'You put me on top of it, like a rug.', 'giada-rinaldi'),
    s('Le due donne si guardano senza tavolo in mezzo abbastanza largo.', 'The two women look at each other without a table wide enough between them.'),
    s('Fuori, lontano, l\'acqua della diga fa il suo rumore abituale.', 'Outside, far off, the dam water makes its usual sound.'),
    s('Dentro, la rabbia è più alta dell\'acqua.', 'Inside, the anger is higher than the water.'),
    s('Elsa parla più piano.', 'Elsa speaks more quietly.'),
    s('Non ti odio.', 'I do not hate you.', 'elsa'),
    s('Giada scuote la testa.', 'Giada shakes her head.'),
    s('Io adesso odio quello che hai fatto.', 'Right now I hate what you did.', 'giada-rinaldi'),
    s('Forse domani odierei meno.', 'Maybe tomorrow I would hate less.', 'giada-rinaldi'),
    s('Stasera no.', 'Tonight, no.', 'giada-rinaldi'),
    s('Elsa annuisce, accettando il colpo.', 'Elsa nods, accepting the blow.'),
    s('Dormi qui comunque.', 'Sleep here anyway.', 'elsa'),
    s('Non perché sei Anna.', 'Not because you are Anna.', 'elsa'),
    s('Perché fuori, di notte, la strada non perdona.', 'Because outside, at night, the road does not forgive.', 'elsa'),
    s('Giada vuole rifiutare per principio.', 'Giada wants to refuse on principle.'),
    s('Poi pensa all\'auto alta dell\'ingegnere e all\'acqua.', 'Then she thinks of the engineer\'s high car and the water.'),
    s('Il principio non tiene le gambe asciutte.', 'Principle does not keep legs dry.'),
    s('Va bene.', 'All right.', 'giada-rinaldi'),
    s('Dormo qui.', 'I sleep here.', 'giada-rinaldi'),
    s('Ma non sono tornata.', 'But I have not come back.', 'giada-rinaldi'),
    s('Non per te.', 'Not for you.', 'giada-rinaldi'),
    s('Elsa spegne la luce del bancone.', 'Elsa turns off the counter light.'),
    s('Lo so.', 'I know.', 'elsa'),
    s('Adesso lo so.', 'Now I know.', 'elsa'),
    s('Giada sale le scale senza dire buonanotte.', 'Giada goes up the stairs without saying good night.'),
    s('In camera la foto di Anna è ancora sul comodino.', 'In the room Anna\'s photo is still on the nightstand.'),
    s('Durante la lite Giada elenca anche le piccole cose.', 'During the fight Giada also lists the small things.'),
    s('Il caffè pronto al mattino come per qualcuno atteso.', 'Coffee ready in the morning as for someone expected.'),
    s('La stanza senza polvere, troppo perfetta per un\'ospite casuale.', 'The room without dust, too perfect for a chance guest.'),
    s('Il modo in cui Elsa la guarda quando tace.', 'The way Elsa looks at her when she is silent.'),
    s('Ogni dettaglio era una rete.', 'Every detail was a net.'),
    s('Elsa non nega i dettagli.', 'Elsa does not deny the details.'),
    s('Dice solo che l\'amore sbagliato non avvisa.', 'She only says that the wrong kind of love does not give notice.', 'elsa'),
    s('Giada rifiuta la parola amore per quella trappola.', 'Giada refuses the word love for that trap.'),
    s('Chiamalo bisogno, allora.', 'Call it need, then.', 'giada-rinaldi'),
    s('Il bisogno non mi rende Anna.', 'Need does not make me Anna.', 'giada-rinaldi'),
    s('Elsa si siede su una sedia bassa, all\'improvviso vecchia.', 'Elsa sits on a low chair, suddenly old.'),
    s('Hai ragione.', 'You are right.', 'elsa'),
    s('Volevo Anna.', 'I wanted Anna.', 'elsa'),
    s('Volevo chiudere un conto aperto da troppi anni.', 'I wanted to close an account open for too many years.', 'elsa'),
    s('Tu sei entrata in quel conto senza firmare.', 'You entered that account without signing.', 'elsa'),
    s('Giada resta in piedi.', 'Giada stays standing.'),
    s('Allora chiudi il conto senza di me.', 'Then close the account without me.', 'giada-rinaldi'),
    s('Chiudilo con una foto, con un nome, con il vuoto.', 'Close it with a photo, with a name, with the emptiness.', 'giada-rinaldi'),
    s('Non con una ragazza viva che deve andare a Trento.', 'Not with a living girl who has to go to Trento.', 'giada-rinaldi'),
    s('Elsa passa una mano sugli occhi.', 'Elsa passes a hand over her eyes.'),
    s('D\'accordo.', 'All right.', 'elsa'),
    s('Da domani ti chiamo solo Giada.', 'From tomorrow I will only call you Giada.', 'elsa'),
    s('Anche se la bocca sbaglia.', 'Even if the mouth slips.', 'elsa'),
    s('Giada accetta la promessa senza ringraziare.', 'Giada accepts the promise without thanking her.'),
    s('Le promesse, a Collevento, hanno una storia cattiva.', 'Promises, in Collevento, have a bad history.'),
    s('Però questa, almeno, nasce da una lite vera.', 'But this one, at least, is born from a real fight.'),
    s('E una lite vera è più onesta di una stanza già fatta.', 'And a real fight is more honest than a room already made up.'),
    s('Giada la volta a faccia in giù.', 'Giada turns it face down.'),
    s('Non per cancellare la madre.', 'Not to erase the mother.'),
    s('Per ricordare che stanotte ha vinto, almeno, il proprio nome.', 'To remember that tonight she won, at least, her own name.'),
    ],
    questions: [
    q('What did Elsa want?', ['Anna back, not a guest', 'Money from Giada', 'The engineer to stay'], 0, 'Elsa admits she wanted Anna, not a guest.'),
    q('What made Giada angry?', ['Being treated as Anna\'s return', 'Bad food', 'No phone signal'], 0, 'The fight is about identity and the ready room/register.'),
    q('Does Giada leave the inn that night?', ['No, she sleeps there', 'Yes, she walks the dam road', 'She goes with the engineer'], 0, 'She stays because the night road is unsafe, but keeps her name.'),
    ],
  },

];
