import { chapter, q, s, type StorySpec } from './pre-rome-helpers';

export const story03: StorySpec = {
  id: 'luca-prima-di-roma-03',
  title: 'At the supermarket',
  titleIt: 'Al supermercato',
  synopsis: 'Luca fa la spesa a Pietralba: lista, banco, prezzi e quantità.',
  characterIds: ['luca', 'marta', 'pina'],
  locationIds: ['casa-pietralba', 'cucina-pietralba', 'supermercato-pietralba'],
  chapters: [
    chapter({
      id: 'luca-prima-di-roma-03-01',
      number: 1,
      title: 'The list',
      titleIt: 'La lista',
      locationIds: ['casa-pietralba', 'cucina-pietralba'],
      characterIds: ['luca', 'marta'],
      primaryDomain: 'food',
      secondaryDomains: ['quantities'],
      summary: 'Marta gives Luca a shopping list with bread, milk, pasta, fruit, sugar, and two apples.',
      facts: [
        'Marta gives Luca the shopping list',
        'The list has bread, milk, pasta, fruit, and sugar',
        'Marta wants two apples',
        'Luca goes to the supermarket',
      ],
      paragraphs: [
        [
          s('s01', 'Marta è in cucina.', 'marta essere in cucina'),
          s('s02', 'Luca è in cucina con Marta.', 'luca essere in cucina con marta'),
          s('s03', 'Marta ha la lista.', 'marta avere la lista'),
          s('s04', 'Luca guarda la lista.', 'luca guardare la lista'),
          s('s05', 'Questa è la lista.', 'questo essere la lista', 'marta'),
          s('s06', 'Sulla lista c\'è pane.', 'sulla lista ce pane', 'marta'),
          s('s07', "C'è latte.", 'ce latte', 'marta'),
          s('s08', "C'è pasta.", 'ce pasta', 'marta'),
        ],
        [
          s('s09', "C'è frutta.", 'ce frutta', 'marta'),
          s('s10', "C'è anche zucchero.", 'ce anche zucchero', 'marta'),
          s('s11', 'Due mele.', 'due mela', 'marta'),
          s('s12', 'Un po\' di pane.', 'un poco di pane', 'marta'),
          s('s13', 'Luca ascolta Marta.', 'luca ascoltare marta'),
          s('s14', 'Luca prende la lista.', 'luca prendere la lista'),
          s('s15', 'Va bene mamma.', 'andare bene mamma', 'luca'),
          s('s16', 'Grazie mamma.', 'grazie mamma', 'luca'),
        ],
        [
          s('s17', 'Luca va al supermercato.', 'luca andare al supermercato'),
          s('s18', 'Oggi Luca compra pane.', 'oggi luca comprare pane'),
          s('s19', 'Compra latte e pasta.', 'comprare latte e pasta'),
          s('s20', 'Compra frutta e zucchero.', 'comprare frutta e zucchero'),
          s('s21', 'Il pane è sulla lista.', 'il pane essere sulla lista'),
          s('s22', 'Il latte è sulla lista.', 'il latte essere sulla lista'),
          s('s23', 'Due mele sono sulla lista.', 'due mela essere sulla lista'),
          s('s24', 'La lista è importante.', 'la lista essere importante'),
          s('s25', 'Luca guarda tutto sulla lista.', 'luca guardare tutto sulla lista'),
          s('s26', 'Adesso Luca è pronto.', 'adesso luca essere pronto'),
        ],
      ],
      questions: [
        q('lpr03-ch01-q01', 'direct', 'What is on the list?', ['Bread, milk, pasta, fruit, and sugar', 'Shoes and books', 'Tickets and keys'], 0, 'Pane, latte, pasta, frutta e zucchero.'),
        q('lpr03-ch01-q02', 'direct', 'How many apples does Marta want?', ['One', 'Two', 'Ten'], 1, 'Due mele.'),
        q('lpr03-ch01-q03', 'event', 'Where is Luca going?', ['To the supermarket', 'To Rome', 'To school'], 0, 'Luca va al supermercato.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-03-02',
      number: 2,
      title: 'At the counter',
      titleIt: 'Al banco',
      locationIds: ['supermercato-pietralba'],
      characterIds: ['luca', 'pina'],
      primaryDomain: 'ordering',
      secondaryDomains: ['food', 'social'],
      summary: 'Luca orders bread, cheese, and milk from Signora Pina at the counter.',
      facts: [
        'Luca is at the supermarket counter',
        'Signora Pina works at the counter',
        'Luca says vorrei and per favore',
        'Luca orders bread, cheese, and milk',
      ],
      paragraphs: [
        [
          s('s01', 'Luca è al supermercato.', 'luca essere al supermercato'),
          s('s02', 'Luca è al banco.', 'luca essere al banco'),
          s('s03', 'Signora Pina è al banco.', 'signora pina essere al banco'),
          s('s04', 'Buongiorno signora.', 'buongiorno signora', 'luca'),
          s('s05', 'Buongiorno Luca.', 'buongiorno luca', 'pina'),
          s('s06', 'Luca ha la lista.', 'luca avere la lista'),
          s('s07', 'Luca guarda la lista.', 'luca guardare la lista'),
          s('s08', 'Vorrei del pane per favore.', 'volere del pane per favore', 'luca'),
        ],
        [
          s('s09', 'Va bene.', 'andare bene', 'pina'),
          s('s10', 'Pina dà il pane.', 'pina dare il pane'),
          s('s11', 'Vorrei del formaggio.', 'volere del formaggio', 'luca'),
          s('s12', 'Questo formaggio?', 'questo formaggio', 'pina'),
          s('s13', 'Sì grazie.', 'si_yes grazie', 'luca'),
          s('s14', 'Pina dà il formaggio.', 'pina dare il formaggio'),
          s('s15', 'Vorrei del latte per favore.', 'volere del latte per favore', 'luca'),
          s('s16', 'Ecco il latte.', 'ecco il latte', 'pina'),
        ],
        [
          s('s17', 'Luca prende il latte.', 'luca prendere il latte'),
          s('s18', 'Altro?', 'altro', 'pina'),
          s('s19', 'No grazie.', 'no grazie', 'luca'),
          s('s20', 'Luca dice grazie.', 'luca dire grazie'),
          s('s21', 'Prego.', 'prego', 'pina'),
          s('s22', 'Luca guarda il pane.', 'luca guardare il pane'),
          s('s23', 'Luca guarda il formaggio.', 'luca guardare il formaggio'),
          s('s24', 'La lista è qui.', 'la lista essere qui'),
          s('s25', 'Adesso Luca guarda i prezzi.', 'adesso luca guardare il prezzo'),
        ],
      ],
      questions: [
        q('lpr03-ch02-q01', 'character', 'Who is at the counter?', ['Marta', 'Signora Pina', 'Paolo'], 1, 'Signora Pina è al banco.'),
        q('lpr03-ch02-q02', 'direct', 'What does Luca order first?', ['Bread', 'Wine', 'Pasta'], 0, 'Vorrei del pane per favore.'),
        q('lpr03-ch02-q03', 'direct', 'What else does Luca order?', ['Cheese and milk', 'Coffee and pizza', 'Apples only'], 0, 'Vorrei del formaggio e del latte.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-03-03',
      number: 3,
      title: 'How much is it?',
      titleIt: 'Quanto costa?',
      locationIds: ['supermercato-pietralba'],
      characterIds: ['luca', 'pina'],
      primaryDomain: 'prices',
      secondaryDomains: ['numbers'],
      summary: 'Luca asks prices. Bread is cheap, milk costs one euro fifty, and he chooses economical cheese.',
      facts: [
        'Bread costs two euros',
        'Milk costs one euro and fifty cents',
        'This cheese costs five euros and is too expensive',
        'Luca chooses the economical cheese',
      ],
      paragraphs: [
        [
          s('s01', 'Quanto costa il pane?', 'quanto costare il pane', 'luca'),
          s('s02', 'Il pane costa due euro.', 'il pane costare due euro', 'pina'),
          s('s03', 'Due euro.', 'due euro', 'luca'),
          s('s04', 'Quanto costa il latte?', 'quanto costare il latte', 'luca'),
          s('s05', 'Il latte costa un euro e cinquanta.', 'il latte costare un euro e cinquanta', 'pina'),
          s('s06', 'Un euro e cinquanta.', 'un euro e cinquanta', 'luca'),
          s('s07', 'Il latte non è caro.', 'il latte non essere caro', 'luca'),
          s('s08', 'Luca guarda i prezzi.', 'luca guardare il prezzo'),
        ],
        [
          s('s09', 'Quanto costa il formaggio?', 'quanto costare il formaggio', 'luca'),
          s('s10', 'Questo formaggio costa cinque euro.', 'questo formaggio costare cinque euro', 'pina'),
          s('s11', 'Cinque euro.', 'cinque euro', 'luca'),
          s('s12', 'È troppo caro.', 'essere troppo caro', 'luca'),
          s('s13', 'Quello formaggio è economico.', 'quello formaggio essere economico', 'pina'),
          s('s14', 'Quello è economico.', 'quello essere economico', 'luca'),
          s('s15', 'Prendo quello per favore.', 'prendere quello per favore', 'luca'),
          s('s16', 'Va bene.', 'andare bene', 'pina'),
        ],
        [
          s('s17', 'Pina dà il formaggio economico.', 'pina dare il formaggio economico'),
          s('s18', 'Luca prende il formaggio.', 'luca prendere il formaggio'),
          s('s19', 'Il pane costa poco.', 'il pane costare poco', 'luca'),
          s('s20', 'Il formaggio costa poco.', 'il formaggio costare poco', 'luca'),
          s('s21', 'Questo era troppo caro.', 'questo essere troppo caro', 'luca'),
          s('s22', 'Quello è meglio.', 'quello essere bene', 'luca'),
          s('s23', 'Grazie signora.', 'grazie signora', 'luca'),
          s('s24', 'Prego.', 'prego', 'pina'),
          s('s25', 'Luca guarda tutto al banco.', 'luca guardare tutto al banco'),
        ],
      ],
      questions: [
        q('lpr03-ch03-q01', 'direct', 'How much is the bread?', ['€2', '€5', '€10'], 0, 'Il pane costa due euro.'),
        q('lpr03-ch03-q02', 'direct', 'How much is the milk?', ['One euro and fifty cents', 'Five euros', 'Ten euros'], 0, 'Il latte costa un euro e cinquanta.'),
        q('lpr03-ch03-q03', 'inference', 'Which cheese does Luca choose?', ['The expensive one for five euros', 'The economical one', 'No cheese'], 1, 'Quello è economico. Prendo quello.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-03-04',
      number: 4,
      title: 'How much do I take?',
      titleIt: 'Quanto ne prendo?',
      locationIds: ['supermercato-pietralba'],
      characterIds: ['luca', 'pina'],
      primaryDomain: 'quantities',
      secondaryDomains: ['food', 'prices'],
      summary: 'Luca chooses quantities: a kilo of apples, a hectogram of cheese, a bottle of oil and milk, a pack of pasta.',
      facts: [
        'Luca takes one kilo of apples',
        'Luca takes one hectogram of cheese',
        'Luca takes a bottle of oil and a bottle of milk',
        'Luca takes a pack of pasta but forgets the sugar',
      ],
      paragraphs: [
        [
          s('s01', 'Quanto ne prendo?', 'quanto ne prendere', 'luca'),
          s('s02', 'Un chilo di mele.', 'un chilo di mela', 'pina'),
          s('s03', 'Luca prende un chilo di mele.', 'luca prendere un chilo di mela'),
          s('s04', 'Un etto di formaggio.', 'un etto di formaggio', 'luca'),
          s('s05', 'Va bene.', 'andare bene', 'pina'),
          s('s06', 'Pina dà un etto di formaggio.', 'pina dare un etto di formaggio'),
          s('s07', 'Una bottiglia di olio.', 'una bottiglia di olio', 'luca'),
          s('s08', 'Una bottiglia di latte.', 'una bottiglia di latte', 'luca'),
        ],
        [
          s('s09', 'Un pacco di pasta.', 'un pacco di pasta', 'luca'),
          s('s10', 'Luca prende il pacco di pasta.', 'luca prendere il pacco di pasta'),
          s('s11', 'Luca prende la bottiglia di olio.', 'luca prendere la bottiglia di olio'),
          s('s12', 'Luca prende la bottiglia di latte.', 'luca prendere la bottiglia di latte'),
          s('s13', 'I numeri sono sulla lista.', 'il numero essere sulla lista'),
          s('s14', 'Luca ascolta Pina.', 'luca ascoltare pina'),
          s('s15', 'Un chilo due etti.', 'un chilo due etto', 'pina'),
          s('s16', 'Luca guarda le mele.', 'luca guardare le mela'),
        ],
        [
          s('s17', 'Altro?', 'altro', 'pina'),
          s('s18', 'No grazie.', 'no grazie', 'luca'),
          s('s19', 'Luca guarda la lista.', 'luca guardare la lista'),
          s('s20', 'Pane latte pasta frutta.', 'pane latte pasta frutta', 'luca'),
          s('s21', 'Luca dimentica lo zucchero.', 'luca dimenticare lo zucchero'),
          s('s22', 'Lo zucchero non è qui.', 'lo zucchero non essere qui'),
          s('s23', 'Adesso la lista è piena.', 'adesso la lista essere pieno'),
          s('s24', 'Luca va al banco.', 'luca andare al banco'),
          s('s25', 'Tutto è pronto.', 'tutto essere pronto', 'luca'),
        ],
      ],
      questions: [
        q('lpr03-ch04-q01', 'direct', 'How many apples does Luca take?', ['One kilo', 'One bottle', 'One pack'], 0, 'Un chilo di mele.'),
        q('lpr03-ch04-q02', 'direct', 'What comes in a bottle?', ['Oil and milk', 'Pasta and cheese', 'Bread and sugar'], 0, 'Una bottiglia di olio e una bottiglia di latte.'),
        q('lpr03-ch04-q03', 'direct', 'How much cheese does Luca take?', ['One hectogram', 'Five kilos', 'Two packs'], 0, 'Un etto di formaggio.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-03-05',
      number: 5,
      title: 'Can I pay?',
      titleIt: 'Si può pagare?',
      locationIds: ['supermercato-pietralba'],
      characterIds: ['luca', 'pina'],
      primaryDomain: 'shopping',
      secondaryDomains: ['prices', 'social'],
      summary: 'Luca pays ten euros with cash and takes the receipt.',
      facts: [
        'Everything costs ten euros',
        'Luca pays with money',
        'Luca gets the receipt',
        'Luca says arrivederci to Pina',
      ],
      paragraphs: [
        [
          s('s01', 'Luca è al banco.', 'luca essere al banco'),
          s('s02', 'Si può pagare?', 'si_yes potere pagare', 'luca'),
          s('s03', 'Sì certo.', 'si_yes certo', 'pina'),
          s('s04', 'Quanto costa tutto?', 'quanto costare tutto', 'luca'),
          s('s05', 'Tutto costa dieci euro.', 'tutto costare dieci euro', 'pina'),
          s('s06', 'Dieci euro.', 'dieci euro', 'luca'),
          s('s07', 'Dieci euro va bene.', 'dieci euro andare bene', 'luca'),
          s('s08', 'Luca guarda i soldi.', 'luca guardare il soldi'),
        ],
        [
          s('s09', 'Luca paga con i soldi.', 'luca pagare con il soldi'),
          s('s10', 'Ecco dieci euro.', 'ecco dieci euro', 'luca'),
          s('s11', 'Grazie.', 'grazie', 'pina'),
          s('s12', "C'è lo scontrino?", 'ce lo scontrino', 'luca'),
          s('s13', 'Sì ecco lo scontrino.', 'si_yes ecco lo scontrino', 'pina'),
          s('s14', 'Luca prende lo scontrino.', 'luca prendere lo scontrino'),
          s('s15', 'Lo scontrino è importante.', 'lo scontrino essere importante'),
          s('s16', 'Luca può pagare.', 'luca potere pagare'),
        ],
        [
          s('s17', 'Luca guarda lo scontrino.', 'luca guardare lo scontrino'),
          s('s18', 'Il prezzo è dieci euro.', 'il prezzo essere dieci euro'),
          s('s19', 'Tutto è pronto.', 'tutto essere pronto', 'luca'),
          s('s20', 'La lista è quasi pronta.', 'la lista essere pronto', 'luca'),
          s('s21', 'Arrivederci signora.', 'arrivederci signora', 'luca'),
          s('s22', 'Arrivederci Luca.', 'arrivederci luca', 'pina'),
          s('s23', 'Luca esce dal supermercato.', 'luca uscire dal supermercato'),
          s('s24', 'Luca torna a casa.', 'luca tornare a casa'),
        ],
      ],
      questions: [
        q('lpr03-ch05-q01', 'direct', 'How much is everything?', ['€2', '€10', '€50'], 1, 'Tutto costa dieci euro.'),
        q('lpr03-ch05-q02', 'direct', 'How does Luca pay?', ['With money', 'With a phone', 'He does not pay'], 0, 'Luca paga con i soldi.'),
        q('lpr03-ch05-q03', 'direct', 'What does Luca ask for after paying?', ['The receipt', 'More cheese', 'A new list'], 0, "C'è lo scontrino?"),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-03-06',
      number: 6,
      title: 'Something is missing',
      titleIt: 'Manca qualcosa',
      locationIds: ['casa-pietralba', 'cucina-pietralba', 'supermercato-pietralba'],
      characterIds: ['luca', 'marta', 'pina'],
      primaryDomain: 'shopping',
      secondaryDomains: ['likes', 'food'],
      summary: 'At home Marta sees sugar is missing. Luca goes back to the shop. He likes apples but not oil.',
      facts: [
        'Sugar is missing at home',
        'Luca goes back to the supermarket',
        'Pina gives Luca the sugar',
        'Luca likes apples but not oil',
      ],
      paragraphs: [
        [
          s('s01', 'Luca è a casa.', 'luca essere a casa'),
          s('s02', 'Luca è in cucina.', 'luca essere in cucina'),
          s('s03', 'Marta guarda la lista.', 'marta guardare la lista'),
          s('s04', 'Marta guarda tutto.', 'marta guardare tutto'),
          s('s05', 'Manca lo zucchero.', 'mancare lo zucchero', 'marta'),
          s('s06', 'Lo zucchero non c\'è.', 'lo zucchero non ce', 'marta'),
          s('s07', 'Scusa mamma.', 'scusa mamma', 'luca'),
          s('s08', 'Luca torna al supermercato.', 'luca tornare al supermercato'),
        ],
        [
          s('s09', 'Luca è al banco.', 'luca essere al banco'),
          s('s10', 'Scusa signora.', 'scusa signora', 'luca'),
          s('s11', 'Manca lo zucchero.', 'mancare lo zucchero', 'luca'),
          s('s12', 'Vorrei lo zucchero per favore.', 'volere lo zucchero per favore', 'luca'),
          s('s13', 'Ecco lo zucchero.', 'ecco lo zucchero', 'pina'),
          s('s14', 'Luca prende lo zucchero.', 'luca prendere lo zucchero'),
          s('s15', 'Grazie signora.', 'grazie signora', 'luca'),
          s('s16', 'Prego.', 'prego', 'pina'),
        ],
        [
          s('s17', 'A Luca piacciono le mele.', 'a luca piacere le mela'),
          s('s18', 'A Luca non piace l\'olio.', 'a luca non piacere olio'),
          s('s19', 'Ma lo zucchero va bene.', 'ma lo zucchero andare bene', 'luca'),
          s('s20', 'Luca torna a casa.', 'luca tornare a casa'),
          s('s21', 'Marta guarda lo zucchero.', 'marta guardare lo zucchero'),
          s('s22', 'Adesso la lista è pronta.', 'adesso la lista essere pronto'),
          s('s23', 'Tutto è qui.', 'tutto essere qui'),
          s('s24', 'Manca qualcosa?', 'mancare altro', 'marta'),
          s('s25', 'No tutto è pronto.', 'no tutto essere pronto', 'luca'),
        ],
      ],
      questions: [
        q('lpr03-ch06-q01', 'direct', 'What is missing at home?', ['Sugar', 'Milk', 'Bread'], 0, 'Manca lo zucchero.'),
        q('lpr03-ch06-q02', 'direct', 'What does Luca like?', ['Apples', 'Oil', 'The receipt'], 0, 'A Luca piacciono le mele.'),
        q('lpr03-ch06-q03', 'event', 'What does Luca do when sugar is missing?', ['He goes back to the supermarket', 'He throws away the list', 'He goes to Rome'], 0, 'Luca torna al supermercato.'),
      ],
    }),
  ],
};
