import { chapter, q, s, type StorySpec } from './pre-rome-helpers';

export const story04: StorySpec = {
  id: 'luca-prima-di-roma-04',
  title: 'Around town',
  titleIt: 'In paese',
  synopsis: 'Luca si muove per Pietralba: piazza, direzioni, tempo e autobus.',
  characterIds: ['luca', 'davide', 'franco'],
  locationIds: [
    'pietralba',
    'piazza-pietralba',
    'via-nazionale-pietralba',
    'farmacia-pietralba',
    'bar-franco',
    'parco-pietralba',
    'fermata-bus-pietralba',
    'stazione-pietralba',
  ],
  chapters: [
    chapter({
      id: 'luca-prima-di-roma-04-01',
      number: 1,
      title: 'Where is the square?',
      titleIt: "Dov'è la piazza?",
      locationIds: ['pietralba', 'piazza-pietralba', 'via-nazionale-pietralba', 'farmacia-pietralba', 'parco-pietralba', 'bar-franco'],
      characterIds: ['luca', 'davide'],
      primaryDomain: 'places',
      secondaryDomains: ['descriptions'],
      summary: 'Luca arrives in Pietralba and Davide names the town places: piazza, street, pharmacy, park, bar.',
      facts: ['Luca is in Pietralba', 'The piazza is in the center', 'The pharmacy is on Via Nazionale', 'Bar da Franco is near the piazza'],
      paragraphs: [
        [
          s('s01', 'Luca è a Pietralba.', 'luca essere a pietralba'),
          s('s02', 'Oggi Luca esce in paese.', 'oggi luca uscire in paese'),
          s('s03', 'Luca cammina verso la piazza.', 'luca camminare verso la piazza'),
          s('s04', 'Davide è in piazza.', 'davide essere in piazza'),
          s('s05', 'Ciao Davide.', 'ciao davide', 'luca'),
          s('s06', 'Ciao Luca.', 'ciao luca', 'davide'),
          s('s07', 'La piazza è grande.', 'la piazza essere grande', 'davide'),
          s('s08', 'La piazza è al centro.', 'la piazza essere al centro', 'davide'),
          s('s09', 'Pietralba è un paese piccolo.', 'pietralba essere un paese piccolo'),
          s('s10', 'Il paese è tranquillo e bello.', 'il paese essere tranquillo e bello'),
        ],
        [
          s('s11', "Dov'è la farmacia?", 'dove la farmacia', 'luca'),
          s('s12', 'La farmacia è in Via Nazionale.', 'la farmacia essere in via nazionale', 'davide'),
          s('s13', 'Via Nazionale è una strada.', 'via nazionale essere una strada', 'davide'),
          s('s14', 'La strada va al centro.', 'la strada andare al centro', 'davide'),
          s('s15', 'La farmacia non è lontana.', 'la farmacia non essere lontano', 'davide'),
          s('s16', "Dov'è il parco?", 'dove il parco', 'luca'),
          s('s17', 'Il parco è vicino alla piazza.', 'il parco essere vicino alla piazza', 'davide'),
          s('s18', 'Il parco è piccolo ma bello.', 'il parco essere piccolo ma bello', 'davide'),
          s('s19', "Dov'è il bar?", 'dove il bar', 'luca'),
          s('s20', 'Il bar è di Franco.', 'il bar essere di franco', 'davide'),
        ],
        [
          s('s21', 'Il bar è accanto alla piazza.', 'il bar essere accanto alla piazza', 'davide'),
          s('s22', 'Franco lavora al bar ogni giorno.', 'franco lavorare al bar ogni giorno', 'davide'),
          s('s23', 'Luca deve andare alla farmacia.', 'luca dovere andare alla farmacia'),
          s('s24', 'Poi Luca incontra Davide di nuovo.', 'poi luca incontrare davide di nuovo'),
          s('s25', 'Prima la farmacia.', 'prima la farmacia', 'luca'),
          s('s26', 'Va bene.', 'andare bene', 'davide'),
          s('s27', 'Davide aspetta qui in piazza.', 'davide aspettare qui in piazza', 'davide'),
          s('s28', 'Luca conosce bene Davide.', 'luca conoscere bene davide'),
          s('s29', 'Il paese ha una piazza e un parco.', 'il paese avere una piazza e un parco'),
          s('s30', 'A Pietralba ci sono pochi negozi.', 'a pietralba ci essere poco negozio', 'davide'),
          s('s31', 'La farmacia apre presto.', 'la farmacia aprire presto', 'davide'),
          s('s32', 'Luca va verso Via Nazionale.', 'luca andare verso via nazionale'),
          s('s33', 'Il bar apre tutti i giorni.', 'il bar aprire tutto il giorno', 'davide'),
        ],
      ],
      questions: [
        q('lpr04-ch01-q01', 'direct', 'Where is the pharmacy?', ['On Via Nazionale', 'In Rome', 'At the train station'], 0, 'La farmacia è in Via Nazionale.'),
        q('lpr04-ch01-q02', 'direct', 'Where is the bar?', ['Far from the piazza', 'Next to the piazza', 'Underground'], 1, 'Il bar è accanto alla piazza.'),
        q('lpr04-ch01-q03', 'direct', 'What must Luca do first?', ['Go to the pharmacy', 'Take a train to Rome', 'Go home'], 0, 'Prima la farmacia.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-04-02',
      number: 2,
      title: 'Right and left',
      titleIt: 'A destra, a sinistra',
      locationIds: ['piazza-pietralba', 'via-nazionale-pietralba', 'farmacia-pietralba'],
      characterIds: ['luca', 'davide'],
      primaryDomain: 'directions',
      secondaryDomains: ['places'],
      summary: 'Davide gives directions to the pharmacy: straight on Via Nazionale, then right.',
      facts: ['Go straight on Via Nazionale', 'The pharmacy is on the right', 'The park is on the left', 'Luca reaches the pharmacy'],
      paragraphs: [
        [
          s('s01', 'Luca vuole la farmacia.', 'luca volere la farmacia'),
          s('s02', 'Come arrivo alla farmacia?', 'come arrivare alla farmacia', 'luca'),
          s('s03', 'Vai dritto.', 'andare dritto', 'davide'),
          s('s04', 'Vai in Via Nazionale.', 'andare in via nazionale', 'davide'),
          s('s05', 'Poi vai a destra.', 'poi andare a destra', 'davide'),
          s('s06', 'La farmacia è a destra.', 'la farmacia essere a destra', 'davide'),
          s('s07', 'Il parco è a sinistra.', 'il parco essere a sinistra', 'davide'),
          s('s08', 'Non andare a sinistra.', 'non andare a sinistra', 'davide'),
          s('s09', 'La farmacia è vicina.', 'la farmacia essere vicino', 'davide'),
          s('s10', 'Non è lontano.', 'non essere lontano', 'davide'),
        ],
        [
          s('s11', 'Va bene.', 'andare bene', 'luca'),
          s('s12', 'Grazie Davide.', 'grazie davide', 'luca'),
          s('s13', 'Luca va dritto.', 'luca andare dritto'),
          s('s14', 'Luca cammina in Via Nazionale.', 'luca camminare in via nazionale'),
          s('s15', 'La strada è lunga e dritta.', 'la strada essere lungo e dritto'),
          s('s16', 'A sinistra c\'è il parco.', 'a sinistra ce il parco'),
          s('s17', 'Luca non va a sinistra.', 'luca non andare a sinistra'),
          s('s18', 'Luca va a destra.', 'luca andare a destra'),
          s('s19', 'Cammina piano.', 'camminare piano', 'luca'),
          s('s20', 'La strada ha negozi.', 'la strada avere negozio'),
        ],
        [
          s('s21', 'Ecco la farmacia.', 'ecco la farmacia'),
          s('s22', 'La farmacia è qui.', 'la farmacia essere qui', 'luca'),
          s('s23', 'La farmacia è davanti a Luca.', 'la farmacia essere davanti a luca'),
          s('s24', 'Dietro c\'è la strada.', 'dietro ce la strada'),
          s('s25', 'Luca entra in farmacia.', 'luca entrare in farmacia'),
          s('s26', 'Compra una cosa in farmacia.', 'comprare una cosa in farmacia'),
          s('s27', 'Ora Luca cerca Davide.', 'ora luca cercare davide'),
          s('s28', 'A destra è facile.', 'a destra essere facile', 'luca'),
          s('s29', 'Luca esce dalla farmacia.', 'luca uscire dalla farmacia'),
          s('s30', 'Torna verso la piazza.', 'tornare verso la piazza'),
          s('s31', 'Davide aspetta in piazza.', 'davide aspettare in piazza'),
          s('s32', 'Luca vede la piazza davanti.', 'luca vedere la piazza davanti'),
          s('s33', 'Luca cammina verso Davide.', 'luca camminare verso davide'),
          s('s34', 'La farmacia è dietro ora.', 'la farmacia essere dietro ora'),
          s('s35', 'Luca e Davide si vedono.', 'luca e davide si vedere'),
          s('s36', 'Davide sorride in piazza.', 'davide sorridere in piazza'),
        ],
      ],
      questions: [
        q('lpr04-ch02-q01', 'direct', 'How does Davide tell Luca to start?', ['Go straight', 'Take the train', 'Go home'], 0, 'Vai dritto.'),
        q('lpr04-ch02-q02', 'direct', 'Where is the pharmacy?', ['On the left', 'On the right', 'Underground'], 1, 'La farmacia è a destra.'),
        q('lpr04-ch02-q03', 'direct', 'Does Luca reach the pharmacy?', ['Yes', 'No', 'He goes to Rome'], 0, 'Ecco la farmacia. Luca entra in farmacia.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-04-03',
      number: 3,
      title: 'What’s the weather like?',
      titleIt: 'Che tempo fa?',
      locationIds: ['piazza-pietralba', 'parco-pietralba', 'farmacia-pietralba'],
      characterIds: ['luca', 'davide'],
      primaryDomain: 'weather',
      secondaryDomains: ['descriptions'],
      summary: 'After the pharmacy Luca meets Davide. Today it is sunny and warm; they talk about rain and cold.',
      facts: ['Today it is sunny and warm', 'It is not raining now', 'Sometimes it rains in Pietralba and then it is cold'],
      paragraphs: [
        [
          s('s01', 'Luca esce dalla farmacia.', 'luca uscire dalla farmacia'),
          s('s02', 'Luca e Davide sono in piazza.', 'luca e davide essere in piazza'),
          s('s03', 'Che tempo fa oggi?', 'che tempo fare oggi', 'luca'),
          s('s04', "C'è il sole.", 'ce il sole', 'davide'),
          s('s05', 'Fa caldo.', 'fare caldo', 'davide'),
          s('s06', 'Oggi non piove.', 'oggi non piovere'),
          s('s07', 'Il tempo è bello.', 'il tempo essere bello', 'davide'),
          s('s08', 'Luca guarda il sole.', 'luca guardare il sole'),
          s('s09', 'Il sole è forte.', 'il sole essere forte', 'davide'),
          s('s10', 'Luca ha caldo.', 'luca avere caldo', 'luca'),
        ],
        [
          s('s11', 'A Pietralba a volte piove.', 'a pietralba a volta piovere', 'davide'),
          s('s12', 'Quando piove fa freddo.', 'quando piovere fare freddo', 'davide'),
          s('s13', 'Oggi non fa freddo.', 'oggi non fare freddo', 'luca'),
          s('s14', 'Il tempo non è nuvoloso.', 'il tempo non essere nuvoloso', 'davide'),
          s('s15', 'Il tempo è bello e chiaro.', 'il tempo essere bello e chiaro', 'davide'),
          s('s16', 'Davide è contento.', 'davide essere contento'),
          s('s17', 'Con il sole fa caldo.', 'con il sole fare caldo'),
          s('s18', 'Che tempo bello.', 'che tempo bello', 'luca'),
          s('s19', 'Oggi non fa freddo.', 'oggi non fare freddo', 'davide'),
          s('s20', 'La piazza è al sole.', 'la piazza essere al sole'),
        ],
        [
          s('s21', 'Andiamo al parco.', 'andare al parco', 'davide'),
          s('s22', 'Il parco è vicino.', 'il parco essere vicino', 'davide'),
          s('s23', 'Al parco c\'è il sole.', 'al parco ce il sole'),
          s('s24', 'Fa caldo anche al parco.', 'fare caldo anche al parco'),
          s('s25', 'Luca e Davide camminano.', 'luca e davide camminare'),
          s('s26', 'Quando piove restiamo a casa.', 'quando piovere restare a casa', 'davide'),
          s('s27', 'Oggi camminiamo al parco.', 'oggi camminare al parco', 'davide'),
          s('s28', 'Oggi il tempo è diverso.', 'oggi il tempo essere diverso', 'luca'),
          s('s29', 'Il parco è bello e caldo.', 'il parco essere bello e caldo'),
          s('s30', 'Luca è contento.', 'luca essere contento', 'luca'),
          s('s31', 'Il sole non va via.', 'il sole non andare via', 'davide'),
          s('s32', 'Fa caldo in piazza e al parco.', 'fare caldo in piazza e al parco'),
          s('s33', 'Oggi non piove.', 'oggi non piovere', 'davide'),
          s('s34', 'Il tempo è bello.', 'il tempo essere bello', 'davide'),
          s('s35', 'Luca e Davide sono felici.', 'luca e davide essere felice'),
        ],
      ],
      questions: [
        q('lpr04-ch03-q01', 'direct', 'What is the weather like today?', ['Sunny and warm', 'Rainy and cold', 'Snowy and icy'], 0, "C'è il sole. Fa caldo."),
        q('lpr04-ch03-q02', 'direct', 'Is it raining now?', ['Yes', 'No', 'Only in Rome'], 1, 'Oggi non piove.'),
        q('lpr04-ch03-q03', 'inference', 'When does it feel cold in Pietralba?', ['When it rains', 'When it is sunny', 'At night only'], 0, 'Quando piove fa freddo.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-04-04',
      number: 4,
      title: 'The seasons',
      titleIt: 'Le stagioni',
      locationIds: ['parco-pietralba', 'piazza-pietralba'],
      characterIds: ['luca', 'davide'],
      primaryDomain: 'seasons',
      secondaryDomains: ['weather'],
      summary: 'It is spring today. They name all four seasons and typical weather for each.',
      facts: ['It is spring now', 'Summer is hot', 'Autumn can be rainy', 'Winter is cold'],
      paragraphs: [
        [
          s('s01', 'Oggi è primavera.', 'oggi essere primavera', 'davide'),
          s('s02', 'In primavera c\'è il sole.', 'in primavera ce il sole', 'davide'),
          s('s03', 'Adesso è primavera a Pietralba.', 'adesso essere primavera a pietralba'),
          s('s04', 'La primavera è bella.', 'la primavera essere bello', 'luca'),
          s('s05', 'A Luca piace la primavera.', 'a luca piacere la primavera', 'luca'),
          s('s06', 'Le stagioni sono quattro.', 'le stagione essere quattro', 'davide'),
          s('s07', 'Primavera estate autunno inverno.', 'primavera estate autunno inverno', 'davide'),
          s('s08', 'Ogni stagione ha un tempo.', 'ogni stagione avere un tempo', 'davide'),
          s('s09', 'Ogni stagione è diversa.', 'ogni stagione essere diverso', 'davide'),
          s('s10', 'Luca impara le stagioni.', 'luca imparare le stagione'),
        ],
        [
          s('s11', 'In estate fa molto caldo.', 'in estate fare molto caldo', 'luca'),
          s('s12', "L'estate è calda.", 'estate essere caldo', 'luca'),
          s('s13', "A Davide piace l'estate.", 'a davide piacere estate', 'davide'),
          s('s14', 'In autunno a volte piove.', 'in autunno a volta piovere', 'davide'),
          s('s15', 'In autunno il tempo è nuvoloso.', 'in autunno il tempo essere nuvoloso', 'davide'),
          s('s16', 'In inverno fa freddo.', 'in inverno fare freddo', 'luca'),
          s('s17', "L'inverno è freddo.", 'inverno essere freddo', 'luca'),
          s('s18', 'In inverno non c\'è il sole.', 'in inverno non ce il sole', 'davide'),
          s('s19', 'In inverno fa molto freddo.', 'in inverno fare molto freddo', 'davide'),
          s('s20', 'In estate non piove molto.', 'in estate non piovere molto', 'luca'),
        ],
        [
          s('s21', 'Oggi il tempo è di primavera.', 'oggi il tempo essere di primavera'),
          s('s22', 'Fa caldo ma non troppo.', 'fare caldo ma non troppo', 'luca'),
          s('s23', 'Non piove oggi.', 'non piovere oggi', 'davide'),
          s('s24', 'Luca e Davide sono al parco.', 'luca e davide essere al parco'),
          s('s25', 'Il parco è bello.', 'il parco essere bello', 'davide'),
          s('s26', 'In primavera il parco è bello.', 'in primavera il parco essere bello', 'davide'),
          s('s27', 'Domani forse piove.', 'domani forse piovere', 'davide'),
          s('s28', 'Ma oggi è primavera.', 'ma oggi essere primavera', 'luca'),
          s('s29', 'Il sole è di primavera.', 'il sole essere di primavera', 'davide'),
          s('s30', 'A Luca piace questa stagione.', 'a luca piacere questo stagione', 'luca'),
          s('s31', 'Le quattro stagioni sono diverse.', 'le quattro stagione essere diverso', 'davide'),
          s('s32', 'Oggi non fa freddo.', 'oggi non fare freddo', 'luca'),
          s('s33', 'La primavera ha il sole.', 'la primavera avere il sole', 'davide'),
        ],
      ],
      questions: [
        q('lpr04-ch04-q01', 'direct', 'What season is it now?', ['Winter', 'Spring', 'Autumn'], 1, 'Oggi è primavera.'),
        q('lpr04-ch04-q02', 'direct', 'What is summer like?', ['Very hot', 'Very cold', 'Always raining'], 0, 'In estate fa molto caldo.'),
        q('lpr04-ch04-q03', 'direct', 'How many seasons do they name?', ['Two', 'Four', 'Twelve'], 1, 'Primavera estate autunno inverno.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-04-05',
      number: 5,
      title: 'The bus',
      titleIt: "L'autobus",
      locationIds: ['fermata-bus-pietralba', 'via-nazionale-pietralba'],
      characterIds: ['luca', 'davide'],
      primaryDomain: 'transportation',
      secondaryDomains: ['schedules', 'clock'],
      summary: 'At the bus stop Luca and Davide choose to wait for the ten o\'clock bus and buy a ticket.',
      facts: ['The bus stop is on Via Nazionale', 'An early bus is not the right one', 'They wait for the bus at 10:00', 'Luca needs a ticket'],
      paragraphs: [
        [
          s('s01', 'Luca e Davide vanno alla fermata.', 'luca e davide andare alla fermata'),
          s('s02', 'La fermata è in Via Nazionale.', 'la fermata essere in via nazionale', 'davide'),
          s('s03', "Dov'è l'autobus?", 'dove autobus', 'luca'),
          s('s04', 'Guarda l\'orario.', 'guardare orario', 'davide'),
          s('s05', "C'è un autobus alle nove.", 'ce un autobus alle nove', 'davide'),
          s('s06', 'Ma non va al parco.', 'ma non andare al parco', 'davide'),
          s('s07', "L'autobus giusto è alle dieci.", 'autobus giusto essere alle dieci', 'davide'),
          s('s08', 'Sono le nove e mezzo.', 'essere le nove e mezzo'),
          s('s09', 'Aspettiamo ancora.', 'aspettare ancora', 'davide'),
          s('s10', 'Luca legge l\'orario.', 'luca leggere orario'),
        ],
        [
          s('s11', 'Aspettiamo.', 'aspettare', 'davide'),
          s('s12', 'Luca vuole aspettare.', 'luca volere aspettare', 'luca'),
          s('s13', 'Non prendiamo l\'autobus delle nove.', 'non prendere autobus delle nove', 'luca'),
          s('s14', "C'è un biglietto?", 'ce un biglietto', 'luca'),
          s('s15', 'Sì il biglietto è importante.', 'si_yes il biglietto essere importante', 'davide'),
          s('s16', 'Luca compra un biglietto.', 'luca comprare un biglietto'),
          s('s17', 'Il biglietto costa poco.', 'il biglietto costare poco', 'davide'),
          s('s18', 'Aspettiamo alla fermata.', 'aspettare alla fermata', 'davide'),
          s('s19', 'La fermata è vicino al parco.', 'la fermata essere vicino al parco', 'davide'),
          s('s20', 'Oggi fa caldo.', 'oggi fare caldo'),
          s('s21', 'Davide guarda l\'orario con Luca.', 'davide guardare orario con luca'),
          s('s22', 'Alle nove passa un autobus.', 'alle nove passare un autobus', 'davide'),
        ],
        [
          s('s23', 'Sono le dieci.', 'essere le dieci'),
          s('s24', "Ecco l'autobus.", 'ecco autobus'),
          s('s25', "L'orario dice dieci.", 'orario dire dieci', 'davide'),
          s('s26', 'Luca prende l\'autobus.', 'luca prendere autobus'),
          s('s27', 'Ha il biglietto.', 'avere il biglietto', 'luca'),
          s('s28', "L'autobus va al parco.", 'autobus andare al parco', 'davide'),
          s('s29', 'Luca e Davide entrano.', 'luca e davide entrare'),
          s('s30', 'Bene aspettare.', 'bene aspettare', 'luca'),
          s('s31', 'Dieci è l\'orario giusto.', 'dieci essere orario giusto', 'davide'),
          s('s32', 'L\'autobus parte.', 'autobus partire'),
          s('s33', 'Luca ha il biglietto.', 'luca avere il biglietto'),
          s('s34', 'Davide sorride.', 'davide sorridere'),
          s('s35', 'La fermata resta dietro.', 'la fermata restare dietro'),
          s('s36', 'Il parco è vicino.', 'il parco essere vicino', 'davide'),
          s('s37', 'Il biglietto è importante.', 'il biglietto essere importante'),
          s('s38', 'Sono le dieci.', 'essere le dieci', 'davide'),
          s('s39', "L'orario è giusto.", 'orario essere giusto', 'luca'),
        ],
      ],
      questions: [
        q('lpr04-ch05-q01', 'direct', 'Which bus do they take?', ['The nine o\'clock bus', 'The ten o\'clock bus', 'No bus'], 1, "L'autobus giusto è alle dieci."),
        q('lpr04-ch05-q02', 'direct', 'What does Luca need for the bus?', ['A ticket', 'A suitcase', 'A map of Rome'], 0, 'Il biglietto è importante.'),
        q('lpr04-ch05-q03', 'direct', 'Why do they wait?', ['The nine bus does not go to the park', 'It is raining', 'The station is closed'], 0, 'Ma non va al parco.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-04-06',
      number: 6,
      title: 'We are lost',
      titleIt: 'Siamo persi',
      locationIds: ['piazza-pietralba', 'bar-franco', 'via-nazionale-pietralba'],
      characterIds: ['luca', 'franco', 'davide'],
      primaryDomain: 'directions',
      secondaryDomains: ['social', 'places'],
      summary: 'Luca gets lost after the bus and asks Franco at the bar for directions to Davide.',
      facts: ['Luca is lost', 'Franco is at the bar', 'Davide is at the bar', 'Franco gives directions with near and far'],
      paragraphs: [
        [
          s('s01', "Luca esce dall'autobus.", 'luca uscire autobus'),
          s('s02', 'Ma Davide non è qui.', 'ma davide non essere qui'),
          s('s03', 'Luca non sa dove è Davide.', 'luca non sapere dove essere davide'),
          s('s04', 'Luca non sa.', 'luca non sapere'),
          s('s05', 'Franco è qui.', 'franco essere qui'),
          s('s06', 'Scusa.', 'scusa', 'luca'),
          s('s07', "Dov'è Davide?", 'dove davide', 'luca'),
          s('s08', 'Davide è al bar.', 'davide essere al bar', 'franco'),
          s('s09', 'Franco lavora al bar.', 'franco lavorare al bar'),
          s('s10', "Dov'è il bar?", 'dove il bar', 'luca'),
        ],
        [
          s('s11', 'Il bar non è lontano.', 'il bar non essere lontano', 'franco'),
          s('s12', 'Vai dritto e poi a sinistra.', 'andare dritto e poi a sinistra', 'franco'),
          s('s13', 'Il bar è vicino.', 'il bar essere vicino', 'franco'),
          s('s14', 'Non è lontano.', 'non essere lontano', 'franco'),
          s('s15', 'La piazza è lontana da qui.', 'la piazza essere lontano da qui', 'franco'),
          s('s16', 'Il bar è davanti al parco.', 'il bar essere davanti al parco', 'franco'),
          s('s17', 'Dietro il bar c\'è Via Nazionale.', 'dietro il bar ce via nazionale', 'franco'),
          s('s18', 'Franco è gentile.', 'franco essere gentile', 'luca'),
          s('s19', 'Parla piano a Luca.', 'parlare piano a luca', 'franco'),
          s('s20', 'Il bar è accanto al parco.', 'il bar essere accanto al parco', 'franco'),
        ],
        [
          s('s21', 'Grazie Franco.', 'grazie franco', 'luca'),
          s('s22', 'Luca va dritto.', 'luca andare dritto'),
          s('s23', 'Luca va a sinistra.', 'luca andare a sinistra'),
          s('s24', 'Ecco il bar.', 'ecco il bar'),
          s('s25', 'Davide è accanto al bar.', 'davide essere accanto al bar', 'franco'),
          s('s26', 'Ciao Luca.', 'ciao luca', 'davide'),
          s('s27', 'Sono qui.', 'essere qui', 'luca'),
          s('s28', 'Ecco Davide.', 'ecco davide', 'luca'),
          s('s29', 'Luca e Davide sono contenti.', 'luca e davide essere contento'),
          s('s30', 'Franco sorride dal bar.', 'franco sorridere dal bar'),
          s('s31', 'Il bar è vicino al parco.', 'il bar essere vicino al parco', 'franco'),
          s('s32', 'Luca dice grazie di nuovo.', 'luca dire grazie di nuovo', 'luca'),
          s('s33', 'Luca cammina verso il bar.', 'luca camminare verso il bar'),
          s('s34', 'Vede il bar davanti.', 'vedere il bar davanti', 'luca'),
          s('s35', 'Ora Luca sa.', 'ora luca sapere', 'luca'),
          s('s36', 'Davide aspetta fuori dal bar.', 'davide aspettare fuori dal bar'),
        ],
      ],
      questions: [
        q('lpr04-ch06-q01', 'direct', 'Who helps Luca find Davide?', ['Franco', 'A stranger from Rome', 'Marta'], 0, 'Franco gives directions at the bar.'),
        q('lpr04-ch06-q02', 'direct', 'Where is Davide?', ['At the bar', 'At the pharmacy', 'On a Rome train'], 0, 'Davide è al bar.'),
        q('lpr04-ch06-q03', 'direct', 'What directions does Franco give?', ['Straight then left', 'Take a plane', 'Go to Rome Termini'], 0, 'Vai dritto e poi a sinistra.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-04-07',
      number: 7,
      title: 'At the station',
      titleIt: 'In stazione',
      locationIds: ['stazione-pietralba'],
      characterIds: ['luca', 'davide'],
      primaryDomain: 'transportation',
      secondaryDomains: ['places', 'schedules'],
      summary: 'Luca and Davide visit Pietralba station, check the timetable and platform. Luca does not leave for Rome today.',
      facts: ['Pietralba has a local station', 'There is a train at 11:00 on platform one', 'Luca does not board a Rome train today', 'One day Luca will take the train but not today'],
      paragraphs: [
        [
          s('s01', 'Luca e Davide vanno in stazione.', 'luca e davide andare in stazione'),
          s('s02', 'Questa è la stazione di Pietralba.', 'questo essere la stazione di pietralba', 'davide'),
          s('s03', 'La stazione è piccola.', 'la stazione essere piccolo', 'davide'),
          s('s04', "Dov'è il binario?", 'dove il binario', 'luca'),
          s('s05', 'Il binario è uno.', 'il binario essere uno', 'davide'),
          s('s06', "C'è un treno alle undici.", 'ce un treno alle undici', 'davide'),
          s('s07', 'Guarda l\'orario.', 'guardare orario', 'davide'),
          s('s08', "L'orario è alla stazione.", 'orario essere alla stazione', 'davide'),
          s('s09', 'La stazione ha un binario.', 'la stazione avere un binario', 'davide'),
          s('s10', 'Luca guarda la stazione.', 'luca guardare la stazione'),
        ],
        [
          s('s11', 'Il treno parte alle undici.', 'il treno partire alle undici', 'davide'),
          s('s12', 'Sono le dieci e mezzo.', 'essere le dieci e mezzo'),
          s('s13', 'Il treno non va a Roma oggi.', 'il treno non andare a roma oggi', 'davide'),
          s('s14', 'Oggi Luca resta a Pietralba.', 'oggi luca restare a pietralba', 'davide'),
          s('s15', 'Luca guarda il binario.', 'luca guardare il binario'),
          s('s16', 'Davide guarda l\'orario.', 'davide guardare orario'),
          s('s17', 'Un giorno Luca prende il treno.', 'un giorno luca prendere il treno', 'davide'),
          s('s18', 'Non oggi.', 'non oggi', 'luca'),
          s('s19', 'Il treno è piccolo.', 'il treno essere piccolo', 'davide'),
          s('s20', 'Undici è l\'orario del treno.', 'undici essere orario del treno', 'davide'),
        ],
        [
          s('s21', "C'è un treno per Roma.", 'ce un treno per roma', 'davide'),
          s('s22', 'Ma oggi Luca non parte.', 'ma oggi luca non partire', 'luca'),
          s('s23', 'Luca resta qui.', 'luca restare qui', 'luca'),
          s('s24', 'La stazione di Pietralba è vicina.', 'la stazione di pietralba essere vicino', 'davide'),
          s('s25', 'Il binario è vuoto adesso.', 'il binario essere vuoto adesso', 'davide'),
          s('s26', 'Oggi andiamo a casa.', 'oggi andare a casa', 'davide'),
          s('s27', 'Luca è contento a Pietralba.', 'luca essere contento a pietralba'),
          s('s28', 'Domani è un altro giorno.', 'domani essere un altro giorno', 'davide'),
          s('s29', 'Luca non prende il treno oggi.', 'luca non prendere il treno oggi', 'luca'),
          s('s30', 'Un giorno va a Roma.', 'un giorno andare a roma', 'davide'),
          s('s31', 'Ma oggi resta qui.', 'ma oggi restare qui', 'luca'),
          s('s32', 'La stazione è qui a Pietralba.', 'la stazione essere qui a pietralba', 'davide'),
          s('s33', 'Il binario uno è libero.', 'il binario uno essere libero', 'davide'),
        ],
      ],
      questions: [
        q('lpr04-ch07-q01', 'direct', 'Which station are they at?', ['Rome Termini', 'Pietralba station', 'A metro stop in Rome'], 1, 'Questa è la stazione di Pietralba.'),
        q('lpr04-ch07-q02', 'direct', 'Is Luca going to Rome today?', ['Yes', 'No', 'He is already in Rome'], 1, 'Oggi Luca resta a Pietralba.'),
        q('lpr04-ch07-q03', 'direct', 'What time is the local train mentioned?', ['11:00', '8:00', '20:00'], 0, "C'è un treno alle undici."),
      ],
    }),
  ],
};
