import { chapter, q, s, type StorySpec } from './pre-rome-helpers';

export const story05: StorySpec = {
  id: 'luca-prima-di-roma-05',
  title: "Luca's party",
  titleIt: 'La festa di Luca',
  synopsis: 'Il compleanno di Luca a Pietralba: inviti, gusti, festa e partenza.',
  characterIds: ['luca', 'marta', 'paolo', 'chiara', 'lidia', 'davide', 'elisa'],
  locationIds: [
    'casa-pietralba',
    'cucina-pietralba',
    'soggiorno-pietralba',
    'stazione-pietralba',
  ],
  chapters: [
    chapter({
      id: 'luca-prima-di-roma-05-01',
      number: 1,
      title: 'My birthday',
      titleIt: 'Il mio compleanno',
      locationIds: ['casa-pietralba', 'soggiorno-pietralba'],
      characterIds: ['luca', 'marta', 'paolo', 'chiara', 'lidia'],
      primaryDomain: 'birthdays',
      secondaryDomains: ['dates', 'age'],
      summary: 'Today is Luca’s birthday on 12 May. He is 24. The family says auguri.',
      facts: ['Today is 12 May', 'Luca is 24', 'There is a party at home today'],
      paragraphs: [
        [
          s('s01', 'Oggi è il compleanno di Luca.', 'oggi essere il compleanno di luca'),
          s('s02', 'Oggi è il dodici maggio.', 'oggi essere il dodici maggio'),
          s('s03', 'Il dodici maggio è il compleanno di Luca.', 'il dodici maggio essere il compleanno di luca'),
          s('s04', 'Luca ha ventiquattro anni.', 'luca avere ventiquattro anno'),
          s('s05', 'Quanti anni hai oggi?', 'quanto anno avere oggi', 'chiara'),
          s('s06', 'Ho ventiquattro anni.', 'avere ventiquattro anno', 'luca'),
          s('s07', 'Luca è nel soggiorno.', 'luca essere nel soggiorno'),
          s('s08', 'La famiglia è a casa.', 'la famiglia essere a casa'),
          s('s09', 'Marta entra nel soggiorno.', 'marta entrare nel soggiorno'),
          s('s10', 'Auguri Luca.', 'auguri luca', 'marta'),
          s('s11', 'Grazie mamma.', 'grazie mamma', 'luca'),
          s('s12', 'Il compleanno è oggi.', 'il compleanno essere oggi'),
          s('s13', 'Luca è a casa oggi.', 'luca essere a casa oggi'),
        ],
        [
          s('s14', 'Paolo è qui.', 'paolo essere qui'),
          s('s15', 'Auguri Luca.', 'auguri luca', 'paolo'),
          s('s16', 'Grazie papà.', 'grazie papa', 'luca'),
          s('s17', 'Chiara sorride.', 'chiara sorridere'),
          s('s18', 'Auguri.', 'auguri', 'chiara'),
          s('s19', 'Lidia è a casa.', 'lidia essere a casa'),
          s('s20', 'Auguri Luca.', 'auguri luca', 'lidia'),
          s('s21', 'Grazie nonna.', 'grazie nonna', 'luca'),
          s('s22', 'Sabato c\'è una festa.', 'sabato ce una festa', 'marta'),
          s('s23', 'La festa è a casa.', 'la festa essere a casa'),
          s('s24', 'La festa è nel soggiorno.', 'la festa essere nel soggiorno'),
          s('s25', 'Tutti sono nel soggiorno.', 'tutto essere nel soggiorno'),
          s('s26', 'Marta prepara la festa.', 'marta preparare la festa'),
        ],
        [
          s('s27', 'Luca è felice.', 'luca essere felice'),
          s('s28', 'Marta è felice.', 'marta essere felice'),
          s('s29', 'Chiara è contenta.', 'chiara essere contento'),
          s('s30', 'Il compleanno è importante.', 'il compleanno essere importante'),
          s('s31', 'Il dodici maggio è il mio giorno.', 'il dodici maggio essere il mio giorno', 'luca'),
          s('s32', 'Luca guarda la famiglia.', 'luca guardare la famiglia'),
          s('s33', 'Tutti dicono auguri.', 'tutto dire auguri'),
          s('s34', 'Oggi è un giorno importante.', 'oggi essere un giorno importante', 'paolo'),
          s('s35', 'Luca sorride.', 'luca sorridere'),
          s('s36', 'Pietralba è piccola ma la famiglia è grande.', 'pietralba essere piccolo ma la famiglia essere grande', 'lidia'),
          s('s37', 'La famiglia è qui per Luca.', 'la famiglia essere qui per luca', 'marta'),
          s('s38', 'Il compleanno di Luca è oggi.', 'il compleanno di luca essere oggi'),
          s('s39', 'Ventiquattro anni oggi.', 'ventiquattro anno oggi', 'chiara'),
        ],
      ],
      questions: [
        q('lpr05-ch01-q01', 'direct', 'What date is Luca’s birthday?', ['11 May', '12 May', '1 January'], 1, 'Oggi è il dodici maggio.'),
        q('lpr05-ch01-q02', 'direct', 'How old is Luca today?', ['16', '24', '70'], 1, 'Luca ha ventiquattro anni.'),
        q('lpr05-ch01-q03', 'direct', 'Where is the party?', ['At home in Pietralba', 'In Rome', 'At the supermarket'], 0, 'La festa è a casa.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-05-02',
      number: 2,
      title: 'I invite you',
      titleIt: 'Ti invito',
      locationIds: ['casa-pietralba', 'soggiorno-pietralba'],
      characterIds: ['luca', 'davide', 'chiara', 'elisa'],
      primaryDomain: 'invitations',
      secondaryDomains: ['days', 'social'],
      summary: 'Luca invites Davide and Elisa for Saturday. Davide says yes; Elisa says forse.',
      facts: ['The party is on Saturday', 'Davide accepts the invitation', 'Elisa might come'],
      paragraphs: [
        [
          s('s01', 'Luca invita gli amici.', 'luca invitare gli amico'),
          s('s02', 'Davide è nel soggiorno.', 'davide essere nel soggiorno'),
          s('s03', 'Ciao Luca.', 'ciao luca', 'davide'),
          s('s04', 'Ciao Davide.', 'ciao davide', 'luca'),
          s('s05', 'Vieni sabato?', 'venire sabato', 'luca'),
          s('s06', 'Sì vengo.', 'si_yes venire', 'davide'),
          s('s07', 'Sabato c\'è la festa.', 'sabato ce la festa', 'luca'),
          s('s08', 'Va bene.', 'andare bene', 'davide'),
          s('s09', 'L\'invito è per sabato.', 'invito essere per sabato', 'luca'),
          s('s10', 'Davide dice sì.', 'davide dire si_yes'),
          s('s11', 'Luca è contento.', 'luca essere contento'),
          s('s12', 'Davide viene sabato.', 'davide venire sabato'),
          s('s13', 'Sabato è il giorno della festa.', 'sabato essere il giorno della festa', 'luca'),
        ],
        [
          s('s14', 'Chiara è con Elisa.', 'chiara essere con elisa'),
          s('s15', 'Elisa è amica di Chiara.', 'elisa essere amico di chiara'),
          s('s16', 'Elisa è qui oggi.', 'elisa essere qui oggi'),
          s('s17', 'Ciao Elisa.', 'ciao elisa', 'luca'),
          s('s18', 'Ciao Luca.', 'ciao luca', 'elisa'),
          s('s19', 'Elisa vieni sabato?', 'elisa venire sabato', 'luca'),
          s('s20', 'Forse.', 'forse', 'elisa'),
          s('s21', 'Forse vengo.', 'forse venire', 'elisa'),
          s('s22', 'Elisa dice forse.', 'elisa dire forse'),
          s('s23', 'Chiara guarda Elisa.', 'chiara guardare elisa'),
          s('s24', 'Luca invita anche Elisa.', 'luca invitare anche elisa'),
          s('s25', 'Elisa forse viene sabato.', 'elisa forse venire sabato'),
          s('s26', 'Chiara vuole Elisa sabato.', 'chiara volere elisa sabato'),
        ],
        [
          s('s27', 'Sabato siamo a casa.', 'sabato essere a casa', 'luca'),
          s('s28', 'L\'invito è per la festa.', 'invito essere per la festa', 'luca'),
          s('s29', 'La festa è sabato.', 'la festa essere sabato'),
          s('s30', 'Davide è felice.', 'davide essere felice'),
          s('s31', 'Chiara è contenta.', 'chiara essere contento'),
          s('s32', 'Elisa sorride.', 'elisa sorridere'),
          s('s33', 'Luca prepara l\'invito.', 'luca preparare invito'),
          s('s34', 'Sabato è un giorno importante.', 'sabato essere un giorno importante', 'chiara'),
          s('s35', 'Gli amici vengono a casa.', 'gli amico venire a casa'),
          s('s36', 'Davide dice sì a sabato.', 'davide dire si_yes a sabato'),
          s('s37', 'Elisa dice forse a sabato.', 'elisa dire forse a sabato'),
          s('s39', 'Luca invita per sabato.', 'luca invitare per sabato'),
          s('s40', 'Vieni sabato Elisa.', 'venire sabato elisa', 'chiara'),
          s('s41', 'Forse vengo sabato.', 'forse venire sabato', 'elisa'),
          s('s42', 'L\'invito è pronto.', 'invito essere pronto', 'luca'),
          s('s43', 'Davide è un amico di Luca.', 'davide essere un amico di luca'),
          s('s44', 'Davide ascolta Luca.', 'davide ascoltare luca'),
          s('s45', 'Elisa guarda Chiara.', 'elisa guardare chiara'),
        ],
      ],
      questions: [
        q('lpr05-ch02-q01', 'direct', 'When is the party?', ['Monday', 'Saturday', 'Tomorrow morning'], 1, 'Sabato c\'è la festa.'),
        q('lpr05-ch02-q02', 'direct', 'Does Davide come?', ['Yes', 'No', 'He is in Rome'], 0, 'Sì vengo.'),
        q('lpr05-ch02-q03', 'character', 'What does Elisa say?', ['Maybe', 'Never', 'I live in Rome'], 0, 'Forse vengo.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-05-03',
      number: 3,
      title: 'What do you like?',
      titleIt: 'Cosa ti piace?',
      locationIds: ['casa-pietralba', 'cucina-pietralba'],
      characterIds: ['luca', 'marta', 'davide', 'elisa'],
      primaryDomain: 'likes',
      secondaryDomains: ['food'],
      summary: 'They talk about party food and music. Luca likes torta and musica; he does not like olio.',
      facts: ['Luca likes cake and music', 'Luca does not like oil', 'Davide likes juice; Elisa likes fruit'],
      paragraphs: [
        [
          s('s01', 'Marta è in cucina.', 'marta essere in cucina'),
          s('s02', 'Luca e gli amici sono qui.', 'luca e gli amico essere qui'),
          s('s03', 'Cosa ti piace?', 'cosa ti piacere', 'marta'),
          s('s04', 'Cosa ti piace Davide?', 'cosa ti piacere davide', 'marta'),
          s('s05', 'A Davide piace il succo.', 'a davide piacere il succo', 'davide'),
          s('s06', 'Cosa ti piace Elisa?', 'cosa ti piacere elisa', 'marta'),
          s('s07', 'A Elisa piace la frutta.', 'a elisa piacere la frutta', 'elisa'),
          s('s08', 'A Marta piace il pane.', 'a marta piacere il pane', 'marta'),
          s('s09', 'E tu Luca?', 'e tu luca', 'marta'),
          s('s10', 'A Luca piace la torta.', 'a luca piacere la torta', 'luca'),
          s('s11', 'A Luca piace la musica.', 'a luca piacere la musica', 'luca'),
          s('s12', 'Luca sorride.', 'luca sorridere'),
          s('s13', 'Marta ascolta tutti.', 'marta ascoltare tutto'),
        ],
        [
          s('s14', 'A Luca non piace l\'olio.', 'a luca non piacere olio', 'luca'),
          s('s14b', 'L\'olio no.', 'olio no', 'luca'),
          s('s15', 'Va bene.', 'andare bene', 'marta'),
          s('s16', 'Per la festa c\'è torta.', 'per la festa ce torta'),
          s('s17', "C'è succo.", 'ce succo'),
          s('s18', "C'è frutta.", 'ce frutta'),
          s('s19', "C'è musica.", 'ce musica'),
          s('s20', 'Non c\'è olio.', 'non ce olio', 'marta'),
          s('s21', 'Davide sorride.', 'davide sorridere'),
          s('s22', 'Elisa è contenta.', 'elisa essere contento'),
          s('s23', 'La musica è bella.', 'la musica essere bello', 'elisa'),
          s('s24', 'La torta è bella.', 'la torta essere bello', 'davide'),
          s('s25', 'Il pane è sul tavolo.', 'il pane essere sul tavolo', 'marta'),
        ],
        [
          s('s26', 'A Luca piacciono gli amici.', 'a luca piacere gli amico'),
          s('s27', 'A Luca piace la festa.', 'a luca piacere la festa', 'luca'),
          s('s28', 'Sì mi piace la torta.', 'si_yes mi piacere la torta', 'luca'),
          s('s29', 'Sì mi piace la musica.', 'si_yes mi piacere la musica', 'luca'),
          s('s30', 'No non mi piace l\'olio.', 'no non mi piacere olio', 'luca'),
          s('s31', 'La festa è bella.', 'la festa essere bello', 'davide'),
          s('s32', 'Marta è felice.', 'marta essere felice'),
          s('s33', 'Luca è felice.', 'luca essere felice'),
          s('s34', 'Tutti prendono la torta.', 'tutto prendere la torta'),
          s('s35', 'La torta e la musica sono pronte.', 'la torta e la musica essere pronto', 'marta'),
          s('s36', 'Va bene così.', 'andare bene cosi', 'luca'),
          s('s37', 'Per la festa tutto è pronto.', 'per la festa tutto essere pronto', 'marta'),
        ],
      ],
      questions: [
        q('lpr05-ch03-q01', 'direct', 'What does Luca like for the party?', ['Cake and music', 'Oil and work', 'The Rome café'], 0, 'A Luca piace la torta e la musica.'),
        q('lpr05-ch03-q02', 'direct', 'What does Luca not like?', ['Friends', 'Oil', 'Juice'], 1, "A Luca non piace l'olio."),
        q('lpr05-ch03-q03', 'character', 'What does Elisa like?', ['Fruit', 'Oil', 'Tickets'], 0, 'A Elisa piace la frutta.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-05-04',
      number: 4,
      title: 'We prepare the party',
      titleIt: 'Prepariamo la festa',
      locationIds: ['casa-pietralba', 'cucina-pietralba'],
      characterIds: ['luca', 'marta', 'paolo', 'chiara'],
      primaryDomain: 'birthdays',
      secondaryDomains: ['family', 'quantities', 'food'],
      summary: 'Marta and Luca prepare the party: one torta, two bottles of succo, and fruit.',
      facts: ['There is one cake', 'There are two bottles of juice', 'The family prepares together'],
      paragraphs: [
        [
          s('s01', 'Marta è in cucina.', 'marta essere in cucina'),
          s('s02', 'Luca aiuta Marta.', 'luca aiutare marta'),
          s('s03', 'Prepariamo la festa.', 'preparare la festa', 'marta'),
          s('s04', 'La famiglia prepara insieme.', 'la famiglia preparare insieme'),
          s('s05', 'Paolo è in cucina.', 'paolo essere in cucina'),
          s('s06', 'Chiara porta il pane.', 'chiara portare il pane'),
          s('s07', 'Oggi è sabato.', 'oggi essere sabato'),
          s('s08', 'La festa è oggi.', 'la festa essere oggi'),
          s('s09', 'Marta guarda il tavolo.', 'marta guardare il tavolo'),
          s('s10', 'Luca è pronto.', 'luca essere pronto'),
          s('s11', 'Prepariamo tutto.', 'preparare tutto', 'paolo'),
          s('s12', 'La cucina è piena.', 'la cucina essere pieno'),
          s('s13', 'Chiara aiuta anche.', 'chiara aiutare anche'),
        ],
        [
          s('s14', "C'è una torta.", 'ce una torta'),
          s('s15', 'Una torta per il compleanno.', 'una torta per il compleanno', 'marta'),
          s('s16', 'Quanto succo?', 'quanto succo', 'chiara'),
          s('s17', 'Due bottiglie di succo.', 'due bottiglia di succo', 'marta'),
          s('s18', 'Due bottiglie.', 'due bottiglia', 'luca'),
          s('s19', 'Un po\' di frutta.', 'un poco di frutta', 'luca'),
          s('s20', 'Poca frutta ma bella.', 'poco frutta ma bello', 'chiara'),
          s('s21', 'Il succo è pronto.', 'il succo essere pronto'),
          s('s22', 'La torta è grande.', 'la torta essere grande'),
          s('s23', 'Marta conta le bottiglie.', 'marta contare le bottiglia'),
          s('s24', 'Due bottiglie sono qui.', 'due bottiglia essere qui', 'paolo'),
          s('s25', 'Una torta e due bottiglie.', 'una torta e due bottiglia', 'marta'),
          s('s26', 'Quanto pane?', 'quanto pane', 'luca'),
          s('s27', 'Un po\' di pane.', 'un poco di pane', 'chiara'),
        ],
        [
          s('s28', 'Paolo aiuta Marta.', 'paolo aiutare marta'),
          s('s29', 'Chiara mette il pane sul tavolo.', 'chiara mettere il pane sul tavolo'),
          s('s30', 'Luca guarda la cucina.', 'luca guardare la cucina'),
          s('s31', 'La famiglia è in cucina.', 'la famiglia essere in cucina'),
          s('s32', 'La festa è pronta.', 'la festa essere pronto', 'paolo'),
          s('s33', 'Oggi è un giorno importante.', 'oggi essere un giorno importante'),
          s('s34', 'Luca è contento.', 'luca essere contento'),
          s('s35', 'Marta è felice.', 'marta essere felice'),
          s('s36', 'Tutto è pronto per la festa.', 'tutto essere pronto per la festa', 'marta'),
          s('s37', 'Il compleanno è quasi qui.', 'il compleanno essere quasi qui', 'chiara'),
          s('s38', 'Prepariamo insieme.', 'preparare insieme', 'paolo'),
          s('s39', 'La famiglia lavora insieme.', 'la famiglia lavorare insieme', 'marta'),
          s('s40', 'Ora andiamo al soggiorno.', 'ora andare al soggiorno', 'paolo'),
        ],
      ],
      questions: [
        q('lpr05-ch04-q01', 'direct', 'How much cake is there?', ['One cake', 'Ten cakes', 'No cake'], 0, "C'è una torta."),
        q('lpr05-ch04-q02', 'direct', 'How much juice do they prepare?', ['Two bottles', 'One kilo', 'Five euros'], 0, 'Due bottiglie di succo.'),
        q('lpr05-ch04-q03', 'character', 'Who helps Marta prepare?', ['Sofia', 'Luca and Paolo', 'Franco'], 1, 'Luca aiuta Marta. Paolo aiuta Marta.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-05-05',
      number: 5,
      title: 'At the party',
      titleIt: 'Alla festa',
      locationIds: ['casa-pietralba', 'soggiorno-pietralba'],
      characterIds: ['luca', 'marta', 'paolo', 'chiara', 'lidia', 'davide', 'elisa'],
      primaryDomain: 'social',
      secondaryDomains: ['birthdays', 'introductions'],
      summary: 'Guests arrive. Davide and Elisa come. They say piacere and auguri.',
      facts: ['Davide and Elisa come to the party', 'Elisa meets the family', 'Everyone says auguri to Luca'],
      paragraphs: [
        [
          s('s01', 'La festa è nel soggiorno.', 'la festa essere nel soggiorno'),
          s('s02', 'C\'è musica.', 'ce musica'),
          s('s03', 'C\'è torta.', 'ce torta'),
          s('s04', 'C\'è succo.', 'ce succo'),
          s('s05', 'Davide arriva.', 'davide arrivare'),
          s('s06', 'Elisa arriva.', 'elisa arrivare'),
          s('s07', 'Ciao Luca.', 'ciao luca', 'elisa'),
          s('s08', 'Ciao Elisa.', 'ciao elisa', 'luca'),
          s('s09', 'Ciao Davide.', 'ciao davide', 'luca'),
          s('s10', 'Davide è felice.', 'davide essere felice'),
          s('s11', 'Elisa sorride.', 'elisa sorridere'),
          s('s12', 'La famiglia è qui.', 'la famiglia essere qui'),
          s('s13', 'Davide conosce la famiglia.', 'davide conoscere la famiglia'),
          s('s14', 'Elisa è nuova a casa.', 'elisa essere nuovo a casa'),
        ],
        [
          s('s15', 'Marta guarda Elisa.', 'marta guardare elisa'),
          s('s16', 'Piacere.', 'piacere', 'marta'),
          s('s17', 'Piacere signora.', 'piacere signora', 'elisa'),
          s('s18', 'Io mi chiamo Elisa.', 'io mi chiamarsi elisa', 'elisa'),
          s('s19', 'Elisa è amica di Chiara.', 'elisa essere amico di chiara'),
          s('s20', 'Piacere Elisa.', 'piacere elisa', 'paolo'),
          s('s21', 'Piacere.', 'piacere', 'lidia'),
          s('s22', 'Chiara presenta Elisa.', 'chiara presentare elisa'),
          s('s23', 'Elisa è nuova qui.', 'elisa essere nuovo qui', 'chiara'),
          s('s24', 'Luca è contento.', 'luca essere contento'),
          s('s25', 'Tutti dicono piacere.', 'tutto dire piacere'),
          s('s26', 'Elisa guarda la famiglia.', 'elisa guardare la famiglia'),
          s('s27', 'Marta sorride a Elisa.', 'marta sorridere a elisa'),
        ],
        [
          s('s28', 'Auguri Luca.', 'auguri luca', 'davide'),
          s('s29', 'Auguri.', 'auguri', 'elisa'),
          s('s30', 'Auguri Luca.', 'auguri luca', 'paolo'),
          s('s31', 'Auguri Luca.', 'auguri luca', 'lidia'),
          s('s32', 'Grazie a tutti.', 'grazie a tutto', 'luca'),
          s('s33', 'C\'è torta e musica.', 'ce torta e musica'),
          s('s34', 'Lidia è alla festa.', 'lidia essere alla festa'),
          s('s35', 'Paolo è contento.', 'paolo essere contento'),
          s('s36', 'Siamo tutti qui.', 'essere tutto qui', 'chiara'),
          s('s37', 'La festa è bella.', 'la festa essere bello'),
          s('s38', 'Luca è felice.', 'luca essere felice'),
          s('s39', 'Il compleanno è importante.', 'il compleanno essere importante', 'marta'),
          s('s40', 'Davide mangia la torta.', 'davide mangiare la torta'),
          s('s41', 'Elisa beve il succo.', 'elisa bere il succo'),
          s('s42', 'Tutti parlano insieme.', 'tutto parlare insieme', 'chiara'),
          s('s43', 'La musica è alta.', 'la musica essere alto', 'davide'),
          s('s44', 'Elisa è contenta.', 'elisa essere contento'),
          s('s45', 'Marta serve la torta.', 'marta servire la torta'),
          s('s46', 'Luca prende la torta.', 'luca prendere la torta'),
          s('s47', 'Tutti mangiano insieme.', 'tutto mangiare insieme', 'paolo'),
          s('s48', 'La festa continua.', 'la festa continuare', 'chiara'),
          s('s49', 'Luca dice grazie a tutti.', 'luca dire grazie a tutto', 'luca'),
          s('s50', 'Chiara è felice.', 'chiara essere felice'),
        ],
      ],
      questions: [
        q('lpr05-ch05-q01', 'character', 'Who arrives as guests?', ['Sofia and Marco', 'Davide and Elisa', 'Pina and Franco'], 1, 'Davide arriva. Elisa arriva.'),
        q('lpr05-ch05-q02', 'direct', 'How is Elisa introduced?', ['Chiara’s friend', 'Luca’s mother', 'A Rome neighbor'], 0, 'Elisa è amica di Chiara.'),
        q('lpr05-ch05-q03', 'direct', 'What do the guests say to Luca?', ['Arrivederci Roma', 'Auguri', 'Buon viaggio only'], 1, 'They say auguri.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-05-06',
      number: 6,
      title: 'Tomorrow I leave',
      titleIt: 'Domani parto',
      locationIds: ['casa-pietralba', 'stazione-pietralba'],
      characterIds: ['luca', 'marta', 'paolo', 'davide'],
      primaryDomain: 'social',
      secondaryDomains: ['transportation', 'family'],
      summary: 'After the party Luca says he leaves tomorrow for Rome. Goodbye at Pietralba station; he is on the train.',
      facts: ['Luca leaves tomorrow for Rome', 'They say goodbye at Pietralba station', 'Luca is on the train leaving Pietralba'],
      paragraphs: [
        [
          s('s01', 'Dopo la festa Luca parla.', 'dopo la festa luca parlare'),
          s('s02', 'La famiglia è in casa.', 'la famiglia essere in casa'),
          s('s03', 'Domani parto.', 'domani partire', 'luca'),
          s('s04', 'Domani parto per Roma.', 'domani partire per roma', 'luca'),
          s('s05', 'Domani Luca va a Roma.', 'domani luca andare a roma'),
          s('s06', 'Roma non è Pietralba.', 'roma non essere pietralba', 'marta'),
          s('s07', 'Sì mamma.', 'si_yes mamma', 'luca'),
          s('s08', 'Paolo è un po\' triste.', 'paolo essere un poco triste'),
          s('s09', 'Marta è un po\' triste.', 'marta essere un poco triste'),
          s('s10', 'Luca guarda la famiglia.', 'luca guardare la famiglia'),
          s('s11', 'Domani è un giorno nuovo.', 'domani essere un giorno nuovo', 'luca'),
          s('s12', 'La famiglia ascolta Luca.', 'la famiglia ascoltare luca'),
          s('s13', 'Paolo guarda Luca.', 'paolo guardare luca'),
          s('s14', 'Marta è triste ma felice.', 'marta essere triste ma felice'),
        ],
        [
          s('s15', 'È mattina.', 'essere mattina'),
          s('s15b', 'Luca va alla stazione.', 'luca andare alla stazione'),
          s('s16', 'Davide è alla stazione.', 'davide essere alla stazione'),
          s('s17', 'Questa è la stazione di Pietralba.', 'questo essere la stazione di pietralba'),
          s('s18', 'Pietralba ha una stazione piccola.', 'pietralba avere una stazione piccolo'),
          s('s19', 'Marta è qui.', 'marta essere qui'),
          s('s20', 'Paolo è qui.', 'paolo essere qui'),
          s('s21', 'Arrivederci Luca.', 'arrivederci luca', 'marta'),
          s('s22', 'Arrivederci.', 'arrivederci', 'paolo'),
          s('s23', 'A presto.', 'a presto', 'davide'),
          s('s24', 'Buon viaggio.', 'buono viaggio', 'davide'),
          s('s25', 'Grazie Davide.', 'grazie davide', 'luca'),
          s('s26', 'Marta guarda Luca.', 'marta guardare luca'),
        ],
        [
          s('s27', 'Luca è sul treno.', 'luca essere sul treno'),
          s('s28', 'Il treno parte.', 'il treno partire'),
          s('s29', 'Luca guarda Pietralba.', 'luca guardare pietralba'),
          s('s30', 'Pietralba è piccola.', 'pietralba essere piccolo'),
          s('s31', 'La famiglia resta alla stazione.', 'la famiglia restare alla stazione'),
          s('s32', 'Davide guarda il treno.', 'davide guardare il treno'),
          s('s33', 'Luca è sul treno verso Roma.', 'luca essere sul treno verso roma'),
          s('s34', 'Roma è lontana.', 'roma essere lontano', 'luca'),
          s('s35', 'Luca è un po\' triste.', 'luca essere un poco triste'),
          s('s36', 'Ma Luca è anche felice.', 'ma luca essere anche felice', 'luca'),
          s('s37', 'Domani inizia un giorno nuovo.', 'domani iniziare un giorno nuovo'),
          s('s38', 'Il treno va via da Pietralba.', 'il treno andare via da pietralba'),
          s('s39', 'Luca dice arrivederci.', 'luca dire arrivederci'),
          s('s40', 'Pietralba è lontana.', 'pietralba essere lontano'),
        ],
      ],
      questions: [
        q('lpr05-ch06-q01', 'direct', 'Where is Luca going?', ['To Rome tomorrow', 'He already arrived in Rome', 'To the supermarket'], 0, 'Domani Luca va a Roma.'),
        q('lpr05-ch06-q02', 'direct', 'Where do they say goodbye?', ['Pietralba station', 'Rome Termini', 'Bar Centrale'], 0, 'Questa è la stazione di Pietralba.'),
        q('lpr05-ch06-q03', 'event', 'Where is Luca at the end of the story?', ['On the train leaving Pietralba', 'Arriving in Rome hungry', 'At a Rome café'], 0, 'Luca è sul treno. Il treno parte. No Rome arrival.'),
      ],
    }),
  ],
};
