import { chapter, q, s, type StorySpec } from './pre-rome-helpers';

export const story02: StorySpec = {
  id: 'luca-prima-di-roma-02',
  title: "A day in Luca's life",
  titleIt: 'Una giornata di Luca',
  synopsis: 'Una giornata a Pietralba: ore, giorni, date e orari di Chiara.',
  characterIds: ['luca', 'marta', 'paolo', 'chiara', 'lidia'],
  locationIds: ['casa-pietralba', 'cucina-pietralba', 'camera-luca-pietralba', 'soggiorno-pietralba'],
  chapters: [
    chapter({
      id: 'luca-prima-di-roma-02-01',
      number: 1,
      title: 'What time is it?',
      titleIt: 'Che ore sono?',
      locationIds: ['casa-pietralba', 'soggiorno-pietralba'],
      characterIds: ['luca', 'chiara'],
      primaryDomain: 'clock',
      secondaryDomains: ['numbers'],
      summary: 'Luca checks the clock in the soggiorno. Chiara must leave for school at eight.',
      facts: ['It is seven-thirty', 'Chiara must leave at eight', 'Luca reads the orologio'],
      paragraphs: [
        [
          s('s01', 'Luca è nel soggiorno.', 'luca essere nel soggiorno'),
          s('s02', 'Sono le sette.', 'essere le sette'),
          s('s03', 'Luca guarda l\'orologio.', 'luca guardare orologio'),
          s('s04', 'L\'orologio è sul tavolo.', 'orologio essere sul tavolo'),
          s('s05', 'Che ore sono?', 'che ora essere', 'chiara'),
          s('s06', 'Sono le sette e mezzo.', 'essere le sette e mezzo', 'luca'),
          s('s07', 'Devo aiutare Chiara.', 'dovere aiutare chiara', 'luca'),
          s('s08', 'Chiara deve andare a scuola.', 'chiara dovere andare a scuola'),
          s('s09', 'A che ora?', 'a che ora', 'chiara'),
          s('s10', 'Alle otto.', 'alle otto', 'luca'),
          s('s11', 'Alle otto e mezzo.', 'alle otto e mezzo', 'chiara'),
          s('s12', 'No alle otto.', 'no alle otto', 'luca'),
          s('s37', 'Alle otto Chiara deve uscire.', 'alle otto chiara dovere uscire'),
          s('s38', 'Luca guarda l\'orologio ogni momento.', 'luca guardare orologio ogni momento'),
        ],
        [
          s('s13', 'Adesso sono le sette e mezzo.', 'adesso essere le sette e mezzo', 'luca'),
          s('s14', 'C\'è tempo.', 'ce tempo', 'luca'),
          s('s15', 'Quanto tempo?', 'quanto tempo', 'chiara'),
          s('s16', 'Mezza ora.', 'mezzo ora', 'luca'),
          s('s17', 'Poi sono le otto.', 'poi essere le otto', 'luca'),
          s('s18', 'Devo essere pronta.', 'dovere essere pronto', 'chiara'),
          s('s19', 'Sì presto.', 'si_yes presto', 'luca'),
          s('s20', 'Luca guarda di nuovo l\'orologio.', 'luca guardare di nuovo orologio'),
          s('s21', 'Sono ancora le sette e mezzo.', 'essere ancora le sette e mezzo', 'luca'),
          s('s22', 'Le ore sono importanti.', 'le ora essere importante', 'chiara'),
          s('s23', 'Oggi le ore contano.', 'oggi le ora contare', 'luca'),
          s('s24', 'Chiara ascolta Luca.', 'chiara ascoltare luca'),
          s('s39', 'Manca mezza ora alle otto.', 'mancare mezzo ora alle otto', 'luca'),
          s('s40', 'Chiara deve essere pronta presto.', 'chiara dovere essere pronto presto', 'chiara'),
        ],
        [
          s('s25', 'Alle otto Chiara parte.', 'alle otto chiara partire', 'luca'),
          s('s26', 'Prima sono le otto.', 'prima essere le otto', 'chiara'),
          s('s27', 'Luca dice le ore.', 'luca dire le ora'),
          s('s28', 'Sette sette e mezzo otto.', 'sette sette e mezzo otto', 'luca'),
          s('s29', 'Capisco.', 'capire', 'chiara'),
          s('s30', 'L\'orologio è qui.', 'orologio essere qui', 'luca'),
          s('s31', 'Guarda l\'orologio insieme.', 'guardare orologio insieme', 'luca'),
          s('s32', 'Sono le sette e mezzo adesso.', 'essere le sette e mezzo adesso', 'chiara'),
          s('s33', 'Sì e alle otto esci.', 'si_yes e alle otto uscire', 'luca'),
          s('s34', 'Va bene.', 'andare bene', 'chiara'),
          s('s35', 'Luca resta nel soggiorno.', 'luca restare nel soggiorno'),
          s('s36', 'Il tempo passa.', 'il tempo passare'),
          s('s41', 'Luca e Chiara guardano l\'orologio.', 'luca e chiara guardare orologio'),
          s('s42', 'Poi Chiara esce di casa.', 'poi chiara uscire di casa'),
        ],
      ],
      questions: [
        q('lpr02-ch01-q01', 'direct', 'What time does Luca tell Chiara it is?', ['Seven-thirty', 'Eight-thirty', 'Noon'], 0, 'Sono le sette e mezzo.'),
        q('lpr02-ch01-q02', 'sequence', 'When must Chiara leave for school?', ['At seven-thirty', 'At eight', 'At four'], 1, 'Alle otto Chiara parte.'),
        q('lpr02-ch01-q03', 'character', 'Who reads the clock to help Chiara?', ['Marta', 'Luca', 'Paolo'], 1, 'Luca guarda l\'orologio and tells the time.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-02-02',
      number: 2,
      title: 'The morning',
      titleIt: 'La mattina',
      locationIds: ['casa-pietralba', 'camera-luca-pietralba', 'cucina-pietralba'],
      characterIds: ['luca', 'marta', 'chiara'],
      primaryDomain: 'daily_routine',
      secondaryDomains: ['clock', 'food'],
      summary: 'Luca gets up at seven, has breakfast with Marta, and Chiara leaves for school at eight.',
      facts: ['Luca gets up at 7', 'They eat colazione in the cucina', 'Chiara goes to school at 8'],
      paragraphs: [
        [
          s('s01', 'È mattina.', 'essere mattina'),
          s('s02', 'Sono le sette.', 'essere le sette'),
          s('s03', 'Luca si sveglia.', 'luca si svegliare'),
          s('s04', 'Luca si alza.', 'luca si alzare'),
          s('s05', 'Luca è in camera.', 'luca essere in camera'),
          s('s06', 'Luca guarda l\'orologio.', 'luca guardare orologio'),
          s('s07', 'Sono le sette.', 'essere le sette', 'luca'),
          s('s08', 'Poi Luca va in cucina.', 'poi luca andare in cucina'),
          s('s09', 'Marta è in cucina.', 'marta essere in cucina'),
          s('s10', 'Buongiorno Luca.', 'buongiorno luca', 'marta'),
          s('s11', 'Buongiorno mamma.', 'buongiorno mamma', 'luca'),
          s('s12', 'Chiara è in cucina.', 'chiara essere in cucina'),
          s('s37', 'Luca si alza presto ogni mattina.', 'luca si alzare presto ogni mattina'),
          s('s38', 'In camera Luca guarda l\'orologio.', 'in camera luca guardare orologio'),
        ],
        [
          s('s13', 'Luca fa colazione.', 'luca fare colazione'),
          s('s14', "C'è pane.", 'ce pane'),
          s('s15', "C'è latte.", 'ce latte'),
          s('s16', 'Luca mangia pane.', 'luca mangiare pane'),
          s('s17', 'Luca beve latte.', 'luca bere latte'),
          s('s18', 'Chiara fa colazione.', 'chiara fare colazione'),
          s('s19', 'Marta prepara la colazione.', 'marta preparare la colazione'),
          s('s20', 'La colazione è buona.', 'la colazione essere buono', 'chiara'),
          s('s21', 'Sono le otto.', 'essere le otto'),
          s('s22', 'Chiara deve andare a scuola.', 'chiara dovere andare a scuola', 'marta'),
          s('s23', 'Alle otto Chiara parte.', 'alle otto chiara partire'),
          s('s24', 'A presto.', 'a presto', 'chiara'),
          s('s39', 'Marta e Luca fanno colazione insieme.', 'marta e luca fare colazione insieme'),
          s('s40', 'Chiara mangia pane e beve latte.', 'chiara mangiare pane e bere latte'),
        ],
        [
          s('s25', 'Ciao Chiara.', 'ciao chiara', 'luca'),
          s('s26', 'Ciao Luca.', 'ciao luca', 'chiara'),
          s('s27', 'Chiara esce di casa.', 'chiara uscire di casa'),
          s('s28', 'Luca resta a casa.', 'luca restare a casa'),
          s('s29', 'Marta resta in cucina.', 'marta restare in cucina'),
          s('s30', 'Luca aiuta Marta.', 'luca aiutare marta'),
          s('s31', 'La mattina è tranquilla.', 'la mattina essere tranquillo'),
          s('s32', 'Sono le otto e mezzo.', 'essere le otto e mezzo'),
          s('s33', 'Chiara è a scuola adesso.', 'chiara essere a scuola adesso', 'marta'),
          s('s34', 'Luca è a casa.', 'luca essere a casa'),
          s('s35', 'Oggi la mattina è importante.', 'oggi la mattina essere importante', 'luca'),
          s('s36', 'La famiglia è insieme prima di scuola.', 'la famiglia essere insieme prima di scuola'),
          s('s41', 'Alle otto e mezzo la casa è tranquilla.', 'alle otto e mezzo la casa essere tranquillo'),
          s('s42', 'Luca pensa a Chiara a scuola.', 'luca pensare a chiara a scuola'),
        ],
      ],
      questions: [
        q('lpr02-ch02-q01', 'direct', 'What time does Luca get up?', ['7:00', '8:00', '12:00'], 0, 'Sono le sette when he wakes up.'),
        q('lpr02-ch02-q02', 'direct', 'What does Luca eat and drink at breakfast?', ['Pizza and wine', 'Bread and milk', 'Pasta and coffee'], 1, 'Luca mangia pane and beve latte.'),
        q('lpr02-ch02-q03', 'sequence', 'What happens at eight o’clock?', ['Chiara leaves for school', 'Luca goes to sleep', 'They eat dinner'], 0, 'Alle otto Chiara parte.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-02-03',
      number: 3,
      title: 'Days of the week',
      titleIt: 'I giorni della settimana',
      locationIds: ['casa-pietralba', 'soggiorno-pietralba'],
      characterIds: ['luca', 'paolo', 'chiara'],
      primaryDomain: 'days',
      secondaryDomains: ['schedules'],
      summary: 'Today is Monday. The family names the weekdays and talks about school days.',
      facts: ['Today is Monday', 'Tomorrow is Tuesday', 'Chiara has school on weekdays'],
      paragraphs: [
        [
          s('s01', 'Luca e Chiara sono nel soggiorno.', 'luca e chiara essere nel soggiorno'),
          s('s02', 'Paolo è qui.', 'paolo essere qui'),
          s('s03', 'Oggi è lunedì.', 'oggi essere lunedi'),
          s('s04', 'Che giorno è oggi?', 'che giorno essere oggi', 'chiara'),
          s('s05', 'Oggi è lunedì.', 'oggi essere lunedi', 'luca'),
          s('s06', 'Ieri è domenica.', 'ieri essere domenica', 'paolo'),
          s('s07', 'Domani è martedì.', 'domani essere martedi', 'luca'),
          s('s08', 'Luca dice i giorni.', 'luca dire il giorno'),
          s('s09', 'Lunedì martedì mercoledì.', 'lunedi martedi mercoledi', 'luca'),
          s('s10', 'Giovedì venerdì.', 'giovedi venerdi', 'chiara'),
          s('s11', 'Sabato domenica.', 'sabato domenica', 'paolo'),
          s('s12', 'La settimana ha sette giorni.', 'la settimana avere sette giorno'),
          s('s37', 'Mercoledì e giovedì Chiara ha scuola.', 'mercoledi e giovedi chiara avere scuola'),
          s('s38', 'Venerdì Chiara ha scuola anche.', 'venerdi chiara avere scuola anche'),
        ],
        [
          s('s13', 'Oggi Chiara ha scuola.', 'oggi chiara avere scuola'),
          s('s14', 'Domani Chiara ha scuola.', 'domani chiara avere scuola'),
          s('s15', 'Martedì Chiara ha scuola.', 'martedi chiara avere scuola', 'chiara'),
          s('s16', 'Sabato Chiara non ha scuola.', 'sabato chiara non avere scuola'),
          s('s17', 'Domenica siamo a casa.', 'domenica essere a casa', 'paolo'),
          s('s18', 'Ogni giorno ha un nome.', 'ogni giorno avere un nome', 'luca'),
          s('s19', 'Lunedì è il primo giorno di scuola.', 'lunedi essere il primo giorno di scuola', 'chiara'),
          s('s20', 'Oggi è lunedì.', 'oggi essere lunedi', 'luca'),
          s('s21', 'Domani è martedì.', 'domani essere martedi', 'paolo'),
          s('s22', 'Chiara ascolta i giorni.', 'chiara ascoltare il giorno'),
          s('s23', 'Paolo parla con Luca.', 'paolo parlare con luca'),
          s('s24', 'I giorni sono importanti.', 'il giorno essere importante', 'luca'),
          s('s39', 'Paolo lavora ogni giorno della settimana.', 'paolo lavorare ogni giorno della settimana'),
          s('s40', 'Luca resta a casa il lunedì.', 'luca restare a casa il lunedi'),
        ],
        [
          s('s25', 'Che giorno è domani?', 'che giorno essere domani', 'chiara'),
          s('s26', 'Domani è martedì.', 'domani essere martedi', 'luca'),
          s('s27', 'E ieri?', 'e ieri', 'chiara'),
          s('s28', 'Ieri è domenica.', 'ieri essere domenica', 'paolo'),
          s('s29', 'Oggi Chiara va a scuola.', 'oggi chiara andare a scuola'),
          s('s30', 'Domani Chiara va a scuola.', 'domani chiara andare a scuola', 'paolo'),
          s('s31', 'Va bene.', 'andare bene', 'paolo'),
          s('s32', 'La settimana è lunga.', 'la settimana essere lungo', 'chiara'),
          s('s33', 'Ma oggi è solo lunedì.', 'ma oggi essere solo lunedi', 'luca'),
          s('s34', 'Luca guarda Chiara.', 'luca guardare chiara'),
          s('s35', 'Chiara è pronta per scuola.', 'chiara essere pronto per scuola'),
          s('s36', 'Oggi è un giorno di scuola.', 'oggi essere un giorno di scuola', 'luca'),
          s('s41', 'Domenica la famiglia resta insieme.', 'domenica la famiglia restare insieme'),
          s('s42', 'Oggi è il primo giorno della settimana.', 'oggi essere il primo giorno della settimana'),
        ],
      ],
      questions: [
        q('lpr02-ch03-q01', 'direct', 'What day is today?', ['Sunday', 'Monday', 'Saturday'], 1, 'Oggi è lunedì.'),
        q('lpr02-ch03-q02', 'direct', 'What day is tomorrow?', ['Tuesday', 'Friday', 'Sunday'], 0, 'Domani è martedì.'),
        q('lpr02-ch03-q03', 'direct', 'When does Chiara not have school?', ['Monday', 'Saturday', 'Tuesday'], 1, 'Sabato Chiara non ha scuola.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-02-04',
      number: 4,
      title: 'The calendar',
      titleIt: 'Il calendario',
      locationIds: ['casa-pietralba', 'soggiorno-pietralba'],
      characterIds: ['luca', 'marta', 'chiara'],
      primaryDomain: 'dates',
      secondaryDomains: ['days', 'numbers'],
      summary: 'The family reads the date: today is Monday 12 May.',
      facts: ['Today is 12 May', 'May is a month', 'The year has twelve months'],
      paragraphs: [
        [
          s('s01', 'Marta è nel soggiorno.', 'marta essere nel soggiorno'),
          s('s02', 'Luca e Chiara sono qui.', 'luca e chiara essere qui'),
          s('s03', 'Che giorno è oggi?', 'che giorno essere oggi', 'marta'),
          s('s04', 'Oggi è lunedì.', 'oggi essere lunedi', 'luca'),
          s('s05', 'Oggi è il dodici maggio.', 'oggi essere il dodici maggio', 'chiara'),
          s('s06', 'Maggio è un mese.', 'maggio essere un mese'),
          s('s07', 'L\'anno ha dodici mesi.', 'anno avere dodici mese', 'luca'),
          s('s08', 'Gennaio febbraio marzo.', 'gennaio febbraio marzo', 'marta'),
          s('s09', 'Aprile maggio giugno.', 'aprile maggio giugno', 'chiara'),
          s('s10', 'Luglio agosto settembre.', 'luglio agosto settembre', 'luca'),
          s('s11', 'Ottobre novembre dicembre.', 'ottobre novembre dicembre', 'marta'),
          s('s12', 'Dodici mesi in un anno.', 'dodici mese in un anno', 'luca'),
          s('s37', 'Marta guarda il mese di maggio.', 'marta guardare il mese di maggio'),
          s('s38', 'Il numero dodici è importante oggi.', 'il numero dodici essere importante oggi'),
        ],
        [
          s('s13', 'Il dodici è un numero.', 'il dodici essere un numero'),
          s('s14', 'Oggi il numero è dodici.', 'oggi il numero essere dodici', 'chiara'),
          s('s15', 'Domani è il tredici maggio.', 'domani essere il tredici maggio', 'luca'),
          s('s16', "Ieri è l'undici maggio.", 'ieri essere undici maggio', 'chiara'),
          s('s17', 'Il giorno è importante.', 'il giorno essere importante', 'marta'),
          s('s18', 'Oggi Luca guarda il mese.', 'oggi luca guardare il mese'),
          s('s19', 'Maggio è ora.', 'maggio essere ora', 'luca'),
          s('s20', 'Siamo a maggio.', 'essere a maggio', 'marta'),
          s('s21', 'Che mese è?', 'che mese essere', 'chiara'),
          s('s22', 'È maggio.', 'essere maggio', 'luca'),
          s('s23', 'Il dodici maggio è oggi.', 'il dodici maggio essere oggi', 'chiara'),
          s('s24', 'Luca scrive il numero.', 'luca scrivere il numero'),
          s('s39', 'Ieri è undici e oggi dodici.', 'ieri essere undici e oggi dodici', 'marta'),
          s('s40', 'Domani è tredici maggio martedì.', 'domani essere tredici maggio martedi', 'luca'),
        ],
        [
          s('s25', 'Uno due tre.', 'uno due tre', 'chiara'),
          s('s26', 'Fino a dodici.', 'fino a dodici', 'luca'),
          s('s27', 'Oggi è il dodici.', 'oggi essere il dodici', 'marta'),
          s('s28', 'Domani è il tredici.', 'domani essere il tredici', 'luca'),
          s('s29', 'Ieri è l\'undici.', 'ieri essere undici', 'chiara'),
          s('s30', 'L\'anno è importante.', 'anno essere importante', 'marta'),
          s('s31', 'Oggi è una bella giornata.', 'oggi essere una bello giornata', 'luca'),
          s('s32', 'Il dodici maggio è lunedì.', 'il dodici maggio essere lunedi', 'chiara'),
          s('s33', 'Luca capisce il numero.', 'luca capire il numero'),
          s('s34', 'Chiara capisce anche.', 'chiara capire anche'),
          s('s35', 'Marta è contenta.', 'marta essere contento'),
          s('s36', 'Oggi tutti sanno il giorno.', 'oggi tutto sapere il giorno', 'luca'),
          s('s41', 'Luca impara i mesi.', 'luca imparare il mese'),
          s('s42', 'Chiara impara i numeri del mese.', 'chiara imparare il numero del mese'),
        ],
      ],
      questions: [
        q('lpr02-ch04-q01', 'direct', 'What is today’s date?', ['11 May', '12 May', '13 June'], 1, 'Oggi è il dodici maggio.'),
        q('lpr02-ch04-q02', 'direct', 'How many months are in a year?', ['7', '10', '12'], 2, 'L\'anno ha dodici mesi.'),
        q('lpr02-ch04-q03', 'direct', 'What is tomorrow’s date?', ['13 May', '12 May', '1 January'], 0, 'Domani è il tredici maggio.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-02-05',
      number: 5,
      title: 'Chiara’s timetable',
      titleIt: "L'orario di Chiara",
      locationIds: ['casa-pietralba', 'soggiorno-pietralba'],
      characterIds: ['luca', 'chiara', 'paolo'],
      primaryDomain: 'schedules',
      secondaryDomains: ['clock', 'days'],
      summary: 'Chiara shows her school timetable. Luca helps Paolo at nine.',
      facts: ['Chiara starts school at 8', 'Italian is at nine', 'Luca helps papà at 9'],
      paragraphs: [
        [
          s('s01', 'Chiara ha un orario.', 'chiara avere un orario'),
          s('s02', 'L\'orario è sul tavolo.', 'orario essere sul tavolo'),
          s('s03', 'Lunedì alle otto Chiara è a scuola.', 'lunedi alle otto chiara essere a scuola'),
          s('s04', 'Alle nove Chiara ha italiano.', 'alle nove chiara avere italiano', 'chiara'),
          s('s05', 'Alle dieci Chiara è libera.', 'alle dieci chiara essere libero'),
          s('s06', 'Alle undici Chiara è ancora a scuola.', 'alle undici chiara essere ancora a scuola'),
          s('s07', 'Luca non ha scuola.', 'luca non avere scuola'),
          s('s08', 'Alle nove Luca aiuta papà.', 'alle nove luca aiutare papa'),
          s('s09', 'Alle dieci Luca è a casa.', 'alle dieci luca essere a casa'),
          s('s10', 'Paolo è a casa.', 'paolo essere a casa'),
          s('s11', 'Luca guarda l\'orario.', 'luca guardare orario'),
          s('s12', 'Chiara spiega l\'orario.', 'chiara spiegare orario'),
          s('s37', 'Paolo legge l\'orario con Luca.', 'paolo leggere orario con luca'),
          s('s38', 'Alle otto inizia la scuola.', 'alle otto iniziare la scuola', 'chiara'),
        ],
        [
          s('s13', 'Alle otto scuola.', 'alle otto scuola', 'chiara'),
          s('s14', 'Alle nove italiano.', 'alle nove italiano', 'chiara'),
          s('s15', 'Alle dieci sono libera.', 'alle dieci essere libero', 'chiara'),
          s('s16', 'Alle undici sono a scuola.', 'alle undici essere a scuola', 'chiara'),
          s('s17', 'Martedì l\'orario è diverso.', 'martedi orario essere diverso', 'paolo'),
          s('s18', 'Ma lunedì è così.', 'ma lunedi essere cosi', 'chiara'),
          s('s19', 'L\'orario è ogni giorno.', 'orario essere ogni giorno'),
          s('s20', 'Chiara guarda l\'orario.', 'chiara guardare orario'),
          s('s21', 'Luca ascolta Chiara.', 'luca ascoltare chiara'),
          s('s22', 'Oggi è lunedì.', 'oggi essere lunedi'),
          s('s23', 'Alle otto Chiara parte.', 'alle otto chiara partire'),
          s('s24', 'Luca dice a presto.', 'luca dire a presto'),
          s('s39', 'Alle undici la scuola continua.', 'alle undici la scuola continuare', 'chiara'),
          s('s40', 'Luca non va a scuola oggi.', 'luca non andare a scuola oggi', 'paolo'),
        ],
        [
          s('s25', 'A che ora hai italiano?', 'a che ora avere italiano', 'luca'),
          s('s26', 'Alle nove.', 'alle nove', 'chiara'),
          s('s27', 'E a che ora sei libera?', 'e a che ora essere libero', 'luca'),
          s('s28', 'Alle dieci.', 'alle dieci', 'chiara'),
          s('s29', 'Paolo ascolta.', 'paolo ascoltare'),
          s('s30', 'Alle nove io aiuto papà.', 'alle nove io aiutare papa', 'luca'),
          s('s31', 'Va bene.', 'andare bene', 'paolo'),
          s('s32', 'L\'orario è chiaro.', 'orario essere chiaro', 'chiara'),
          s('s33', 'Oggi l\'orario è importante.', 'oggi orario essere importante', 'luca'),
          s('s34', 'Chiara mette l\'orario sul tavolo.', 'chiara mettere orario sul tavolo'),
          s('s35', 'Luca ricorda le ore.', 'luca ricordare le ora'),
          s('s36', 'Otto nove dieci undici.', 'otto nove dieci undici', 'luca'),
          s('s41', 'Ma Luca aiuta papà alle nove.', 'ma luca aiutare papa alle nove', 'paolo'),
          s('s42', 'L\'orario di lunedì è importante.', 'orario di lunedi essere importante', 'chiara'),
        ],
      ],
      questions: [
        q('lpr02-ch05-q01', 'direct', 'When does Chiara start school on Monday?', ['7:00', '8:00', '12:00'], 1, 'Lunedì alle otto Chiara è a scuola.'),
        q('lpr02-ch05-q02', 'direct', 'What does Chiara have at nine?', ['Breakfast', 'Italian', 'Dinner'], 1, 'Alle nove Chiara ha italiano.'),
        q('lpr02-ch05-q03', 'direct', 'What does Luca do at nine?', ['He goes to school', 'He helps papà', 'He sleeps'], 1, 'Alle nove Luca aiuta papà.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-02-06',
      number: 6,
      title: 'The afternoon',
      titleIt: 'Il pomeriggio',
      locationIds: ['casa-pietralba', 'soggiorno-pietralba'],
      characterIds: ['luca', 'paolo', 'chiara'],
      primaryDomain: 'daily_routine',
      secondaryDomains: ['clock', 'family'],
      summary: 'Luca helps Paolo at three. Chiara comes home from school at four.',
      facts: ['It is 3 p.m.', 'Luca helps Paolo', 'Chiara comes home at 16:00'],
      paragraphs: [
        [
          s('s01', 'È pomeriggio.', 'essere pomeriggio'),
          s('s02', 'Sono le tre.', 'essere le tre'),
          s('s03', 'Luca è nel soggiorno.', 'luca essere nel soggiorno'),
          s('s04', 'Paolo è a casa.', 'paolo essere a casa'),
          s('s05', 'Luca aiuta Paolo.', 'luca aiutare paolo'),
          s('s06', 'Luca e Paolo parlano.', 'luca e paolo parlare'),
          s('s07', 'Alle tre Luca aiuta papà.', 'alle tre luca aiutare papa', 'paolo'),
          s('s08', 'Grazie Luca.', 'grazie luca', 'paolo'),
          s('s09', 'Prego papà.', 'prego papa', 'luca'),
          s('s10', 'Poi Luca va fuori.', 'poi luca andare fuori'),
          s('s11', 'Luca aspetta Chiara.', 'luca aspettare chiara'),
          s('s12', 'Chiara torna a casa alle quattro.', 'chiara tornare a casa alle quattro', 'paolo'),
          s('s37', 'Paolo e Luca lavorano insieme.', 'paolo e luca lavorare insieme'),
          s('s38', 'Luca aspetta Chiara fuori.', 'luca aspettare chiara fuori'),
        ],
        [
          s('s13', 'Sono le quattro.', 'essere le quattro'),
          s('s14', 'Chiara torna a casa.', 'chiara tornare a casa'),
          s('s15', 'Ciao Luca.', 'ciao luca', 'chiara'),
          s('s16', 'Ciao Chiara.', 'ciao chiara', 'luca'),
          s('s17', 'Come stai?', 'come stare', 'luca'),
          s('s18', 'Sto bene.', 'stare bene', 'chiara'),
          s('s19', 'La scuola è finita.', 'la scuola essere finire', 'chiara'),
          s('s20', 'Adesso siamo a casa.', 'adesso essere a casa', 'paolo'),
          s('s21', 'Luca e Chiara entrano.', 'luca e chiara entrare'),
          s('s22', 'Paolo è nel soggiorno.', 'paolo essere nel soggiorno'),
          s('s23', 'Alle sedici Chiara è a casa.', 'alle sedici chiara essere a casa', 'luca'),
          s('s24', 'Sedici è lo stesso di quattro.', 'sedici essere lo stesso di quattro', 'paolo'),
          s('s39', 'Luca va fuori alle quattro.', 'luca andare fuori alle quattro'),
          s('s40', 'Chiara cammina a casa.', 'chiara camminare a casa'),
        ],
        [
          s('s25', 'Il pomeriggio è tranquillo.', 'il pomeriggio essere tranquillo'),
          s('s26', 'Luca resta con la famiglia.', 'luca restare con la famiglia'),
          s('s27', 'Chiara parla di scuola.', 'chiara parlare di scuola'),
          s('s28', 'Oggi ho italiano.', 'oggi avere italiano', 'chiara'),
          s('s29', 'Alle nove.', 'alle nove', 'chiara'),
          s('s30', 'Luca ascolta.', 'luca ascoltare'),
          s('s31', 'Paolo sorride.', 'paolo sorridere'),
          s('s32', 'Sono le quattro e mezzo.', 'essere le quattro e mezzo'),
          s('s33', 'La famiglia è insieme.', 'la famiglia essere insieme'),
          s('s34', 'Il pomeriggio passa.', 'il pomeriggio passare'),
          s('s35', 'Poi è sera.', 'poi essere sera', 'luca'),
          s('s36', 'Ma adesso è pomeriggio.', 'ma adesso essere pomeriggio', 'chiara'),
          s('s41', 'Tutti sono felici a casa.', 'tutto essere felice a casa', 'paolo'),
          s('s42', 'Il pomeriggio finisce presto.', 'il pomeriggio finire presto', 'luca'),
        ],
      ],
      questions: [
        q('lpr02-ch06-q01', 'direct', 'What time is it when the afternoon starts here?', ['3:00', '8:00', '10:00'], 0, 'Sono le tre.'),
        q('lpr02-ch06-q02', 'direct', 'Who does Luca help in the afternoon?', ['Marta', 'Paolo', 'Lidia'], 1, 'Luca aiuta Paolo / papà.'),
        q('lpr02-ch06-q03', 'sequence', 'What happens at four o’clock?', ['Chiara comes home', 'They eat dinner', 'Luca leaves town'], 0, 'Alle quattro Chiara torna a casa.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-02-07',
      number: 7,
      title: 'The evening',
      titleIt: 'La sera',
      locationIds: ['casa-pietralba', 'cucina-pietralba'],
      characterIds: ['luca', 'marta', 'paolo', 'chiara', 'lidia'],
      primaryDomain: 'daily_routine',
      secondaryDomains: ['clock', 'family'],
      summary: 'Dinner is at eight. Tomorrow Chiara has school again.',
      facts: ['Dinner is at 8 p.m.', 'The family eats together', 'Tomorrow is another school day'],
      paragraphs: [
        [
          s('s01', 'È sera.', 'essere sera'),
          s('s02', 'Sono le otto.', 'essere le otto'),
          s('s03', 'A che ora è la cena?', 'a che ora essere la cena', 'chiara'),
          s('s04', 'La cena è alle otto.', 'la cena essere alle otto', 'marta'),
          s('s05', 'La famiglia è in cucina.', 'la famiglia essere in cucina'),
          s('s06', 'Marta prepara la cena.', 'marta preparare la cena'),
          s('s07', 'Luca mangia con la famiglia.', 'luca mangiare con la famiglia'),
          s('s08', 'Lidia è a cena.', 'lidia essere a cena'),
          s('s09', 'Paolo è in cucina.', 'paolo essere in cucina'),
          s('s10', 'Chiara è in cucina.', 'chiara essere in cucina'),
          s('s11', 'Buona sera.', 'buono sera', 'lidia'),
          s('s12', 'Buona sera nonna.', 'buono sera nonna', 'luca'),
          s('s37', 'Marta mette il pane sul tavolo.', 'marta mettere il pane sul tavolo'),
          s('s38', 'Paolo mangia con la famiglia.', 'paolo mangiare con la famiglia'),
        ],
        [
          s('s13', 'La cena è buona.', 'la cena essere buono', 'paolo'),
          s('s14', 'Marta cucina bene.', 'marta cucinare bene', 'paolo'),
          s('s15', 'Luca mangia pane e pasta.', 'luca mangiare pane e pasta'),
          s('s16', 'Chiara beve acqua.', 'chiara bere acqua'),
          s('s17', 'Poi sono le nove.', 'poi essere le nove'),
          s('s18', 'Chiara è stanca.', 'chiara essere stanco'),
          s('s19', 'Domani Chiara ha scuola.', 'domani chiara avere scuola', 'marta'),
          s('s20', 'Domani è martedì.', 'domani essere martedi', 'luca'),
          s('s21', 'Domani Luca si alza alle sette.', 'domani luca si alzare alle sette'),
          s('s22', 'Ogni giorno è diverso.', 'ogni giorno essere diverso', 'lidia'),
          s('s23', 'Ma domani c\'è scuola.', 'ma domani ce scuola', 'chiara'),
          s('s24', 'Alle otto di mattina.', 'alle otto di mattina', 'marta'),
          s('s39', 'Lidia parla con Luca e Chiara.', 'lidia parlare con luca e chiara'),
          s('s40', 'Domani mattina tutti si alzano presto.', 'domani mattina tutto si alzare presto', 'marta'),
        ],
        [
          s('s25', 'Luca guarda l\'orologio.', 'luca guardare orologio'),
          s('s26', 'Sono le nove.', 'essere le nove', 'luca'),
          s('s27', 'La giornata è finita.', 'la giornata essere finire', 'paolo'),
          s('s28', 'Oggi è una bella giornata.', 'oggi essere una bello giornata', 'lidia'),
          s('s29', 'Luca è contento.', 'luca essere contento'),
          s('s30', 'La famiglia è insieme.', 'la famiglia essere insieme'),
          s('s31', 'A domani.', 'a domani', 'luca'),
          s('s32', 'A domani Chiara.', 'a domani chiara', 'marta'),
          s('s33', 'Buona notte.', 'buono notte', 'lidia'),
          s('s34', 'Buona notte nonna.', 'buono notte nonna', 'chiara'),
          s('s35', 'Luca va in camera.', 'luca andare in camera'),
          s('s36', 'Domani la scuola di Chiara continua.', 'domani la scuola di chiara continuare', 'luca'),
          s('s41', 'Chiara dorme presto.', 'chiara dormire presto', 'marta'),
          s('s42', 'Luca guarda l\'orologio alle nove.', 'luca guardare orologio alle nove'),
        ],
      ],
      questions: [
        q('lpr02-ch07-q01', 'direct', 'What time is dinner?', ['7:00', '8:00 p.m.', 'Noon'], 1, 'La cena è alle otto.'),
        q('lpr02-ch07-q02', 'direct', 'Who prepares dinner?', ['Paolo', 'Marta', 'Chiara'], 1, 'Marta prepara la cena.'),
        q('lpr02-ch07-q03', 'direct', 'What happens tomorrow morning?', ['Chiara has school', 'They go on a trip', 'There is no school'], 0, 'Domani Chiara ha scuola alle otto.'),
      ],
    }),
  ],
};
