import { chapter, q, s, type StorySpec } from './pre-rome-helpers';

export const story01: StorySpec = {
  id: 'luca-prima-di-roma-01',
  title: 'Luca introduces himself',
  titleIt: 'Luca si presenta',
  synopsis: 'A Pietralba Luca si presenta: nome, età, famiglia, casa e l’amico Davide.',
  characterIds: ['luca', 'marta', 'paolo', 'chiara', 'lidia', 'davide'],
  locationIds: [
    'pietralba',
    'casa-pietralba',
    'camera-luca-pietralba',
    'cucina-pietralba',
    'soggiorno-pietralba',
  ],
  chapters: [
    chapter({
      id: 'luca-prima-di-roma-01-01',
      number: 1,
      title: 'Hi, I am Luca',
      titleIt: 'Ciao, sono Luca',
      locationIds: ['pietralba', 'casa-pietralba', 'soggiorno-pietralba'],
      characterIds: ['luca', 'davide'],
      primaryDomain: 'introductions',
      secondaryDomains: ['social'],
      summary: 'Davide visits. Luca introduces himself: name, home, Pietralba.',
      facts: ['Luca lives in Pietralba', 'Luca is from Pietralba', 'His name is Luca', 'Davide is his friend'],
      paragraphs: [
        [
          s('s01', 'Luca è a Pietralba.', 'luca essere a pietralba'),
          s('s02', 'Pietralba è un paese piccolo.', 'pietralba essere un paese piccolo'),
          s('s03', 'Pietralba non è Roma.', 'pietralba non essere roma'),
          s('s04', 'Luca è a casa.', 'luca essere a casa'),
          s('s05', 'Luca è nel soggiorno.', 'luca essere nel soggiorno'),
          s('s06', "C'è una persona alla porta.", 'ce una persona alla porta'),
          s('s07', 'Luca apre la porta.', 'luca aprire la porta'),
          s('s08', 'Davide è qui.', 'davide essere qui'),
          s('s09', 'Ciao Luca.', 'ciao luca', 'davide'),
          s('s10', 'Ciao.', 'ciao', 'luca'),
          s('s11', 'Buongiorno.', 'buongiorno', 'davide'),
          s('s12', 'Buongiorno Davide.', 'buongiorno davide', 'luca'),
        ],
        [
          s('s13', 'Entra.', 'entrare', 'luca'),
          s('s14', 'Davide entra in casa.', 'davide entrare in casa'),
          s('s15', 'I due amici sono nel soggiorno.', 'il due amico essere nel soggiorno'),
          s('s16', 'Mi chiamo Luca.', 'mi chiamarsi luca', 'luca', [
            { surface: 'Mi chiamo', literalEn: 'myself I call', naturalEn: 'my name is', tokenStart: 0, tokenEnd: 1 },
          ]),
          s('s17', 'Io sono Luca.', 'io essere luca', 'luca'),
          s('s18', 'Tu come ti chiami?', 'tu come ti chiamarsi', 'luca'),
          s('s19', 'Io mi chiamo Davide.', 'io mi chiamarsi davide', 'davide'),
          s('s20', 'Siamo amici.', 'essere amico', 'luca'),
          s('s21', 'Io abito qui.', 'io abitare qui', 'luca'),
          s('s22', 'Abito a Pietralba.', 'abitare a pietralba', 'luca'),
          s('s23', 'Anche Davide abita qui.', 'anche davide abitare qui'),
          s('s24', 'Davide è di Pietralba.', 'davide essere di pietralba'),
        ],
        [
          s('s25', 'Luca è di Pietralba.', 'luca essere di pietralba'),
          s('s26', 'Roma è lontana.', 'roma essere lontano', 'davide'),
          s('s27', 'Sì Roma è lontana.', 'si_yes roma essere lontano', 'luca'),
          s('s28', 'Oggi io resto a casa.', 'oggi io restare a casa', 'luca'),
          s('s29', 'Va bene.', 'andare bene', 'davide'),
          s('s30', 'Davide è contento.', 'davide essere contento'),
          s('s31', 'Luca è contento.', 'luca essere contento'),
          s('s32', 'Pietralba è piccola ma bella.', 'pietralba essere piccolo ma bello', 'luca'),
          s('s33', 'Io sono Luca di Pietralba.', 'io essere luca di pietralba', 'luca'),
          s('s34', 'Piacere.', 'piacere', 'davide'),
          s('s35', 'Piacere Davide.', 'piacere davide', 'luca'),
          s('s36', 'Davide resta un momento.', 'davide restare un momento'),
          s('s37', 'Luca parla ancora.', 'luca parlare ancora'),
          s('s38', 'Io abito qui a Pietralba.', 'io abitare qui a pietralba', 'luca'),
        ],
      ],
      questions: [
        q('lpr01-ch01-q01', 'direct', 'What is the protagonist’s name?', ['Davide', 'Luca', 'Paolo'], 1, 'He says “Mi chiamo Luca.”'),
        q('lpr01-ch01-q02', 'direct', 'Where does Luca live?', ['In Rome', 'In Pietralba', 'At the station'], 1, 'He lives in Pietralba, not Rome.'),
        q('lpr01-ch01-q03', 'event', 'Why does Davide come into the house?', ['Luca opens the door and invites him in', 'They go to Rome', 'Marta calls them'], 0, 'Davide is at the door; Luca says entra.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-01-02',
      number: 2,
      title: 'How old are you?',
      titleIt: 'Quanti anni hai?',
      locationIds: ['casa-pietralba', 'soggiorno-pietralba'],
      characterIds: ['luca', 'chiara', 'davide'],
      primaryDomain: 'age',
      secondaryDomains: ['numbers'],
      summary: 'Chiara and Luca compare ages; Davide is 25.',
      facts: ['Luca is 24', 'Chiara is 16', 'Davide is 25'],
      paragraphs: [
        [
          s('s01', 'Luca e Chiara sono nel soggiorno.', 'luca e chiara essere nel soggiorno'),
          s('s02', 'Chiara guarda Luca.', 'chiara guardare luca'),
          s('s03', 'Quanti anni hai?', 'quanto anno avere', 'chiara'),
          s('s04', 'Ho ventiquattro anni.', 'avere ventiquattro anno', 'luca'),
          s('s05', 'Luca ha ventiquattro anni.', 'luca avere ventiquattro anno'),
          s('s06', 'E tu?', 'e tu', 'luca'),
          s('s07', 'Ho sedici anni.', 'avere sedici anno', 'chiara'),
          s('s08', 'Chiara ha sedici anni.', 'chiara avere sedici anno'),
          s('s09', 'Sedici è poco.', 'sedici essere poco', 'luca'),
          s('s10', 'Ventiquattro è molto.', 'ventiquattro essere molto', 'chiara'),
          s('s11', 'Io sono grande.', 'io essere grande', 'luca'),
          s('s12', 'Io non sono grande.', 'io non essere grande', 'chiara'),
        ],
        [
          s('s13', 'Uno due tre quattro cinque.', 'uno due tre quattro cinque', 'chiara'),
          s('s14', 'Sei sette otto nove dieci.', 'sei sette otto nove dieci', 'luca'),
          s('s15', 'Undici dodici tredici.', 'undici dodici tredici', 'chiara'),
          s('s16', 'Quattordici quindici sedici.', 'quattordici quindici sedici', 'luca'),
          s('s17', 'Sedici è l\'età di Chiara.', 'sedici essere eta di chiara'),
          s('s18', 'Ventiquattro è l\'età di Luca.', 'ventiquattro essere eta di luca'),
          s('s19', 'Chiara conta ancora.', 'chiara contare ancora'),
          s('s20', 'Diciassette diciotto diciannove venti.', 'diciassette diciotto diciannove venti', 'chiara'),
          s('s21', 'Ventuno ventidue ventitre ventiquattro.', 'ventuno ventidue ventitre ventiquattro', 'luca'),
          s('s22', 'Davide arriva.', 'davide arrivare'),
          s('s23', 'Ciao.', 'ciao', 'davide'),
          s('s24', 'Quanti anni hai Davide?', 'quanto anno avere davide', 'luca'),
        ],
        [
          s('s25', 'Ho venticinque anni.', 'avere venticinque anno', 'davide'),
          s('s26', 'Davide ha venticinque anni.', 'davide avere venticinque anno'),
          s('s27', 'Venticinque è più di ventiquattro.', 'venticinque essere piu di ventiquattro', 'chiara'),
          s('s28', 'Davide è grande.', 'davide essere grande'),
          s('s29', 'Luca è grande anche.', 'luca essere grande anche'),
          s('s30', 'Chiara ha sedici anni.', 'chiara avere sedici anno'),
          s('s31', 'Chi è più grande?', 'chi essere piu grande', 'chiara'),
          s('s32', 'Davide.', 'davide', 'luca'),
          s('s33', 'Poi Luca.', 'poi luca', 'davide'),
          s('s34', 'Poi io.', 'poi io', 'chiara'),
          s('s35', 'Trenta è un numero grande.', 'trenta essere un numero grande', 'luca'),
        ],
      ],
      questions: [
        q('lpr01-ch02-q01', 'direct', 'How old is Luca?', ['16', '24', '30'], 1, 'Luca ha ventiquattro anni.'),
        q('lpr01-ch02-q02', 'character', 'How old is Chiara?', ['14', '16', '25'], 1, 'Chiara ha sedici anni.'),
        q('lpr01-ch02-q03', 'inference', 'Who is the oldest of the three?', ['Chiara', 'Luca', 'Davide'], 2, 'Davide is 25; Luca 24; Chiara 16.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-01-03',
      number: 3,
      title: 'My family',
      titleIt: 'La mia famiglia',
      locationIds: ['casa-pietralba', 'cucina-pietralba'],
      characterIds: ['luca', 'marta', 'paolo', 'chiara', 'lidia'],
      primaryDomain: 'family',
      secondaryDomains: ['introductions'],
      summary: 'In the kitchen Luca names each family member; they sit together.',
      facts: ['Marta is Luca’s mother', 'Paolo is Luca’s father', 'Chiara is Luca’s sister', 'Lidia is Luca’s grandmother'],
      paragraphs: [
        [
          s('s01', 'La famiglia è in cucina.', 'la famiglia essere in cucina'),
          s('s02', 'Luca è in cucina.', 'luca essere in cucina'),
          s('s03', 'C\'è un tavolo.', 'ce un tavolo'),
          s('s04', 'Ci sono cinque sedie.', 'ci essere cinque sedia'),
          s('s05', 'Marta è alla porta della cucina.', 'marta essere alla porta della cucina'),
          s('s06', 'Ciao Luca.', 'ciao luca', 'marta'),
          s('s07', 'Ciao mamma.', 'ciao mamma', 'luca'),
          s('s08', 'Questa è Marta.', 'questo essere marta', 'luca'),
          s('s09', 'Marta è la mia mamma.', 'marta essere la mio mamma', 'luca'),
          s('s10', 'Paolo entra.', 'paolo entrare'),
          s('s11', 'Questo è Paolo.', 'questo essere paolo', 'luca'),
          s('s12', 'Paolo è il mio papà.', 'paolo essere il mio papa', 'luca'),
        ],
        [
          s('s13', 'Buongiorno.', 'buongiorno', 'paolo'),
          s('s14', 'Chiara è qui.', 'chiara essere qui'),
          s('s15', 'Chiara è la mia sorella.', 'chiara essere la mio sorella', 'luca'),
          s('s16', 'Lei è piccola.', 'lei essere piccolo', 'luca'),
          s('s17', 'Io non sono piccola.', 'io non essere piccolo', 'chiara'),
          s('s18', 'Lidia arriva.', 'lidia arrivare'),
          s('s19', 'Lidia è la mia nonna.', 'lidia essere la mio nonna', 'luca'),
          s('s20', 'Nonna Lidia è a casa.', 'nonna lidia essere a casa'),
          s('s21', 'Ciao nonna.', 'ciao nonna', 'luca'),
          s('s22', 'Ciao Luca.', 'ciao luca', 'lidia'),
          s('s23', 'Siamo cinque.', 'essere cinque', 'marta'),
          s('s24', 'Mamma papà sorella nonna e io.', 'mamma papa sorella nonna e io', 'luca'),
        ],
        [
          s('s25', 'La mia famiglia è di Pietralba.', 'la mio famiglia essere di pietralba', 'luca'),
          s('s26', 'Io tu lui lei.', 'io tu lui lei', 'chiara'),
          s('s27', 'Lui è papà.', 'lui essere papa', 'luca'),
          s('s28', 'Lei è mamma.', 'lei essere mamma', 'luca'),
          s('s29', 'La famiglia è piccola.', 'la famiglia essere piccolo'),
          s('s30', 'Ma la famiglia è importante.', 'ma la famiglia essere importante', 'paolo'),
          s('s31', 'Luca è felice.', 'luca essere felice'),
          s('s32', 'Marta guarda la famiglia.', 'marta guardare la famiglia'),
          s('s33', 'Tutti sono a casa.', 'tutto essere a casa'),
          s('s34', 'La mia famiglia è qui.', 'la mio famiglia essere qui', 'luca'),
          s('s35', 'Va bene così.', 'andare bene cosi', 'lidia'),
        ],
      ],
      questions: [
        q('lpr01-ch03-q01', 'character', 'Who is Marta?', ['Luca’s sister', 'Luca’s mother', 'Luca’s friend'], 1, 'Marta è la mia mamma.'),
        q('lpr01-ch03-q02', 'character', 'Who is Lidia?', ['Luca’s father', 'Luca’s grandmother', 'Chiara’s friend'], 1, 'Lidia è la nonna.'),
        q('lpr01-ch03-q03', 'direct', 'How many people are in the family here?', ['Three', 'Five', 'Eight'], 1, 'Siamo cinque: mamma, papà, sorella, nonna, Luca.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-01-04',
      number: 4,
      title: 'My house',
      titleIt: 'Casa mia',
      locationIds: ['casa-pietralba', 'cucina-pietralba', 'camera-luca-pietralba', 'soggiorno-pietralba'],
      characterIds: ['luca', 'marta', 'chiara'],
      primaryDomain: 'descriptions',
      secondaryDomains: ['family', 'numbers'],
      summary: 'Luca walks Chiara through kitchen, living room, and bedroom.',
      facts: ['The house has a kitchen', 'Luca has a bedroom', 'There is a living room', 'The house is small'],
      paragraphs: [
        [
          s('s01', 'Questa è casa mia.', 'questo essere casa mio', 'luca'),
          s('s02', 'La casa è piccola.', 'la casa essere piccolo'),
          s('s03', 'Luca e Chiara sono in cucina.', 'luca e chiara essere in cucina'),
          s('s04', "C'è una cucina.", 'ce una cucina'),
          s('s05', 'La cucina è grande.', 'la cucina essere grande', 'marta'),
          s('s06', "C'è un tavolo.", 'ce un tavolo'),
          s('s07', 'Ci sono quattro sedie.', 'ci essere quattro sedia'),
          s('s08', "C'è una finestra.", 'ce una finestra'),
          s('s09', 'La finestra è aperta.', 'la finestra essere aprire', 'chiara'),
          s('s10', 'Marta è in cucina.', 'marta essere in cucina'),
          s('s11', 'Quante stanze ci sono?', 'quanto stanza ci essere', 'chiara'),
          s('s12', 'Aspetta.', 'aspettare', 'luca'),
        ],
        [
          s('s13', 'Adesso il soggiorno.', 'adesso il soggiorno', 'luca'),
          s('s14', 'Luca e Chiara vanno nel soggiorno.', 'luca e chiara andare nel soggiorno'),
          s('s15', "C'è un soggiorno.", 'ce un soggiorno'),
          s('s16', 'Il soggiorno è piccolo.', 'il soggiorno essere piccolo'),
          s('s17', "C'è una porta.", 'ce una porta'),
          s('s18', 'La porta è chiusa.', 'la porta essere chiudere'),
          s('s19', "C'è una foto.", 'ce una foto', 'luca'),
          s('s20', 'La foto è della famiglia.', 'la foto essere della famiglia'),
          s('s21', 'Poi la mia camera.', 'poi la mio camera', 'luca'),
          s('s22', 'Luca apre la porta.', 'luca aprire la porta'),
          s('s23', 'Luca è in camera.', 'luca essere in camera'),
          s('s24', 'Chiara entra.', 'chiara entrare'),
        ],
        [
          s('s25', "C'è un letto.", 'ce un letto'),
          s('s26', "C'è una sedia.", 'ce una sedia'),
          s('s27', "C'è un libro sul letto.", 'ce un libro sul letto'),
          s('s28', 'La camera è piccola.', 'la camera essere piccolo'),
          s('s29', "C'è anche un bagno.", 'ce anche un bagno', 'marta'),
          s('s30', 'Cucina soggiorno camera bagno.', 'cucina soggiorno camera bagno', 'luca'),
          s('s31', 'Ci sono quattro stanze.', 'ci essere quattro stanza', 'luca'),
          s('s32', 'La casa non è grande.', 'la casa non essere grande'),
          s('s33', 'Ma la casa è bella.', 'ma la casa essere bello'),
          s('s34', 'Io sono in camera.', 'io essere in camera', 'luca'),
          s('s35', 'Siamo a casa insieme.', 'essere a casa insieme'),
        ],
      ],
      questions: [
        q('lpr01-ch04-q01', 'direct', 'How many rooms does Luca count?', ['Two', 'Four', 'Ten'], 1, 'Cucina, soggiorno, camera, bagno.'),
        q('lpr01-ch04-q02', 'direct', 'What is in Luca’s bedroom?', ['A bed, a chair, and a book', 'A supermarket list', 'A train ticket'], 0, 'Letto, sedia, libro sul letto.'),
        q('lpr01-ch04-q03', 'inference', 'Is the house big?', ['Yes, very big', 'No, it is small but nice', 'There is no house'], 1, 'La casa è piccola. Ma è bella.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-01-05',
      number: 5,
      title: 'This is Davide',
      titleIt: 'Questo è Davide',
      locationIds: ['casa-pietralba', 'soggiorno-pietralba'],
      characterIds: ['luca', 'davide', 'marta'],
      primaryDomain: 'social',
      secondaryDomains: ['introductions', 'descriptions'],
      summary: 'Luca introduces tall, friendly Davide to Marta; they talk.',
      facts: ['Davide is Luca’s friend', 'Davide is tall', 'Davide is from Pietralba'],
      paragraphs: [
        [
          s('s01', 'Davide è alla porta.', 'davide essere alla porta'),
          s('s02', 'Luca apre la porta.', 'luca aprire la porta'),
          s('s03', 'Ciao Davide.', 'ciao davide', 'luca'),
          s('s04', 'Ciao Luca.', 'ciao luca', 'davide'),
          s('s05', 'Davide entra nel soggiorno.', 'davide entrare nel soggiorno'),
          s('s06', 'Marta arriva.', 'marta arrivare'),
          s('s07', 'Mamma questo è Davide.', 'mamma questo essere davide', 'luca'),
          s('s08', 'Davide è il mio amico.', 'davide essere il mio amico', 'luca'),
          s('s09', 'Piacere.', 'piacere', 'marta'),
          s('s10', 'Piacere signora.', 'piacere signora', 'davide'),
          s('s11', 'Io mi chiamo Davide.', 'io mi chiamarsi davide', 'davide'),
          s('s12', 'Davide è di Pietralba.', 'davide essere di pietralba'),
        ],
        [
          s('s13', 'Davide è alto.', 'davide essere alto'),
          s('s14', 'Luca non è alto.', 'luca non essere alto'),
          s('s15', 'Davide è simpatico.', 'davide essere simpatico'),
          s('s16', 'Lui è un amico.', 'lui essere un amico', 'luca'),
          s('s17', 'Lei è la mamma.', 'lei essere la mamma', 'luca'),
          s('s18', 'Davide abita vicino.', 'davide abitare vicino'),
          s('s19', "Dov'è la tua casa?", 'dove la tuo casa', 'marta'),
          s('s20', 'La casa è vicina.', 'la casa essere vicino', 'davide'),
          s('s21', 'La casa di Davide è piccola.', 'la casa di davide essere piccolo'),
          s('s22', 'Anche questa casa è piccola.', 'anche questo casa essere piccolo', 'marta'),
          s('s23', 'Siamo tutti a Pietralba.', 'essere tutto a pietralba'),
          s('s24', 'Pietralba è un paese piccolo.', 'pietralba essere un paese piccolo', 'davide'),
        ],
        [
          s('s25', 'Vuoi un caffè?', 'volere un caffe', 'marta'),
          s('s26', 'Sì grazie.', 'si_yes grazie', 'davide'),
          s('s27', 'Marta è gentile.', 'marta essere gentile'),
          s('s28', 'Davide è contento.', 'davide essere contento'),
          s('s29', 'Luca e Davide parlano.', 'luca e davide parlare'),
          s('s30', 'Siamo amici.', 'essere amico', 'luca'),
          s('s31', 'Sì siamo amici.', 'si_yes essere amico', 'davide'),
          s('s32', 'Grazie.', 'grazie', 'marta'),
          s('s33', 'Prego.', 'prego', 'davide'),
          s('s34', 'Oggi è un giorno bello.', 'oggi essere un giorno bello'),
          s('s35', 'Davide resta un momento.', 'davide restare un momento'),
          s('s36', 'Marta ascolta gli amici.', 'marta ascoltare gli amico'),
          s('s37', 'Luca è felice.', 'luca essere felice'),
          s('s38', 'Davide è un amico importante.', 'davide essere un amico importante'),
        ],
      ],
      questions: [
        q('lpr01-ch05-q01', 'character', 'Who is Davide?', ['Luca’s father', 'Luca’s friend', 'The shopkeeper'], 1, 'Davide è il mio amico.'),
        q('lpr01-ch05-q02', 'direct', 'How is Davide described?', ['Tall and friendly', 'Tired and hungry', 'Old and quiet'], 0, 'Davide è alto e simpatico.'),
        q('lpr01-ch05-q03', 'direct', 'Where does Davide live?', ['Far from town', 'Near Luca, in Pietralba', 'In Rome'], 1, 'Davide abita vicino. È di Pietralba.'),
      ],
    }),
    chapter({
      id: 'luca-prima-di-roma-01-06',
      number: 6,
      title: 'Numbers at home',
      titleIt: 'I numeri in casa',
      locationIds: ['casa-pietralba', 'cucina-pietralba'],
      characterIds: ['luca', 'marta', 'paolo', 'chiara', 'lidia'],
      primaryDomain: 'numbers',
      secondaryDomains: ['family'],
      summary: 'House number 12, phone digits, five at dinner; Lidia is 70.',
      facts: ['The house number is 12', 'Five people eat at home', 'Luca recites phone digits', 'Lidia is 70'],
      paragraphs: [
        [
          s('s01', 'La famiglia è in cucina.', 'la famiglia essere in cucina'),
          s('s02', 'È ora di cena.', 'essere ora di cena'),
          s('s03', 'Quante persone ci sono?', 'quanto persona ci essere', 'marta'),
          s('s04', 'Ci sono cinque persone.', 'ci essere cinque persona', 'luca'),
          s('s05', 'Uno due tre quattro cinque.', 'uno due tre quattro cinque', 'chiara'),
          s('s06', 'Siamo cinque a cena.', 'essere cinque a cena'),
          s('s07', 'Cinque sedie cinque persone.', 'cinque sedia cinque persona', 'paolo'),
          s('s08', 'Il numero della casa è dodici.', 'il numero della casa essere dodici'),
          s('s09', 'Dodici è un numero.', 'dodici essere un numero', 'paolo'),
          s('s10', 'La porta ha il numero dodici.', 'la porta avere il numero dodici'),
          s('s11', 'Luca guarda la porta.', 'luca guardare la porta'),
          s('s12', 'Sì è dodici.', 'si_yes essere dodici', 'luca'),
        ],
        [
          s('s13', 'Il mio numero è questo.', 'il mio numero essere questo', 'luca'),
          s('s14', 'Il telefono è a casa.', 'il telefono essere a casa'),
          s('s15', 'Tre quattro uno.', 'tre quattro uno', 'luca'),
          s('s16', 'Due due zero.', 'due due zero', 'luca'),
          s('s17', 'Otto nove sette.', 'otto nove sette', 'luca'),
          s('s18', 'Chiara ascolta i numeri.', 'chiara ascoltare il numero'),
          s('s19', 'Ancora per favore.', 'ancora per favore', 'chiara'),
          s('s20', 'Tre quattro uno due due zero.', 'tre quattro uno due due zero', 'luca'),
          s('s21', 'Otto nove sette.', 'otto nove sette', 'luca'),
          s('s22', 'Va bene.', 'andare bene', 'chiara'),
          s('s23', 'Nonna Lidia ha ottanta anni?', 'nonna lidia avere ottanta anno', 'chiara'),
          s('s24', 'No.', 'no', 'lidia'),
        ],
        [
          s('s25', 'Ho settanta anni.', 'avere settanta anno', 'lidia'),
          s('s26', 'Settanta non è ottanta.', 'settanta non essere ottanta', 'paolo'),
          s('s27', 'Settanta è un numero grande.', 'settanta essere un numero grande'),
          s('s28', 'Dodici cinque settanta.', 'dodici cinque settanta', 'marta'),
          s('s29', 'Il numero della casa è dodici.', 'il numero della casa essere dodici'),
          s('s30', 'Le persone a cena sono cinque.', 'le persona a cena essere cinque'),
          s('s31', 'Lidia ha settanta anni.', 'lidia avere settanta anno'),
          s('s32', 'I numeri sono in casa.', 'il numero essere in casa'),
          s('s33', 'Luca è contento.', 'luca essere contento'),
          s('s34', 'La cena è pronta.', 'la cena essere pronto', 'marta'),
          s('s35', 'Adesso mangiamo.', 'adesso mangiare', 'paolo'),
        ],
      ],
      questions: [
        q('lpr01-ch06-q01', 'direct', 'What is the house number?', ['5', '12', '70'], 1, 'Il numero della casa è dodici.'),
        q('lpr01-ch06-q02', 'direct', 'How many people are at dinner?', ['Two', 'Five', 'Twelve'], 1, 'Siamo cinque a cena.'),
        q('lpr01-ch06-q03', 'character', 'How old is Nonna Lidia?', ['24', '70', '80'], 1, 'She says settanta, not ottanta.'),
      ],
    }),
  ],
};
