import type { CEFRLevel, MajorCEFRLevel } from '@/src/cefr/levels';

export type CefrContentProfile = {
  level: CEFRLevel;
  major: MajorCEFRLevel;
  label: string;
  narrativeStage: string;
  targetVocabularySize: number;
  sentenceLengthRange: [number, number];
  averageSentenceLength: number;
  maximumSentenceComplexity: number;
  repetitionTarget: number;
  dialoguePercentage: number;
  narrationPercentage: number;
  idiomFrequency: number;
  connectorFrequency: number;
  tenseComplexity: number;
  subordinateClauseFrequency: number;
  inferenceDifficulty: number;
  vocabularyNoveltyPercentage: number;
  /** Supporting stamina target, not a pass/fail rule. */
  wordCountRange: [number, number];
};

export const CEFR_PROFILES: Record<CEFRLevel, CefrContentProfile> = {
  A1: {
    level: 'A1',
    major: 'A1',
    label: 'Simple everyday stories',
    narrativeStage: 'Luca arrives in Rome.',
    targetVocabularySize: 280,
    sentenceLengthRange: [2, 10],
    averageSentenceLength: 6,
    maximumSentenceComplexity: 1.4,
    repetitionTarget: 0.78,
    dialoguePercentage: 0.28,
    narrationPercentage: 0.72,
    idiomFrequency: 0.04,
    connectorFrequency: 0.08,
    tenseComplexity: 0.1,
    subordinateClauseFrequency: 0.05,
    inferenceDifficulty: 0.1,
    vocabularyNoveltyPercentage: 0.22,
    wordCountRange: [150, 350],
  },
  'A1+': {
    level: 'A1+',
    major: 'A1',
    label: 'Simple everyday stories',
    narrativeStage: 'Luca finds his place.',
    targetVocabularySize: 340,
    sentenceLengthRange: [3, 12],
    averageSentenceLength: 7,
    maximumSentenceComplexity: 1.7,
    repetitionTarget: 0.74,
    dialoguePercentage: 0.32,
    narrationPercentage: 0.68,
    idiomFrequency: 0.06,
    connectorFrequency: 0.12,
    tenseComplexity: 0.18,
    subordinateClauseFrequency: 0.1,
    inferenceDifficulty: 0.18,
    vocabularyNoveltyPercentage: 0.2,
    wordCountRange: [250, 450],
  },
  A2: {
    level: 'A2',
    major: 'A2',
    label: 'Longer adventures and conversations',
    narrativeStage: "Luca's new life.",
    targetVocabularySize: 500,
    sentenceLengthRange: [5, 18],
    averageSentenceLength: 10,
    maximumSentenceComplexity: 2.2,
    repetitionTarget: 0.68,
    dialoguePercentage: 0.38,
    narrationPercentage: 0.62,
    idiomFrequency: 0.1,
    connectorFrequency: 0.2,
    tenseComplexity: 0.35,
    subordinateClauseFrequency: 0.22,
    inferenceDifficulty: 0.3,
    vocabularyNoveltyPercentage: 0.18,
    wordCountRange: [400, 700],
  },
  'A2+': {
    level: 'A2+',
    major: 'A2',
    label: 'Longer adventures and conversations',
    narrativeStage: 'New problems.',
    targetVocabularySize: 620,
    sentenceLengthRange: [6, 20],
    averageSentenceLength: 12,
    maximumSentenceComplexity: 2.5,
    repetitionTarget: 0.64,
    dialoguePercentage: 0.4,
    narrationPercentage: 0.6,
    idiomFrequency: 0.14,
    connectorFrequency: 0.24,
    tenseComplexity: 0.42,
    subordinateClauseFrequency: 0.28,
    inferenceDifficulty: 0.38,
    vocabularyNoveltyPercentage: 0.16,
    wordCountRange: [500, 900],
  },
  B1: {
    level: 'B1',
    major: 'B1',
    label: 'More natural conversations and complex situations',
    narrativeStage: 'Bigger decisions.',
    targetVocabularySize: 900,
    sentenceLengthRange: [8, 28],
    averageSentenceLength: 16,
    maximumSentenceComplexity: 3.2,
    repetitionTarget: 0.55,
    dialoguePercentage: 0.42,
    narrationPercentage: 0.58,
    idiomFrequency: 0.2,
    connectorFrequency: 0.32,
    tenseComplexity: 0.55,
    subordinateClauseFrequency: 0.4,
    inferenceDifficulty: 0.5,
    vocabularyNoveltyPercentage: 0.14,
    wordCountRange: [700, 1200],
  },
  'B1+': {
    level: 'B1+',
    major: 'B1',
    label: 'More natural conversations and complex situations',
    narrativeStage: 'Relationships and work.',
    targetVocabularySize: 1100,
    sentenceLengthRange: [8, 32],
    averageSentenceLength: 18,
    maximumSentenceComplexity: 3.6,
    repetitionTarget: 0.5,
    dialoguePercentage: 0.44,
    narrationPercentage: 0.56,
    idiomFrequency: 0.24,
    connectorFrequency: 0.36,
    tenseComplexity: 0.62,
    subordinateClauseFrequency: 0.46,
    inferenceDifficulty: 0.58,
    vocabularyNoveltyPercentage: 0.12,
    wordCountRange: [900, 1500],
  },
  'B2+': {
    level: 'B2+',
    major: 'B2',
    label: 'Rich, natural Italian',
    narrativeStage: 'More complicated adult life.',
    targetVocabularySize: 2000,
    sentenceLengthRange: [10, 44],
    averageSentenceLength: 23,
    maximumSentenceComplexity: 4.6,
    repetitionTarget: 0.35,
    dialoguePercentage: 0.46,
    narrationPercentage: 0.54,
    idiomFrequency: 0.36,
    connectorFrequency: 0.45,
    tenseComplexity: 0.8,
    subordinateClauseFrequency: 0.58,
    inferenceDifficulty: 0.76,
    vocabularyNoveltyPercentage: 0.09,
    wordCountRange: [1500, 2500],
  },
  B2: {
    level: 'B2',
    major: 'B2',
    label: 'Rich, natural Italian',
    narrativeStage: 'More complicated adult life.',
    targetVocabularySize: 1600,
    sentenceLengthRange: [10, 40],
    averageSentenceLength: 22,
    maximumSentenceComplexity: 4.2,
    repetitionTarget: 0.4,
    dialoguePercentage: 0.45,
    narrationPercentage: 0.55,
    idiomFrequency: 0.32,
    connectorFrequency: 0.42,
    tenseComplexity: 0.75,
    subordinateClauseFrequency: 0.55,
    inferenceDifficulty: 0.7,
    vocabularyNoveltyPercentage: 0.1,
    wordCountRange: [1200, 2000],
  },
  C1: {
    level: 'C1',
    major: 'C1',
    label: 'Authentic Italian storytelling',
    narrativeStage: 'Natural Italian.',
    targetVocabularySize: 2500,
    sentenceLengthRange: [8, 48],
    averageSentenceLength: 24,
    maximumSentenceComplexity: 5,
    repetitionTarget: 0.3,
    dialoguePercentage: 0.48,
    narrationPercentage: 0.52,
    idiomFrequency: 0.42,
    connectorFrequency: 0.48,
    tenseComplexity: 0.88,
    subordinateClauseFrequency: 0.62,
    inferenceDifficulty: 0.85,
    vocabularyNoveltyPercentage: 0.08,
    wordCountRange: [1500, 3000],
  },
};

export function profileFor(level: CEFRLevel): CefrContentProfile {
  return CEFR_PROFILES[level];
}
